/*
/* 
-- Flows for APEX - flow_call_activities.pkb
-- 
-- (c) Copyright Oracle Corporation and / or its affiliates, 2020,2022.
--
-- Created  27 Sep-2022 Richard Allen.   Oracle Corporation.
--

You can use this query to replace the region source query for the Task Details page generated by APEX
Approval Component v22.1.   If a Flows for APEX process has multiple Approval Tasks and you want to have a 
single set of Comments between approving users (across multiple calls to the Approval Component), this  
query will combine them.
This should work for APEX v22.1 / Flows for APEX v22.2.
No promises or expectations about whether this will work in future releases of either Oracle APEX
or Flows for APEX as both products are liable to change in this area.

Obviously, hook the last line up to your page...

By convention, we always create a parameter with a static ID of 'PROCESS_ID' in our Approval Tasks to hold the 
Flows for APEX Process_ID (Instance ID).  The Approval Task Plugin for returning approval outcomes to
Flows for APEX also works with a default parameter name of PROCESS_ID. for this.
*/

select apex_string.get_initials(c.created_by) as user_icon,
       'u-color-'||ora_hash(c.created_by,45)  as icon_modifier,
       lower(c.created_by)                    as user_name, /*SEC:CASE--OK*/
       text                                   as comment_text,
       c.created_on                           as comment_date,
       null                                   as comment_modifiers,
       null                                   as actions,
       null                                   as attribute_1,
       null                                   as attribute_2,
       null                                   as attribute_3,
       null                                   as attribute_4
from apex_task_parameters p
join apex_tasks t
  on t.task_id = p.task_id
 and t.workspace = p.workspace
join apex_task_comments c
  on t.task_id = c.task_id
 and t.workspace = c.workspace
where p.param_static_id = 'PROCESS_ID'
and p.param_value = (select param_value
                     from apex_task_parameters
                     where param_static_id = 'PROCESS_ID'
                       and task_id = :PXXX_TASK_ID)