---
# ====== Application: Flows for APEX =========================
id: 100
identification: 
  name: Flows for APEX
  alias: FLOWS4APEX
  version: 25.1

row-search: 
  tokenize: false
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: flow_engine_app_api.apex_error_handling

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: N
  favicon-html: <link rel="icon" sizes="32x32" href="#APP_IMAGES#favicon.png">

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Authentication # 12495636783173880401

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin-when-cross-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: FLOWS4APEX

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Session
  automatic-time-zone: true
  automatic-csv-encoding: true

application-format-masks: 
  date: dd.mm.yyyy
  date-time: 'dd.mm.yyyy hh24:mi:ss'
  timestamp: 'dd.mm.yyyy hh24:mi:ss'
  timestamp-time-zone: 'dd.mm.yyyy hh24:mi:ss'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_IMAGES#app-100-logo.png'
  text: Flows for APEX

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:3:&SESSION.'
    page: 3 # Dashboard

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&SESSION.'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Desktop Navigation Menu # 12495635966008880385

navigation-bar: 
  implementation: List
  list: Desktop Navigation Bar # 12495499558192880054
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_IMAGES#js/flows4apex#MIN#.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_IMAGES#css/flows4apex#MIN#.css'
  - '#APP_FILES#bpmn-io/bpmn-font/css/bpmn-embedded#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Workflow

component-settings: 
- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 1182306920811988
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 1602332831396424
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 1602430316396423
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 1602632841396423
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 1602717923396423
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 1602871870396423
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 1603104235396423
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 1760504774

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 4174066140699943
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: PLUGIN_COM.FLOWS4APEX.MANAGE_INSTA
  id: 33700780045345979
  identification: 
    name: PLUGIN_COM.FLOWS4APEX.MANAGE_INSTANCE.PROCESS
    type: Process

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_IR ========================
  id: 12495637049419880410
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 12495637696260880410
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 12495638240314880412
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 12495638591473880412
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 1760504898

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 12495638754943880417
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 1760504898

language-mappings: 
- # ====== Language Mapping: Italian (Italy) (it) ==============
  id: 2717958559026966
  attributes: 
    translation-application: 100006
    language: Italian (Italy) (it)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Korean (ko) =======================
  id: 5648198079050972
  attributes: 
    translation-application: 100007
    language: Korean (ko)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Chinese (Taiwan) (zh-tw) ==========
  id: 5672514122653306
  attributes: 
    translation-application: 100008
    language: Chinese (Taiwan) (zh-tw)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Chinese (China) (zh-cn) ===========
  id: 5672660075655263
  attributes: 
    translation-application: 100009
    language: Chinese (China) (zh-cn)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: French (France) (fr) ==============
  id: 9033928420999483
  attributes: 
    translation-application: 100001
    language: French (France) (fr)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Portuguese (Brazil) (pt-br) =======
  id: 53002706255554766
  attributes: 
    translation-application: 100002
    language: Portuguese (Brazil) (pt-br)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Japanese (ja) =====================
  id: 53002824512556233
  attributes: 
    translation-application: 100003
    language: Japanese (ja)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: German (Germany) (de) =============
  id: 53913409405549240
  attributes: 
    translation-application: 100004
    language: German (Germany) (de)

  globalization: 
    document-direction: Left-To-Right

- # ====== Language Mapping: Spanish (Traditional Sort) (es) ===
  id: 65314222214861109
  attributes: 
    translation-application: 100005
    language: Spanish (Traditional Sort) (es)

  globalization: 
    document-direction: Left-To-Right

