declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version='1.0' encoding='UTF-8'?>]'
      ,q'[<bpmn:definitions xmlns:bpmn='http://www.omg.org/spec/BPMN/20100524/MODEL' xmlns:bpmndi='http://www.omg.org/spec/BPMN/20100524/DI' xmlns:dc='http://www.omg.org/spec/DD/20100524/DC' xmlns:di='http://www.omg.org/spec/DD/20100524/DI' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:apex='http://www.apex.mt-ag.com' id='Definitions_0wpri2w' targetNamespace='http://bpmn.io/schema/bpmn' exporter='Camunda Modeler' exporterVersion='4.2.0'>]'
      ,q'[  <bpmn:collaboration id='Collaboration_0iz09gx'>]'
      ,q'[    <bpmn:participant id='Participant_1eelczk' name='My Flows For APEX Pool' processRef='Process_1f6tnxw' />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id='Process_1f6tnxw' isExecutable='true'>]'
      ,q'[    <bpmn:laneSet id='LaneSet_1kndmqr'>]'
      ,q'[      <bpmn:lane id='Lane_09houmv' name='Department B Lane'>]'
      ,q'[        <bpmn:flowNodeRef>Activity_userTask</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_scriptTask</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_ManualTask</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1a5in2d</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1ev2yqx</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0owgu48</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_0sjg6jc</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_0elt40y</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_1j5qhdr</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_0h6qtrg</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_05958zc</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1edlcc8</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1n9ks7b</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1o9oe05</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0r8att5</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_18civ6r</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[      <bpmn:lane id='Lane_1malyps' name='Department A Lane'>]'
      ,q'[        <bpmn:flowNodeRef>StartEvent_1</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_stdTask</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_MainSplit</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_08afvxa</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_1p4ubrv</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_EBG</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_TimerG</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_TimerH</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_10uxh66</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1td0zrj</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_00w4hzt</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_1tokmzs</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1jigpbk</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0j8t4fy</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_0crg1vq</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_1jpqrhk</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_0g4ggyl</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_03exw8r</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_Notify</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_1v7plws</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[    </bpmn:laneSet>]'
      ,q'[    <bpmn:startEvent id='StartEvent_1' name='Start'>]'
      ,q'[      <bpmn:outgoing>Flow_1u5kfn1</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id='Activity_stdTask' name='standard Task'>]'
      ,q'[      <bpmn:incoming>Flow_1u5kfn1</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0k089wp</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:parallelGateway id='Gateway_MainSplit' name='Parallel Gateway&#10;- splits process'>]'
      ,q'[      <bpmn:incoming>Flow_0k089wp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1q7lyne</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_15m8qw2</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1sl1mr5</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:userTask id='Activity_userTask' name='userTask&#10;(call APEX page or URL)'>]'
      ,q'[      <bpmn:incoming>Flow_1q7lyne</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0av2w95</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:scriptTask id='Activity_scriptTask' name='scriptTask&#10;(run a PL/SQL script)'>]'
      ,q'[      <bpmn:incoming>Flow_0av2w95</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0395vvt</bpmn:outgoing>]'
      ,q'[      <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:manualTask id='Activity_ManualTask' name='Manual Task&#10;(placeholder for non computer task)'>]'
      ,q'[      <bpmn:incoming>Flow_0395vvt</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12bf5hj</bpmn:outgoing>]'
      ,q'[    </bpmn:manualTask>]'
      ,q'[    <bpmn:exclusiveGateway id='Gateway_1a5in2d' name='Exclusive Gateway - Choose 1 Path' default='Flow_B'>]'
      ,q'[      <bpmn:incoming>Flow_12bf5hj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_B</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_A</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_C</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:task id='Activity_1ev2yqx' name='Option B&#10;(default)'>]'
      ,q'[      <bpmn:incoming>Flow_B</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1dyxw9o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id='Activity_0owgu48' name='Option A'>]'
      ,q'[      <bpmn:incoming>Flow_A</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_03kgsyn</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id='Event_0sjg6jc' name='Terminate End&#10;Terminates the entire process'>]'
      ,q'[      <bpmn:incoming>Flow_C</bpmn:incoming>]'
      ,q'[      <bpmn:terminateEventDefinition id='TerminateEventDefinition_1ixj664' />]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:exclusiveGateway id='Gateway_0elt40y' name='Merge'>]'
      ,q'[      <bpmn:incoming>Flow_1dyxw9o</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_03kgsyn</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0f0z11o</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:endEvent id='Event_1j5qhdr' name='End'>]'
      ,q'[      <bpmn:incoming>Flow_139aflr</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:inclusiveGateway id='Gateway_0h6qtrg' name='Inclusive Gateway&#10;- Pick 1 or more Options' default='Flow_E'>]'
      ,q'[      <bpmn:incoming>Flow_0f0z11o</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_D</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0miynpd</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_E</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id='Activity_05958zc' name='D'>]'
      ,q'[      <bpmn:incoming>Flow_D</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02uxial</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:inclusiveGateway id='Gateway_1edlcc8' name='Closing Inclusive Gateway&#10;- Merges and&#10;Synchronises paths'>]'
      ,q'[      <bpmn:incoming>Flow_02uxial</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_135n6n7</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1mpw2yu</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ml8gyp</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id='Activity_1n9ks7b' name='C'>]'
      ,q'[      <bpmn:incoming>Flow_0miynpd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_135n6n7</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id='Activity_1o9oe05' name='E'>]'
      ,q'[      <bpmn:incoming>Flow_E</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1mpw2yu</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id='Activity_08afvxa' name='Close Input Period and Proceed'>]'
      ,q'[      <bpmn:incoming>Flow_1qh3zb4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1320p09</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id='Event_1p4ubrv'>]'
      ,q'[      <bpmn:incoming>Flow_1hkw8tj</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:eventBasedGateway id='Gateway_EBG' name='Event Based Gateway&#10;- picks first event to occur only'>]'
      ,q'[      <bpmn:incoming>Flow_1sl1mr5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1hbzc2c</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0ab2ygs</bpmn:outgoing>]'
      ,q'[    </bpmn:eventBasedGateway>]'
      ,q'[    <bpmn:intermediateCatchEvent id='Event_TimerG' name='Timer G'>]'
      ,q'[      <bpmn:incoming>Flow_1hbzc2c</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_04ew1x4</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id='TimerEventDefinition_1gjz34e'>]'
      ,q'[        <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT2M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:intermediateCatchEvent id='Event_TimerH' name='Timer H'>]'
      ,q'[      <bpmn:incoming>Flow_0ab2ygs</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0bevchi</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id='TimerEventDefinition_12qqs40'>]'
      ,q'[        <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT3M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:task id='Activity_10uxh66' name='G'>]'
      ,q'[      <bpmn:incoming>Flow_04ew1x4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0e3ltbj</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:exclusiveGateway id='Gateway_1td0zrj'>]'
      ,q'[      <bpmn:incoming>Flow_0e3ltbj</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0mw3yoc</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1lkzgyz</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:task id='Activity_00w4hzt' name='H'>]'
      ,q'[      <bpmn:incoming>Flow_0bevchi</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mw3yoc</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id='Event_1tokmzs' name='Process End'>]'
      ,q'[      <bpmn:incoming>Flow_05y14rb</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:parallelGateway id='Gateway_1jigpbk' name='Merging Parallel Gateway&#10;- Merges and&#10;Syncronises paths'>]'
      ,q'[      <bpmn:incoming>Flow_0g7i78z</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1ml8gyp</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1lkzgyz</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1320p09</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_05y14rb</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:serviceTask id='Activity_0r8att5' name='Send&#10;reminder&#10;Email'>]'
      ,q'[      <bpmn:incoming>Flow_1bssnss</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_139aflr</bpmn:outgoing>]'
      ,q'[      <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:boundaryEvent id='Event_18civ6r' cancelActivity='false' attachedToRef='Activity_userTask'>]'
      ,q'[      <bpmn:outgoing>Flow_1bssnss</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id='TimerEventDefinition_12bhsbj'>]'
      ,q'[        <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT120M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1u5kfn1' sourceRef='StartEvent_1' targetRef='Activity_stdTask' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0k089wp' sourceRef='Activity_stdTask' targetRef='Gateway_MainSplit' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1q7lyne' sourceRef='Gateway_MainSplit' targetRef='Activity_userTask' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0av2w95' sourceRef='Activity_userTask' targetRef='Activity_scriptTask' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_15m8qw2' sourceRef='Gateway_MainSplit' targetRef='Activity_0j8t4fy' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0395vvt' sourceRef='Activity_scriptTask' targetRef='Activity_ManualTask' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_12bf5hj' sourceRef='Activity_ManualTask' targetRef='Gateway_1a5in2d' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_B' name='route B&#10;(default path)' sourceRef='Gateway_1a5in2d' targetRef='Activity_1ev2yqx' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_A' name='route A' sourceRef='Gateway_1a5in2d' targetRef='Activity_0owgu48' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_C' name='route C&#10;(bad path)' sourceRef='Gateway_1a5in2d' targetRef='Event_0sjg6jc' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1dyxw9o' sourceRef='Activity_1ev2yqx' targetRef='Gateway_0elt40y' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_03kgsyn' sourceRef='Activity_0owgu48' targetRef='Gateway_0elt40y' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1bssnss' sourceRef='Event_18civ6r' targetRef='Activity_0r8att5' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_139aflr' sourceRef='Activity_0r8att5' targetRef='Event_1j5qhdr' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0f0z11o' sourceRef='Gateway_0elt40y' targetRef='Gateway_0h6qtrg' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_D' name='path D' sourceRef='Gateway_0h6qtrg' targetRef='Activity_05958zc' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_02uxial' sourceRef='Activity_05958zc' targetRef='Gateway_1edlcc8' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0miynpd' name='path C' sourceRef='Gateway_0h6qtrg' targetRef='Activity_1n9ks7b' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_135n6n7' sourceRef='Activity_1n9ks7b' targetRef='Gateway_1edlcc8' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_E' name='path E&#10;(default path)' sourceRef='Gateway_0h6qtrg' targetRef='Activity_1o9oe05' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1mpw2yu' sourceRef='Activity_1o9oe05' targetRef='Gateway_1edlcc8' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0g7i78z' sourceRef='Activity_0j8t4fy' targetRef='Gateway_1jigpbk' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1ml8gyp' sourceRef='Gateway_1edlcc8' targetRef='Gateway_1jigpbk' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0f14hah' sourceRef='Event_0g4ggyl' targetRef='Activity_Notify' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1qh3zb4' sourceRef='Event_0crg1vq' targetRef='Activity_08afvxa' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_10ebnqk' sourceRef='Event_1jpqrhk' targetRef='Activity_03exw8r' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1hkw8tj' sourceRef='Activity_03exw8r' targetRef='Event_1p4ubrv' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_05y14rb' sourceRef='Gateway_1jigpbk' targetRef='Event_1tokmzs' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1sl1mr5' sourceRef='Gateway_MainSplit' targetRef='Gateway_EBG' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1hbzc2c' sourceRef='Gateway_EBG' targetRef='Event_TimerG' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0ab2ygs' sourceRef='Gateway_EBG' targetRef='Event_TimerH' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_04ew1x4' sourceRef='Event_TimerG' targetRef='Activity_10uxh66' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0e3ltbj' sourceRef='Activity_10uxh66' targetRef='Gateway_1td0zrj' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0bevchi' sourceRef='Event_TimerH' targetRef='Activity_00w4hzt' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_0mw3yoc' sourceRef='Activity_00w4hzt' targetRef='Gateway_1td0zrj' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1lkzgyz' sourceRef='Gateway_1td0zrj' targetRef='Gateway_1jigpbk' />]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1d0hvhw' sourceRef='Activity_Notify' targetRef='Event_1v7plws' />]'
      ,q'[    <bpmn:subProcess id='Activity_0j8t4fy' name='Sub Process F'>]'
      ,q'[      <bpmn:incoming>Flow_15m8qw2</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0g7i78z</bpmn:outgoing>]'
      ,q'[      <bpmn:startEvent id='Event_08c82vn' name='F Start'>]'
      ,q'[        <bpmn:outgoing>Flow_06l5x9i</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_06l5x9i' sourceRef='Event_08c82vn' targetRef='Gateway_FSplit' />]'
      ,q'[      <bpmn:parallelGateway id='Gateway_FSplit' name='F Split'>]'
      ,q'[        <bpmn:incoming>Flow_06l5x9i</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_toF2</bpmn:outgoing>]'
      ,q'[        <bpmn:outgoing>Flow_toF1</bpmn:outgoing>]'
      ,q'[      </bpmn:parallelGateway>]'
      ,q'[      <bpmn:subProcess id='Activity_subProcF1' name='Sub Process F1'>]'
      ,q'[        <bpmn:incoming>Flow_toF1</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1eyfbtd</bpmn:outgoing>]'
      ,q'[        <bpmn:startEvent id='Event_F1Start' name='F1 Start'>]'
      ,q'[          <bpmn:outgoing>Flow_0oyf6xf</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:task id='Activity_0gj73o4' name='Task F1A&#10;(with Timeout Timer)'>]'
      ,q'[          <bpmn:incoming>Flow_0oyf6xf</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_1rsbmbe</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_0oyf6xf' sourceRef='Event_F1Start' targetRef='Activity_0gj73o4' />]'
      ,q'[        <bpmn:exclusiveGateway id='Gateway_1vj65s8' name='All OK?' default='Flow_1qccguc'>]'
      ,q'[          <bpmn:incoming>Flow_1rsbmbe</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_1qccguc</bpmn:outgoing>]'
      ,q'[          <bpmn:outgoing>Flow_1f2lsls</bpmn:outgoing>]'
      ,q'[        </bpmn:exclusiveGateway>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_1rsbmbe' sourceRef='Activity_0gj73o4' targetRef='Gateway_1vj65s8' />]'
      ,q'[        <bpmn:task id='Activity_0u7ha21' name='F1B'>]'
      ,q'[          <bpmn:incoming>Flow_1qccguc</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_13gdlkj</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_1qccguc' name='Yes' sourceRef='Gateway_1vj65s8' targetRef='Activity_0u7ha21' />]'
      ,q'[        <bpmn:endEvent id='Event_1km6ey2' name='F1 Happy End'>]'
      ,q'[          <bpmn:incoming>Flow_13gdlkj</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_13gdlkj' sourceRef='Activity_0u7ha21' targetRef='Event_1km6ey2' />]'
      ,q'[        <bpmn:task id='Activity_1jlvbjb' name='Process Error Handler'>]'
      ,q'[          <bpmn:incoming>Flow_1f2lsls</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_13w3z3z</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_1f2lsls' name='No - Process Error' sourceRef='Gateway_1vj65s8' targetRef='Activity_1jlvbjb' />]'
      ,q'[        <bpmn:sequenceFlow id='Flow_13w3z3z' sourceRef='Activity_1jlvbjb' targetRef='Event_104j4jl' />]'
      ,q'[        <bpmn:endEvent id='Event_104j4jl' name='F1 Error End'>]'
      ,q'[          <bpmn:incoming>Flow_13w3z3z</bpmn:incoming>]'
      ,q'[          <bpmn:errorEventDefinition id='ErrorEventDefinition_1x4hxz5' />]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:task id='Activity_0guy1ox' name='Handle Timeout'>]'
      ,q'[          <bpmn:incoming>Flow_03ice2s</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_10714n0</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_03ice2s' sourceRef='Event_1ko5r23' targetRef='Activity_0guy1ox' />]'
      ,q'[        <bpmn:sequenceFlow id='Flow_10714n0' sourceRef='Activity_0guy1ox' targetRef='Event_0mtust8' />]'
      ,q'[        <bpmn:endEvent id='Event_0mtust8' name='Terminating End&#10;Immediately ends Sub Process'>]'
      ,q'[          <bpmn:incoming>Flow_10714n0</bpmn:incoming>]'
      ,q'[          <bpmn:terminateEventDefinition id='TerminateEventDefinition_0hlwdiw' />]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:boundaryEvent id='Event_1ko5r23' name='Interrupting Timer Boundary Event' attachedToRef='Activity_0gj73o4'>]'
      ,q'[          <bpmn:outgoing>Flow_03ice2s</bpmn:outgoing>]'
      ,q'[          <bpmn:timerEventDefinition id='TimerEventDefinition_0h3jerj'>]'
      ,q'[            <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT120M</bpmn:timeDuration>]'
      ,q'[          </bpmn:timerEventDefinition>]'
      ,q'[        </bpmn:boundaryEvent>]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[      <bpmn:subProcess id='Activity_subProcF2' name='Sub Process F2'>]'
      ,q'[        <bpmn:incoming>Flow_toF2</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1kgfn9a</bpmn:outgoing>]'
      ,q'[        <bpmn:startEvent id='Event_F2Start' name='F2 Start'>]'
      ,q'[          <bpmn:outgoing>Flow_0nyapnc</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_0nyapnc' sourceRef='Event_F2Start' targetRef='Activity_subProcF2A' />]'
      ,q'[        <bpmn:exclusiveGateway id='Gateway_0rv26eu' name='Everything OK?' default='Flow_0hzmts8'>]'
      ,q'[          <bpmn:incoming>Flow_0bler3b</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0hzmts8</bpmn:outgoing>]'
      ,q'[          <bpmn:outgoing>Flow_1dar5q9</bpmn:outgoing>]'
      ,q'[        </bpmn:exclusiveGateway>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_0bler3b' sourceRef='Activity_subProcF2A' targetRef='Gateway_0rv26eu' />]'
      ,q'[        <bpmn:exclusiveGateway id='Gateway_0ixs2o5'>]'
      ,q'[          <bpmn:incoming>Flow_0hzmts8</bpmn:incoming>]'
      ,q'[          <bpmn:incoming>Flow_0hra594</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_1t5akvc</bpmn:outgoing>]'
      ,q'[        </bpmn:exclusiveGateway>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_0hzmts8' name='Y' sourceRef='Gateway_0rv26eu' targetRef='Gateway_0ixs2o5' />]'
      ,q'[        <bpmn:sequenceFlow id='Flow_1dar5q9' name='N' sourceRef='Gateway_0rv26eu' targetRef='Event_16famrn' />]'
      ,q'[        <bpmn:sequenceFlow id='Flow_0hra594' sourceRef='Event_16famrn' targetRef='Gateway_0ixs2o5' />]'
      ,q'[        <bpmn:intermediateThrowEvent id='Event_16famrn' name='Escalation Intermediate Throw Event'>]'
      ,q'[          <bpmn:incoming>Flow_1dar5q9</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0hra594</bpmn:outgoing>]'
      ,q'[          <bpmn:escalationEventDefinition id='EscalationEventDefinition_0ue9ndq' />]'
      ,q'[        </bpmn:intermediateThrowEvent>]'
      ,q'[        <bpmn:sequenceFlow id='Flow_1t5akvc' sourceRef='Gateway_0ixs2o5' targetRef='Event_1c43ovj' />]'
      ,q'[        <bpmn:endEvent id='Event_1c43ovj' name='F2 End'>]'
      ,q'[          <bpmn:incoming>Flow_1t5akvc</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:subProcess id='Activity_subProcF2A' name='F2A Collapsed SubProcess&#10;(Click to Open)'>]'
      ,q'[          <bpmn:incoming>Flow_0nyapnc</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0bler3b</bpmn:outgoing>]'
      ,q'[          <bpmn:startEvent id='Event_F2AStart' name='F2A Start'>]'
      ,q'[            <bpmn:outgoing>Flow_0x0i35d</bpmn:outgoing>]'
      ,q'[          </bpmn:startEvent>]'
      ,q'[          <bpmn:task id='Activity_F2ATask' name='F2ATask'>]'
      ,q'[            <bpmn:incoming>Flow_0x0i35d</bpmn:incoming>]'
      ,q'[            <bpmn:outgoing>Flow_1oedyea</bpmn:outgoing>]'
      ,q'[          </bpmn:task>]'
      ,q'[          <bpmn:sequenceFlow id='Flow_0x0i35d' sourceRef='Event_F2AStart' targetRef='Activity_F2ATask' />]'
      ,q'[          <bpmn:endEvent id='Event_EndF2A' name='EndF2A'>]'
      ,q'[            <bpmn:incoming>Flow_1oedyea</bpmn:incoming>]'
      ,q'[          </bpmn:endEvent>]'
      ,q'[          <bpmn:sequenceFlow id='Flow_1oedyea' sourceRef='Activity_F2ATask' targetRef='Event_EndF2A' />]'
      ,q'[        </bpmn:subProcess>]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_toF2' name='to F2' sourceRef='Gateway_FSplit' targetRef='Activity_subProcF2' />]'
      ,q'[      <bpmn:sequenceFlow id='Flow_toF1' name='to Fl' sourceRef='Gateway_FSplit' targetRef='Activity_subProcF1' />]'
      ,q'[      <bpmn:sequenceFlow id='Flow_05k289e' sourceRef='Event_1i9jh45' targetRef='Event_17azdxc' />]'
      ,q'[      <bpmn:endEvent id='Event_03lhv9d'>]'
      ,q'[        <bpmn:incoming>Flow_1eyfbtd</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_1eyfbtd' sourceRef='Activity_subProcF1' targetRef='Event_03lhv9d' />]'
      ,q'[      <bpmn:endEvent id='Event_1wkp2r5'>]'
      ,q'[        <bpmn:incoming>Flow_1kgfn9a</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_1kgfn9a' sourceRef='Activity_subProcF2' targetRef='Event_1wkp2r5' />]'
      ,q'[      <bpmn:boundaryEvent id='Event_F2Esc' name='Non-Interrupting Escalation Catch&#10;Boundary Event' cancelActivity='false' attachedToRef='Activity_subProcF2'>]'
      ,q'[        <bpmn:outgoing>Flow_031cc6f</bpmn:outgoing>]'
      ,q'[        <bpmn:escalationEventDefinition id='EscalationEventDefinition_1afovgx' />]'
      ,q'[      </bpmn:boundaryEvent>]'
      ,q'[      <bpmn:boundaryEvent id='Event_1i9jh45' name='Error Boundary Event' attachedToRef='Activity_subProcF1'>]'
      ,q'[        <bpmn:outgoing>Flow_05k289e</bpmn:outgoing>]'
      ,q'[        <bpmn:errorEventDefinition id='ErrorEventDefinition_11g00uv' />]'
      ,q'[      </bpmn:boundaryEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_031cc6f' sourceRef='Event_F2Esc' targetRef='Activity_07bme0u' />]'
      ,q'[      <bpmn:sequenceFlow id='Flow_0wjommq' sourceRef='Activity_07bme0u' targetRef='Event_0pyofjb' />]'
      ,q'[      <bpmn:intermediateThrowEvent id='Event_0pyofjb' name='LinkA'>]'
      ,q'[        <bpmn:incoming>Flow_0wjommq</bpmn:incoming>]'
      ,q'[        <bpmn:linkEventDefinition id='LinkEventDefinition_0imlax6' name='' />]'
      ,q'[      </bpmn:intermediateThrowEvent>]'
      ,q'[      <bpmn:intermediateCatchEvent id='Event_03nb0gh' name='LinkA'>]'
      ,q'[        <bpmn:outgoing>Flow_0a3amjb</bpmn:outgoing>]'
      ,q'[        <bpmn:linkEventDefinition id='LinkEventDefinition_1klargh' name='' />]'
      ,q'[      </bpmn:intermediateCatchEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_0a3amjb' sourceRef='Event_03nb0gh' targetRef='Event_1ar0fb8' />]'
      ,q'[      <bpmn:exclusiveGateway id='Gateway_05mhmtp' name='All OK Now?' default='Flow_1jynl0c'>]'
      ,q'[        <bpmn:incoming>Flow_0uoidfy</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1jynl0c</bpmn:outgoing>]'
      ,q'[        <bpmn:outgoing>Flow_0zm2lio</bpmn:outgoing>]'
      ,q'[      </bpmn:exclusiveGateway>]'
      ,q'[      <bpmn:endEvent id='Event_194ut3i'>]'
      ,q'[        <bpmn:incoming>Flow_1jynl0c</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_1jynl0c' name='Y' sourceRef='Gateway_05mhmtp' targetRef='Event_194ut3i' />]'
      ,q'[      <bpmn:intermediateThrowEvent id='Event_17azdxc' name='LinkA'>]'
      ,q'[        <bpmn:incoming>Flow_05k289e</bpmn:incoming>]'
      ,q'[        <bpmn:linkEventDefinition id='LinkEventDefinition_098srpp' name='' />]'
      ,q'[      </bpmn:intermediateThrowEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_0zm2lio' name='N' sourceRef='Gateway_05mhmtp' targetRef='Activity_0kj16yj' />]'
      ,q'[      <bpmn:sequenceFlow id='Flow_0203h3w' sourceRef='Activity_0kj16yj' targetRef='Event_0yd41jx' />]'
      ,q'[      <bpmn:endEvent id='Event_0yd41jx' name='Escalating End'>]'
      ,q'[        <bpmn:incoming>Flow_0203h3w</bpmn:incoming>]'
      ,q'[        <bpmn:escalationEventDefinition id='EscalationEventDefinition_1niprfw' />]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id='Flow_0uoidfy' sourceRef='Event_1ar0fb8' targetRef='Gateway_05mhmtp' />]'
      ,q'[      <bpmn:intermediateCatchEvent id='Event_1ar0fb8' name='Timer Catch Event&#10;(2 Day Delay)'>]'
      ,q'[        <bpmn:incoming>Flow_0a3amjb</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0uoidfy</bpmn:outgoing>]'
      ,q'[        <bpmn:timerEventDefinition id='TimerEventDefinition_1ywd80b'>]'
      ,q'[          <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT2M</bpmn:timeDuration>]'
      ,q'[        </bpmn:timerEventDefinition>]'
      ,q'[      </bpmn:intermediateCatchEvent>]'
      ,q'[      <bpmn:serviceTask id='Activity_07bme0u' name='Email Manager to Help'>]'
      ,q'[        <bpmn:incoming>Flow_031cc6f</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0wjommq</bpmn:outgoing>]'
      ,q'[        <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[      </bpmn:serviceTask>]'
      ,q'[      <bpmn:task id='Activity_0kj16yj' name='Prepare for SubProcess&#10;Termination'>]'
      ,q'[        <bpmn:incoming>Flow_0zm2lio</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0203h3w</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:textAnnotation id='TextAnnotation_1nzqkt7'>]'
      ,q'[        <bpmn:text>All running paths must end before the sub process completes and moves on to the next task</bpmn:text>]'
      ,q'[      </bpmn:textAnnotation>]'
      ,q'[      <bpmn:association id='Association_1x9wuxi' sourceRef='Event_03lhv9d' targetRef='TextAnnotation_1nzqkt7' />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:boundaryEvent id='Event_0crg1vq' name='Interrupting Timer on F' attachedToRef='Activity_0j8t4fy'>]'
      ,q'[      <bpmn:outgoing>Flow_1qh3zb4</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id='TimerEventDefinition_0b8p9qg'>]'
      ,q'[        <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT130M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:boundaryEvent id='Event_1jpqrhk' name='Non Interrupting Timer on F' cancelActivity='false' attachedToRef='Activity_0j8t4fy'>]'
      ,q'[      <bpmn:outgoing>Flow_10ebnqk</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id='TimerEventDefinition_17ny1xz'>]'
      ,q'[        <bpmn:timeDuration xsi:type='bpmn:tFormalExpression'>PT120M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:boundaryEvent id='Event_0g4ggyl' name='Interrupting Escalation Handler&#10;(Terminates F)' attachedToRef='Activity_0j8t4fy'>]'
      ,q'[      <bpmn:outgoing>Flow_0f14hah</bpmn:outgoing>]'
      ,q'[      <bpmn:escalationEventDefinition id='EscalationEventDefinition_1i2ea4w' />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:scriptTask id='Activity_03exw8r' name='Post Reminders'>]'
      ,q'[      <bpmn:incoming>Flow_10ebnqk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1hkw8tj</bpmn:outgoing>]'
      ,q'[      <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:task id='Activity_Notify' name='Notify Manager of Termination'>]'
      ,q'[      <bpmn:incoming>Flow_0f14hah</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1d0hvhw</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id='Flow_1320p09' sourceRef='Activity_08afvxa' targetRef='Gateway_1jigpbk' />]'
      ,q'[    <bpmn:endEvent id='Event_1v7plws' name='F Term End'>]'
      ,q'[      <bpmn:incoming>Flow_1d0hvhw</bpmn:incoming>]'
      ,q'[      <bpmn:terminateEventDefinition id='TerminateEventDefinition_1hfrp0v' />]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:textAnnotation id='TextAnnotation_0ig39o8'>]'
      ,q'[      <bpmn:text>Annotations help explain the model to readers</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id='Association_14q8sx5' sourceRef='Activity_userTask' targetRef='TextAnnotation_0ig39o8' />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id='BPMNDiagram_1'>]'
      ,q'[    <bpmndi:BPMNPlane id='BPMNPlane_1' bpmnElement='Collaboration_0iz09gx'>]'
      ,q'[      <bpmndi:BPMNShape id='Participant_1eelczk_di' bpmnElement='Participant_1eelczk' isHorizontal='true'>]'
      ,q'[        <dc:Bounds x='160' y='80' width='1850' height='1240' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Lane_1malyps_di' bpmnElement='Lane_1malyps' isHorizontal='true'>]'
      ,q'[        <dc:Bounds x='190' y='420' width='1820' height='900' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Lane_09houmv_di' bpmnElement='Lane_09houmv' isHorizontal='true'>]'
      ,q'[        <dc:Bounds x='190' y='80' width='1820' height='340' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1320p09_di' bpmnElement='Flow_1320p09'>]'
      ,q'[        <di:waypoint x='1720' y='1180' />]'
      ,q'[        <di:waypoint x='1890' y='1180' />]'
      ,q'[        <di:waypoint x='1890' y='790' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1d0hvhw_di' bpmnElement='Flow_1d0hvhw'>]'
      ,q'[        <di:waypoint x='1140' y='1180' />]'
      ,q'[        <di:waypoint x='1162' y='1180' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1lkzgyz_di' bpmnElement='Flow_1lkzgyz'>]'
      ,q'[        <di:waypoint x='915' y='1260' />]'
      ,q'[        <di:waypoint x='1890' y='1260' />]'
      ,q'[        <di:waypoint x='1890' y='790' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0mw3yoc_di' bpmnElement='Flow_0mw3yoc'>]'
      ,q'[        <di:waypoint x='810' y='1260' />]'
      ,q'[        <di:waypoint x='865' y='1260' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0bevchi_di' bpmnElement='Flow_0bevchi'>]'
      ,q'[        <di:waypoint x='658' y='1260' />]'
      ,q'[        <di:waypoint x='710' y='1260' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0e3ltbj_di' bpmnElement='Flow_0e3ltbj'>]'
      ,q'[        <di:waypoint x='810' y='1160' />]'
      ,q'[        <di:waypoint x='890' y='1160' />]'
      ,q'[        <di:waypoint x='890' y='1235' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_04ew1x4_di' bpmnElement='Flow_04ew1x4'>]'
      ,q'[        <di:waypoint x='658' y='1160' />]'
      ,q'[        <di:waypoint x='710' y='1160' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0ab2ygs_di' bpmnElement='Flow_0ab2ygs'>]'
      ,q'[        <di:waypoint x='550' y='1185' />]'
      ,q'[        <di:waypoint x='550' y='1260' />]'
      ,q'[        <di:waypoint x='622' y='1260' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1hbzc2c_di' bpmnElement='Flow_1hbzc2c'>]'
      ,q'[        <di:waypoint x='575' y='1160' />]'
      ,q'[        <di:waypoint x='622' y='1160' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1sl1mr5_di' bpmnElement='Flow_1sl1mr5'>]'
      ,q'[        <di:waypoint x='480' y='625' />]'
      ,q'[        <di:waypoint x='480' y='1160' />]'
      ,q'[        <di:waypoint x='525' y='1160' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_05y14rb_di' bpmnElement='Flow_05y14rb'>]'
      ,q'[        <di:waypoint x='1915' y='765' />]'
      ,q'[        <di:waypoint x='1952' y='765' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1hkw8tj_di' bpmnElement='Flow_1hkw8tj'>]'
      ,q'[        <di:waypoint x='1420' y='1180' />]'
      ,q'[        <di:waypoint x='1452' y='1180' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_10ebnqk_di' bpmnElement='Flow_10ebnqk'>]'
      ,q'[        <di:waypoint x='1220' y='1128' />]'
      ,q'[        <di:waypoint x='1220' y='1180' />]'
      ,q'[        <di:waypoint x='1320' y='1180' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1qh3zb4_di' bpmnElement='Flow_1qh3zb4'>]'
      ,q'[        <di:waypoint x='1560' y='1128' />]'
      ,q'[        <di:waypoint x='1560' y='1180' />]'
      ,q'[        <di:waypoint x='1620' y='1180' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0f14hah_di' bpmnElement='Flow_0f14hah'>]'
      ,q'[        <di:waypoint x='990' y='1128' />]'
      ,q'[        <di:waypoint x='990' y='1180' />]'
      ,q'[        <di:waypoint x='1040' y='1180' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1ml8gyp_di' bpmnElement='Flow_1ml8gyp'>]'
      ,q'[        <di:waypoint x='1765' y='250' />]'
      ,q'[        <di:waypoint x='1890' y='250' />]'
      ,q'[        <di:waypoint x='1890' y='740' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0g7i78z_di' bpmnElement='Flow_0g7i78z'>]'
      ,q'[        <di:waypoint x='1680' y='765' />]'
      ,q'[        <di:waypoint x='1865' y='765' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1mpw2yu_di' bpmnElement='Flow_1mpw2yu'>]'
      ,q'[        <di:waypoint x='1640' y='360' />]'
      ,q'[        <di:waypoint x='1740' y='360' />]'
      ,q'[        <di:waypoint x='1740' y='275' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1wt3yjm_di' bpmnElement='Flow_E'>]'
      ,q'[        <di:waypoint x='1440' y='275' />]'
      ,q'[        <di:waypoint x='1440' y='360' />]'
      ,q'[        <di:waypoint x='1540' y='360' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1447' y='326' width='65' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_135n6n7_di' bpmnElement='Flow_135n6n7'>]'
      ,q'[        <di:waypoint x='1640' y='150' />]'
      ,q'[        <di:waypoint x='1740' y='150' />]'
      ,q'[        <di:waypoint x='1740' y='225' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0miynpd_di' bpmnElement='Flow_0miynpd'>]'
      ,q'[        <di:waypoint x='1440' y='225' />]'
      ,q'[        <di:waypoint x='1440' y='150' />]'
      ,q'[        <di:waypoint x='1540' y='150' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1463' y='133' width='33' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_02uxial_di' bpmnElement='Flow_02uxial'>]'
      ,q'[        <di:waypoint x='1640' y='250' />]'
      ,q'[        <di:waypoint x='1715' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_03skdre_di' bpmnElement='Flow_D'>]'
      ,q'[        <di:waypoint x='1465' y='250' />]'
      ,q'[        <di:waypoint x='1540' y='250' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1473' y='232' width='33' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0f0z11o_di' bpmnElement='Flow_0f0z11o'>]'
      ,q'[        <di:waypoint x='1345' y='250' />]'
      ,q'[        <di:waypoint x='1415' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_139aflr_di' bpmnElement='Flow_139aflr'>]'
      ,q'[        <di:waypoint x='750' y='370' />]'
      ,q'[        <di:waypoint x='802' y='370' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1bssnss_di' bpmnElement='Flow_1bssnss'>]'
      ,q'[        <di:waypoint x='580' y='308' />]'
      ,q'[        <di:waypoint x='580' y='370' />]'
      ,q'[        <di:waypoint x='650' y='370' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_03kgsyn_di' bpmnElement='Flow_03kgsyn'>]'
      ,q'[        <di:waypoint x='1230' y='140' />]'
      ,q'[        <di:waypoint x='1320' y='140' />]'
      ,q'[        <di:waypoint x='1320' y='225' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1dyxw9o_di' bpmnElement='Flow_1dyxw9o'>]'
      ,q'[        <di:waypoint x='1230' y='250' />]'
      ,q'[        <di:waypoint x='1295' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0xjsivb_di' bpmnElement='Flow_C'>]'
      ,q'[        <di:waypoint x='1040' y='275' />]'
      ,q'[        <di:waypoint x='1040' y='360' />]'
      ,q'[        <di:waypoint x='1132' y='360' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1054' y='326' width='51' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0iu6gi4_di' bpmnElement='Flow_A'>]'
      ,q'[        <di:waypoint x='1040' y='225' />]'
      ,q'[        <di:waypoint x='1040' y='140' />]'
      ,q'[        <di:waypoint x='1130' y='140' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1062' y='143' width='36' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0ir2osx_di' bpmnElement='Flow_B'>]'
      ,q'[        <di:waypoint x='1065' y='250' />]'
      ,q'[        <di:waypoint x='1130' y='250' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1057' y='216' width='65' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_12bf5hj_di' bpmnElement='Flow_12bf5hj'>]'
      ,q'[        <di:waypoint x='950' y='250' />]'
      ,q'[        <di:waypoint x='1015' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0395vvt_di' bpmnElement='Flow_0395vvt'>]'
      ,q'[        <di:waypoint x='790' y='250' />]'
      ,q'[        <di:waypoint x='850' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_15m8qw2_di' bpmnElement='Flow_15m8qw2'>]'
      ,q'[        <di:waypoint x='505' y='600' />]'
      ,q'[        <di:waypoint x='600' y='600' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0av2w95_di' bpmnElement='Flow_0av2w95'>]'
      ,q'[        <di:waypoint x='630' y='250' />]'
      ,q'[        <di:waypoint x='690' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1q7lyne_di' bpmnElement='Flow_1q7lyne'>]'
      ,q'[        <di:waypoint x='480' y='575' />]'
      ,q'[        <di:waypoint x='480' y='250' />]'
      ,q'[        <di:waypoint x='530' y='250' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0k089wp_di' bpmnElement='Flow_0k089wp'>]'
      ,q'[        <di:waypoint x='400' y='600' />]'
      ,q'[        <di:waypoint x='455' y='600' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1u5kfn1_di' bpmnElement='Flow_1u5kfn1'>]'
      ,q'[        <di:waypoint x='248' y='600' />]'
      ,q'[        <di:waypoint x='300' y='600' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='_BPMNShape_StartEvent_2' bpmnElement='StartEvent_1'>]'
      ,q'[        <dc:Bounds x='212' y='582' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='218' y='625' width='24' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_05egit3_di' bpmnElement='Activity_stdTask'>]'
      ,q'[        <dc:Bounds x='300' y='560' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_19sx8sy_di' bpmnElement='Gateway_MainSplit'>]'
      ,q'[        <dc:Bounds x='455' y='575' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='488' y='632' width='84' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0c53mbs_di' bpmnElement='Activity_userTask'>]'
      ,q'[        <dc:Bounds x='530' y='210' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1d8dhsd_di' bpmnElement='Activity_scriptTask'>]'
      ,q'[        <dc:Bounds x='690' y='210' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_03tagro_di' bpmnElement='Activity_ManualTask'>]'
      ,q'[        <dc:Bounds x='850' y='210' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_1a5in2d_di' bpmnElement='Gateway_1a5in2d' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1015' y='225' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='950' y='180' width='80' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1ev2yqx_di' bpmnElement='Activity_1ev2yqx'>]'
      ,q'[        <dc:Bounds x='1130' y='210' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0owgu48_di' bpmnElement='Activity_0owgu48'>]'
      ,q'[        <dc:Bounds x='1130' y='100' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1citjar_di' bpmnElement='Event_0sjg6jc'>]'
      ,q'[        <dc:Bounds x='1132' y='342' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1173' y='360' width='73' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0elt40y_di' bpmnElement='Gateway_0elt40y' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1295' y='225' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1304' y='282' width='32' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1j5qhdr_di' bpmnElement='Event_1j5qhdr'>]'
      ,q'[        <dc:Bounds x='802' y='352' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='810' y='395' width='20' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0pqx7yh_di' bpmnElement='Gateway_0h6qtrg'>]'
      ,q'[        <dc:Bounds x='1415' y='225' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1345' y='190' width='90' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_05958zc_di' bpmnElement='Activity_05958zc'>]'
      ,q'[        <dc:Bounds x='1540' y='210' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0bkzha0_di' bpmnElement='Gateway_1edlcc8'>]'
      ,q'[        <dc:Bounds x='1715' y='225' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1758' y='282' width='83' height='66' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1n9ks7b_di' bpmnElement='Activity_1n9ks7b'>]'
      ,q'[        <dc:Bounds x='1540' y='110' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1o9oe05_di' bpmnElement='Activity_1o9oe05'>]'
      ,q'[        <dc:Bounds x='1540' y='320' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_08afvxa_di' bpmnElement='Activity_08afvxa'>]'
      ,q'[        <dc:Bounds x='1620' y='1140' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1p4ubrv_di' bpmnElement='Event_1p4ubrv'>]'
      ,q'[        <dc:Bounds x='1452' y='1162' width='36' height='36' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0hjgvl4_di' bpmnElement='Gateway_EBG'>]'
      ,q'[        <dc:Bounds x='525' y='1135' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='438' y='1176' width='83' height='53' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1rp12bz_di' bpmnElement='Event_TimerG'>]'
      ,q'[        <dc:Bounds x='622' y='1142' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='621' y='1185' width='40' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_19z3jbf_di' bpmnElement='Event_TimerH'>]'
      ,q'[        <dc:Bounds x='622' y='1242' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='621' y='1285' width='39' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_10uxh66_di' bpmnElement='Activity_10uxh66'>]'
      ,q'[        <dc:Bounds x='710' y='1120' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_1td0zrj_di' bpmnElement='Gateway_1td0zrj' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='865' y='1235' width='50' height='50' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_00w4hzt_di' bpmnElement='Activity_00w4hzt'>]'
      ,q'[        <dc:Bounds x='710' y='1220' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1tokmzs_di' bpmnElement='Event_1tokmzs'>]'
      ,q'[        <dc:Bounds x='1952' y='747' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1939' y='790' width='63' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0mce1tt_di' bpmnElement='Gateway_1jigpbk'>]'
      ,q'[        <dc:Bounds x='1865' y='740' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1785' y='797' width='90' height='53' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_149vhoy_di' bpmnElement='Activity_0r8att5'>]'
      ,q'[        <dc:Bounds x='650' y='330' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_03waax2_di' bpmnElement='Event_1v7plws'>]'
      ,q'[        <dc:Bounds x='1162' y='1162' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1152' y='1205' width='57' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1g13boe_di' bpmnElement='Activity_0j8t4fy' isExpanded='true'>]'
      ,q'[        <dc:Bounds x='600' y='435' width='1080' height='675' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0uoidfy_di' bpmnElement='Flow_0uoidfy'>]'
      ,q'[        <di:waypoint x='1358' y='1035' />]'
      ,q'[        <di:waypoint x='1395' y='1035' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0203h3w_di' bpmnElement='Flow_0203h3w'>]'
      ,q'[        <di:waypoint x='1560' y='935' />]'
      ,q'[        <di:waypoint x='1622' y='935' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0zm2lio_di' bpmnElement='Flow_0zm2lio'>]'
      ,q'[        <di:waypoint x='1420' y='1010' />]'
      ,q'[        <di:waypoint x='1420' y='935' />]'
      ,q'[        <di:waypoint x='1460' y='935' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1431' y='970' width='8' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1jynl0c_di' bpmnElement='Flow_1jynl0c'>]'
      ,q'[        <di:waypoint x='1445' y='1035' />]'
      ,q'[        <di:waypoint x='1622' y='1035' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1530' y='1017' width='8' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0a3amjb_di' bpmnElement='Flow_0a3amjb'>]'
      ,q'[        <di:waypoint x='1288' y='1035' />]'
      ,q'[        <di:waypoint x='1322' y='1035' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0wjommq_di' bpmnElement='Flow_0wjommq'>]'
      ,q'[        <di:waypoint x='1090' y='1035' />]'
      ,q'[        <di:waypoint x='1142' y='1035' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_031cc6f_di' bpmnElement='Flow_031cc6f'>]'
      ,q'[        <di:waypoint x='930' y='973' />]'
      ,q'[        <di:waypoint x='930' y='1035' />]'
      ,q'[        <di:waypoint x='990' y='1035' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1kgfn9a_di' bpmnElement='Flow_1kgfn9a'>]'
      ,q'[        <di:waypoint x='1350' y='805' />]'
      ,q'[        <di:waypoint x='1622' y='805' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1eyfbtd_di' bpmnElement='Flow_1eyfbtd'>]'
      ,q'[        <di:waypoint x='1420' y='555' />]'
      ,q'[        <di:waypoint x='1622' y='555' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_05k289e_di' bpmnElement='Flow_05k289e'>]'
      ,q'[        <di:waypoint x='1438' y='655' />]'
      ,q'[        <di:waypoint x='1622' y='655' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1eru5rx_di' bpmnElement='Flow_toF1'>]'
      ,q'[        <di:waypoint x='710' y='710' />]'
      ,q'[        <di:waypoint x='710' y='595' />]'
      ,q'[        <di:waypoint x='750' y='595' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='716' y='650' width='22' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1c3cdi9_di' bpmnElement='Flow_toF2'>]'
      ,q'[        <di:waypoint x='710' y='760' />]'
      ,q'[        <di:waypoint x='710' y='854' />]'
      ,q'[        <di:waypoint x='760' y='854' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='681' y='651' width='26' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_06l5x9i_di' bpmnElement='Flow_06l5x9i'>]'
      ,q'[        <di:waypoint x='658' y='735' />]'
      ,q'[        <di:waypoint x='685' y='735' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='Event_08c82vn_di' bpmnElement='Event_08c82vn'>]'
      ,q'[        <dc:Bounds x='622' y='717' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='623' y='760' width='34' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0wacmvg_di' bpmnElement='Gateway_FSplit'>]'
      ,q'[        <dc:Bounds x='685' y='710' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='664' y='693' width='32' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1bun2of_di' bpmnElement='Activity_subProcF1' isExpanded='true'>]'
      ,q'[        <dc:Bounds x='750' y='475' width='670' height='255' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_10714n0_di' bpmnElement='Flow_10714n0'>]'
      ,q'[        <di:waypoint x='1020' y='665' />]'
      ,q'[        <di:waypoint x='1052' y='665' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_03ice2s_di' bpmnElement='Flow_03ice2s'>]'
      ,q'[        <di:waypoint x='890' y='603' />]'
      ,q'[        <di:waypoint x='890' y='665' />]'
      ,q'[        <di:waypoint x='920' y='665' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_13w3z3z_di' bpmnElement='Flow_13w3z3z'>]'
      ,q'[        <di:waypoint x='1300' y='655' />]'
      ,q'[        <di:waypoint x='1342' y='655' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1f2lsls_di' bpmnElement='Flow_1f2lsls'>]'
      ,q'[        <di:waypoint x='1120' y='570' />]'
      ,q'[        <di:waypoint x='1120' y='655' />]'
      ,q'[        <di:waypoint x='1200' y='655' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1122' y='621' width='75' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_13gdlkj_di' bpmnElement='Flow_13gdlkj'>]'
      ,q'[        <di:waypoint x='1300' y='545' />]'
      ,q'[        <di:waypoint x='1342' y='545' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1qccguc_di' bpmnElement='Flow_1qccguc'>]'
      ,q'[        <di:waypoint x='1145' y='545' />]'
      ,q'[        <di:waypoint x='1200' y='545' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1164' y='527' width='18' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1rsbmbe_di' bpmnElement='Flow_1rsbmbe'>]'
      ,q'[        <di:waypoint x='940' y='545' />]'
      ,q'[        <di:waypoint x='1095' y='545' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0oyf6xf_di' bpmnElement='Flow_0oyf6xf'>]'
      ,q'[        <di:waypoint x='808' y='545' />]'
      ,q'[        <di:waypoint x='840' y='545' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1atmvvp_di' bpmnElement='Event_F1Start'>]'
      ,q'[        <dc:Bounds x='772' y='527' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='770' y='570' width='40' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0gj73o4_di' bpmnElement='Activity_0gj73o4'>]'
      ,q'[        <dc:Bounds x='840' y='505' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_1vj65s8_di' bpmnElement='Gateway_1vj65s8' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1095' y='520' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1071' y='518' width='38' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0u7ha21_di' bpmnElement='Activity_0u7ha21'>]'
      ,q'[        <dc:Bounds x='1200' y='505' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1km6ey2_di' bpmnElement='Event_1km6ey2'>]'
      ,q'[        <dc:Bounds x='1342' y='527' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1325' y='570' width='71' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1jlvbjb_di' bpmnElement='Activity_1jlvbjb'>]'
      ,q'[        <dc:Bounds x='1200' y='615' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1vevdb0_di' bpmnElement='Event_104j4jl'>]'
      ,q'[        <dc:Bounds x='1342' y='637' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1329' y='680' width='63' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0guy1ox_di' bpmnElement='Activity_0guy1ox'>]'
      ,q'[        <dc:Bounds x='920' y='625' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1snpwfa_di' bpmnElement='Event_0mtust8'>]'
      ,q'[        <dc:Bounds x='1052' y='647' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1027' y='690' width='87' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1obg85y_di' bpmnElement='Event_1ko5r23'>]'
      ,q'[        <dc:Bounds x='872' y='567' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='801' y='595' width='78' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_10prt96_di' bpmnElement='Activity_subProcF2' isExpanded='true'>]'
      ,q'[        <dc:Bounds x='760' y='753' width='590' height='202' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1t5akvc_di' bpmnElement='Flow_1t5akvc'>]'
      ,q'[        <di:waypoint x='1215' y='825' />]'
      ,q'[        <di:waypoint x='1272' y='825' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0hra594_di' bpmnElement='Flow_0hra594'>]'
      ,q'[        <di:waypoint x='1148' y='895' />]'
      ,q'[        <di:waypoint x='1190' y='895' />]'
      ,q'[        <di:waypoint x='1190' y='850' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1dar5q9_di' bpmnElement='Flow_1dar5q9'>]'
      ,q'[        <di:waypoint x='1070' y='850' />]'
      ,q'[        <di:waypoint x='1070' y='895' />]'
      ,q'[        <di:waypoint x='1112' y='895' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1081' y='870' width='8' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0hzmts8_di' bpmnElement='Flow_0hzmts8'>]'
      ,q'[        <di:waypoint x='1095' y='825' />]'
      ,q'[        <di:waypoint x='1165' y='825' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1126' y='807' width='8' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0bler3b_di' bpmnElement='Flow_0bler3b'>]'
      ,q'[        <di:waypoint x='980' y='825' />]'
      ,q'[        <di:waypoint x='1045' y='825' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0nyapnc_di' bpmnElement='Flow_0nyapnc'>]'
      ,q'[        <di:waypoint x='818' y='825' />]'
      ,q'[        <di:waypoint x='880' y='825' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0nq6sli_di' bpmnElement='Event_F2Start'>]'
      ,q'[        <dc:Bounds x='782' y='807' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='780' y='850' width='40' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0rv26eu_di' bpmnElement='Gateway_0rv26eu' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1045' y='800' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1031.5' y='776' width='77' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_0ixs2o5_di' bpmnElement='Gateway_0ixs2o5' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1165' y='800' width='50' height='50' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1kmzijd_di' bpmnElement='Event_16famrn'>]'
      ,q'[        <dc:Bounds x='1112' y='877' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1149' y='905' width='62' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1c43ovj_di' bpmnElement='Event_1c43ovj'>]'
      ,q'[        <dc:Bounds x='1272' y='807' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1272' y='850' width='36' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_03kqukz_di' bpmnElement='Activity_subProcF2A' isExpanded='false'>]'
      ,q'[        <dc:Bounds x='880' y='785' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_1oedyea_di' bpmnElement='Flow_1oedyea'>]'
      ,q'[        <di:waypoint x='970' y='820' />]'
      ,q'[        <di:waypoint x='1022' y='820' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id='Flow_0x0i35d_di' bpmnElement='Flow_0x0i35d'>]'
      ,q'[        <di:waypoint x='818' y='820' />]'
      ,q'[        <di:waypoint x='870' y='820' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0xhv1o8_di' bpmnElement='Event_F2AStart'>]'
      ,q'[        <dc:Bounds x='782' y='802' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='776' y='870' width='47' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1foixjn_di' bpmnElement='Activity_F2ATask'>]'
      ,q'[        <dc:Bounds x='870' y='780' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_07batcd_di' bpmnElement='Event_EndF2A'>]'
      ,q'[        <dc:Bounds x='1022' y='802' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1020' y='845' width='40' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_03lhv9d_di' bpmnElement='Event_03lhv9d'>]'
      ,q'[        <dc:Bounds x='1622' y='537' width='36' height='36' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1wkp2r5_di' bpmnElement='Event_1wkp2r5'>]'
      ,q'[        <dc:Bounds x='1622' y='787' width='36' height='36' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_04jlqb2_di' bpmnElement='Event_0pyofjb'>]'
      ,q'[        <dc:Bounds x='1142' y='1017' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1146' y='1060' width='28' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0s2njo0_di' bpmnElement='Event_03nb0gh'>]'
      ,q'[        <dc:Bounds x='1252' y='1017' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1256' y='1060' width='28' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Gateway_05mhmtp_di' bpmnElement='Gateway_05mhmtp' isMarkerVisible='true'>]'
      ,q'[        <dc:Bounds x='1395' y='1010' width='50' height='50' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1389' y='1067' width='63' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_194ut3i_di' bpmnElement='Event_194ut3i'>]'
      ,q'[        <dc:Bounds x='1622' y='1017' width='36' height='36' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0gb8w62_di' bpmnElement='Event_17azdxc'>]'
      ,q'[        <dc:Bounds x='1622' y='637' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1627' y='680' width='28' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0220gli_di' bpmnElement='Event_0yd41jx'>]'
      ,q'[        <dc:Bounds x='1622' y='917' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1603' y='960' width='74' height='14' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0c9r2uu_di' bpmnElement='Event_1ar0fb8'>]'
      ,q'[        <dc:Bounds x='1322' y='1017' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1306' y='1060' width='68' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0fjkffv_di' bpmnElement='Activity_07bme0u'>]'
      ,q'[        <dc:Bounds x='990' y='995' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0xyp3mc_di' bpmnElement='Activity_0kj16yj'>]'
      ,q'[        <dc:Bounds x='1460' y='895' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='TextAnnotation_1nzqkt7_di' bpmnElement='TextAnnotation_1nzqkt7'>]'
      ,q'[        <dc:Bounds x='1460' y='455' width='132' height='75' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_0s9z99m_di' bpmnElement='Event_1i9jh45'>]'
      ,q'[        <dc:Bounds x='1402' y='637' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1442' y='680' width='75' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1026xtr_di' bpmnElement='Event_F2Esc'>]'
      ,q'[        <dc:Bounds x='912' y='937' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='838' y='975' width='83' height='40' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Association_1x9wuxi_di' bpmnElement='Association_1x9wuxi'>]'
      ,q'[        <di:waypoint x='1625' y='545' />]'
      ,q'[        <di:waypoint x='1592' y='524' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_1dg82fs_di' bpmnElement='Activity_03exw8r'>]'
      ,q'[        <dc:Bounds x='1320' y='1140' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Activity_0clb94i_di' bpmnElement='Activity_Notify'>]'
      ,q'[        <dc:Bounds x='1040' y='1140' width='100' height='80' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='TextAnnotation_0ig39o8_di' bpmnElement='TextAnnotation_0ig39o8'>]'
      ,q'[        <dc:Bounds x='650' y='116' width='140' height='54' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_11dxhil_di' bpmnElement='Event_0g4ggyl'>]'
      ,q'[        <dc:Bounds x='972' y='1092' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='914' y='1123' width='71' height='53' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1xu4vjx_di' bpmnElement='Event_1jpqrhk'>]'
      ,q'[        <dc:Bounds x='1202' y='1092' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1230' y='1126' width='79' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_1rvlutc_di' bpmnElement='Event_0crg1vq'>]'
      ,q'[        <dc:Bounds x='1542' y='1092' width='36' height='36' />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x='1456' y='1126' width='87' height='27' />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id='Event_14ldymq_di' bpmnElement='Event_18civ6r'>]'
      ,q'[        <dc:Bounds x='562' y='272' width='36' height='36' />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id='Association_14q8sx5_di' bpmnElement='Association_14q8sx5'>]'
      ,q'[        <di:waypoint x='620' y='210' />]'
      ,q'[        <di:waypoint x='661' y='170' />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_bpmn_parser_pkg.upload_and_parse(
    pi_dgrm_name => 'V5FullSyntax',
    pi_dgrm_version => '0',
    pi_dgrm_category => 'My demos',
    pi_dgrm_content => l_dgrm_content
);
end;
/
