
PROMPT >> Loading Example "MyBigExportExample"
begin
insert into flow_diagrams( dgrm_name, dgrm_content)
 values (
'MyBigExportExample',
apex_string.join_clob(
  apex_t_varchar2(
  '<?xml version="1.0" encoding="UTF-8"?>'
  , '<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="7.2.0">'
  , '  <bpmn:collaboration id="Collaboration_03m7mlg">'
  , '    <bpmn:participant id="Participant_1bg6eoy" name="MyBigExportCo" processRef="Process_0rxermh" />'
  , '  </bpmn:collaboration>'
  , '  <bpmn:process id="Process_0rxermh" isExecutable="false">'
  , '    <bpmn:laneSet id="LaneSet_0q6sxw0">'
  , '      <bpmn:lane id="Lane_1pfwkd3" name="Sales">'
  , '        <bpmn:flowNodeRef>Event_12r2r0r</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0bx24jl</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_1vn4tgg</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1fh9sk7</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1ucg2k6</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Event_1rpdwar</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '      <bpmn:lane id="Lane_01xuw1t" name="Finance">'
  , '        <bpmn:flowNodeRef>Activity_1qcogzg</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0hl3wef</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0ihn0nz</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_1qon03h</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1ow2uze</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0kh5iel</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0pozgkx</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '      <bpmn:lane id="Lane_06hpti2" name="Warehouse">'
  , '        <bpmn:flowNodeRef>Activity_1nzl5vj</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0dubqws</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0slewqs</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1cozv1y</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1dewv3m</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0vab9yd</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_10k4nk8</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0dofsl8</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0etzv1y</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_1gk5qxz</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_1ll5xmd</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Event_1nncfer</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '    </bpmn:laneSet>'
  , '    <bpmn:startEvent id="Event_12r2r0r" name="receive &#10;order">'
  , '      <bpmn:outgoing>Flow_1q9sehx</bpmn:outgoing>'
  , '    </bpmn:startEvent>'
  , '    <bpmn:task id="Activity_0bx24jl" name="check order">'
  , '      <bpmn:incoming>Flow_1q9sehx</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_167awfe</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_1q9sehx" sourceRef="Event_12r2r0r" targetRef="Activity_0bx24jl" />'
  , '    <bpmn:sequenceFlow id="Flow_167awfe" sourceRef="Activity_0bx24jl" targetRef="Gateway_1vn4tgg" />'
  , '    <bpmn:parallelGateway id="Gateway_1vn4tgg">'
  , '      <bpmn:incoming>Flow_167awfe</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1sd13zp</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_1c1r2zc</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_1g7mq2r</bpmn:outgoing>'
  , '    </bpmn:parallelGateway>'
  , '    <bpmn:task id="Activity_1fh9sk7" name="acknowledge receipt">'
  , '      <bpmn:incoming>Flow_1sd13zp</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1q1imb1</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_1sd13zp" sourceRef="Gateway_1vn4tgg" targetRef="Activity_1fh9sk7" />'
  , '    <bpmn:sequenceFlow id="Flow_1q1imb1" sourceRef="Activity_1fh9sk7" targetRef="Gateway_0kh5iel" />'
  , '    <bpmn:sequenceFlow id="Flow_1c1r2zc" sourceRef="Gateway_1vn4tgg" targetRef="Activity_1qcogzg" />'
  , '    <bpmn:task id="Activity_1qcogzg" name="prepare invoice">'
  , '      <bpmn:incoming>Flow_1c1r2zc</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_08g9ycd</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_0hl3wef" name="send invoice">'
  , '      <bpmn:incoming>Flow_08g9ycd</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_13x43g3</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:exclusiveGateway id="Gateway_0ihn0nz" name="export order">'
  , '      <bpmn:incoming>Flow_13x43g3</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1augub3</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_1y89hxj</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:subProcess id="Activity_1ow2uze" name="export documentation">'
  , '      <bpmn:incoming>Flow_1augub3</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_12eskoa</bpmn:outgoing>'
  , '      <bpmn:startEvent id="Event_0n2zeza" name="start export doc">'
  , '        <bpmn:outgoing>Flow_168l50p</bpmn:outgoing>'
  , '      </bpmn:startEvent>'
  , '      <bpmn:sequenceFlow id="Flow_168l50p" sourceRef="Event_0n2zeza" targetRef="Gateway_0r2ju5v" />'
  , '      <bpmn:parallelGateway id="Gateway_0r2ju5v">'
  , '        <bpmn:incoming>Flow_168l50p</bpmn:incoming>'
  , '        <bpmn:outgoing>Flow_14k6c03</bpmn:outgoing>'
  , '        <bpmn:outgoing>Flow_1bxvzh6</bpmn:outgoing>'
  , '      </bpmn:parallelGateway>'
  , '      <bpmn:task id="Activity_1c61tqz" name="create export customs doc">'
  , '        <bpmn:incoming>Flow_14k6c03</bpmn:incoming>'
  , '        <bpmn:outgoing>Flow_1lo31ye</bpmn:outgoing>'
  , '      </bpmn:task>'
  , '      <bpmn:sequenceFlow id="Flow_14k6c03" sourceRef="Gateway_0r2ju5v" targetRef="Activity_1c61tqz" />'
  , '      <bpmn:task id="Activity_1w0hgj6" name="create LC docs">'
  , '        <bpmn:incoming>Flow_1bxvzh6</bpmn:incoming>'
  , '        <bpmn:outgoing>Flow_0xp2sdz</bpmn:outgoing>'
  , '      </bpmn:task>'
  , '      <bpmn:sequenceFlow id="Flow_1bxvzh6" sourceRef="Gateway_0r2ju5v" targetRef="Activity_1w0hgj6" />'
  , '      <bpmn:sequenceFlow id="Flow_1lo31ye" sourceRef="Activity_1c61tqz" targetRef="Gateway_0wuum5f" />'
  , '      <bpmn:parallelGateway id="Gateway_0wuum5f">'
  , '        <bpmn:incoming>Flow_1lo31ye</bpmn:incoming>'
  , '        <bpmn:incoming>Flow_0xp2sdz</bpmn:incoming>'
  , '        <bpmn:outgoing>Flow_0tikood</bpmn:outgoing>'
  , '      </bpmn:parallelGateway>'
  , '      <bpmn:sequenceFlow id="Flow_0xp2sdz" sourceRef="Activity_1w0hgj6" targetRef="Gateway_0wuum5f" />'
  , '      <bpmn:endEvent id="Event_0ctcxyt" name="export&#10;doc&#10;complete">'
  , '        <bpmn:incoming>Flow_0tikood</bpmn:incoming>'
  , '      </bpmn:endEvent>'
  , '      <bpmn:sequenceFlow id="Flow_0tikood" sourceRef="Gateway_0wuum5f" targetRef="Event_0ctcxyt" />'
  , '    </bpmn:subProcess>'
  , '    <bpmn:exclusiveGateway id="Gateway_1qon03h">'
  , '      <bpmn:incoming>Flow_12eskoa</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_1y89hxj</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1k267dh</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:sequenceFlow id="Flow_08g9ycd" sourceRef="Activity_1qcogzg" targetRef="Activity_0hl3wef" />'
  , '    <bpmn:sequenceFlow id="Flow_13x43g3" sourceRef="Activity_0hl3wef" targetRef="Gateway_0ihn0nz" />'
  , '    <bpmn:sequenceFlow id="Flow_1augub3" name="export" sourceRef="Gateway_0ihn0nz" targetRef="Activity_1ow2uze" />'
  , '    <bpmn:sequenceFlow id="Flow_12eskoa" sourceRef="Activity_1ow2uze" targetRef="Gateway_1qon03h" />'
  , '    <bpmn:sequenceFlow id="Flow_1y89hxj" name="local" sourceRef="Gateway_0ihn0nz" targetRef="Gateway_1qon03h" />'
  , '    <bpmn:parallelGateway id="Gateway_0kh5iel">'
  , '      <bpmn:incoming>Flow_1k267dh</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_1q1imb1</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_0m694ug</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_11f3g1p</bpmn:outgoing>'
  , '    </bpmn:parallelGateway>'
  , '    <bpmn:sequenceFlow id="Flow_1k267dh" sourceRef="Gateway_1qon03h" targetRef="Gateway_0kh5iel" />'
  , '    <bpmn:task id="Activity_0pozgkx" name="approve order for shipping">'
  , '      <bpmn:incoming>Flow_11f3g1p</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1ldxdu0</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_11f3g1p" sourceRef="Gateway_0kh5iel" targetRef="Activity_0pozgkx" />'
  , '    <bpmn:sequenceFlow id="Flow_1ldxdu0" sourceRef="Activity_0pozgkx" targetRef="Activity_1nzl5vj" />'
  , '    <bpmn:task id="Activity_1nzl5vj" name="dispatch goods">'
  , '      <bpmn:incoming>Flow_1ldxdu0</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0wgmqzj</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_0wgmqzj" sourceRef="Activity_1nzl5vj" targetRef="Activity_1ucg2k6" />'
  , '    <bpmn:task id="Activity_1ucg2k6" name="notify customer">'
  , '      <bpmn:incoming>Flow_0wgmqzj</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0lktm44</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:endEvent id="Event_1rpdwar" name="end">'
  , '      <bpmn:incoming>Flow_0lktm44</bpmn:incoming>'
  , '    </bpmn:endEvent>'
  , '    <bpmn:sequenceFlow id="Flow_0lktm44" sourceRef="Activity_1ucg2k6" targetRef="Event_1rpdwar" />'
  , '    <bpmn:inclusiveGateway id="Gateway_0dubqws" name="ship modes?">'
  , '      <bpmn:incoming>Flow_1g7mq2r</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0b9zlpb</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_0rpxblp</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_1klmqrg</bpmn:outgoing>'
  , '    </bpmn:inclusiveGateway>'
  , '    <bpmn:task id="Activity_0slewqs" name="arrange air shipment">'
  , '      <bpmn:incoming>Flow_0b9zlpb</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0i176ud</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_1cozv1y" name="arrange ocean shipment">'
  , '      <bpmn:incoming>Flow_0rpxblp</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1ffzptq</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_1dewv3m" name="arrange surface shipment">'
  , '      <bpmn:incoming>Flow_1klmqrg</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1b2cybl</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_0b9zlpb" name="includes&#10;air freight?" sourceRef="Gateway_0dubqws" targetRef="Activity_0slewqs" />'
  , '    <bpmn:sequenceFlow id="Flow_0rpxblp" name="includes&#10;ocean&#10;freight?" sourceRef="Gateway_0dubqws" targetRef="Activity_1cozv1y" />'
  , '    <bpmn:sequenceFlow id="Flow_1klmqrg" name="includes&#10;surface&#10;transport?" sourceRef="Gateway_0dubqws" targetRef="Activity_1dewv3m" />'
  , '    <bpmn:sequenceFlow id="Flow_0i176ud" sourceRef="Activity_0slewqs" targetRef="Gateway_0vab9yd" />'
  , '    <bpmn:sequenceFlow id="Flow_1ffzptq" sourceRef="Activity_1cozv1y" targetRef="Gateway_0vab9yd" />'
  , '    <bpmn:sequenceFlow id="Flow_1b2cybl" sourceRef="Activity_1dewv3m" targetRef="Gateway_0vab9yd" />'
  , '    <bpmn:sequenceFlow id="Flow_1g7mq2r" sourceRef="Gateway_1vn4tgg" targetRef="Gateway_0dubqws" />'
  , '    <bpmn:sequenceFlow id="Flow_0wnn500" sourceRef="Activity_0etzv1y" targetRef="Gateway_10k4nk8" />'
  , '    <bpmn:sequenceFlow id="Flow_106dv3q" name="export" sourceRef="Gateway_10k4nk8" targetRef="Activity_1ll5xmd" />'
  , '    <bpmn:sequenceFlow id="Flow_06832ls" name="local" sourceRef="Gateway_10k4nk8" targetRef="Activity_0dofsl8" />'
  , '    <bpmn:sequenceFlow id="Flow_1lvy3kz" sourceRef="Activity_0dofsl8" targetRef="Gateway_1gk5qxz" />'
  , '    <bpmn:sequenceFlow id="Flow_1s2y3pb" sourceRef="Gateway_0vab9yd" targetRef="Activity_0etzv1y" />'
  , '    <bpmn:inclusiveGateway id="Gateway_0vab9yd">'
  , '      <bpmn:incoming>Flow_0i176ud</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_1ffzptq</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_1b2cybl</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1s2y3pb</bpmn:outgoing>'
  , '    </bpmn:inclusiveGateway>'
  , '    <bpmn:exclusiveGateway id="Gateway_10k4nk8" name="export order?">'
  , '      <bpmn:incoming>Flow_0wnn500</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_106dv3q</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_06832ls</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:task id="Activity_0dofsl8" name="domestic packing">'
  , '      <bpmn:incoming>Flow_06832ls</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1lvy3kz</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_0etzv1y" name="pick goods">'
  , '      <bpmn:incoming>Flow_1s2y3pb</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0wnn500</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_0m694ug" sourceRef="Gateway_1gk5qxz" targetRef="Gateway_0kh5iel" />'
  , '    <bpmn:exclusiveGateway id="Gateway_1gk5qxz">'
  , '      <bpmn:incoming>Flow_1lvy3kz</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_04hn48e</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0m694ug</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:task id="Activity_1ll5xmd" name="export packing">'
  , '      <bpmn:incoming>Flow_106dv3q</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0kel409</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_0kel409" sourceRef="Activity_1ll5xmd" targetRef="Event_1nncfer" />'
  , '    <bpmn:sequenceFlow id="Flow_04hn48e" sourceRef="Event_1nncfer" targetRef="Gateway_1gk5qxz" />'
  , '    <bpmn:intermediateCatchEvent id="Event_1nncfer" name="24Hr &#10;security hold">'
  , '      <bpmn:incoming>Flow_0kel409</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_04hn48e</bpmn:outgoing>'
  , '      <bpmn:timerEventDefinition id="TimerEventDefinition_06mibkf" />'
  , '    </bpmn:intermediateCatchEvent>'
  , '  </bpmn:process>'
  , '  <bpmndi:BPMNDiagram id="BPMNDiagram_1">'
  , '    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_03m7mlg">'
  , '      <bpmndi:BPMNShape id="Participant_1bg6eoy_di" bpmnElement="Participant_1bg6eoy" isHorizontal="true">'
  , '        <dc:Bounds x="170" y="110" width="1930" height="1060" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_1pfwkd3_di" bpmnElement="Lane_1pfwkd3" isHorizontal="true">'
  , '        <dc:Bounds x="200" y="110" width="1900" height="230" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_01xuw1t_di" bpmnElement="Lane_01xuw1t" isHorizontal="true">'
  , '        <dc:Bounds x="200" y="340" width="1900" height="440" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_06hpti2_di" bpmnElement="Lane_06hpti2" isHorizontal="true">'
  , '        <dc:Bounds x="200" y="780" width="1900" height="390" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNEdge id="Flow_1q9sehx_di" bpmnElement="Flow_1q9sehx">'
  , '        <di:waypoint x="288" y="260" />'
  , '        <di:waypoint x="340" y="260" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_167awfe_di" bpmnElement="Flow_167awfe">'
  , '        <di:waypoint x="440" y="260" />'
  , '        <di:waypoint x="495" y="260" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1sd13zp_di" bpmnElement="Flow_1sd13zp">'
  , '        <di:waypoint x="545" y="260" />'
  , '        <di:waypoint x="600" y="260" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1q1imb1_di" bpmnElement="Flow_1q1imb1">'
  , '        <di:waypoint x="700" y="260" />'
  , '        <di:waypoint x="1620" y="260" />'
  , '        <di:waypoint x="1620" y="530" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1c1r2zc_di" bpmnElement="Flow_1c1r2zc">'
  , '        <di:waypoint x="520" y="285" />'
  , '        <di:waypoint x="520" y="580" />'
  , '        <di:waypoint x="590" y="580" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_08g9ycd_di" bpmnElement="Flow_08g9ycd">'
  , '        <di:waypoint x="690" y="580" />'
  , '        <di:waypoint x="740" y="580" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_13x43g3_di" bpmnElement="Flow_13x43g3">'
  , '        <di:waypoint x="840" y="580" />'
  , '        <di:waypoint x="895" y="580" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1augub3_di" bpmnElement="Flow_1augub3">'
  , '        <di:waypoint x="945" y="580" />'
  , '        <di:waypoint x="1000" y="580" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="957" y="562" width="31" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_12eskoa_di" bpmnElement="Flow_12eskoa">'
  , '        <di:waypoint x="1410" y="555" />'
  , '        <di:waypoint x="1465" y="555" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1y89hxj_di" bpmnElement="Flow_1y89hxj">'
  , '        <di:waypoint x="920" y="605" />'
  , '        <di:waypoint x="920" y="730" />'
  , '        <di:waypoint x="1490" y="730" />'
  , '        <di:waypoint x="1490" y="580" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1194" y="712" width="23" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1k267dh_di" bpmnElement="Flow_1k267dh">'
  , '        <di:waypoint x="1515" y="555" />'
  , '        <di:waypoint x="1595" y="555" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_11f3g1p_di" bpmnElement="Flow_11f3g1p">'
  , '        <di:waypoint x="1645" y="555" />'
  , '        <di:waypoint x="1730" y="555" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1ldxdu0_di" bpmnElement="Flow_1ldxdu0">'
  , '        <di:waypoint x="1780" y="595" />'
  , '        <di:waypoint x="1780" y="960" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0wgmqzj_di" bpmnElement="Flow_0wgmqzj">'
  , '        <di:waypoint x="1830" y="1000" />'
  , '        <di:waypoint x="1850" y="1000" />'
  , '        <di:waypoint x="1850" y="260" />'
  , '        <di:waypoint x="1870" y="260" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0lktm44_di" bpmnElement="Flow_0lktm44">'
  , '        <di:waypoint x="1970" y="260" />'
  , '        <di:waypoint x="2012" y="260" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0b9zlpb_di" bpmnElement="Flow_0b9zlpb">'
  , '        <di:waypoint x="645" y="860" />'
  , '        <di:waypoint x="700" y="860" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="647" y="826" width="52" height="27" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0rpxblp_di" bpmnElement="Flow_0rpxblp">'
  , '        <di:waypoint x="620" y="885" />'
  , '        <di:waypoint x="620" y="970" />'
  , '        <di:waypoint x="700" y="970" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="634" y="919" width="41" height="40" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1klmqrg_di" bpmnElement="Flow_1klmqrg">'
  , '        <di:waypoint x="620" y="885" />'
  , '        <di:waypoint x="620" y="1080" />'
  , '        <di:waypoint x="700" y="1080" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="630" y="1030" width="50" height="40" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0i176ud_di" bpmnElement="Flow_0i176ud">'
  , '        <di:waypoint x="800" y="860" />'
  , '        <di:waypoint x="880" y="860" />'
  , '        <di:waypoint x="880" y="945" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1ffzptq_di" bpmnElement="Flow_1ffzptq">'
  , '        <di:waypoint x="800" y="970" />'
  , '        <di:waypoint x="855" y="970" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1b2cybl_di" bpmnElement="Flow_1b2cybl">'
  , '        <di:waypoint x="800" y="1080" />'
  , '        <di:waypoint x="880" y="1080" />'
  , '        <di:waypoint x="880" y="995" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1g7mq2r_di" bpmnElement="Flow_1g7mq2r">'
  , '        <di:waypoint x="520" y="285" />'
  , '        <di:waypoint x="520" y="860" />'
  , '        <di:waypoint x="595" y="860" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0wnn500_di" bpmnElement="Flow_0wnn500">'
  , '        <di:waypoint x="1130" y="970" />'
  , '        <di:waypoint x="1235" y="970" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_106dv3q_di" bpmnElement="Flow_106dv3q">'
  , '        <di:waypoint x="1260" y="945" />'
  , '        <di:waypoint x="1260" y="900" />'
  , '        <di:waypoint x="1300" y="900" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1251" y="863" width="31" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_06832ls_di" bpmnElement="Flow_06832ls">'
  , '        <di:waypoint x="1260" y="995" />'
  , '        <di:waypoint x="1260" y="1040" />'
  , '        <di:waypoint x="1330" y="1040" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1268" y="1011" width="23" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1lvy3kz_di" bpmnElement="Flow_1lvy3kz">'
  , '        <di:waypoint x="1430" y="1040" />'
  , '        <di:waypoint x="1560" y="1040" />'
  , '        <di:waypoint x="1560" y="925" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1s2y3pb_di" bpmnElement="Flow_1s2y3pb">'
  , '        <di:waypoint x="905" y="970" />'
  , '        <di:waypoint x="1030" y="970" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0m694ug_di" bpmnElement="Flow_0m694ug">'
  , '        <di:waypoint x="1585" y="900" />'
  , '        <di:waypoint x="1620" y="900" />'
  , '        <di:waypoint x="1620" y="580" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0kel409_di" bpmnElement="Flow_0kel409">'
  , '        <di:waypoint x="1400" y="900" />'
  , '        <di:waypoint x="1452" y="900" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_04hn48e_di" bpmnElement="Flow_04hn48e">'
  , '        <di:waypoint x="1488" y="900" />'
  , '        <di:waypoint x="1535" y="900" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNShape id="Event_12r2r0r_di" bpmnElement="Event_12r2r0r">'
  , '        <dc:Bounds x="252" y="242" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="251" y="285" width="39" height="27" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0bx24jl_di" bpmnElement="Activity_0bx24jl">'
  , '        <dc:Bounds x="340" y="220" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0kwsqmq_di" bpmnElement="Gateway_1vn4tgg">'
  , '        <dc:Bounds x="495" y="235" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1fh9sk7_di" bpmnElement="Activity_1fh9sk7">'
  , '        <dc:Bounds x="600" y="220" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1qcogzg_di" bpmnElement="Activity_1qcogzg">'
  , '        <dc:Bounds x="590" y="540" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0hl3wef_di" bpmnElement="Activity_0hl3wef">'
  , '        <dc:Bounds x="740" y="540" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0ihn0nz_di" bpmnElement="Gateway_0ihn0nz" isMarkerVisible="true">'
  , '        <dc:Bounds x="895" y="555" width="50" height="50" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="880" y="523" width="60" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1qon03h_di" bpmnElement="Gateway_1qon03h" isMarkerVisible="true">'
  , '        <dc:Bounds x="1465" y="530" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1ejve4q_di" bpmnElement="Gateway_0kh5iel">'
  , '        <dc:Bounds x="1595" y="530" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0pozgkx_di" bpmnElement="Activity_0pozgkx">'
  , '        <dc:Bounds x="1730" y="515" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1nzl5vj_di" bpmnElement="Activity_1nzl5vj">'
  , '        <dc:Bounds x="1730" y="960" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1ucg2k6_di" bpmnElement="Activity_1ucg2k6">'
  , '        <dc:Bounds x="1870" y="220" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Event_1rpdwar_di" bpmnElement="Event_1rpdwar">'
  , '        <dc:Bounds x="2012" y="242" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="2021" y="285" width="19" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1h0efk0_di" bpmnElement="Gateway_0dubqws">'
  , '        <dc:Bounds x="595" y="835" width="50" height="50" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="548" y="823" width="63" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0slewqs_di" bpmnElement="Activity_0slewqs">'
  , '        <dc:Bounds x="700" y="820" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1cozv1y_di" bpmnElement="Activity_1cozv1y">'
  , '        <dc:Bounds x="700" y="930" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1dewv3m_di" bpmnElement="Activity_1dewv3m">'
  , '        <dc:Bounds x="700" y="1040" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0492lql_di" bpmnElement="Gateway_0vab9yd">'
  , '        <dc:Bounds x="855" y="945" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_10k4nk8_di" bpmnElement="Gateway_10k4nk8" isMarkerVisible="true">'
  , '        <dc:Bounds x="1235" y="945" width="50" height="50" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1177" y="903" width="66" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0dofsl8_di" bpmnElement="Activity_0dofsl8">'
  , '        <dc:Bounds x="1330" y="1000" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0etzv1y_di" bpmnElement="Activity_0etzv1y">'
  , '        <dc:Bounds x="1030" y="930" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1gk5qxz_di" bpmnElement="Gateway_1gk5qxz" isMarkerVisible="true">'
  , '        <dc:Bounds x="1535" y="875" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1ll5xmd_di" bpmnElement="Activity_1ll5xmd">'
  , '        <dc:Bounds x="1300" y="860" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Event_00xl908_di" bpmnElement="Event_1nncfer">'
  , '        <dc:Bounds x="1452" y="882" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1439" y="925" width="62" height="27" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0jce9tj_di" bpmnElement="Activity_1ow2uze" isExpanded="true">'
  , '        <dc:Bounds x="1000" y="400" width="410" height="250" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNEdge id="Flow_168l50p_di" bpmnElement="Flow_168l50p">'
  , '        <di:waypoint x="1058" y="480" />'
  , '        <di:waypoint x="1075" y="480" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_14k6c03_di" bpmnElement="Flow_14k6c03">'
  , '        <di:waypoint x="1125" y="480" />'
  , '        <di:waypoint x="1150" y="480" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1bxvzh6_di" bpmnElement="Flow_1bxvzh6">'
  , '        <di:waypoint x="1100" y="505" />'
  , '        <di:waypoint x="1100" y="590" />'
  , '        <di:waypoint x="1150" y="590" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1lo31ye_di" bpmnElement="Flow_1lo31ye">'
  , '        <di:waypoint x="1250" y="480" />'
  , '        <di:waypoint x="1275" y="480" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0xp2sdz_di" bpmnElement="Flow_0xp2sdz">'
  , '        <di:waypoint x="1250" y="590" />'
  , '        <di:waypoint x="1300" y="590" />'
  , '        <di:waypoint x="1300" y="505" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0tikood_di" bpmnElement="Flow_0tikood">'
  , '        <di:waypoint x="1325" y="480" />'
  , '        <di:waypoint x="1352" y="480" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNShape id="Event_0n2zeza_di" bpmnElement="Event_0n2zeza">'
  , '        <dc:Bounds x="1021.6666666666665" y="462" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1002" y="505" width="76" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0mv8ore_di" bpmnElement="Gateway_0r2ju5v">'
  , '        <dc:Bounds x="1075" y="455" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1c61tqz_di" bpmnElement="Activity_1c61tqz">'
  , '        <dc:Bounds x="1150" y="440" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1w0hgj6_di" bpmnElement="Activity_1w0hgj6">'
  , '        <dc:Bounds x="1150" y="550" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0qkw3di_di" bpmnElement="Gateway_0wuum5f">'
  , '        <dc:Bounds x="1275" y="455" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Event_0ctcxyt_di" bpmnElement="Event_0ctcxyt">'
  , '        <dc:Bounds x="1352" y="462" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1348" y="505" width="45" height="40" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '    </bpmndi:BPMNPlane>'
  , '  </bpmndi:BPMNDiagram>'
  , '</bpmn:definitions>'
  , ''
  )
));
commit;
end;
/
 
PROMPT >> Example "MyBigExportExample" loaded.
PROMPT >> ========================================================
 

