PROMPT >> Loading Example "Shipment Process"
begin
insert into flow_diagrams( dgrm_name, dgrm_content)
 values (
'Shipment Process',
apex_string.join_clob(
  apex_t_varchar2(
  '<?xml version="1.0" encoding="UTF-8"?>'
  , '<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
  , '  xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" '
  , '  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" '
  , '  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" '
  , '  xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="7.2.0">'
  , '  <bpmn:collaboration id="Collaboration_1jwf2de">'
  , '    <bpmn:participant id="Participant_0g5cg3q" name="Hardware Retailer" processRef="Process_0rxermh" />'
  , '  </bpmn:collaboration>'
  , '  <bpmn:process id="Process_0rxermh" isExecutable="false">'
  , '    <bpmn:laneSet id="LaneSet_1h0jp4d">'
  , '      <bpmn:lane id="Lane_1c6myqg" name="Logistics Manager">'
  , '        <bpmn:flowNodeRef>Activity_0kx4g7c</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '      <bpmn:lane id="Lane_0gayxzq" name="Clerk">'
  , '        <bpmn:flowNodeRef>Event_0u1xt9v</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0szl76x</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0ghaomd</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_1hjffmz</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_125wy0m</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0icl811</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_11vekpg</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_02e6p2j</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_13ubm9r</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0ez1x6t</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_1xunehy</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '      <bpmn:lane id="Lane_1ctn8o3" name="Warehouse Worker">'
  , '        <bpmn:flowNodeRef>Activity_1bzg6td</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Gateway_0r12nuh</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Activity_0y5yax8</bpmn:flowNodeRef>'
  , '        <bpmn:flowNodeRef>Event_19maiga</bpmn:flowNodeRef>'
  , '      </bpmn:lane>'
  , '    </bpmn:laneSet>'
  , '    <bpmn:sequenceFlow id="Flow_0s4vpqa" name="extra insurance required" sourceRef="Gateway_0ghaomd" targetRef="Activity_0kx4g7c" />'
  , '    <bpmn:sequenceFlow id="Flow_02fkv4z" sourceRef="Activity_02e6p2j" targetRef="Gateway_1hjffmz" />'
  , '    <bpmn:startEvent id="Event_0u1xt9v" name="Goods to ship">'
  , '      <bpmn:outgoing>Flow_0gx9sf7</bpmn:outgoing>'
  , '    </bpmn:startEvent>'
  , '    <bpmn:sequenceFlow id="Flow_0o4rc5v" name="Always" sourceRef="Gateway_0ghaomd" targetRef="Activity_0icl811" />'
  , '    <bpmn:sequenceFlow id="Flow_1iooy2j" sourceRef="Activity_125wy0m" targetRef="Activity_11vekpg" />'
  , '    <bpmn:task id="Activity_0szl76x" name="Check if extra insurance is necessary">'
  , '      <bpmn:incoming>Flow_1lttbjy</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0r90u26</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:inclusiveGateway id="Gateway_0ghaomd">'
  , '      <bpmn:incoming>Flow_0r90u26</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0o4rc5v</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_0s4vpqa</bpmn:outgoing>'
  , '    </bpmn:inclusiveGateway>'
  , '    <bpmn:exclusiveGateway id="Gateway_1hjffmz" name="Mode of delivery">'
  , '      <bpmn:incoming>Flow_02fkv4z</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1lttbjy</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_09xutc3</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:task id="Activity_125wy0m" name="Request quotes from carriers">'
  , '      <bpmn:incoming>Flow_09xutc3</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1iooy2j</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_1lttbjy" name="Normal Post" sourceRef="Gateway_1hjffmz" targetRef="Activity_0szl76x" />'
  , '    <bpmn:sequenceFlow id="Flow_0r90u26" sourceRef="Activity_0szl76x" targetRef="Gateway_0ghaomd" />'
  , '    <bpmn:sequenceFlow id="Flow_09xutc3" name="Special Carrier" sourceRef="Gateway_1hjffmz" targetRef="Activity_125wy0m" />'
  , '    <bpmn:task id="Activity_0icl811" name="Fill in a Post label">'
  , '      <bpmn:incoming>Flow_0o4rc5v</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1jpzslp</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_11vekpg" name="Assign a carrier &#38; prepare paperwork">'
  , '      <bpmn:incoming>Flow_1iooy2j</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0m72m6q</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_0kx4g7c" name="Take out extra insurance">'
  , '      <bpmn:incoming>Flow_0s4vpqa</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_03n80rz</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:task id="Activity_02e6p2j" name="Decide if normal post or special shipment">'
  , '      <bpmn:incoming>Flow_1qm7qnv</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_02fkv4z</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_0gx9sf7" sourceRef="Event_0u1xt9v" targetRef="Gateway_13ubm9r" />'
  , '    <bpmn:sequenceFlow id="Flow_1qm7qnv" sourceRef="Gateway_13ubm9r" targetRef="Activity_02e6p2j" />'
  , '    <bpmn:task id="Activity_1bzg6td" name="Package goods">'
  , '      <bpmn:incoming>Flow_05ubjfa</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_00y2g5e</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_05ubjfa" sourceRef="Gateway_13ubm9r" targetRef="Activity_1bzg6td" />'
  , '    <bpmn:parallelGateway id="Gateway_13ubm9r">'
  , '      <bpmn:incoming>Flow_0gx9sf7</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1qm7qnv</bpmn:outgoing>'
  , '      <bpmn:outgoing>Flow_05ubjfa</bpmn:outgoing>'
  , '    </bpmn:parallelGateway>'
  , '    <bpmn:sequenceFlow id="Flow_00y2g5e" sourceRef="Activity_1bzg6td" targetRef="Gateway_0r12nuh" />'
  , '    <bpmn:sequenceFlow id="Flow_1jpzslp" sourceRef="Activity_0icl811" targetRef="Gateway_1xunehy" />'
  , '    <bpmn:sequenceFlow id="Flow_0m72m6q" sourceRef="Activity_11vekpg" targetRef="Gateway_0ez1x6t" />'
  , '    <bpmn:sequenceFlow id="Flow_03n80rz" sourceRef="Activity_0kx4g7c" targetRef="Gateway_1xunehy" />'
  , '    <bpmn:sequenceFlow id="Flow_1xvu9rm" sourceRef="Gateway_0ez1x6t" targetRef="Gateway_0r12nuh" />'
  , '    <bpmn:parallelGateway id="Gateway_0r12nuh">'
  , '      <bpmn:incoming>Flow_00y2g5e</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_1xvu9rm</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1fgfu9q</bpmn:outgoing>'
  , '    </bpmn:parallelGateway>'
  , '    <bpmn:exclusiveGateway id="Gateway_0ez1x6t">'
  , '      <bpmn:incoming>Flow_0m72m6q</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_099zv95</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_1xvu9rm</bpmn:outgoing>'
  , '    </bpmn:exclusiveGateway>'
  , '    <bpmn:inclusiveGateway id="Gateway_1xunehy">'
  , '      <bpmn:incoming>Flow_1jpzslp</bpmn:incoming>'
  , '      <bpmn:incoming>Flow_03n80rz</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_099zv95</bpmn:outgoing>'
  , '    </bpmn:inclusiveGateway>'
  , '    <bpmn:sequenceFlow id="Flow_099zv95" sourceRef="Gateway_1xunehy" targetRef="Gateway_0ez1x6t" />'
  , '    <bpmn:task id="Activity_0y5yax8" name="Add paperwork and move package to pick area">'
  , '      <bpmn:incoming>Flow_1fgfu9q</bpmn:incoming>'
  , '      <bpmn:outgoing>Flow_0pxgphg</bpmn:outgoing>'
  , '    </bpmn:task>'
  , '    <bpmn:sequenceFlow id="Flow_1fgfu9q" sourceRef="Gateway_0r12nuh" targetRef="Activity_0y5yax8" />'
  , '    <bpmn:endEvent id="Event_19maiga" name="Goods available for pick">'
  , '      <bpmn:incoming>Flow_0pxgphg</bpmn:incoming>'
  , '    </bpmn:endEvent>'
  , '    <bpmn:sequenceFlow id="Flow_0pxgphg" sourceRef="Activity_0y5yax8" targetRef="Event_19maiga" />'
  , '    <bpmn:textAnnotation id="TextAnnotation_0x6xbm3">'
  , '      <bpmn:text>Insurance is included in carrier service</bpmn:text>'
  , '    </bpmn:textAnnotation>'
  , '    <bpmn:association id="Association_05b7nq4" sourceRef="Activity_125wy0m" targetRef="TextAnnotation_0x6xbm3" />'
  , '  </bpmn:process>'
  , '  <bpmndi:BPMNDiagram id="BPMNDiagram_1">'
  , '    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1jwf2de">'
  , '      <bpmndi:BPMNShape id="Participant_0g5cg3q_di" bpmnElement="Participant_0g5cg3q" isHorizontal="true">'
  , '        <dc:Bounds x="490" y="155" width="1710" height="830" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_1ctn8o3_di" bpmnElement="Lane_1ctn8o3" isHorizontal="true">'
  , '        <dc:Bounds x="520" y="760" width="1680" height="225" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_0gayxzq_di" bpmnElement="Lane_0gayxzq" isHorizontal="true">'
  , '        <dc:Bounds x="520" y="415" width="1680" height="345" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Lane_1c6myqg_di" bpmnElement="Lane_1c6myqg" isHorizontal="true">'
  , '        <dc:Bounds x="520" y="155" width="1680" height="260" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="TextAnnotation_0x6xbm3_di" bpmnElement="TextAnnotation_0x6xbm3">'
  , '        <dc:Bounds x="1190" y="920" width="100" height="54" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNEdge id="Flow_0s4vpqa_di" bpmnElement="Flow_0s4vpqa">'
  , '        <di:waypoint x="1430" y="510" />'
  , '        <di:waypoint x="1430" y="290" />'
  , '        <di:waypoint x="1560" y="290" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1452" y="256" width="76" height="27" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_02fkv4z_di" bpmnElement="Flow_02fkv4z">'
  , '        <di:waypoint x="930" y="650" />'
  , '        <di:waypoint x="1090" y="650" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0o4rc5v_di" bpmnElement="Flow_0o4rc5v">'
  , '        <di:waypoint x="1455" y="535" />'
  , '        <di:waypoint x="1560" y="535" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1482.0000000000002" y="513" width="35" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1iooy2j_di" bpmnElement="Flow_1iooy2j">'
  , '        <di:waypoint x="1555" y="650" />'
  , '        <di:waypoint x="1650" y="650" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1lttbjy_di" bpmnElement="Flow_1lttbjy">'
  , '        <di:waypoint x="1115" y="625" />'
  , '        <di:waypoint x="1115" y="535" />'
  , '        <di:waypoint x="1220" y="535" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1044" y="577" width="62" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0r90u26_di" bpmnElement="Flow_0r90u26">'
  , '        <di:waypoint x="1320" y="535" />'
  , '        <di:waypoint x="1405" y="535" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_09xutc3_di" bpmnElement="Flow_09xutc3">'
  , '        <di:waypoint x="1140" y="650" />'
  , '        <di:waypoint x="1455" y="650" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1222" y="623" width="75" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0gx9sf7_di" bpmnElement="Flow_0gx9sf7">'
  , '        <di:waypoint x="668" y="650" />'
  , '        <di:waypoint x="725" y="650" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1qm7qnv_di" bpmnElement="Flow_1qm7qnv">'
  , '        <di:waypoint x="775" y="650" />'
  , '        <di:waypoint x="830" y="650" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_05ubjfa_di" bpmnElement="Flow_05ubjfa">'
  , '        <di:waypoint x="750" y="675" />'
  , '        <di:waypoint x="750" y="870" />'
  , '        <di:waypoint x="830" y="870" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_00y2g5e_di" bpmnElement="Flow_00y2g5e">'
  , '        <di:waypoint x="930" y="870" />'
  , '        <di:waypoint x="1795" y="870" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1jpzslp_di" bpmnElement="Flow_1jpzslp">'
  , '        <di:waypoint x="1660" y="535" />'
  , '        <di:waypoint x="1795" y="535" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0m72m6q_di" bpmnElement="Flow_0m72m6q">'
  , '        <di:waypoint x="1750" y="650" />'
  , '        <di:waypoint x="1795" y="650" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_03n80rz_di" bpmnElement="Flow_03n80rz">'
  , '        <di:waypoint x="1660" y="290" />'
  , '        <di:waypoint x="1820" y="290" />'
  , '        <di:waypoint x="1820" y="510" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1xvu9rm_di" bpmnElement="Flow_1xvu9rm">'
  , '        <di:waypoint x="1820" y="675" />'
  , '        <di:waypoint x="1820" y="845" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_099zv95_di" bpmnElement="Flow_099zv95">'
  , '        <di:waypoint x="1820" y="560" />'
  , '        <di:waypoint x="1820" y="625" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_1fgfu9q_di" bpmnElement="Flow_1fgfu9q">'
  , '        <di:waypoint x="1845" y="870" />'
  , '        <di:waypoint x="1930" y="870" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNEdge id="Flow_0pxgphg_di" bpmnElement="Flow_0pxgphg">'
  , '        <di:waypoint x="2030" y="870" />'
  , '        <di:waypoint x="2112" y="870" />'
  , '      </bpmndi:BPMNEdge>'
  , '      <bpmndi:BPMNShape id="Event_0u1xt9v_di" bpmnElement="Event_0u1xt9v">'
  , '        <dc:Bounds x="632" y="632" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="616" y="675" width="69" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0szl76x_di" bpmnElement="Activity_0szl76x">'
  , '        <dc:Bounds x="1220" y="495" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_132btwr_di" bpmnElement="Gateway_0ghaomd">'
  , '        <dc:Bounds x="1405" y="510" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1hjffmz_di" bpmnElement="Gateway_1hjffmz" isMarkerVisible="true">'
  , '        <dc:Bounds x="1090" y="625" width="50" height="50" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="1074" y="682" width="82" height="14" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_125wy0m_di" bpmnElement="Activity_125wy0m">'
  , '        <dc:Bounds x="1455" y="610" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0icl811_di" bpmnElement="Activity_0icl811">'
  , '        <dc:Bounds x="1560" y="495" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_11vekpg_di" bpmnElement="Activity_11vekpg">'
  , '        <dc:Bounds x="1650" y="610" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0kx4g7c_di" bpmnElement="Activity_0kx4g7c">'
  , '        <dc:Bounds x="1560" y="250" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_02e6p2j_di" bpmnElement="Activity_02e6p2j">'
  , '        <dc:Bounds x="830" y="610" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_1bzg6td_di" bpmnElement="Activity_1bzg6td">'
  , '        <dc:Bounds x="830" y="830" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1va7u0r_di" bpmnElement="Gateway_13ubm9r">'
  , '        <dc:Bounds x="725" y="625" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0197ul1_di" bpmnElement="Gateway_0r12nuh">'
  , '        <dc:Bounds x="1795" y="845" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_1fy5p2u_di" bpmnElement="Gateway_0ez1x6t" isMarkerVisible="true">'
  , '        <dc:Bounds x="1795" y="625" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Gateway_0mm3u8u_di" bpmnElement="Gateway_1xunehy">'
  , '        <dc:Bounds x="1795" y="510" width="50" height="50" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Activity_0y5yax8_di" bpmnElement="Activity_0y5yax8">'
  , '        <dc:Bounds x="1930" y="830" width="100" height="80" />'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNShape id="Event_19maiga_di" bpmnElement="Event_19maiga">'
  , '        <dc:Bounds x="2112" y="852" width="36" height="36" />'
  , '        <bpmndi:BPMNLabel>'
  , '          <dc:Bounds x="2091" y="895" width="79" height="27" />'
  , '        </bpmndi:BPMNLabel>'
  , '      </bpmndi:BPMNShape>'
  , '      <bpmndi:BPMNEdge id="Association_05b7nq4_di" bpmnElement="Association_05b7nq4">'
  , '        <di:waypoint x="1455" y="650" />'
  , '        <di:waypoint x="1240" y="650" />'
  , '        <di:waypoint x="1240" y="920" />'
  , '      </bpmndi:BPMNEdge>'
  , '    </bpmndi:BPMNPlane>'
  , '  </bpmndi:BPMNDiagram>'
  , '</bpmn:definitions>'
  )
));
commit;
end;
/
 
PROMPT >> Example "Shipment Process" loaded.
PROMPT >> ========================================================
