prompt --application/shared_components/user_interface/lovs/diagrams_instanciated_lov
begin
--   Manifest
--     DIAGRAMS_INSTANCIATED_LOV
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.05.31'
,p_release=>'24.1.8'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(66615520889086574)
,p_lov_name=>'DIAGRAMS_INSTANCIATED_LOV'
,p_source_type=>'TABLE'
,p_location=>'LOCAL'
,p_query_table=>'FLOW_DIAGRAMS_INSTANCIATED_LOV'
,p_return_column_name=>'DGRM_ID'
,p_display_column_name=>'DGRM_NAME'
,p_group_column_name=>'DGRM_CATEGORY'
,p_group_sort_direction=>'ASC'
,p_default_sort_column_name=>'DGRM_NAME'
,p_default_sort_direction=>'ASC'
,p_version_scn=>1760504921
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(66619493214096628)
,p_query_column_name=>'DGRM_ID'
,p_display_sequence=>10
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(66619733681096628)
,p_query_column_name=>'DGRM_NAME'
,p_heading=>'Name'
,p_display_sequence=>20
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(66620198364096628)
,p_query_column_name=>'DGRM_CATEGORY'
,p_heading=>'Category'
,p_display_sequence=>30
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(66620549721096629)
,p_query_column_name=>'DGRM_VERSION'
,p_heading=>'Version'
,p_display_sequence=>40
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(66620978691096630)
,p_query_column_name=>'DGRM_STATUS'
,p_heading=>'Status'
,p_display_sequence=>50
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp.component_end;
end;
/
