name: Bug report
description: Report a bug you've found
title: "[bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: flows4apex_version
    attributes:
      label: Flows for APEX version
      options:
        - 5.1.1
        - 5.1.2
        - 21.1 
        - 22.1
        - 22.2
        - 23.1 (latest)
        - Current Development
    validations:
      required: true
  - type: dropdown
    id: oracle_db_version
    attributes:
      label: Oracle Database version
      description: We only support Oracle Database 19 and higher
      options:
        - 18c or lower (unsupported)
        - 19c
        - 21c
        - 23c
    validations:
      required: true
  - type: dropdown
    id: oracle_apex_version
    attributes:
      label: Oracle APEX version
      description: We only support Oracle APEX 20.2 and higher
      options:
        - 19.2 and lower (unsupported)
        - 20.1 (unsupported)
        - 20.2
        - 21.1
        - 21.2
        - 22.1
        - 22.2
        - 23.1
        - newer
    validations:
      required: true
  - type: dropdown
    id: model_linted
    attributes:
      label: Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?
      description: Please validate your BPMN model using the BPMN Linting tool (the grey button at the bottom of the Flow Modeler) to make sure your model does not contain any errors before logging an issue.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce 
      description: Help us to reproduce your issue by adding details of the different steps.
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
