CREATE TABLE "FLOW_OBJECTS" 
   (	"OBJT_ID" VARCHAR2(50 CHAR), 
	"OBJT_NAME" VARCHAR2(200 CHAR), 
	"OBJT_DGRM_NAME" VARCHAR2(150 CHAR), 
	"OBJT_TYPE" VARCHAR2(50 CHAR), 
	"OBJT_TAG_NAME" VARCHAR2(50 CHAR), 
	"OBJT_INCOMING" VARCHAR2(50 CHAR), 
	"OBJT_OUTGOING" VARCHAR2(50 CHAR), 
	"OBJT_ORIGIN" VARCHAR2(50), 
	 CONSTRAINT "OBJT_PK" PRIMARY KEY ("OBJT_DGRM_NAME", "OBJT_ID")
  USING INDEX  ENABLE
   )
/

ALTER TABLE "FLOW_OBJECTS" ADD CONSTRAINT "OBJT_DGRM_FK" FOREIGN KEY ("OBJT_DGRM_NAME")
	  REFERENCES "FLOW_DIAGRAMS" ("DGRM_NAME") ON DELETE CASCADE ENABLE
/