CREATE TABLE  "FLOW_SUBFLOWS" 
   (	"SBFL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SBFL_PARENT_SUBFLOW" NUMBER, 
	"SBFL_PARENT_PROCESS" NUMBER NOT NULL ENABLE, 
	"SBFL_STARTING_OBJECT" VARCHAR2(50), 
	"SBFL_ROUTE" VARCHAR2(100), 
	"SBFL_LAST_COMPLETED" VARCHAR2(50), 
	"SBFL_CURRENT" VARCHAR2(50), 
	"SBFL_STATUS" VARCHAR2(20), 
	"SBFL_LAST_UPDATE" DATE, 
	 CONSTRAINT "SUBFLOWS_PK" PRIMARY KEY ("SBFL_ID")
  USING INDEX  ENABLE
   )
/

ALTER TABLE  "FLOW_SUBFLOWS" ADD CONSTRAINT "CON_PARENT_FK" FOREIGN KEY ("SBFL_PARENT_PROCESS")
	  REFERENCES  "FLOW_PROCESSES" ("PRCS_ID") ON DELETE CASCADE ENABLE
/
