CREATE TABLE "FLOW_PROCESSES" 
   (	"PRCS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP , 
	"PRCS_NAME" VARCHAR2(150), 
	"PRCS_DGRM_NAME" VARCHAR2(150), 
	"PRCS_STATUS" VARCHAR2(20),
	"PRCS_MAIN_SUBFLOW" NUMBER,
	"PRCS_INIT_DATE" DATE, 
	"PRCS_LAST_UPDATE" DATE, 
	 CONSTRAINT "PRCS_PK" PRIMARY KEY ("PRCS_ID")
  USING INDEX  ENABLE
   )
/

ALTER TABLE "FLOW_PROCESSES" ADD CONSTRAINT "PRCS_DGRM_FK" FOREIGN KEY ("PRCS_DGRM_NAME")
	  REFERENCES "FLOW_DIAGRAMS" ("DGRM_NAME") ON DELETE CASCADE ENABLE
/