CREATE TABLE  "FLOW_SUBFLOW_LOG" 
   (	"SFLG_PRCS_ID" NUMBER NOT NULL ENABLE, 
	"SFLG_OBJT_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"SFLG_SBFL_ID" NUMBER NOT NULL ENABLE, 
	"SFLG_LAST_UPDATED" DATE, 
	"SFLG_NOTES" VARCHAR2(200)
   )
/
