create table flow_tasks
( task_id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
, task_objt_id NUMBER              -- remove this as non-persistent across diagram parses??
, task_objt_bpmn_id varchar2(50)   -- currently real pk as need to persist across diagram parses 
, task_dgrm_id NUMBER
, task_type varchar2(50)  -- 'apex_page', etc
, task_app_id NUMBER
, task_app_alias varchar2(50)
, task_page_id NUMBER
, task_request varchar2(50)
, task_clear_cache varchar2(50)
, task_set_items varchar2(200)
, task_set_values varchar2(200)
, task_URL varchar2(200)
);

alter table flow_tasks add constraint task_pk primary key (task_id);

create table flow_scripts
( scrp_id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
, scrp_objt_id NUMBER              -- remove this??? (see above)
, scrp_objt_bpmn_id varchar2(50)   -- currently real pk as need to persist across diagram parses 
, scrp_dgrm_id NUMBER
, scrp_type varchar2(50)         -- values 'PL/SQL Procedure', 'Send Email Task', etc.
, scrp_syncronous varchar2(20)   -- values 'synchronous' 'non-synchronous'
, scrp_schema varchar2(50)
, scrp_package varchar2(50)
, scrp_procedure varchar2(50)
);

--  make this ultimtely flexible and have 

create table flow_script_parameters 
( scrv_scrp_id number
, scrv_parameter_name varchar2(50)
, scrv_value varchar2(50)
, scrv_value_type varchar2(50)  -- literal, process_variable, PK, etc 
);




alter table flow_scripts add constraint scrp_pk primary key (scrp_id);

/*
alter table flow_processes add 
( prcs_ref_obj_type  VARCHAR2(50 CHAR)    
, prcs_ref_obj_id    NUMBER
, prcs_initiator varchar2(200)
, prcs_priority NUMBER
);
*/

-- I'd like to be able to create a variable that contains a set of items.  
-- Use case might be to set the list of userids that need to approve an expense report
-- this then allows us to implement multiple instantiation of objects in parallel or in series
-- which solves the problem that got me into flows for apex in the first place!
-- We could use apex:list:notation or <json>

-- Q: do we leave PK separate and in flow_processes?  - or make everything a proc var?

-- Q -- default flag on Excl GW on flow_objects
