CREATE TABLE flow_connections (
    conn_id           NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    conn_bpmn_id      VARCHAR2(50 CHAR) NOT NULL,
    conn_dgrm_id      NUMBER NOT NULL,
    conn_name         VARCHAR2(200 CHAR),
    conn_src_objt_id  NUMBER,
    conn_tgt_objt_id  NUMBER,
    conn_type         VARCHAR2(50 CHAR),
    conn_tag_name     VARCHAR2(50 CHAR),
    conn_origin       VARCHAR2(50 CHAR)
);

ALTER TABLE flow_connections ADD CONSTRAINT conn_pk PRIMARY KEY ( conn_id );

ALTER TABLE flow_connections ADD CONSTRAINT conn_uk UNIQUE ( conn_dgrm_id,
                                                             conn_bpmn_id );

CREATE TABLE flow_diagrams (
    dgrm_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    dgrm_name     VARCHAR2(150 CHAR) NOT NULL,
    dgrm_content  CLOB
);

ALTER TABLE flow_diagrams ADD CONSTRAINT dgrm_pk PRIMARY KEY ( dgrm_id );

ALTER TABLE flow_diagrams ADD CONSTRAINT dgrm_uk UNIQUE ( dgrm_name );

CREATE TABLE flow_objects (
    objt_id        NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    objt_bpmn_id   VARCHAR2(50 CHAR) NOT NULL,
    objt_dgrm_id   NUMBER NOT NULL,
    objt_name      VARCHAR2(200 CHAR),
    objt_type      VARCHAR2(50 CHAR),
    objt_tag_name  VARCHAR2(50 CHAR),
    objt_objt_id   NUMBER,
    objt_sub_tag_name VARCHAR2(50 CHAR),
    objt_timer_date VARCHAR2(50 BYTE), 
	objt_timer_duration VARCHAR2(50 BYTE), 
	objt_timer_cycle VARCHAR2(50 BYTE)
);

ALTER TABLE flow_objects ADD CONSTRAINT objt_pk PRIMARY KEY ( objt_id );

ALTER TABLE flow_objects ADD CONSTRAINT objt_uk UNIQUE ( objt_dgrm_id,
                                                         objt_bpmn_id );

CREATE TABLE flow_processes (
    prcs_id            NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    prcs_dgrm_id       NUMBER NOT NULL,
    prcs_name          VARCHAR2(150) NOT NULL,
    prcs_status        VARCHAR2(20) NOT NULL,
    prcs_main_subflow  NUMBER,
    prcs_init_ts       TIMESTAMP NOT NULL,
    prcs_last_update   TIMESTAMP
);

ALTER TABLE flow_processes ADD CONSTRAINT prcs_pk PRIMARY KEY ( prcs_id );

CREATE TABLE flow_subflow_log (
    sflg_prcs_id       NUMBER NOT NULL,
    sflg_objt_id       VARCHAR2(50) NOT NULL,
    sflg_sbfl_id       NUMBER NOT NULL,
    sflg_last_updated  DATE,
    sflg_notes         VARCHAR2(200)
);

CREATE TABLE flow_subflows (
    sbfl_id               NUMBER
        GENERATED ALWAYS AS IDENTITY ( START WITH 1 NOCACHE )
    NOT NULL,
    sbfl_prcs_id          NUMBER NOT NULL,
    sbfl_sbfl_id          NUMBER,
    sbfl_starting_object  VARCHAR2(50),
    sbfl_route            VARCHAR2(100),
    sbfl_last_completed   VARCHAR2(50),
    sbfl_current          VARCHAR2(50),
    sbfl_status           VARCHAR2(30),
    sbfl_last_update      TIMESTAMP NOT NULL
);

ALTER TABLE flow_subflows ADD CONSTRAINT sbfl_pk PRIMARY KEY ( sbfl_id );

ALTER TABLE flow_connections
    ADD CONSTRAINT conn_dgrm_fk FOREIGN KEY ( conn_dgrm_id )
        REFERENCES flow_diagrams ( dgrm_id )
            ON DELETE CASCADE;

ALTER TABLE flow_connections
    ADD CONSTRAINT conn_src_objt_fk FOREIGN KEY ( conn_src_objt_id )
        REFERENCES flow_objects ( objt_id )
            ON DELETE SET NULL;

ALTER TABLE flow_connections
    ADD CONSTRAINT conn_tgt_objt_fk FOREIGN KEY ( conn_tgt_objt_id )
        REFERENCES flow_objects ( objt_id )
            ON DELETE SET NULL;

ALTER TABLE flow_objects
    ADD CONSTRAINT objt_dgrm_fk FOREIGN KEY ( objt_dgrm_id )
        REFERENCES flow_diagrams ( dgrm_id )
            ON DELETE CASCADE;

ALTER TABLE flow_objects
    ADD CONSTRAINT objt_objt_fk FOREIGN KEY ( objt_objt_id )
        REFERENCES flow_objects ( objt_id );

ALTER TABLE flow_processes
    ADD CONSTRAINT prcs_dgrm_fk FOREIGN KEY ( prcs_dgrm_id )
        REFERENCES flow_diagrams ( dgrm_id )
            ON DELETE CASCADE;

ALTER TABLE flow_subflows
    ADD CONSTRAINT sbfl_parent_sbfl_fk FOREIGN KEY ( sbfl_sbfl_id )
        REFERENCES flow_subflows ( sbfl_id )
            ON DELETE CASCADE;

ALTER TABLE flow_subflows
    ADD CONSTRAINT sbfl_prcs_fk FOREIGN KEY ( sbfl_prcs_id )
        REFERENCES flow_processes ( prcs_id )
            ON DELETE CASCADE;



  CREATE TABLE "FLOW_TIMERS" 
   (	"TIMR_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIMR_PRCS_ID" NUMBER NOT NULL ENABLE, 
	"TIMR_SBFL_ID" NUMBER NOT NULL ENABLE, 
	"TIMR_LAST_RUN" TIMESTAMP (6) WITH TIME ZONE, 
	"TIMR_RUN_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"TIMR_CREATED_ON" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	"TIMR_STATUS" VARCHAR2(1 BYTE), 
	"TIMR_DATE_STRING" VARCHAR2(50 BYTE), 
	"TIMR_DURATION_STRING" VARCHAR2(50 BYTE), 
	"TIMR_CYCLE_STRING" VARCHAR2(2050 BYTE), 
	"TIMR_START_ON" TIMESTAMP (6) WITH TIME ZONE, 
	"TIMR_INTERVAL_YM" INTERVAL YEAR (2) TO MONTH, 
	"TIMR_INTERVAL_DS" INTERVAL DAY (2) TO SECOND (6), 
	"TIMR_REPEAT_TIMES" NUMBER, 
	 CONSTRAINT "TIMR_PK" PRIMARY KEY ("TIMR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TIMR_UK" UNIQUE ("TIMR_PRCS_ID", "TIMR_SBFL_ID")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_STATUS" IS 'Stauts of the timer. For the status codes see constant definitions in FLOW_TIMERS_PKG package declaration.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_DATE_STRING" IS 'Temporary column for testing. It will be removed when the new model from Moritz is available.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_DURATION_STRING" IS 'Temporary column for testing. It will be removed when the new model from Moritz is available.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_CYCLE_STRING" IS 'Temporary column for testing. It will be removed when the new model from Moritz is available.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_START_ON" IS 'Expected start datetime.
Used for both date and duration definitions.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_INTERVAL_YM" IS 'Interval YM for cycles.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_INTERVAL_DS" IS 'Interval DS for cycles.';
   COMMENT ON COLUMN "FLOW_TIMERS"."TIMR_REPEAT_TIMES" IS 'Number of runs for cycles.';
