/* 
-- Flows for APEX - install_ddl_comments.sql
-- 
-- (c) Copyright Flowquest Consulting Limited. 2024.
--
-- Created  01-Mar-2024  Richard Allen, Flowquest Consulting
--
*/

comment on table flow_diagrams              is 'Flows for APEX table containing process definitions and their BPMN diagrams as a BPMN (XML) file';
comment on table flow_objects               is 'Flows for APEX table containing parsed process definition data for BPMN objects making up a process';
comment on table flow_connections           is 'Flows for APEX table containing parsed process definition data for BPMN connections between BPMN objects. ';
comment on table flow_object_expressions    is 'Flows for APEX table containing parsed process definition data for Flows for APEX variable expressions';
comment on table flow_processes             is 'Flows for APEX table containing live run-time state of process instances. ';
comment on table flow_subflows              is 'Flows for APEX table containing live run-time state of the subflows currently running as part process instance. ';
comment on table flow_process_variables     is 'Flows for APEX table containing live run-time state of process variables that have been set for a process instance. ';
comment on table flow_subflog_log           is 'Flows for APEX table containing live run-time state of all steps of a process instance that have been completed.';
comment on table flow_instance_diagrams     is 'Flows for APEX table containing live run-time usage of process diagrams by a process instance,  This is mainly used for real-time tracking of BPMN Call Activities ';
comment on table flow_timers                is 'Flows for APEX table containing live run-time state of all timers set on current process instances. ';
comment on table flow_message_subscriptions is 'Flows for APEX table containing live run-time state of all current message subscriptions for all process instances, used for process collaboration and BPMN messageFlow. ';
comment on table flow_flow_event_log        is 'Flows for APEX table containing event logging information for all process diagram creation, editting and deletion.';
comment on table flow_parser_log            is 'Flows for APEX table containing event logging information for any error conditions found when parsing BPMN process diagrams';
comment on table flow_instance_event_log    is 'Flows for APEX table containing event logging information for any process instance-level events, inclding instance start, stop, and errors.';
comment on table flow_step_event_log        is 'Flows for APEX table containing event logging information for each process step.';
comment on table flow_variable_event_log    is 'Flows for APEX table containing event logging information for creation, updating and deleting events for process variables';
comment on table flow_rest_event_log        is 'Flows for APEX table containing event logging information all received REST calls to the Flows for APEX engine.';
comment on table flow_message_received_log  is 'Flows for APEX table containing event logging information for all process collaboration (BPMN message flow) messages received by the system.';
comment on table flow_instance_stats        is 'Flows for APEX table containing statistics at summary level for each process instance occuring within a period.';
comment on table flow_step_stats            is 'Flows for APEX table containing statistics at summary level for each process step occuring within a period.';
comment on table flow_stats_history         is 'Flows for APEX table containing details on when flow statistics were gathered.';
comment on table flow_configuration         is 'Flows for APEX table containing system configuration options currently active for the Flows for APEX system';
comment on table flow_messages              is 'Flows for APEX table containing language-specific error and warning messages used by Flows for APEX.';

comment on column flow_diagrams.dgrm_id           is 'Unique reference number for a diagram'; 
comment on column flow_diagrams.dgrm_name         is 'diagram name - often the business process name'; 
comment on column flow_diagrams.dgrm_version      is 'version of this diagram'; 
comment on column flow_diagrams.dgrm_status       is 'current diagram status - draft, released (for normal production use), depracated (for use only by current instances), or archived (no longer in use)'; 
comment on column flow_diagrams.dgrm_category     is ' '; 
comment on column flow_diagrams.dgrm_last_update  is ' '; 
comment on column flow_diagrams.dgrm_content      is ' '; 

comment on column FLOW_CONFIGURATION.CFIG_KEY is ' ';                       
comment on column FLOW_CONFIGURATION.CFIG_VALUE is ' ';                     
comment on column FLOW_CONNECTIONS.CONN_ID is ' ';                          
comment on column FLOW_CONNECTIONS.CONN_BPMN_ID is ' ';                     
comment on column FLOW_CONNECTIONS.CONN_DGRM_ID is ' ';                     
comment on column FLOW_CONNECTIONS.CONN_NAME is ' ';                        
comment on column FLOW_CONNECTIONS.CONN_SRC_OBJT_ID is ' ';                 
comment on column FLOW_CONNECTIONS.CONN_TGT_OBJT_ID is ' ';                 
comment on column FLOW_CONNECTIONS.CONN_TAG_NAME is ' ';                    
comment on column FLOW_CONNECTIONS.CONN_ORIGIN is ' ';                      
comment on column FLOW_CONNECTIONS.CONN_IS_DEFAULT is ' ';                  
comment on column FLOW_CONNECTIONS.CONN_SEQUENCE is ' ';                    
comment on column FLOW_CONNECTIONS.CONN_ATTRIBUTES is ' ';                  
comment on column FLOW_DIAGRAMS.DGRM_ID is ' ';                             
comment on column FLOW_DIAGRAMS.DGRM_NAME is ' ';                           
comment on column FLOW_DIAGRAMS.DGRM_VERSION is ' ';                        
comment on column FLOW_DIAGRAMS.DGRM_STATUS is ' ';                         
comment on column FLOW_DIAGRAMS.DGRM_CATEGORY is ' ';                       
comment on column FLOW_DIAGRAMS.DGRM_LAST_UPDATE is ' ';                    
comment on column FLOW_DIAGRAMS.DGRM_CONTENT is ' ';                        
comment on column FLOW_DIAGRAMS_INSTANCIATED_LOV.DGRM_ID is ' ';            
comment on column FLOW_DIAGRAMS_INSTANCIATED_LOV.DGRM_NAME is ' ';          
comment on column FLOW_DIAGRAMS_INSTANCIATED_LOV.DGRM_VERSION is ' ';       
comment on column FLOW_DIAGRAMS_INSTANCIATED_LOV.DGRM_STATUS is ' ';        
comment on column FLOW_DIAGRAMS_INSTANCIATED_LOV.DGRM_CATEGORY is ' ';      
comment on column FLOW_DIAGRAMS_PARSED_LOV.DGRM_ID is ' ';                  
comment on column FLOW_DIAGRAMS_PARSED_LOV.DGRM_NAME is ' ';                
comment on column FLOW_DIAGRAMS_PARSED_LOV.DGRM_VERSION is ' ';             
comment on column FLOW_DIAGRAMS_PARSED_LOV.DGRM_STATUS is ' ';              
comment on column FLOW_DIAGRAMS_PARSED_LOV.DGRM_CATEGORY is ' ';            
comment on column FLOW_DIAGRAMS_VW.DGRM_ID is ' ';                          
comment on column FLOW_DIAGRAMS_VW.DGRM_NAME is ' ';                        
comment on column FLOW_DIAGRAMS_VW.DGRM_VERSION is ' ';                     
comment on column FLOW_DIAGRAMS_VW.DGRM_STATUS is ' ';                      
comment on column FLOW_DIAGRAMS_VW.DGRM_CATEGORY is ' ';                    
comment on column FLOW_DIAGRAMS_VW.DGRM_LAST_UPDATE is ' ';                 
comment on column FLOW_DIAGRAMS_VW.DGRM_CONTENT is ' ';                     
comment on column FLOW_DIAGRAM_CATEGORIES_LOV.D is ' ';                     
comment on column FLOW_DIAGRAM_CATEGORIES_LOV.R is ' ';                     
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_ID is ' ';                  
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_NAME is ' ';                
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_VERSION is ' ';             
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_STATUS is ' ';              
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_CATEGORY is ' ';            
comment on column FLOW_FLOW_EVENT_LOG.LGFL_TIMESTAMP is ' ';                
comment on column FLOW_FLOW_EVENT_LOG.LGFL_USER is ' ';                     
comment on column FLOW_FLOW_EVENT_LOG.LGFL_COMMENT is ' ';                  
comment on column FLOW_FLOW_EVENT_LOG.LGFL_DGRM_ARCHIVE_LOCATION is ' ';    
comment on column FLOW_INSTANCES_VW.PRCS_ID is ' ';                         

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'                  
___________________________________________________________________________ 
comment on column FLOW_INSTANCES_VW.PRCS_NAME is ' ';                       
comment on column FLOW_INSTANCES_VW.DGRM_ID is ' ';                         
comment on column FLOW_INSTANCES_VW.DGRM_NAME is ' ';                       
comment on column FLOW_INSTANCES_VW.DGRM_VERSION is ' ';                    
comment on column FLOW_INSTANCES_VW.DGRM_STATUS is ' ';                     
comment on column FLOW_INSTANCES_VW.PRCS_PRIORITY is ' ';                   
comment on column FLOW_INSTANCES_VW.DGRM_CATEGORY is ' ';                   
comment on column FLOW_INSTANCES_VW.PRCS_STATUS is ' ';                     
comment on column FLOW_INSTANCES_VW.PRCS_INIT_TS is ' ';                    
comment on column FLOW_INSTANCES_VW.PRCS_INIT_BY is ' ';                    
comment on column FLOW_INSTANCES_VW.PRCS_START_TS is ' ';                   
comment on column FLOW_INSTANCES_VW.PRCS_DUE_ON is ' ';                     
comment on column FLOW_INSTANCES_VW.PRCS_COMPLETE_TS is ' ';                
comment on column FLOW_INSTANCES_VW.PRCS_LAST_UPDATE is ' ';                
comment on column FLOW_INSTANCES_VW.PRCS_LAST_UPDATE_BY is ' ';             
comment on column FLOW_INSTANCES_VW.PRCS_BUSINESS_REF is ' ';               
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.CONN_BPMN_ID is ' ';        
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.CONN_NAME is ' ';           
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.CONN_SRC_OBJT_ID is ' ';    
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.SRC_OBJT_BPMN_ID is ' ';    
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.PRCS_ID is ' ';             
comment on column FLOW_INSTANCE_CONNECTIONS_LOV.PRDG_ID is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.PRCS_ID is ' ';                  
comment on column FLOW_INSTANCE_DETAILS_VW.PRCS_NAME is ' ';                
comment on column FLOW_INSTANCE_DETAILS_VW.PRDG_ID is ' ';                  
comment on column FLOW_INSTANCE_DETAILS_VW.PRDG_PRDG_ID is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.DIAGRAM_LEVEL is ' ';            
comment on column FLOW_INSTANCE_DETAILS_VW.CALLING_DGRM is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.CALLING_OBJT is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.BREADCRUMB is ' ';               
comment on column FLOW_INSTANCE_DETAILS_VW.DRILLDOWN_ALLOWED is ' ';        
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_ID is ' ';                  
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_NAME is ' ';                
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_VERSION is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_STATUS is ' ';              
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_CATEGORY is ' ';            
comment on column FLOW_INSTANCE_DETAILS_VW.DGRM_CONTENT is ' ';             
comment on column FLOW_INSTANCE_DETAILS_VW.ALL_COMPLETED is ' ';            
comment on column FLOW_INSTANCE_DETAILS_VW.LAST_COMPLETED is ' ';           
comment on column FLOW_INSTANCE_DETAILS_VW.ALL_CURRENT is ' ';              
comment on column FLOW_INSTANCE_DETAILS_VW.ALL_ERRORS is ' ';               
comment on column FLOW_INSTANCE_DETAILS_VW.PRCS_BUSINESS_REF is ' ';        
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_ID is ' ';                    
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_PRDG_ID is ' ';               
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_PRCS_ID is ' ';               
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_DGRM_ID is ' ';               
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_CALLING_DGRM is ' ';          
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_CALLING_OBJT is ' ';          
comment on column FLOW_INSTANCE_DIAGRAMS.PRDG_DIAGRAM_LEVEL is ' ';         

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'                 
__________________________________________________________________________ 
comment on column FLOW_INSTANCE_DIAGRAMS_LOV.CALLING_DIAGRAM is ' ';       
comment on column FLOW_INSTANCE_DIAGRAMS_LOV.PRDG_ID is ' ';               
comment on column FLOW_INSTANCE_DIAGRAMS_LOV.PRDG_PRCS_ID is ' ';          
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_PRCS_ID is ' ';             
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_OBJT_ID is ' ';             
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_DGRM_ID is ' ';             
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_PRCS_NAME is ' ';           
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_BUSINESS_ID is ' ';         
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_PRCS_EVENT is ' ';          
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_TIMESTAMP is ' ';           
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_DURATION is ' ';            
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_USER is ' ';                
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_COMMENT is ' ';             
comment on column FLOW_INSTANCE_EVENT_LOG.LGPR_ERROR_INFO is ' ';          
comment on column FLOW_INSTANCE_GATEWAYS_LOV.OBJT_ID is ' ';               
comment on column FLOW_INSTANCE_GATEWAYS_LOV.OBJT_BPMN_ID is ' ';          
comment on column FLOW_INSTANCE_GATEWAYS_LOV.CALLING_OBJECT is ' ';        
comment on column FLOW_INSTANCE_GATEWAYS_LOV.OBJT_NAME is ' ';             
comment on column FLOW_INSTANCE_GATEWAYS_LOV.SELECT_OPTION is ' ';         
comment on column FLOW_INSTANCE_GATEWAYS_LOV.PRCS_ID is ' ';               
comment on column FLOW_INSTANCE_GATEWAYS_LOV.PRDG_DIAGRAM_LEVEL is ' ';    
comment on column FLOW_INSTANCE_GATEWAYS_LOV.PRDG_DGRM_ID is ' ';          
comment on column FLOW_INSTANCE_GATEWAYS_LOV.PRDG_PRDG_ID is ' ';          
comment on column FLOW_INSTANCE_GATEWAYS_LOV.PRDG_ID is ' ';               
comment on column FLOW_INSTANCE_STATS.STPR_DGRM_ID is ' ';                 
comment on column FLOW_INSTANCE_STATS.STPR_PERIOD_START is ' ';            
comment on column FLOW_INSTANCE_STATS.STPR_PERIOD is ' ';                  
comment on column FLOW_INSTANCE_STATS.STPR_CREATED is ' ';                 
comment on column FLOW_INSTANCE_STATS.STPR_STARTED is ' ';                 
comment on column FLOW_INSTANCE_STATS.STPR_ERROR is ' ';                   
comment on column FLOW_INSTANCE_STATS.STPR_COMPLETED is ' ';               
comment on column FLOW_INSTANCE_STATS.STPR_TERMINATED is ' ';              
comment on column FLOW_INSTANCE_STATS.STPR_RESET is ' ';                   
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_10PC_IVL is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_50PC_IVL is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_90PC_IVL is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_MAX_IVL is ' ';        
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_10PC_SEC is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_50PC_SEC is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_90PC_SEC is ' ';       
comment on column FLOW_INSTANCE_STATS.STPR_DURATION_MAX_SEC is ' ';        
comment on column FLOW_INSTANCE_TIMELINE_VW.OPERATION is ' ';              
comment on column FLOW_INSTANCE_TIMELINE_VW.DESCRIPTION is ' ';            
comment on column FLOW_INSTANCE_TIMELINE_VW.OBJT is ' ';                   
comment on column FLOW_INSTANCE_TIMELINE_VW.SUBFLOW is ' ';                
comment on column FLOW_INSTANCE_TIMELINE_VW.PROCESS_LEVEL is ' ';          
comment on column FLOW_INSTANCE_TIMELINE_VW.PROC_VAR is ' ';               
comment on column FLOW_INSTANCE_TIMELINE_VW.VALUE is ' ';                  
comment on column FLOW_INSTANCE_TIMELINE_VW.EVENT_COMMENT is ' ';          

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'                   
____________________________________________________________________________ 
comment on column FLOW_INSTANCE_TIMELINE_VW.PERFORMED_ON is ' ';             
comment on column FLOW_INSTANCE_TIMELINE_VW.PERFORMED_BY is ' ';             
comment on column FLOW_INSTANCE_TIMELINE_VW.PRCS_ID is ' ';                  
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_PRCS_ID is ' ';            
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_NAME is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_SCOPE is ' ';              
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_TYPE is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_VC2 is ' ';            
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_NUM is ' ';            
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_DATE is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_TSTZ is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_CLOB is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PROV_VAR_JSON is ' ';           
comment on column FLOW_INSTANCE_VARIABLES_VW.PRCS_NAME is ' ';               
comment on column FLOW_INSTANCE_VARIABLES_VW.PRCS_STATUS is ' ';             
comment on column FLOW_MESSAGES.FMSG_MESSAGE_KEY is ' ';                     
comment on column FLOW_MESSAGES.FMSG_LANG is ' ';                            
comment on column FLOW_MESSAGES.FMSG_MESSAGE_CONTENT is ' ';                 
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_ID is ' ';                  
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_MESSAGE_NAME is ' ';        
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_KEY_NAME is ' ';            
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_KEY_VALUE is ' ';           
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_PAYLOAD is ' ';             
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_PRCS_ID is ' ';             
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_SBFL_ID is ' ';             
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_RECEIVED_ON is ' ';         
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_WAS_CORRELATED is ' ';      
comment on column FLOW_MESSAGE_RECEIVED_LOG.LGRX_COMMENT is ' ';             
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_ID is ' ';                 
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_MESSAGE_NAME is ' ';       
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_KEY_NAME is ' ';           
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_KEY_VALUE is ' ';          
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_PRCS_ID is ' ';            
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_SBFL_ID is ' ';            
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_STEP_KEY is ' ';           
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_CALLBACK is ' ';           
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_CALLBACK_PAR is ' ';       
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_PAYLOAD_VAR is ' ';        
comment on column FLOW_MESSAGE_SUBSCRIPTIONS.MSUB_CREATED is ' ';            
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_ID is ' ';              
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_MESSAGE_NAME is ' ';    
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_KEY_NAME is ' ';        
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_KEY_VALUE is ' ';       
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_PRCS_ID is ' ';         
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_SBFL_ID is ' ';         
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_STEP_KEY is ' ';        
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_CALLBACK is ' ';        
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_CALLBACK_PAR is ' ';    
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_PAYLOAD_VAR is ' ';     

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'              
_______________________________________________________________________ 
comment on column FLOW_MESSAGE_SUBSCRIPTIONS_VW.MSUB_CREATED is ' ';    
comment on column FLOW_OBJECTS.OBJT_ID is ' ';                          
comment on column FLOW_OBJECTS.OBJT_BPMN_ID is ' ';                     
comment on column FLOW_OBJECTS.OBJT_DGRM_ID is ' ';                     
comment on column FLOW_OBJECTS.OBJT_NAME is ' ';                        
comment on column FLOW_OBJECTS.OBJT_TAG_NAME is ' ';                    
comment on column FLOW_OBJECTS.OBJT_SUB_TAG_NAME is ' ';                
comment on column FLOW_OBJECTS.OBJT_OBJT_ID is ' ';                     
comment on column FLOW_OBJECTS.OBJT_OBJT_LANE_ID is ' ';                
comment on column FLOW_OBJECTS.OBJT_ATTACHED_TO is ' ';                 
comment on column FLOW_OBJECTS.OBJT_INTERRUPTING is ' ';                
comment on column FLOW_OBJECTS.OBJT_ATTRIBUTES is ' ';                  
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_ID is ' ';               
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_OBJT_ID is ' ';          
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_SET is ' ';              
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_ORDER is ' ';            
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_VAR_NAME is ' ';         
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_VAR_TYPE is ' ';         
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_TYPE is ' ';             
comment on column FLOW_OBJECT_EXPRESSIONS.EXPR_EXPRESSION is ' ';       
comment on column FLOW_PARSER_LOG.PLOG_ID is ' ';                       
comment on column FLOW_PARSER_LOG.PLOG_DGRM_ID is ' ';                  
comment on column FLOW_PARSER_LOG.PLOG_BPMN_ID is ' ';                  
comment on column FLOW_PARSER_LOG.PLOG_LOG_TIME is ' ';                 
comment on column FLOW_PARSER_LOG.PLOG_PARSE_STEP is ' ';               
comment on column FLOW_PARSER_LOG.PLOG_PAYLOAD is ' ';                  
comment on column FLOW_PROCESSES.PRCS_ID is ' ';                        
comment on column FLOW_PROCESSES.PRCS_DGRM_ID is ' ';                   
comment on column FLOW_PROCESSES.PRCS_NAME is ' ';                      
comment on column FLOW_PROCESSES.PRCS_STATUS is ' ';                    
comment on column FLOW_PROCESSES.PRCS_INIT_TS is ' ';                   
comment on column FLOW_PROCESSES.PRCS_INIT_BY is ' ';                   
comment on column FLOW_PROCESSES.PRCS_START_TS is ' ';                  
comment on column FLOW_PROCESSES.PRCS_COMPLETE_TS is ' ';               
comment on column FLOW_PROCESSES.PRCS_DUE_ON is ' ';                    
comment on column FLOW_PROCESSES.PRCS_ARCHIVED_TS is ' ';               
comment on column FLOW_PROCESSES.PRCS_PRIORITY is ' ';                  
comment on column FLOW_PROCESSES.PRCS_LAST_UPDATE is ' ';               
comment on column FLOW_PROCESSES.PRCS_LAST_UPDATE_BY is ' ';            
comment on column FLOW_PROCESS_VARIABLES.PROV_PRCS_ID is ' ';           
comment on column FLOW_PROCESS_VARIABLES.PROV_SCOPE is ' ';             
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_NAME is ' ';          
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_TYPE is ' ';          
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_VC2 is ' ';           
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_NUM is ' ';           
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_DATE is ' ';          
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_TSTZ is ' ';          
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_CLOB is ' ';          
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_JSON is ' ';          

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'               
________________________________________________________________________ 
comment on column FLOW_PROCESS_VARIABLES.PROV_VAR_NAME_UC is ' ';        
comment on column FLOW_REST_DIAGRAMS_VW.DGRM_ID is ' ';                  
comment on column FLOW_REST_DIAGRAMS_VW.NAME is ' ';                     
comment on column FLOW_REST_DIAGRAMS_VW.VERSION is ' ';                  
comment on column FLOW_REST_DIAGRAMS_VW.STATUS is ' ';                   
comment on column FLOW_REST_DIAGRAMS_VW.CATEGORY is ' ';                 
comment on column FLOW_REST_DIAGRAMS_VW.LINKS is ' ';                    
comment on column FLOW_REST_EVENT_LOG.LGRT_ID is ' ';                    
comment on column FLOW_REST_EVENT_LOG.LGRT_CALL_GUID is ' ';             
comment on column FLOW_REST_EVENT_LOG.LGRT_CLIENT_ID is ' ';             
comment on column FLOW_REST_EVENT_LOG.LGRT_LOG_INFO is ' ';              
comment on column FLOW_REST_EVENT_LOG.LGRT_TOKEN is ' ';                 
comment on column FLOW_REST_EVENT_LOG.LGRT_TIMESTAMP is ' ';             
comment on column FLOW_REST_EVENT_LOG.LGRT_HTTP_METHOD is ' ';           
comment on column FLOW_REST_EVENT_LOG.LGRT_ENDPOINT is ' ';              
comment on column FLOW_REST_EVENT_LOG.LGRT_PAYLOAD is ' ';               
comment on column FLOW_REST_EVENT_LOG.LGRT_ERROR_CODE is ' ';            
comment on column FLOW_REST_EVENT_LOG.LGRT_ERROR_MSG is ' ';             
comment on column FLOW_REST_EVENT_LOG.LGRT_ERROR_STACKTRACE is ' ';      
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.MSUB_ID is ' ';     
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.NAME is ' ';        
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.KEY is ' ';         
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.VALUE is ' ';       
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.PRCS_ID is ' ';     
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.SBFL_ID is ' ';     
comment on column FLOW_REST_MESSAGE_SUBSCRIPTIONS_VW.STEP_KEY is ' ';    
comment on column FLOW_REST_PROCESSES_VW.DGRM_ID is ' ';                 
comment on column FLOW_REST_PROCESSES_VW.PRCS_ID is ' ';                 
comment on column FLOW_REST_PROCESSES_VW.NAME is ' ';                    
comment on column FLOW_REST_PROCESSES_VW.STATUS is ' ';                  
comment on column FLOW_REST_PROCESSES_VW.INIT_TS is ' ';                 
comment on column FLOW_REST_PROCESSES_VW.INIT_BY is ' ';                 
comment on column FLOW_REST_PROCESSES_VW.PROCESS_VARS is ' ';            
comment on column FLOW_REST_PROCESSES_VW.LINKS is ' ';                   
comment on column FLOW_REST_PROCESS_VARS_VW.PRCS_ID is ' ';              
comment on column FLOW_REST_PROCESS_VARS_VW.SCOPE is ' ';                
comment on column FLOW_REST_PROCESS_VARS_VW.NAME is ' ';                 
comment on column FLOW_REST_PROCESS_VARS_VW.TYPE is ' ';                 
comment on column FLOW_REST_PROCESS_VARS_VW.VALUE is ' ';                
comment on column FLOW_REST_SUBFLOWS_VW.PRCS_ID is ' ';                  
comment on column FLOW_REST_SUBFLOWS_VW.SBFL_ID is ' ';                  
comment on column FLOW_REST_SUBFLOWS_VW.SBFL_SBFL_ID is ' ';             
comment on column FLOW_REST_SUBFLOWS_VW.PROCESS_LEVEL is ' ';            
comment on column FLOW_REST_SUBFLOWS_VW.DIAGRAM_LEVEL is ' ';            
comment on column FLOW_REST_SUBFLOWS_VW.CALLING_SBFL is ' ';             
comment on column FLOW_REST_SUBFLOWS_VW.SCOPE is ' ';                    
comment on column FLOW_REST_SUBFLOWS_VW.current is ' ';                  
comment on column FLOW_REST_SUBFLOWS_VW.STEP_KEY is ' ';                 
comment on column FLOW_REST_SUBFLOWS_VW.STATUS is ' ';                   

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'                        
_________________________________________________________________________________ 
comment on column FLOW_REST_SUBFLOWS_VW.BECAME_CURRENT is ' ';                    
comment on column FLOW_REST_SUBFLOWS_VW.RESERVATION is ' ';                       
comment on column FLOW_REST_SUBFLOWS_VW.LINKS is ' ';                             
comment on column FLOW_STARTABLE_DIAGRAMS_VW.DGRM_ID is ' ';                      
comment on column FLOW_STARTABLE_DIAGRAMS_VW.DGRM_NAME is ' ';                    
comment on column FLOW_STARTABLE_DIAGRAMS_VW.DGRM_VERSION is ' ';                 
comment on column FLOW_STARTABLE_DIAGRAMS_VW.DGRM_STATUS is ' ';                  
comment on column FLOW_STARTABLE_DIAGRAMS_VW.PROCESS_NAME is ' ';                 
comment on column FLOW_STARTABLE_DIAGRAMS_VW.PROCESS_BPMN_ID is ' ';              
comment on column FLOW_STARTABLE_DIAGRAMS_VW.POTENTIAL_STARTING_USERS is ' ';     
comment on column FLOW_STARTABLE_DIAGRAMS_VW.POTENTIAL_STARTING_GROUPS is ' ';    
comment on column FLOW_STARTABLE_DIAGRAMS_VW.EXCLUDED_STARTING_USERS is ' ';      
comment on column FLOW_STATS_HISTORY.STHS_ID is ' ';                              
comment on column FLOW_STATS_HISTORY.STHS_DATE is ' ';                            
comment on column FLOW_STATS_HISTORY.STHS_STATUS is ' ';                          
comment on column FLOW_STATS_HISTORY.STHS_TYPE is ' ';                            
comment on column FLOW_STATS_HISTORY.STHS_OPERATION is ' ';                       
comment on column FLOW_STATS_HISTORY.STHS_ERRORS is ' ';                          
comment on column FLOW_STATS_HISTORY.STHS_COMMENTS is ' ';                        
comment on column FLOW_STATS_HISTORY.STHS_CREATED_ON is ' ';                      
comment on column FLOW_STATS_HISTORY.STHS_UPDATED_ON is ' ';                      
comment on column FLOW_STATS_HISTORY.STHS_UPDATED_BY is ' ';                      
comment on column FLOW_STEP_EVENT_LOG.LGSF_PRCS_ID is ' ';                        
comment on column FLOW_STEP_EVENT_LOG.LGSF_OBJT_ID is ' ';                        
comment on column FLOW_STEP_EVENT_LOG.LGSF_SBFL_ID is ' ';                        
comment on column FLOW_STEP_EVENT_LOG.LGSF_STEP_KEY is ' ';                       
comment on column FLOW_STEP_EVENT_LOG.LGSF_SBFL_PROCESS_LEVEL is ' ';             
comment on column FLOW_STEP_EVENT_LOG.LGSF_LAST_COMPLETED is ' ';                 
comment on column FLOW_STEP_EVENT_LOG.LGSF_STATUS_WHEN_COMPLETE is ' ';           
comment on column FLOW_STEP_EVENT_LOG.LGSF_SBFL_DGRM_ID is ' ';                   
comment on column FLOW_STEP_EVENT_LOG.LGSF_WAS_CURRENT is ' ';                    
comment on column FLOW_STEP_EVENT_LOG.LGSF_STARTED is ' ';                        
comment on column FLOW_STEP_EVENT_LOG.LGSF_COMPLETED is ' ';                      
comment on column FLOW_STEP_EVENT_LOG.LGSF_RESERVATION is ' ';                    
comment on column FLOW_STEP_EVENT_LOG.LGSF_DUE_ON is ' ';                         
comment on column FLOW_STEP_EVENT_LOG.LGSF_PRIORITY is ' ';                       
comment on column FLOW_STEP_EVENT_LOG.LGSF_USER is ' ';                           
comment on column FLOW_STEP_EVENT_LOG.LGSF_COMMENT is ' ';                        
comment on column FLOW_STEP_STATS.STSF_DGRM_ID is ' ';                            
comment on column FLOW_STEP_STATS.STSF_OBJT_BPMN_ID is ' ';                       
comment on column FLOW_STEP_STATS.STSF_TAG_NAME is ' ';                           
comment on column FLOW_STEP_STATS.STSF_PERIOD_START is ' ';                       
comment on column FLOW_STEP_STATS.STSF_PERIOD is ' ';                             
comment on column FLOW_STEP_STATS.STSF_COMPLETED is ' ';                          
comment on column FLOW_STEP_STATS.STSF_DURATION_10PC_IVL is ' ';                  
comment on column FLOW_STEP_STATS.STSF_DURATION_50PC_IVL is ' ';                  
comment on column FLOW_STEP_STATS.STSF_DURATION_90PC_IVL is ' ';                  
comment on column FLOW_STEP_STATS.STSF_DURATION_MAX_IVL is ' ';                   
comment on column FLOW_STEP_STATS.STSF_DURATION_10PC_SEC is ' ';                  

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'           
____________________________________________________________________ 
comment on column FLOW_STEP_STATS.STSF_DURATION_50PC_SEC is ' ';     
comment on column FLOW_STEP_STATS.STSF_DURATION_90PC_SEC is ' ';     
comment on column FLOW_STEP_STATS.STSF_DURATION_MAX_SEC is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_10PC_IVL is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_50PC_IVL is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_90PC_IVL is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_MAX_IVL is ' ';       
comment on column FLOW_STEP_STATS.STSF_WAITING_10PC_SEC is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_50PC_SEC is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_90PC_SEC is ' ';      
comment on column FLOW_STEP_STATS.STSF_WAITING_MAX_SEC is ' ';       
comment on column FLOW_SUBFLOWS.SBFL_ID is ' ';                      
comment on column FLOW_SUBFLOWS.SBFL_PRCS_ID is ' ';                 
comment on column FLOW_SUBFLOWS.SBFL_DGRM_ID is ' ';                 
comment on column FLOW_SUBFLOWS.SBFL_SBFL_ID is ' ';                 
comment on column FLOW_SUBFLOWS.SBFL_PROCESS_LEVEL is ' ';           
comment on column FLOW_SUBFLOWS.SBFL_DIAGRAM_LEVEL is ' ';           
comment on column FLOW_SUBFLOWS.SBFL_CALLING_SBFL is ' ';            
comment on column FLOW_SUBFLOWS.SBFL_SCOPE is ' ';                   
comment on column FLOW_SUBFLOWS.SBFL_STARTING_OBJECT is ' ';         
comment on column FLOW_SUBFLOWS.SBFL_ROUTE is ' ';                   
comment on column FLOW_SUBFLOWS.SBFL_LAST_COMPLETED is ' ';          
comment on column FLOW_SUBFLOWS.SBFL_CURRENT is ' ';                 
comment on column FLOW_SUBFLOWS.SBFL_STEP_KEY is ' ';                
comment on column FLOW_SUBFLOWS.SBFL_DUE_ON is ' ';                  
comment on column FLOW_SUBFLOWS.SBFL_PRIORITY is ' ';                
comment on column FLOW_SUBFLOWS.SBFL_STATUS is ' ';                  
comment on column FLOW_SUBFLOWS.SBFL_BECAME_CURRENT is ' ';          
comment on column FLOW_SUBFLOWS.SBFL_WORK_STARTED is ' ';            
comment on column FLOW_SUBFLOWS.SBFL_HAS_EVENTS is ' ';              
comment on column FLOW_SUBFLOWS.SBFL_IS_FOLLOWING_EBG is ' ';        
comment on column FLOW_SUBFLOWS.SBFL_LANE is ' ';                    
comment on column FLOW_SUBFLOWS.SBFL_LANE_NAME is ' ';               
comment on column FLOW_SUBFLOWS.SBFL_LANE_ISROLE is ' ';             
comment on column FLOW_SUBFLOWS.SBFL_LANE_ROLE is ' ';               
comment on column FLOW_SUBFLOWS.SBFL_RESERVATION is ' ';             
comment on column FLOW_SUBFLOWS.SBFL_POTENTIAL_USERS is ' ';         
comment on column FLOW_SUBFLOWS.SBFL_POTENTIAL_GROUPS is ' ';        
comment on column FLOW_SUBFLOWS.SBFL_EXCLUDED_USERS is ' ';          
comment on column FLOW_SUBFLOWS.SBFL_ITERATION_TYPE is ' ';          
comment on column FLOW_SUBFLOWS.SBFL_LOOP_COUNTER is ' ';            
comment on column FLOW_SUBFLOWS.SBFL_LOOP_TOTAL_INSTANCES is ' ';    
comment on column FLOW_SUBFLOWS.SBFL_LAST_UPDATE is ' ';             
comment on column FLOW_SUBFLOWS.SBFL_LAST_UPDATE_BY is ' ';          
comment on column FLOW_SUBFLOWS.SBFL_ITERATION_PATH is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_ID is ' ';                   
comment on column FLOW_SUBFLOWS_VW.SBFL_SBFL_ID is ' ';              
comment on column FLOW_SUBFLOWS_VW.SBFL_PRCS_ID is ' ';              
comment on column FLOW_SUBFLOWS_VW.SBFL_PROCESS_NAME is ' ';         

'COMMENTONCOLUMN'||TABLE_NAME||'.'||COLUMN_NAME||'IS'''';'              
_______________________________________________________________________ 
comment on column FLOW_SUBFLOWS_VW.SBFL_DGRM_ID is ' ';                 
comment on column FLOW_SUBFLOWS_VW.SBFL_SBFL_DGRM_ID is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_DGRM_NAME is ' ';               
comment on column FLOW_SUBFLOWS_VW.SBFL_DGRM_VERSION is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_DGRM_STATUS is ' ';             
comment on column FLOW_SUBFLOWS_VW.SBFL_DGRM_CATEGORY is ' ';           
comment on column FLOW_SUBFLOWS_VW.SBFL_STARTING_OBJECT is ' ';         
comment on column FLOW_SUBFLOWS_VW.SBFL_STARTING_OBJECT_NAME is ' ';    
comment on column FLOW_SUBFLOWS_VW.SBFL_ROUTE is ' ';                   
comment on column FLOW_SUBFLOWS_VW.SBFL_ROUTE_NAME is ' ';              
comment on column FLOW_SUBFLOWS_VW.SBFL_LAST_COMPLETED is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_LAST_COMPLETED_NAME is ' ';     
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT is ' ';                 
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT_NAME is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_ITERATION_PATH is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_STEP_KEY is ' ';                
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT_TAG_NAME is ' ';        
comment on column FLOW_SUBFLOWS_VW.SBFL_BECAME_CURRENT is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_DUE_ON is ' ';                  
comment on column FLOW_SUBFLOWS_VW.SBFL_LAST_UPDATE is ' ';             
comment on column FLOW_SUBFLOWS_VW.SBFL_LAST_UPDATE_BY is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_PRIORITY is ' ';                
comment on column FLOW_SUBFLOWS_VW.SBFL_STATUS is ' ';                  
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT_LANE is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT_LANE_NAME is ' ';       
comment on column FLOW_SUBFLOWS_VW.SBFL_LANE_ISROLE is ' ';             
comment on column FLOW_SUBFLOWS_VW.SBFL_LANE_ROLE is ' ';               
comment on column FLOW_SUBFLOWS_VW.SBFL_PROCESS_LEVEL is ' ';           
comment on column FLOW_SUBFLOWS_VW.SBFL_DIAGRAM_LEVEL is ' ';           
comment on column FLOW_SUBFLOWS_VW.SBFL_LOOP_COUNTER is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_LOOP_TOTAL_INSTANCES is ' ';    
comment on column FLOW_SUBFLOWS_VW.SBFL_SCOPE is ' ';                   
comment on column FLOW_SUBFLOWS_VW.SBFL_CALLING_SBFL is ' ';            
comment on column FLOW_SUBFLOWS_VW.SBFL_RESERVATION is ' ';             
comment on column FLOW_SUBFLOWS_VW.SBFL_POTENTIAL_USERS is ' ';         
comment on column FLOW_SUBFLOWS_VW.SBFL_POTENTIAL_GROUPS is ' ';        
comment on column FLOW_SUBFLOWS_VW.SBFL_EXCLUDED_USERS is ' ';          
comment on column FLOW_SUBFLOWS_VW.SBFL_CURRENT_OBJT_ID is ' ';         
comment on column FLOW_SUBFLOWS_VW.SBFL_PRCS_INIT_TS is ' ';            
comment on column FLOW_SUBFLOWS_VW.TIMR_START_ON is ' ';                
comment on column FLOW_SUBFLOW_LOG.SFLG_PRCS_ID is ' ';                 
comment on column FLOW_SUBFLOW_LOG.SFLG_OBJT_ID is ' ';                 
comment on column FLOW_SUBFLOW_LOG.SFLG_SBFL_ID is ' ';                 
comment on column FLOW_SUBFLOW_LOG.SFLG_STEP_KEY is ' ';                
comment on column FLOW_SUBFLOW_LOG.SFLG_DGRM_ID is ' ';                 
comment on column FLOW_SUBFLOW_LOG.SFLG_DIAGRAM_LEVEL is ' ';           
comment on column FLOW_SUBFLOW_LOG.SFLG_LAST_UPDATED is ' ';            
comment on column FLOW_SUBFLOW_LOG.SFLG_NOTES is ' ';  
                 
comment on column FLOW_TASK_INBOX_VW.SBFL_ID is ' '; 
comment on column FLOW_TASK_INBOX_VW.SBFL_SBFL_ID is ' ';                 
comment on column FLOW_TASK_INBOX_VW.SBFL_PRCS_ID is ' ';                 
comment on column FLOW_TASK_INBOX_VW.SBFL_PROCESS_NAME is ' ';            
comment on column FLOW_TASK_INBOX_VW.SBFL_PRCS_INIT_TS is ' ';            
comment on column FLOW_TASK_INBOX_VW.SBFL_DGRM_ID is ' ';                 
comment on column FLOW_TASK_INBOX_VW.SBFL_DGRM_NAME is ' ';               
comment on column FLOW_TASK_INBOX_VW.SBFL_DGRM_VERSION is ' ';            
comment on column FLOW_TASK_INBOX_VW.SBFL_DGRM_STATUS is ' ';             
comment on column FLOW_TASK_INBOX_VW.SBFL_DGRM_CATEGORY is ' ';           
comment on column FLOW_TASK_INBOX_VW.SBFL_STARTING_OBJECT is ' ';         
comment on column FLOW_TASK_INBOX_VW.SBFL_STARTING_OBJECT_NAME is ' ';    
comment on column FLOW_TASK_INBOX_VW.SBFL_ROUTE is ' ';                   
comment on column FLOW_TASK_INBOX_VW.SBFL_ROUTE_NAME is ' ';              
comment on column FLOW_TASK_INBOX_VW.SBFL_LAST_COMPLETED is ' ';          
comment on column FLOW_TASK_INBOX_VW.SBFL_LAST_COMPLETED_NAME is ' ';     
comment on column FLOW_TASK_INBOX_VW.SBFL_CURRENT is ' ';                 
comment on column FLOW_TASK_INBOX_VW.SBFL_CURRENT_NAME is ' ';            
comment on column FLOW_TASK_INBOX_VW.SBFL_STEP_KEY is ' ';                
comment on column FLOW_TASK_INBOX_VW.SBFL_SCOPE is ' ';                   
comment on column FLOW_TASK_INBOX_VW.LINK_TEXT is ' ';                    
comment on column FLOW_TASK_INBOX_VW.SBFL_CURRENT_TAG_NAME is ' ';        
comment on column FLOW_TASK_INBOX_VW.SBFL_BECAME_CURRENT is ' ';          
comment on column FLOW_TASK_INBOX_VW.SBFL_LAST_UPDATE is ' ';             
comment on column FLOW_TASK_INBOX_VW.SBFL_LAST_UPDATE_BY is ' ';          
comment on column FLOW_TASK_INBOX_VW.SBFL_STATUS is ' ';                  
comment on column FLOW_TASK_INBOX_VW.SBFL_CURRENT_LANE is ' ';            
comment on column FLOW_TASK_INBOX_VW.SBFL_CURRENT_LANE_NAME is ' ';       
comment on column FLOW_TASK_INBOX_VW.SBFL_POTENTIAL_USERS is ' ';         
comment on column FLOW_TASK_INBOX_VW.SBFL_POTENTIAL_GROUPS is ' ';        
comment on column FLOW_TASK_INBOX_VW.SBFL_EXCLUDED_USERS is ' ';          
comment on column FLOW_TASK_INBOX_VW.SBFL_RESERVATION is ' ';             
comment on column FLOW_TASK_INBOX_VW.SBFL_PRIORITY is ' ';                
comment on column FLOW_TASK_INBOX_VW.SBFL_DUE_ON is ' ';                  
comment on column FLOW_TASK_INBOX_VW.SBFL_BUSINESS_REF is ' ';  

comment on column FLOW_TIMERS.TIMR_ID is ' ';                             
comment on column FLOW_TIMERS.TIMR_RUN is ' ';                            
comment on column FLOW_TIMERS.TIMR_PRCS_ID is ' ';                        
comment on column FLOW_TIMERS.TIMR_SBFL_ID is ' ';                        
comment on column FLOW_TIMERS.TIMR_STEP_KEY is ' ';                       
comment on column FLOW_TIMERS.TIMR_TYPE is ' ';                           
comment on column FLOW_TIMERS.TIMR_LAST_RUN is ' ';                       
comment on column FLOW_TIMERS.TIMR_CREATED_ON is ' ';                     
comment on column FLOW_TIMERS.TIMR_STATUS is ' ';                         
comment on column FLOW_TIMERS.TIMR_START_ON is ' ';                       
comment on column FLOW_TIMERS.TIMR_INTERVAL_YM is ' ';                    
comment on column FLOW_TIMERS.TIMR_INTERVAL_DS is ' ';                    
comment on column FLOW_TIMERS.TIMR_REPEAT_TIMES is ' ';                   
comment on column FLOW_TIMERS.TIMR_CALLBACK is ' ';                       
comment on column FLOW_TIMERS.TIMR_CALLBACK_PAR is ' ';     

comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_PRCS_ID is ' ';      
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_SCOPE is ' ';        
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_NAME is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_OBJT_ID is ' ';      
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_SBFL_ID is ' ';      
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_EXPR_SET is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_TIMESTAMP is ' ';    
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_TYPE is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_VC2 is ' ';      
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_NUM is ' ';      
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_DATE is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_TSTZ is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_CLOB is ' ';     
comment on column FLOW_VARIABLE_EVENT_LOG.LGVR_VAR_JSON is ' ';     