create table flow_tasks
( task_id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
, task_objt_id NUMBER
, task_objt_bpmn_id varchar2(50)
, task_dgrm_id NUMBER
, task_type varchar2(50)
, task_app_id NUMBER
, task_app_alias varchar2(50)
, task_page_id NUMBER
, task_request varchar2(50)
, task_clear_cache varchar2(50)
, task_set_items varchar2(200)
, task_set_values varchar2(200)
, task_URL varchar2(200)
);

alter table flow_tasks add constraint task_pk primary key (task_id);

create table flow_scripts
( scrp_id NUMBER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
, scrp_objt_id NUMBER
, scrp_objt_bpmn_id varchar2(50)
, scrp_dgrm_id NUMBER
, scrp_type varchar2(50)
, scrp_syncronous varchar2(20)   -- values 'synchronous' 'non-synchronous'
, scrp_schema varchar2(50)
, scrp_package varchar2(50)
, scrp_procedure varchar2(50)
, scrp_arg1 varchar2(50)
, scrp_value1 varchar2(50)
, scrp_arg2 varchar2(50)
, scrp_value2 varchar2(50)
, scrp_arg3 varchar2(50)
, scrp_value3 varchar2(50)
);

alter table flow_scripts add constraint scrp_pk primary key (scrp_id);

alter table flow_processes add 
( prcs_ref_obj_type  VARCHAR2(50 CHAR)    
, prcs_ref_obj_id    NUMBER
, prcs_initiator varchar2(200)
, prcs_priority NUMBER
, prcs_vc1 varchar2(200)
, prcs_vc2 varchar2(200)
, prcs_vc3 varchar2(200)
, prcs_vc4 varchar2(200)
, prcs_vc5 varchar2(200)
, prcs_vc6 varchar2(200)
, prcs_num1 number
, prcs_num2 number
, prcs_num3 number
, prcs_num4 number
, prcs_num5 number
, prcs_num6 number
)
;

comment on column flow_processes.prcs_ref_obj_id1 is 'Value of this  primary key for the subject of this process. For example, 1001 for Order No 1001';
comment on column flow_processes.prcs_ref_obj_id2 is 'Value of this  primary key for the subject of this process. For example, 1001 for Order No 1001';
comment on column flow_processes.prcs_priority is 'Process Priority.  Not currently used by Flows for APEX but available for application use';
comment on column flow_processes.prcs_vc1 is 'Process Variable prcs_vc1.  Usage for this process is defined in flow_diagrams.prcs_vc1 for relevant diagram';
comment on column flow_processes.prcs_vc2 is 'Process Variable prcs_vc2.  Usage for this process is defined in flow_diagrams.prcs_vc2 for relevant diagram';
comment on column flow_processes.prcs_vc3 is 'Process Variable prcs_vc3.  Usage for this process is defined in flow_diagrams.prcs_vc3 for relevant diagram';
comment on column flow_processes.prcs_vc4 is 'Process Variable prcs_vc4.  Usage for this process is defined in flow_diagrams.prcs_vc4 for relevant diagram';
comment on column flow_processes.prcs_vc5 is 'Process Variable prcs_vc5.  Usage for this process is defined in flow_diagrams.prcs_vc5 for relevant diagram';
comment on column flow_processes.prcs_vc6 is 'Process Variable prcs_vc6.  Usage for this process is defined in flow_diagrams.prcs_vc6 for relevant diagram';
comment on column flow_processes.prcs_num1 is 'Process Variable prcs_num1.  Usage for this process is defined in flow_diagrams.prcs_num1 for relevant diagram';
comment on column flow_processes.prcs_num2 is 'Process Variable prcs_num2.  Usage for this process is defined in flow_diagrams.prcs_num2 for relevant diagram';
comment on column flow_processes.prcs_num3 is 'Process Variable prcs_num3.  Usage for this process is defined in flow_diagrams.prcs_num3 for relevant diagram';
comment on column flow_processes.prcs_num4 is 'Process Variable prcs_num4.  Usage for this process is defined in flow_diagrams.prcs_num4 for relevant diagram';
comment on column flow_processes.prcs_num5 is 'Process Variable prcs_num5.  Usage for this process is defined in flow_diagrams.prcs_num5 for relevant diagram';
comment on column flow_processes.prcs_num6 is 'Process Variable prcs_num6.  Usage for this process is defined in flow_diagrams.prcs_num6 for relevant diagram';

alter table flow_diagrams add
( dgrm_ref_objt_col1 varchar2(60)
, dgrm_ref_objt_col2 varchar2(60)
, dgrm_def_prcs_vc1 varchar2(50)
, dgrm_def_prcs_vc2 varchar2(50)
, dgrm_def_prcs_vc3 varchar2(50)
, dgrm_def_prcs_vc4 varchar2(50)
, dgrm_def_prcs_vc5 varchar2(50)
, dgrm_def_prcs_vc6 varchar2(50)
, dgrm_def_prcs_num1 varchar2(50)
, dgrm_def_prcs_num2 varchar2(50)
, dgrm_def_prcs_num3 varchar2(50)
, dgrm_def_prcs_num4 varchar2(50)
, dgrm_def_prcs_num5 varchar2(50)
, dgrm_def_prcs_num6 varchar2(50)
)
;
comment on column flow_processes.dgrm_ref_obj_col1 is 'Application tablename.columnname of the column storing the subject (primary key) of this process. For example, orders.order_id.';
comment on column flow_processes.dgrm_ref_obj_col2 is 'Application tablename.columnname of the column storing the subject (primary key) of this process. For example, orders.order_id. (compound key)';
comment on column flow_diagrams.dgrm_def_prcs_vc1  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc1.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_vc2  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc2.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_vc3  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc3.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_vc4  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc4.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_vc5  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc5.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_vc6  is 'Defines usage or meaning of Process Variable flow_processes.prcs_vc6.  for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num1 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num1. for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num2 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num2. for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num3 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num3. for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num4 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num4. for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num5 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num5. for instances of this diagram(process)';
comment on column flow_diagrams.dgrm_def_prcs_num6 is 'Defines usage or meaning of Process Variable flow_processes.prcs_num6. for instances of this diagram(process)';
