/*
  Migration Script for Release 5.1.2 to 21.1
*/

PROMPT >> Running DDL for Upgrade from 5.1.2 to 21.1
PROMPT >> -------------------------------------------

PROMPT >> Remove obsolete objects
drop view flow_p0010_subflows_vw;
drop view flow_p0010_variables_vw;
drop view flow_p0010_branches_vw;
drop view flow_p0010_routes_vw;

drop package flow_p0010_api;

PROMPT >> Create new tables
CREATE TABLE flow_object_expressions (
    expr_id          NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    expr_objt_id     NUMBER NOT NULL,
    expr_set         VARCHAR2(20 CHAR) NOT NULL,
    expr_order       NUMBER NOT NULL,
    expr_var_name    VARCHAR2(50 CHAR) NOT NULL,
    expr_var_type    VARCHAR2(50 CHAR) NOT NULL,
    expr_type        VARCHAR2(130 CHAR) NOT NULL,
    expr_expression  VARCHAR2(4000 CHAR) 
 );

ALTER TABLE flow_object_expressions ADD CONSTRAINT expr_pk PRIMARY KEY (expr_id);                                                     

ALTER TABLE flow_object_expressions 
    ADD CONSTRAINT expr_uk UNIQUE ( expr_objt_id, expr_set, expr_order);
  
ALTER TABLE flow_object_expressions
    ADD CONSTRAINT expr_objt_fk FOREIGN KEY ( expr_objt_id )
        REFERENCES flow_objects ( objt_id )
            ON DELETE CASCADE;

ALTER TABLE flow_object_expressions
    ADD CONSTRAINT expr_set_ck
      CHECK ( expr_set in ('beforeEvent', 'onEvent', 'beforeTask', 'afterTask', 'beforeSplit', 'afterMerge') );

create table flow_flow_event_log
( lgfl_dgrm_id       		NUMBER NOT NULL
, lgfl_dgrm_name     		VARCHAR2(150 CHAR) NOT NULL
, lgfl_dgrm_version  		VARCHAR2(10 CHAR) NOT NULL
, lgfl_dgrm_status   		VARCHAR2(10 CHAR) NOT NULL
, lgfl_dgrm_category 		VARCHAR2(30 CHAR)
, lgfl_timestamp 			TIMESTAMP WITH TIME ZONE NOT NULL
, lgfl_user				    VARCHAR2(255 char)
, lgfl_comment              VARCHAR2(2000 CHAR)
, lgfl_dgrm_content  		CLOB
);

create table flow_instance_event_log
( lgpr_prcs_id           	NUMBER NOT NULL
, lgpr_objt_id              VARCHAR2(50 CHAR) NULL
, lgpr_dgrm_id      		NUMBER NOT NULL
, lgpr_prcs_name         	VARCHAR2(150 CHAR) NOT NULL
, lgpr_business_id			VARCHAR2(4000 char)
, lgpr_prcs_event       	VARCHAR2(20 CHAR) NOT NULL
, lgpr_timestamp     		TIMESTAMP WITH TIME ZONE NOT NULL
, lgpr_user 				VARCHAR2(255 char)
, lgpr_comment				VARCHAR2(2000 CHAR)
, lgpr_error_info           VARCHAR2(2000 CHAR)
);


create table flow_step_event_log
( lgsf_prcs_id       		NUMBER NOT NULL
, lgsf_objt_id       		VARCHAR2(50) NOT NULL
, lgsf_sbfl_id      		NUMBER NOT NULL
, lgsf_sbfl_process_level   NUMBER
, lgsf_last_completed 	    VARCHAR2(50) 
, lgsf_status_when_complete VARCHAR2(20)
, lgsf_sbfl_dgrm_id   	    NUMBER NOT NULL
, lgsf_was_current		    TIMESTAMP WITH TIME ZONE
, lgsf_started 			    TIMESTAMP WITH TIME ZONE
, lgsf_completed 			TIMESTAMP WITH TIME ZONE 
, lgsf_reservation		    VARCHAR2(255 char)
, lgsf_user				    VARCHAR2(255 char)	
, lgsf_comment         	    VARCHAR2(2000 CHAR)
);

create table flow_variable_event_log
( lgvr_prcs_id			    number not null
, lgvr_var_name			    varchar2(50 char) not null
, lgvr_objt_id			    VARCHAR2(50 char) 
, lgvr_sbfl_id			    NUMBER
, lgvr_expr_set			    VARCHAR2(20 CHAR) 
, lgvr_timestamp			TIMESTAMP WITH TIME ZONE NOT NULL
, lgvr_var_type			    varchar2(50 char) not null 
, lgvr_var_vc2 			    varchar2(4000 char)
, lgvr_var_num 			    number
, lgvr_var_date 			date
, lgvr_var_clob 			clob
);

create table flow_configuration
( cfig_key                  varchar2(50 char) NOT NULL
, cfig_value                varchar2(2000 char)
);

alter table flow_configuration ADD CONSTRAINT cfig_pk PRIMARY KEY ( cfig_key );

create table flow_messages
( fmsg_message_key          varchar2(30 char) not null
, fmsg_lang                 varchar2(10 char) not null
, fmsg_message_content      varchar2(2000 char) 
);

alter table flow_messages ADD CONSTRAINT fmsg_pk PRIMARY KEY ( fmsg_message_key, fmsg_lang );

PROMPT >> Alter existing tables
alter table flow_subflows add sbfl_dgrm_id number;
alter table flow_subflows add constraint sbfl_dgrm_fk foreign key (sbfl_dgrm_id) references flow_diagrams (dgrm_id) enable;
alter table flow_subflows add sbfl_became_current timestamp with time zone;
alter table flow_subflows add sbfl_work_started timestamp with time zone;

PROMPT >> Datas migration

-- data migration - copy dgrm_id from flow_processes.prcs_dgrm_id to all flow_subflows rows in that process sbfl_dgrm_id
begin
  for rec in (
    select prcs_id, prcs_dgrm_id
    from flow_processes
  )
  loop
    update flow_subflows
       set sbfl_dgrm_id = rec.prcs_dgrm_id
     where sbfl_prcs_id = rec.prcs_id;
  end loop;
end;
/
alter table flow_subflows modify (sbfl_dgrm_id not null);

PROMPT >> Insert new configuration values
insert into flow_configuration (cfig_key, cfig_value) values ('logging_level', 'standard');
insert into flow_configuration (cfig_key, cfig_value) values ('logging_hide_userid', 'false');
insert into flow_configuration (cfig_key, cfig_value) values ('logging_language','en');
insert into flow_configuration (cfig_key, cfig_value) values ('engine_app_mode','production');

PROMPT >> Insert new messages
set define off
PROMPT >> Loading Exported Messages
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'ITE-unsupported-type',
'en',
'Currently unsupported type of Intermediate Throw Event encountered at %0 .'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-child-lock-to',
'en',
'Child Boundary Subflows or Timers of %0 currently locked by another user.  Retry your transaction later.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-no-catch-found',
'en',
'No boundaryEvent of type %0 found to catch event.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-too-many',
'en',
'More than one %0 boundaryEvent found on sub process.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'eng_handle_event_int',
'en',
'Flow Engine Internal Error: Process %0 Subflow %1 Module %2 Current %4 Current Tag %3'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-unsupported-object',
'en',
'Model Error: Process BPMN model next step uses unsupported object %0'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-util-prcs-not-found',
'en',
'Application Error: Process ID %0 not found.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-util-sbfl-not-in-prcs',
'en',
'Subflow ID supplied ( %0 ) not found. Check for process events that changed process flow (timeouts, errors, escalations).'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-invalid-route',
'en',
'Error at gateway %0. Supplied variable %1 contains invalid route: %2'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-merge-error',
'en',
'Internal error processing merging gateway on subflow %0'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-no-route',
'en',
'No gateway routing instruction provided in variable %0 and model contains no default route.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-too-many-defaults',
'en',
'More than one default route specified in model for Gateway %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'link-no-catch',
'en',
'Unable to find matching link catch event named %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'link-too-many-catches',
'en',
'More than one matching link catch event named %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'logging-instance-event',
'en',
'Flows - Internal error logging %0 event'
);
 

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'process-lock-timeout',
'en',
'Process objects for %0 currently locked by another user.  Try again later.'
);
  
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'more_than_1_forward_path',
'en',
'More than 1 forward path found when only 1 allowed.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'no_next_step_found',
'en',
'No Next Step Found on subflow %0.  Check your process diagram.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plsql_script_failed',
'en',
'Process %0: ScriptTask %1 failed due to PL/SQL error - see event log.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plsql_script_requested_stop',
'en',
'Process %0: ScriptTask %1 requested processing stop - see event log.'										  
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timeout_locking_subflow',
'en',
'Unable to lock subflow %0 as currently locked by another user.  Try again later.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-already-placed',
'en',
'Reservation already placed on next task for you.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-by-other_user',
'en',
'Reservation for %0 unsuccessful.  Step already reserved by another user (%1).'
); 
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-failed-not-found',
'en',
'Reservation for %2 unsuccessful.  Subflow %0 in Process %1 not found.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-lock-timeout',
'en',
'Subflow currently locked (not reserved) by another user.  Try your reservation again later.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-release-not-found',
'en',
'Reservation release unsuccessful.  Subflow %0 in Process %1 not found.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'restart-no-error',
'en',
'No Current Error Found.  Check your process diagram.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-already-running',
'en',
'You tried to start a process (id %0)that is already running.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-multiple-already-running',
'en',
'You tried to start a process (id %0) with multiple copies already running.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-multiple-start-events',
'en',
'You have multiple starting events defined. Make sure your diagram has only one start event.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-no-start-event',
'en',
'No starting event is defined in the Flow diagram.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-not-created',
'en',
'You tried to start a process (id %0) that does not exist.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-type-unsupported',
'en',
'Unsupported start event type (%0). Only None (standard) Start Event and Timer Start Event are currently supported.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'startwork-sbfl-not-found',
'en',
'Start Work time recording unsuccessful.  Subflow %0 in Process %1 not found.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'subProcess-no-start',
'en',
'Unable to find Sub-Process Start Event.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'subProcess-too-many-starts',
'en',
'More than one Sub-Process Start found.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-broken',
'en',
'Timer %0 broken in process %1 , subflow : %2.  See error_info.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-cycle-unsupported',
'en',
'Cycle Timer defined for object %0 not currently supported.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-incomplete-definition',
'en',
'Incomplete timer definitions for object %0. Type: %1; Value: %2'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-lock-timeout',
'en',
'Timer for subflow %0 currently locked by another user.  Try again later.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-object-not-found',
'en',
'Object with timer not found in get_timer_definition. Subflow %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timers-lock-timeout',
'en',
'Timers for process %0 currently locked by another user.  Try again later.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var-set-error',
'en',
'Error %0 process variable %1 for process id %1.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_datatype',
'en',
'Error setting process variable.  Incorrect datatype for variable %0.  SQL error shown in debug output.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_date_format',
'en',
'Error setting Process Variable %1: Incorrect Date Format (Subflow: %0, Set: %3.)'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_object_not_found',
'en',
'Internal error looking up object %0 in process_expressions.  SQL error shown in debug output.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_plsql_error',
'en',
'Subflow : %0 Error in %2 expression for Variable : %1'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_no_data',
'en',
'Error setting %2 process variable %1 in process id %0.  No data found in query.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_other',
'en',
'Error setting %2 process variable %1 in process id %0.  SQL error shown in event log.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_too_many_rows',
'en',
'Error setting %2 process variable %1 in process id %0.  Query returns multiple rows.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_static_general',
'en',
'Error setting %2 process variable %1 in process id %0.  See error in event log.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'version-no-rel-or-draft-v0',
'en',
'Cannot find released diagram or draft version 0 of diagram - please specify a version or diagram_id'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
  values (
 'timer_definition_error',
 'en',
 'Error parsing timer definition in process %0, subflow %1. Timer Type: %2, Definition: %3'
 );
 
/* Plug-ins */
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-model-no-version',
'en',
'Version not defined.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-parsing-json-variables',
'en',
'Error during parsing process variables.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-route-not-define',
'en',
'Gateway is not define for routing.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-gateway-not-exist',
'en',
'Gateway define does not exists for this flow.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-no-instance-subflow-id',
'en',
'Unable to get Flow Instance Id and or subflow Id to manage the step.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-wrong-variable-number',
'en',
'Wrong number of APEX item(s) or process variable(s).'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-wrong-variable-type',
'en',
'One or more process variable(s) are a different type than the one defined in the JSON.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-variable-not-a-number',
'en',
'%0 is not a valid number.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-variable-not-a-date',
'en',
'%0 is not a valid date.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-modeler-id-not-found',
'en',
'No data found. Check if Diagram with given ID exists.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-unexpected-error',
'en',
'Unexpected error, please contact your administrator.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-not-parsable',
'en',
'Diagram could not be parsed.<br />Please review your diagram to ensure that it is supported.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-saved',
'en',
'Changes saved!'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-has-changed',
'en',
'Model has changed. Discard changes?'
);

set define off
PROMPT >> Loading Exported Messages
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'ITE-unsupported-type',
'fr',
'Type d''événement de lancer intermédiaire actuellement non pris en charge rencontré à %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-child-lock-to',
'fr',
'Sous-flux enfant ou minuteur de %0 sont actuellement verrouillés par un autre utilisateur. . Réessayez votre transaction plus tard.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-no-catch-found',
'fr',
'Aucun événement de frontière de type %0 trouvé pour capturer l''événement.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'boundary-event-too-many',
'fr',
'Plus d''un événement de frontière %0 trouvé sur le sous-processus.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'eng_handle_event_int',
'fr',
'Erreur interne du moteur de flux: Processus %0 Sous-flux %1 Module %2 Courant %4 Balise courante %3'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-unsupported-object',
'fr',
'Erreur de modèle : L''étape suivante du modèle de processus BPMN utilise un objet non supporté %0'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-util-prcs-not-found',
'fr',
'Erreur applicative : L''ID du processus %0 n''a pas été trouvé.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'engine-util-sbfl-not-in-prcs',
'fr',
'L''ID du sous-flux fourni ( %0 ) est introuvable. Vérifiez les événements du processus qui ont modifié le flux du processus (délais, erreurs, escalades).'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-invalid-route',
'fr',
'Erreur au niveau de la passerelle %0. La variable fournie %1 contient une route invalide : %2'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-merge-error',
'fr',
'Erreur interne de traitement lors de la fusion au nivau de la passerelle sur le sous-flux %0'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-no-route',
'fr',
'Aucune instruction de routage de passerelle n''est fournie dans la variable %0 et le modèle ne contient pas de route par défaut.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'gateway-too-many-defaults',
'fr',
'Plus d''une route par défaut spécifiée dans le modèle pour la passerelle %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'link-no-catch',
'fr',
'Impossible de trouver le lien correspondant à l''événement %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'link-too-many-catches',
'fr',
'Plus d''un lien correspond à l''événement %0.'
);
  
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'logging-instance-event',
'fr',
'Flux - Erreur interne - %0 event'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'process-lock-timeout',
'fr',
'Les objets de traitement pour %0 sont actuellement verrouillés par un autre utilisateur. Réessayez plus tard.'
);
  
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'more_than_1_forward_path',
'fr',
'Plus d''un chemin d''accès trouvé alors qu''un seul est autorisé.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'no_next_step_found',
'fr',
'Aucune étape suivante trouvée pour le sous-flux %0. Vérifiez votre diagramme de processus.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plsql_script_failed',
'fr',
'Processus %0 : Tâche de script %1 a échoué en raison d''une erreur PL/SQL - voir le journal des événements.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plsql_script_requested_stop',
'fr',
'Processus %0: Tâche de script %1 arrêt du traitement demandé - voir le journal des événements.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timeout_locking_subflow',
'fr',
'Impossible de verrouiller le sous-flux %0, celui-ci est actuellement verrouillé par un autre utilisateur. Veuillez réessayer ultérieurement.'
);
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-already-placed',
'fr',
'Réservation déjà effectuée sur la prochaine tâche pour vous.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-by-other_user',
'fr',
'La réservation pour %0 est impossible. L''étape est déjà réservée par un autre utilisateur (%1).'
); 
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-failed-not-found',
'fr',
'La réservation pour %0 est impossible. Sous-flux %0 dans le processus %1 non trouvé.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-lock-timeout',
'fr',
'Sous-flux actuellement verrouillé (non reservé) par un autre utilisteur. Veuillez réessayez ultérieurement.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'reservation-release-not-found',
'fr',
'La libération de la réservation est impossible. Sous-flux %0 dans le processus %1 non trouvé.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'restart-no-error',
'fr',
'Aucune erreur courante trouvée. Vérifiez votre diagramme de processus.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-already-running',
'fr',
'Vous avez essayé de démarrer un processus (id %0) qui est déjà en cours d''exécution.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-multiple-already-running',
'fr',
'Vous avez essayé de démarrer un processus (id %0) dont plusieurs copies sont déjà en cours d''exécution.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-multiple-start-events',
'fr',
'Vous avez défini plusieurs événements de début. Assurez-vous que votre diagramme n''a qu''un seul événement de début.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-no-start-event',
'fr',
'Aucun événement de début n''est défini dans le diagramme de flux.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-not-created',
'fr',
'Vous avez essayé de démarrer un processus (id %0) qui n''existe pas.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'start-type-unsupported',
'fr',
'Type d''événement de début non pris en charge (%0). Seuls les événements de début standard et de type minuteur sont actuellement pris en charge.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'startwork-sbfl-not-found',
'fr',
'Début de l''enregistrement des temps de travail non réussi. Le sous-flux %0 du processus %1 est introuvable.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'subProcess-no-start',
'fr',
'Impossible de trouver l''événement de début de sous-processus.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'subProcess-too-many-starts',
'fr',
'Plus d''un événement de sous-processus trouvé.'
);
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-broken',
'fr',
'Minuteur %0 en erreur dans le processus %1 , sous-flux : %2.  Voir error_info.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-cycle-unsupported',
'fr',
'Minuteur de type cycle défini pour l''objet %0 n''est pas pris en charge actuellement.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-incomplete-definition',
'fr',
'Définition incomplète du minuteur de l''objet %0. Type: %1; Valeur: %2'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-lock-timeout',
'fr',
'La minuteur du sous-flux %0 est verrouillé par un autre utilisateur. Veuillez réessayer ultérieurement.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timer-object-not-found',
'fr',
'Objet avec minuteur non trouvé dans get_timer_definition. Sous-flux %0.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'timers-lock-timeout',
'fr',
'Les minuteurs pour le processus %0 sont verrouillés par un autre utilisateur. Veuillez réessayer ultérieurement.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var-set-error',
'fr',
'Erreur %0 variable de processus %1 pour l''ID de processus %1.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_datatype',
'fr',
'Erreur de définition de la variable de processus. Type de données incorrect pour la variable %0. Erreur SQL affichée dans le débogage.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_date_format',
'fr',
'Erreur de définition de la variable de processus %1 : format de date incorrect (Sous-flux : %0, Valeur : %3.)'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_object_not_found',
'fr',
'Erreur interne dans la recherche de l''objet %0 dans process_expressions. Erreur SQL affichée dans le débogage'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_plsql_error',
'fr',
'Sous-flux : %0 Erreur dans l''expression %2 de la variable : %1'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_no_data',
'fr',
'Ereur lors de la mise à jour de la variable %1 avec la valeur %2 dans le processus %0 - Aucune donnée trouvée dans la requête.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_other',
'fr',
'Ereur lors de la mise à jour de la variable %1 avec la valeur %2 dans le processus %0.  Erreur SQL indiquée dans le journal des événements.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_sql_too_many_rows',
'fr',
'Ereur lors de la mise à jour de la variable %1 avec la valeur %2 dans le processus %0.  La requête renvoie plusieurs lignes.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'var_exp_static_general',
'fr',
'Erreur de définition de la variable de processus %2 %1 dans le processus id %0. Voir l''erreur dans le journal des événements.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'version-no-rel-or-draft-v0',
'fr',
'Impossible de trouver le diagramme publié ou la version 0 du diagramme - veuillez spécifier une version ou un numéro de diagramme.'
);
 
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
  values (
 'timer_definition_error',
 'fr',
 'Erreur lors de l''analyse de la définition du minuteur dans le processus %0, sous-flux %1. Type de minuteur : %2, Définition: %3'
 );
/* Plug-ins */
insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-model-no-version',
'fr',
'La version n''est pas définie.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-parsing-json-variables',
'fr',
'Erreur lors de l''analyse des variables du processus.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-route-not-define',
'fr',
'La passerelle n''est pas définie pour le routage.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-gateway-not-exist',
'fr',
'La définition de la passerelle n''existe pas pour ce flux.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-no-instance-subflow-id',
'fr',
'Impossible d''obtenir l''Id de l''Instance de flux et ou l''Id du sous-flux pour gérer l''étape.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-wrong-variable-number',
'fr',
'Mauvais nombre d''élément(s) APEX ou de variable(s) de processus.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-wrong-variable-type',
'fr',
'Une ou plusieurs variables de processus sont d''un type différent de celui défini dans le JSON.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-variable-not-a-number',
'fr',
'%0 n''est pas un nombre valide.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-variable-not-a-date',
'fr',
'%0 n''est pas une date valide.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-modeler-id-not-found',
'fr',
'Aucune donnée trouvée. Vérifiez si le Diagramme avec l''ID fourni existe.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-unexpected-error',
'fr',
'Erreur inattendue, veuillez contacter votre administrateur.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-not-parsable',
'fr',
'Le diagramme n''a pas pu être analysé.<br />Veuillez examiner votre diagramme pour vous assurer qu''il est pris en charge.'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-saved',
'fr',
'Changements enregistrés !'
);

insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
 values (
'plugin-diagram-has-changed',
'fr',
'Le modèle a changé, annuler les changements?'
);
