prompt --application/deployment/install/install_packages_spec
begin
--   Manifest
--     INSTALL: INSTALL-Packages Spec
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(35319480816885757)
,p_install_id=>wwv_flow_api.id(17031066408817192)
,p_name=>'Packages Spec'
,p_sequence=>30
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create or replace package flow_types_pkg',
'  authid definer',
'as',
'',
'  subtype t_bpmn_id             is varchar2(50 char);',
'  subtype t_bpmn_attributes_key is varchar2(50 char);',
'  subtype t_bpmn_attribute_vc2  is varchar2(4000 char);',
'',
'  subtype t_single_vc2         is varchar2(1 char);',
'',
'  subtype t_expr_type          is varchar2(130 char);',
'  subtype t_expr_set           is varchar2(20 char);',
'',
'  type flow_step_info is record',
'  ( dgrm_id            flow_diagrams.dgrm_id%type',
'  , source_objt_tag    flow_objects.objt_tag_name%type',
'  , source_objt_id     flow_objects.objt_id%type',
'  , target_objt_id     flow_objects.objt_id%type',
'  , target_objt_ref    flow_objects.objt_bpmn_id%type',
'  , target_objt_tag    flow_objects.objt_tag_name%type',
'  , target_objt_subtag flow_objects.objt_sub_tag_name%type',
'  );',
'',
'  type t_subflow_context is record',
'  ( sbfl_id           flow_subflows.sbfl_id%type',
'  , step_key          flow_subflows.sbfl_step_key%type',
'  , route             flow_subflows.sbfl_route%type',
'  );',
'',
'end flow_types_pkg;',
'/',
'',
'create or replace package flow_constants_pkg',
'  authid definer',
'as',
'',
'  gc_version constant varchar2(10 char) := ''22.1.0'';',
'',
'  gc_true          constant varchar2(1 byte) := ''Y'';',
'  gc_false         constant varchar2(1 byte) := ''N'';',
'  gc_vcbool_true   constant varchar2(10 char) := ''true'';',
'  gc_vcbool_false  constant varchar2(10 char) := ''false'';',
'  gc_numbool_true  constant number            := 1;',
'  gc_numbool_false constant number            := 0;',
'',
'  gc_nsmap       constant varchar2(200 char) := ''xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"'';',
'  gc_nsbpmn      constant varchar2(200 char) := ''http://www.omg.org/spec/BPMN/20100524/MODEL'';',
'  gc_nsapex      constant varchar2(200 char) := ''https://flowsforapex.org'';',
'  gc_bpmn_prefix constant varchar2(10 char)  := ''bpmn:'';',
'  gc_apex_prefix constant varchar2(10 char)  := ''apex:'';',
'',
'  -- BPMN Keys',
'  gc_bpmn_process                      constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''process'';',
'  gc_bpmn_subprocess                   constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''subProcess'';',
'',
'  gc_bpmn_start_event                  constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''startEvent'';',
'  gc_bpmn_end_event                    constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''endEvent'';',
'  gc_bpmn_intermediate_throw_event     constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''intermediateThrowEvent'';',
'  gc_bpmn_intermediate_catch_event     constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''intermediateCatchEvent'';',
'  gc_bpmn_boundary_event               constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''boundaryEvent'';',
'',
'  gc_bpmn_terminate_event_definition   constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''terminateEventDefinition'';',
'  gc_bpmn_error_event_definition       constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''errorEventDefinition'';',
'  gc_bpmn_escalation_event_definition  constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''escalationEventDefinition'';',
'  gc_bpmn_link_event_definition        constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''linkEventDefinition'';',
'  gc_bpmn_message_event_definition     constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''messageEventDefinition'';',
'  gc_bpmn_conditional_event_definition constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''conditionalEventDefinition'';',
'  gc_bpmn_signal_event_definition      constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''signalEventDefinition'';',
'',
'  gc_bpmn_timer_event_definition       constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''timerEventDefinition'';',
'  gc_timer_type_date                   constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''timeDate'';',
'  gc_timer_type_duration               constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''timeDuration'';',
'  gc_timer_type_cycle                  constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''timeCycle'';',
'',
'  gc_bpmn_object_documentation         constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''documentation'';',
'',
'  gc_bpmn_gateway_exclusive            constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''exclusiveGateway'';',
'  gc_bpmn_gateway_inclusive            constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''inclusiveGateway'';',
'  gc_bpmn_gateway_parallel             constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''parallelGateway'';',
'  gc_bpmn_gateway_event_based          constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''eventBasedGateway'';',
'',
'  gc_bpmn_sequence_flow                constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''sequenceFlow'';',
'',
'  gc_bpmn_task                         constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''task'';',
'  gc_bpmn_usertask                     constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''userTask'';',
'  gc_bpmn_servicetask                  constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''serviceTask'';',
'  gc_bpmn_manualtask                   constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''manualTask'';',
'  gc_bpmn_scripttask                   constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''scriptTask'';',
'  gc_bpmn_businessruletask             constant flow_types_pkg.t_bpmn_id := gc_bpmn_prefix || ''businessRuleTask'';',
'  ',
'',
'  -- APEX Extensions to BPMN',
'  -- userTask',
'  gc_apex_usertask_apex_page          constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''apexPage'';',
'  gc_apex_usertask_external_url       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''externalUrl'';',
'',
'  gc_apex_usertask_application_id     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''applicationId'';',
'  gc_apex_usertask_page_id            constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''pageId'';',
'  gc_apex_usertask_request            constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''request'';',
'  gc_apex_usertask_cache              constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''cache'';',
'',
'  gc_apex_usertask_page_items          constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''pageItems'';',
'  --gc_apex_usertask_page_item          constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''pageItem'';',
'  gc_apex_usertask_item               constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''itemName'';',
'  gc_apex_usertask_value              constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''itemValue'';',
'',
'  gc_apex_usertask_url                constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''url'';',
'',
'  --serviceTask',
'  gc_apex_servicetask_send_mail       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''sendMail'';',
'',
'  gc_apex_servicetask_email_from      constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''emailFrom'';',
'  gc_apex_servicetask_email_to        constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''emailTo'';',
'  gc_apex_servicetask_email_cc        constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''emailCC'';',
'  gc_apex_servicetask_email_bcc       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''emailBCC'';',
'  gc_apex_servicetask_email_reply_to  constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''emailReplyTo'';',
'  gc_apex_servicetask_use_template    constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''useTemplate'';',
'  gc_apex_servicetask_application_id  constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''applicationId'';',
'  gc_apex_servicetask_template_id     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''templateId'';',
'  gc_apex_servicetask_placeholder     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''placeholder'';',
'  gc_apex_servicetask_subject         constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''subject'';',
'  gc_apex_servicetask_body_text       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''bodyText'';',
'  gc_apex_servicetask_body_html       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''bodyHTML'';',
'  gc_apex_servicetask_attachment      constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''attachment'';',
'  gc_apex_servicetask_immediately     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''immediately'';',
'   ',
'  -- execute PL/SQL tasks',
'  gc_apex_task_execute_plsql    constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''executePlsql'';',
'',
'  gc_apex_task_plsql_engine     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''engine'';',
'  gc_apex_task_plsql_code       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''plsqlCode'';',
'  gc_apex_task_plsql_auto_binds constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''autoBinds'';',
'',
'  --terminateEndEvent',
'  gc_apex_process_status              constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''processStatus'';',
'',
'  -- Oracle format timer definitions',
'  gc_timer_type_oracle_date           constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''oracleDate'';',
'  gc_timer_type_oracle_duration       constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''oracleDuration'';',
'  gc_timer_type_oracle_cycle          constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''oracleCycle'';',
'',
'  gc_apex_timer_date                  constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''date'';',
'  gc_apex_timer_format_mask           constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''formatMask'';',
'  gc_apex_timer_interval_ym           constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''intervalYM'';',
'  gc_apex_timer_interval_ds           constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''intervalDS'';',
'  gc_apex_timer_start_interval_ds     constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''startIntervalDS'';',
'  gc_apex_timer_repeat_interval_ds    constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''repeatIntervalDS'';',
'  gc_apex_timer_max_runs              constant flow_types_pkg.t_bpmn_id := gc_apex_prefix || ''maxRuns'';',
'',
'  -- Special Keys from FLOW_OBJECT_ATTRIBUTES',
'  gc_timer_type_key                   constant flow_types_pkg.t_bpmn_id := ''timerType'';',
'  gc_timer_def_key                    constant flow_types_pkg.t_bpmn_id := ''timerDefinition'';',
'  ',
'  gc_task_type_key                    constant flow_types_pkg.t_bpmn_id := ''taskType'';',
'',
'  gc_terminate_result                 constant flow_types_pkg.t_bpmn_id := ''processStatus'';',
'',
'  -- Flows 4 APEX Substitution Strings',
'  gc_substitution_flow_identifier     constant varchar2(10 char)                    := ''F4A$'';',
'  gc_substitution_prefix              constant flow_types_pkg.t_single_vc2          := ''&'';',
'  gc_substitution_postfix             constant flow_types_pkg.t_single_vc2          := ''.'';',
'  gc_substitution_process_id          constant flow_types_pkg.t_bpmn_attributes_key := ''PROCESS_ID'';',
'  gc_substitution_subflow_id          constant flow_types_pkg.t_bpmn_attributes_key := ''SUBFLOW_ID'';',
'  gc_substitution_step_key            constant flow_types_pkg.t_bpmn_attributes_key := ''STEP_KEY'';',
'  gc_substitution_pattern             constant flow_types_pkg.t_bpmn_attributes_key := gc_substitution_prefix || ''F4A\$(\w*)\.'';',
'',
'  -- Diagram Versioning Status',
'  gc_dgrm_status_draft                constant  varchar2(10 char) := ''draft'';',
'  gc_dgrm_status_released             constant  varchar2(10 char) := ''released'';',
'  gc_dgrm_status_deprecated           constant  varchar2(10 char) := ''deprecated'';',
'  gc_dgrm_status_archived             constant  varchar2(10 char) := ''archived'';',
'',
'  -- Subflow status',
'  gc_sbfl_status_created              constant  varchar2(20 char) := ''created'';',
'  gc_sbfl_status_running              constant  varchar2(20 char) := ''running'';',
'  gc_sbfl_status_waiting_timer        constant  varchar2(20 char) := ''waiting for timer'';',
'  gc_sbfl_status_waiting_gateway      constant  varchar2(20 char) := ''waiting at gateway'';',
'  gc_sbfl_status_waiting_event        constant  varchar2(20 char) := ''waiting for event'';',
'  gc_sbfl_status_proceed_gateway      constant  varchar2(20 char) := ''proceed from gateway'';',
'  gc_sbfl_status_split                constant  varchar2(20 char) := ''split'';',
'  gc_sbfl_status_in_subprocess        constant  varchar2(20 char) := ''in subprocess'';',
'  gc_sbfl_status_error                constant  varchar2(20 char) := ''error'';',
'  gc_sbfl_status_completed            constant  varchar2(20 char) := ''completed'';  -- note sbfl deleted after completion',
'',
'  -- Process Instance Status',
'  gc_prcs_status_created              constant  varchar2(20 char) := ''created'';',
'  gc_prcs_status_running              constant  varchar2(20 char) := ''running'';',
'  gc_prcs_status_completed            constant  varchar2(20 char) := ''completed'';',
'  gc_prcs_status_terminated           constant  varchar2(20 char) := ''terminated'';',
'  gc_prcs_status_error                constant  varchar2(20 char) := ''error'';',
'',
'  -- Process Instance Events',
'  gc_prcs_event_created              constant  varchar2(20 char) := gc_prcs_status_created;',
'  gc_prcs_event_started              constant  varchar2(20 char) := ''started'';',
'  gc_prcs_event_completed            constant  varchar2(20 char) := gc_prcs_status_completed;',
'  gc_prcs_event_terminated           constant  varchar2(20 char) := gc_prcs_status_terminated;',
'  gc_prcs_event_reset                constant  varchar2(20 char) := ''reset'';',
'  gc_prcs_event_error                constant  varchar2(20 char) := gc_prcs_status_error;',
'  gc_prcs_event_restart_step         constant  varchar2(20 char) := ''restart step'';',
'  gc_prcs_event_deleted              constant  varchar2(20 char) := ''deleted'';',
'  gc_prcs_event_rescheduled          constant  varchar2(20 char) := ''rescheduled'';',
'',
'  -- Process Variable Datatypes',
'',
'  gc_prov_var_type_varchar2           constant  varchar2(50 char) := ''VARCHAR2'';',
'  gc_prov_var_type_date               constant  varchar2(50 char) := ''DATE'';',
'  gc_prov_var_type_number             constant  varchar2(50 char) := ''NUMBER'';',
'  gc_prov_var_type_clob               constant  varchar2(50 char) := ''CLOB'';',
'',
'  gc_prov_default_date_format         constant  varchar2(30 char) := ''YYYY-MM-DD HH24:MI:SS'';',
'',
'  -- Standard Process Variables',
'',
'  gc_prov_builtin_business_ref        constant  varchar2(50 char) := ''BUSINESS_REF'';',
'',
'  -- Process Variable Expression Types',
'  gc_expr_type_static                 constant flow_types_pkg.t_expr_type := ''static'';',
'  gc_expr_type_proc_var               constant flow_types_pkg.t_expr_type := ''processVariable'';',
'  gc_expr_type_item                   constant flow_types_pkg.t_expr_type := ''item'';',
'  gc_expr_type_sql                    constant flow_types_pkg.t_expr_type := ''sqlQuerySingle'';',
'  gc_expr_type_sql_delimited_list     constant flow_types_pkg.t_expr_type := ''sqlQueryList'';',
'  gc_expr_type_plsql_function_body    constant flow_types_pkg.t_expr_type := ''plsqlFunctionBody'';',
'  gc_expr_type_plsql_expression       constant flow_types_pkg.t_expr_type := ''plsqlExpression'';',
'',
'-- Process Variable Expression set := ''BeforeTask'';',
'  gc_expr_set_before_task             constant flow_types_pkg.t_expr_set := ''beforeTask'';',
'  gc_expr_set_after_task              constant flow_types_pkg.t_expr_set := ''afterTask'';',
'  gc_expr_set_before_split            constant flow_types_pkg.t_expr_set := ''beforeSplit'';',
'  gc_expr_set_after_merge             constant flow_types_pkg.t_expr_set := ''afterMerge'';',
'  gc_expr_set_before_event            constant flow_types_pkg.t_expr_set := ''beforeEvent'';',
'  gc_expr_set_on_event                constant flow_types_pkg.t_expr_set := ''onEvent'';',
'',
'-- Config Parameter Keys',
'',
'  gc_config_logging_level             constant varchar2(50 char) := ''logging_level'';',
'  gc_config_logging_hide_userid       constant varchar2(50 char) := ''logging_hide_userid'';',
'  gc_config_logging_language          constant varchar2(50 char) := ''logging_language'';',
'  gc_config_engine_app_mode           constant varchar2(50 char) := ''engine_app_mode'';',
'  gc_config_dup_step_prevention       constant varchar2(50 char) := ''duplicate_step_prevention'';',
'  gc_config_timer_max_cycles          constant varchar2(50 char) := ''timer_max_cycles'';',
'',
'-- Config Parameter Valid Values (when not true / false or numeric)',
'',
'  gc_config_logging_level_none        constant varchar2(2000 char) := ''none'';      -- none',
'  gc_config_logging_level_standard    constant varchar2(2000 char) := ''standard'';  -- instances and tasks',
'  gc_config_logging_level_secure      constant varchar2(2000 char) := ''secure'';    -- standard + diagram changes',
'  gc_config_logging_level_full        constant varchar2(2000 char) := ''full'';      -- secure + variable changes',
'  gc_config_engine_app_mode_dev       constant varchar2(2000 char) := ''development'';',
'  gc_config_engine_app_mode_prod      constant varchar2(2000 char) := ''production'';',
'  gc_config_dup_step_prevention_legacy constant varchar2(2000 char) := ''legacy'';   -- null step key allowed',
'  gc_config_dup_step_prevention_strict constant varchar2(2000 char) := ''strict'';   -- step key enforced',
'',
'',
'-- Config Parameter Default Values',
'',
'  gc_config_default_logging_level             constant varchar2(2000 char) := gc_config_logging_level_standard;',
'  gc_config_default_logging_hide_userid       constant varchar2(2000 char) := ''false'';',
'  gc_config_default_logging_language          constant varchar2(2000 char) := ''en'';',
'  gc_config_default_engine_app_mode           constant varchar2(2000 char) := ''production'';',
'  gc_config_default_dup_step_prevention       constant varchar2(2000 char) := ''legacy'';',
'  gc_config_default_default_workspace         constant varchar2(2000 char) := ''FLOWS4APEX'';',
'  gc_config_default_timer_max_cycles          constant varchar2(2000 char) := ''1000'';',
'',
'',
'  -- Default XML for new diagrams',
'  gc_default_xml constant varchar2(4000) := ''<?xml version="1.0" encoding="UTF-8"?>',
'<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b'
||'" exporter="Flows for APEX" exporterVersion="'' || gc_version || ''">',
'<bpmn:process id="Process_0rxermh" isExecutable="false" />',
'<bpmndi:BPMNDiagram id="BPMNDiagram_1">',
'<bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0rxermh" />',
'</bpmndi:BPMNDiagram>',
'</bpmn:definitions>',
''';',
'',
'',
'end flow_constants_pkg;',
'/',
'',
'create or replace package flow_migrate_xml_pkg',
'as',
'  procedure migrate_xml(',
'    p_dgrm_content in out clob',
'  , p_has_changed out boolean',
'  );',
'end flow_migrate_xml_pkg;',
'/',
'',
'create or replace package flow_bpmn_parser_pkg',
'  authid definer',
'as',
'',
'  function upload_diagram',
'  (',
'    pi_dgrm_name       in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version    in flow_diagrams.dgrm_version%type',
'  , pi_dgrm_category   in flow_diagrams.dgrm_category%type',
'  , pi_dgrm_content    in flow_diagrams.dgrm_content%type',
'  , pi_dgrm_status     in flow_diagrams.dgrm_status%type default flow_constants_pkg.gc_dgrm_status_draft',
'  , pi_force_overwrite in boolean default false',
'  ) return flow_diagrams.dgrm_id%type;',
'',
'  procedure upload_diagram',
'  (',
'    pi_dgrm_name     in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version  in flow_diagrams.dgrm_version%type',
'  , pi_dgrm_category in flow_diagrams.dgrm_category%type',
'  , pi_dgrm_content  in flow_diagrams.dgrm_content%type',
'  , pi_dgrm_status   in flow_diagrams.dgrm_status%type default flow_constants_pkg.gc_dgrm_status_draft',
'  , pi_force_overwrite in boolean default false',
'  );',
'',
'  procedure upload_and_parse',
'  (',
'    pi_dgrm_name     in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version  in flow_diagrams.dgrm_version%type',
'  , pi_dgrm_category in flow_diagrams.dgrm_category%type',
'  , pi_dgrm_content  in flow_diagrams.dgrm_content%type',
'  , pi_dgrm_status   in flow_diagrams.dgrm_status%type default flow_constants_pkg.gc_dgrm_status_draft',
'  , pi_force_overwrite in boolean default false',
'  );',
'',
'  procedure parse',
'  (',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type',
'  );',
'',
'  procedure parse',
'  (',
'    pi_dgrm_name     in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version  in flow_diagrams.dgrm_version%type',
'  );',
'',
'  procedure update_diagram',
'  (',
'    pi_dgrm_id      in flow_diagrams.dgrm_id%type',
'  , pi_dgrm_content in flow_diagrams.dgrm_content%type',
'  );',
'',
'end flow_bpmn_parser_pkg;',
'/',
'',
'create or replace package flow_api_pkg',
'as',
'',
'/********************************************************************************',
'**',
'**        FLOW INSTANCE OPERATIONS (Create, Start, Reset, Terminate, Delete)',
'**        STEP OPERATIONS (Reserve, Release, Complete)',
'**',
'********************************************************************************/',
'',
'/***',
'Function flow_create',
'creates a new process instance based on a diagram name and version (process specification)',
'If the version is not specified,',
'  first lookup is to use dgrm_status = ''released''',
'  second lookup is to use dgrm_version = ''0'' and dgrm_status = ''draft''',
'If nothing is found based on above rules an exception will be raised.',
'For accuracy, it''s recommended that you specify a version or use the form of flow_create specifying dgrm_id directly.',
'Returns: Process ID of the newly created process',
'*/',
'  function flow_create',
'  ( ',
'    pi_dgrm_name in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version in flow_diagrams.dgrm_version%type default null',
'  , pi_prcs_name in flow_processes.prcs_name%type',
'  ) return flow_processes.prcs_id%type;',
'',
'/***',
'Function flow_create',
'creates a new process instance based on a diagram id and version (process specification)',
'Returns: Process ID of the newly created process',
'*/',
'  function flow_create',
'  (',
'    pi_dgrm_id   in flow_diagrams.dgrm_id%type',
'  , pi_prcs_name in flow_processes.prcs_name%type',
'  ) return flow_processes.prcs_id%type;',
'',
'/***',
'Procedure  flow_create',
'creates a new process instance based on a diagram name and version (process specification)',
'if the version is not specified, it looks for a copy of the diagram having dgrm_status = ''released''',
'For accuracy, it''s recommended that you specify a version or use the form of flow_create specifying dgrm_id directly.',
'*/',
'  procedure flow_create',
'  (',
'    pi_dgrm_name in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version in flow_diagrams.dgrm_version%type default null',
'  , pi_prcs_name in flow_processes.prcs_name%type',
'  );',
'/***',
'Procedure flow_create',
'creates a new process instance based on a diagram id and version (process specification)',
'*/',
'  procedure flow_create',
'  (',
'    pi_dgrm_id   in flow_diagrams.dgrm_id%type',
'  , pi_prcs_name in flow_processes.prcs_name%type',
'  );',
'/***',
'Procedure flow_start',
'Starts a process that was previously created by flow_create.',
'Flow_start will create the initial subflow, set the current event to the diagram''s start event, ',
'then step on to the next object in the process diagram',
'*/',
'  procedure flow_start',
'  (',
'    p_process_id in flow_processes.prcs_id%type',
'  );',
'/***',
'Procedure flow_reserve_step',
'Reservation is a light-weight process for a user to indicate to other users that he/she intends to work on ',
'the current task in order to prevent multiple users working on the same task at the same time.',
'A reservation is typically made by supplying the reserving user''s username as the p_reservation parameter ',
'(although an application could come up with some other scheme for the reservation parameter, and so it is not ',
'restricted to being a userid).  Other users will be able to see that a reservation has been placed on a step.',
'Reservations are purely a signalling mechanism;  no enforcement is taken in the engine ',
'to restrict other users from undertaking a task reserved by somebody.',
'A reservation can be released using the flow_release_step procedure.',
'A reservation applies only to the current task waiting to be completed.  Once the task is completed, there is ',
'no reservation carried forward onto future tasks in the process.',
'Reservation is not an authorization control, and is not security relevant / enforcing in the engine.',
'*/',
'    procedure flow_reserve_step',
'  (',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  , p_reservation   in flow_subflows.sbfl_reservation%type',
'  );  ',
'/***',
'Procedure flow_release_step',
'Release step is part of the reservation process.  See documentation for flow_reserve_step.',
'Flow_release_step releases a previously made reservation.',
'*/',
'     procedure flow_release_step',
'  (',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  ); ',
'/***',
'Procedure flow_start_step',
'flow_start_step can optionally be called when a user is about to start working on a task.  flow_start_step records the start time for ',
'work on the task, which is used to distinguish betweeen time waiting for the task to get worked on and the time that it is actually ',
'being worked on. Flow_start_step does not perform any functional role in processing a flow instance, and is optional - but it ',
'just helps gather process performance statistics that distinguish queing time from processing time.  ',
'Despite being optional, a well formed, best-practice application will use this call so that process statistics can be captured.',
'*/',
'  procedure flow_start_step',
'  (',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  );',
'',
'/*** Procedure flow_restart_step',
'flow_restart_step is procedure that is designed to be called by an administrator to restart a scriptTask or serviceTask that has ',
'failed due to an error.  The intended usage is that the adminstrator can fix the script or edit the process data that caused the ',
'task to fail, and then restart the task using this call.  ',
'A comment can optionally be provided, which will be added to the task event log entry.',
'It should only be used on a subflow having a status of ''error''',
'*/',
'  procedure flow_restart_step',
'  (',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  , p_comment       in flow_instance_event_log.lgpr_comment%type default null',
'  );',
'',
'/***',
'Procedure flow_complete_step',
'Flow_complete_step is called when a process step has been completed.  Calling flow_complete_step moves the process ',
'forward to the next object(s) in the process diagram, in acordance with the behaviour rules for the objects.',
'History:  Flow_complete_step replaces the flow_next_step call in versions prior to V5.  Unlike flow_next_step, flow_complete_step ',
'is used to move a process forward, regardless of the object type. ',
'*/',
'   procedure flow_complete_step',
'  (',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  ); ',
'',
'/*** ',
'Procedure flow_reschedulule_timer',
'flow_reschedule_timer can be called to change the next scheduled time of a timer on a running timer.',
'It can change the currently scheduled time to a future time, or can instruct the timer to fire immediately.',
'If the Timer event is a single event timer (timer types Date or Duration), it will change the time at which the event is ',
'scheduled to occur to the new time.',
'If the timer is a Cycle Timer, this changes the time that the next firoing is scheduled to occur.  If later cycles exist, the following cycle will ',
'be scheduled at the new firing time + the repeat interval.',
'To fire the timer immediately, set p_is_immediate = true.',
'To change the firing time to another future time, supply a new timestamp with time zone contaiing the new time.',
'A comment can be provided, which is passed to the log file for explanation of any rescheduling.',
'*/',
'procedure flow_reschedule_timer',
'(',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  , p_is_immediate  in boolean default false',
'  , p_new_timestamp in flow_timers.timr_start_on%type default null',
'  , p_comment       in flow_instance_event_log.lgpr_comment%type default null',
'',
');',
'',
'',
'/***',
'Procedure flow_reset',
'flow_reset aborts all processing on a process instance, and returns it to the state when it was',
'initially created.  After a reset, you then need to call flow_start to re-start the process instance.',
'flow_reset is only provided for debug and test usage; for production usage, always delete and start a new process',
'After a reset: ',
'- process instance status is reset to created.  ',
'- process instance progress is deleted.',
'- process variables are LEFT untouched.',
'This is not meant for use in Production Systems.',
'*/',
'  procedure flow_reset',
'  ( ',
'    p_process_id  in flow_processes.prcs_id%type',
'  , p_comment     in flow_instance_event_log.lgpr_comment%type default null',
'  );',
'',
'  /***',
'Procedure flow_terminate',
'flow_delete ends all processing of a process instance, and has the same effect as processing a Terminating End Event inside a Flow Diagram.',
'It ends all subflows, but retains the process definition and the subflow logs for the process.',
'*/',
'  procedure flow_terminate',
'  ( ',
'    p_process_id  in flow_processes.prcs_id%type',
'  , p_comment     in flow_instance_event_log.lgpr_comment%type default null',
'  );',
'',
'  /***',
'Procedure flow_delete',
'flow_delete ends all processing of a process instance.  It removes all subflows and subflow logs of the process.',
'*/',
'  procedure flow_delete',
'  ( ',
'    p_process_id  in flow_processes.prcs_id%type',
'  , p_comment     in flow_instance_event_log.lgpr_comment%type default null    ',
'  );',
'',
' /********************************************************************************',
'**',
'**        APPLICATION HELPERS (URL Builder, etc.)',
'**',
'********************************************************************************/ ',
'',
'  -- get_current_usertask_url',
'  -- used to build a URL for the current task on the specified subflow',
'  -- this is used in, for example, task inboxes to create link to the APEX page that ',
'  -- should be called by the use'))
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.append_to_install_script(
 p_id=>wwv_flow_api.id(35319480816885757)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'r to perform the current userTask object',
'  function get_current_usertask_url',
'  (',
'    p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  , p_step_key   in flow_subflows.sbfl_step_key%type default null',
'  ) return varchar2;',
'',
'  -- message',
'  -- returns a Flows for APEX error message with p0...p9 substitutions in p_lang',
'  function message',
'  ( p_message_key     in varchar2 ',
'  , p_lang            in varchar2 default ''en''',
'  , p0                in varchar2 default null',
'  , p1                in varchar2 default null',
'  , p2                in varchar2 default null',
'  , p3                in varchar2 default null',
'  , p4                in varchar2 default null',
'  , p5                in varchar2 default null',
'  , p6                in varchar2 default null',
'  , p7                in varchar2 default null',
'  , p8                in varchar2 default null',
'  , p9                in varchar2 default null',
'  ) return varchar2;',
'',
'end flow_api_pkg;',
'/',
'',
'create or replace package flow_engine_util',
'-- accessible by (flow_engine, flow_gateways, flow_boundary_events, flow_timers_pkg, flow_logging)',
'as ',
'',
'  function get_dgrm_id',
'  (',
'    p_prcs_id in flow_processes.prcs_id%type',
'  ) return flow_processes.prcs_dgrm_id%type;',
'',
'  function get_config_value',
'  ( ',
'    p_config_key    in flow_configuration.cfig_key%type,',
'    p_default_value in flow_configuration.cfig_value%type',
'  ) return flow_configuration.cfig_value%type;',
'',
'  procedure set_config_value',
'  ( ',
'    p_config_key in flow_configuration.cfig_key%type,',
'    p_value      in flow_configuration.cfig_value%type',
'  );',
'',
'  function check_subflow_exists',
'  (',
'    p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  ) return boolean;',
'',
'  function get_subprocess_parent_subflow',
'  ( p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  , p_current    in flow_objects.objt_bpmn_id%type -- an object in the subprocess',
'  ) return flow_types_pkg.t_subflow_context;',
'',
'  procedure get_number_of_connections',
'  ( pi_dgrm_id                  in flow_diagrams.dgrm_id%type',
'  , pi_target_objt_id           in flow_connections.conn_tgt_objt_id%type',
'  , pi_conn_type                in flow_connections.conn_tag_name%type ',
'  , po_num_forward_connections  out number',
'  , po_num_back_connections     out number',
'  );',
'  ',
'  function get_subflow_info',
'  ( p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_lock_subflow  in boolean default false',
'  , p_lock_process  in boolean default false',
'  ) return flow_subflows%rowtype;',
'',
'  function step_key',
'  ( pi_sbfl_id        in flow_subflows.sbfl_id%type',
'  , pi_current        in flow_subflows.sbfl_current%type',
'  , pi_became_current in flow_subflows.sbfl_became_current%type',
'  ) return flow_subflows.sbfl_step_key%type;',
'',
'  function step_key_valid',
'  ( pi_prcs_id              in flow_processes.prcs_id%type',
'  , pi_sbfl_id              in flow_subflows.sbfl_id%type',
'  , pi_step_key_supplied    in flow_subflows.sbfl_step_key%type',
'  , pi_step_key_required    in flow_subflows.sbfl_step_key%type default null',
'  ) return boolean;',
'',
'  procedure subflow_complete',
'  ( p_process_id        in flow_processes.prcs_id%type',
'  , p_subflow_id        in flow_subflows.sbfl_id%type',
'  );',
'',
'  procedure terminate_level',
'  ( p_process_id    in flow_processes.prcs_id%type',
'  , p_process_level in flow_subflows.sbfl_process_level%type',
'  );',
'',
'  function subflow_start',
'    ( ',
'      p_process_id                in flow_processes.prcs_id%type',
'    , p_parent_subflow            in flow_subflows.sbfl_id%type',
'    , p_starting_object           in flow_objects.objt_bpmn_id%type',
'    , p_current_object            in flow_objects.objt_bpmn_id%type',
'    , p_route                     in flow_subflows.sbfl_route%type',
'    , p_last_completed            in flow_objects.objt_bpmn_id%type',
'    , p_status                    in flow_subflows.sbfl_status%type default flow_constants_pkg.gc_sbfl_status_running',
'    , p_parent_sbfl_proc_level    in flow_subflows.sbfl_process_level%type',
'    , p_new_proc_level            in boolean default false',
'    , p_dgrm_id                   in flow_diagrams.dgrm_id%type',
'    ) return flow_types_pkg.t_subflow_context',
'    ;',
'',
'  function lock_subflow',
'  ( p_subflow_id    in flow_subflows.sbfl_id%type',
'  ) return boolean;',
'',
'end flow_engine_util;',
'/',
'',
'create or replace package flow_gateways',
'accessible by (flow_engine)',
'as ',
'',
'procedure process_para_incl_Gateway',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'procedure process_exclusiveGateway',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
' procedure process_eventBasedGateway',
'  ( p_sbfl_info  in flow_subflows%rowtype',
'  , p_step_info  in flow_types_pkg.flow_step_info',
'  );',
'',
'end flow_gateways;',
'/',
'',
'create or replace package flow_boundary_events',
'accessible by (flow_engine, flow_tasks, flow_timers_pkg)',
'is ',
'',
'  procedure set_boundary_timers ',
'  ( p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  );  ',
'',
'  procedure unset_boundary_timers ',
'  ( p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  );  ',
'',
'  procedure lock_child_boundary_timers',
'  ( p_process_id          in flow_processes.prcs_id%type',
'  , p_subflow_id          in flow_subflows.sbfl_id%type',
'  , p_parent_objt_bpmn_id in flow_objects.objt_bpmn_id%type',
'  ); ',
'',
'  procedure handle_interrupting_boundary_event',
'  ( p_process_id in flow_processes.prcs_id%type',
'  , p_subflow_id in flow_subflows.sbfl_id%type',
'  );',
'  procedure process_boundary_event',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  , p_par_sbfl      in flow_subflows.sbfl_id%type',
'  );',
'',
'end flow_boundary_events;',
'/',
'',
'create or replace package flow_tasks',
'accessible by (flow_engine)',
'as  ',
'',
'  procedure process_task',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'  procedure process_userTask',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'  procedure process_scriptTask',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'  procedure process_serviceTask',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'  procedure process_manualTask',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'  procedure process_businessRuleTask',
'  ( p_sbfl_info     in flow_subflows%rowtype',
'  , p_step_info     in flow_types_pkg.flow_step_info',
'  );',
'',
'end flow_tasks;',
'/',
'',
'create or replace package flow_services',
'  authid current_user',
'as',
'  e_no_default_workspace exception;',
'  e_wrong_default_workspace exception;',
'  e_workspace_not_found exception;',
'  e_email_no_from exception;',
'  e_email_no_to exception;',
'  e_email_no_template exception;',
'  e_email_no_body exception;',
'  e_email_failed exception;',
'  e_json_not_valid exception;',
'',
'  procedure send_email(',
'      pi_prcs_id in flow_processes.prcs_id%type',
'    , pi_sbfl_id in flow_subflows.sbfl_id%type',
'    , pi_objt_id in flow_objects.objt_id%type',
'  );',
'',
'end flow_services;',
'/',
'',
'',
'create or replace package flow_timers_pkg as',
'/******************************************************************************',
' Purpose:',
'   Provides support to timers in Flows for APEX.',
'',
' Grants required:',
'   CREATE JOB',
'******************************************************************************/',
'',
'/******************************************************************************',
'  CONSTANTS',
'******************************************************************************/',
'  c_created    varchar2(1) := ''C''; -- Created and waiting for the first action.',
'  c_active     varchar2(1) := ''A''; -- The time has already completed 1 action',
'                                   -- but will perform more actions.',
'  c_ended      varchar2(1) := ''E''; -- The timer has naturally completed his',
'                                   -- action/s with no external intervention.',
'  c_expired    varchar2(1) := ''X''; -- The timers is stopped by call from the',
'                                   -- flow when stepping forward, before his',
'                                   -- natural end.',
'  c_terminated varchar2(1) := ''T''; -- Abnormal termination by manual',
'                                   -- intervention.',
'  c_broken     varchar2(1) := ''B''; -- Error occured in timer flow.',
'                                   -- Timer will be ignored until manually',
'                                   -- reset to created or active.',
'',
'',
'/******************************************************************************',
'  step_timers',
'    check update status of active timers.',
'******************************************************************************/',
'  procedure step_timers;',
'',
'',
'/******************************************************************************',
'  start_timer',
'    create a new timer instance.',
'******************************************************************************/',
'  procedure start_timer',
'  (',
'    pi_prcs_id    in flow_processes.prcs_id%type',
'  , pi_sbfl_id    in flow_subflows.sbfl_id%type',
'  , pi_step_key   in flow_subflows.sbfl_step_key%type default null',
'  , pi_run        in flow_timers.timr_run%type default 1 -- 1 original, 2-> repeats',
'  , pi_timr_id    in flow_timers.timr_id%type default null -- only set on repeats',
'  );',
'',
'/******************************************************************************',
'  reschedule_timer',
'    change the time that a timer is scheduled to fire to a new time, or now.',
'******************************************************************************/',
'',
'procedure reschedule_timer',
'(',
'    p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type default null',
'  , p_is_immediate  in boolean default false',
'  , p_new_timestamp in flow_timers.timr_start_on%type default null',
'  , p_comment       in flow_instance_event_log.lgpr_comment%type default null',
');',
'',
'',
'/******************************************************************************',
'  expire_timer',
'    increment the progress in a flow pushing it to the next step.',
'******************************************************************************/',
'',
'  procedure expire_timer',
'  (',
'    pi_prcs_id  in  flow_processes.prcs_id%type',
'  , pi_sbfl_id  in  flow_subflows.sbfl_id%type',
'  );',
'',
'/******************************************************************************',
'  lock_timer',
'    locks the specified timer.',
'******************************************************************************/',
'',
'  procedure lock_timer',
'  (',
'    pi_prcs_id  in  flow_processes.prcs_id%type',
'  , pi_sbfl_id  in  flow_subflows.sbfl_id%type',
'  );',
'',
'/******************************************************************************',
'  kill_timer',
'    remove a timer instance before the expiration time.',
'******************************************************************************/',
'',
'  procedure terminate_timer ',
'  (',
'    pi_prcs_id      in flow_processes.prcs_id%type',
'  , pi_sbfl_id      in flow_subflows.sbfl_id%type',
'  , po_return_code out number',
'  );',
'',
'',
'/******************************************************************************',
'  lock_process_timers',
'    locks all the timers of a process.',
'******************************************************************************/',
'',
'  procedure lock_process_timers',
'  (',
'    pi_prcs_id  in  flow_processes.prcs_id%type',
'  );',
'',
'/******************************************************************************',
'  terminate_process_timers',
'    terminate all the timers of a process.',
'******************************************************************************/',
'',
'  procedure terminate_process_timers',
'  (',
'    pi_prcs_id      in flow_processes.prcs_id%type',
'  , po_return_code out number',
'  );',
'',
'/******************************************************************************',
'  delete_process_timers',
'    delete all the timers of a process.',
'******************************************************************************/',
'',
'  procedure delete_process_timers',
'  (',
'    pi_prcs_id      in flow_processes.prcs_id%type',
'  , po_return_code out number',
'  );',
'',
'/******************************************************************************',
'  terminate_all_timers',
'    termintate all the timers of all processes.',
'******************************************************************************/',
'',
'  procedure terminate_all_timers',
'  (',
'    po_return_code  out  number',
'  );',
'',
'',
'/******************************************************************************',
'  disable_scheduled_job',
'    disable the scheduled job processing of timers.',
'******************************************************************************/',
'',
'  procedure disable_scheduled_job;',
'',
'/******************************************************************************',
'  enable_scheduled_job',
'    enable the scheduled job processing of timers.',
'******************************************************************************/',
'',
'  procedure enable_scheduled_job;',
'',
'end flow_timers_pkg;',
'/',
'',
'create or replace package flow_instances ',
'accessible by (flow_api_pkg, flow_engine)',
'as',
'',
'  function create_process',
'    ( p_dgrm_id   in flow_diagrams.dgrm_id%type',
'    , p_prcs_name in flow_processes.prcs_name%type',
'    ) return flow_processes.prcs_id%type',
'    ;',
'',
'  procedure start_process',
'    ( p_process_id    in flow_processes.prcs_id%type',
'    );',
'',
'  procedure reset_process',
'    ( p_process_id  in flow_processes.prcs_id%type',
'    , p_comment     in flow_instance_event_log.lgpr_comment%type default null',
'    );',
'',
'  procedure terminate_process',
'    ( p_process_id  in flow_processes.prcs_id%type',
'    , p_comment     in flow_instance_event_log.lgpr_comment%type default null',
'    );',
'',
'  procedure delete_process',
'    (',
'      p_process_id  in flow_processes.prcs_id%type',
'    , p_comment     in flow_instance_event_log.lgpr_comment%type default null',
'    );',
'',
'end flow_instances;',
'/',
'',
'create or replace package flow_engine',
'accessible by (flow_api_pkg, flow_instances, flow_gateways, flow_tasks, ',
'               flow_boundary_events, flow_timers_pkg)',
'',
'as ',
'  procedure flow_handle_event',
'  ( p_process_id    in flow_processes.prcs_id%type',
'  , p_subflow_id    in flow_subflows.sbfl_id%type',
'  , p_step_key      in flow_subflows.sbfl_step_key%type',
'  , p_timr_id       in flow_timers.timr_id%type default null',
'  , p_run           in flow_timers.timr_run%type default null',
'  ); ',
'procedure flow_complete_step',
'  ( p_process_id        in flow_processes.prcs_id%type',
'  , p_subflow_id        in flow_subflows.sbfl_id%type',
'  , p_step_key          in flow_subflows.sbfl_step_key%type default null',
'  , p_forward_route     in flow_connections.conn_bpmn_id%type default null   ',
'  , p_log_as_completed  in boolean default true',
'  , p_recursive_call    in boolean default true',
'  );',
'',
'procedure start_step',
'  ( p_process_id          in flow_processes.prcs_id%type',
'  , p_subflow_id          in flow_subflows.sbfl_id%type',
'  , p_step_key            in flow_subflows.sbfl_step_key%type default null',
'  , p_called_internally   in boolean default false',
'  );',
'',
'procedure restart_step',
'  ( p_process_id          in flow_processes.prcs_id%type',
'  , p_subflow_id          in flow_subflows.sbfl_id%type',
'  , p_step_key            in flow_subflows.sbfl_step_key%type default null',
'  , p_comment             in flow_instance_event_log.lgpr_comment%type default null',
'  );',
'  ',
'end flow_engine;',
'/',
'',
'create or replace package flow_reservations',
'accessible by (flow_api_pkg, flow_engine)',
'as ',
'',
'    procedure reserve_step',
'    ( p_process_id         in flow_processes.prcs_id%type',
'    , p_subflow_id         in flow_subflows.sbfl_id%type',
'    , p_step_key           in flow_subflows.sbfl_step_key%type',
'    , p_reservation        in flow_subflows.sbfl_reservation%type',
'    , p_called_internally  in boolean default false',
'    );',
'',
'    procedure release_step',
'    ( p_process_id         in flow_processes.prcs_id%type',
'    , p_subflow_id         in flow_subflows.sbfl_id%type',
'    , p_step_key           in flow_subflows.sbfl_step_key%type default null',
'    , p_called_internally  in boolean default false',
'    );',
'',
'end flow_reservations;',
'/',
'',
'create or replace package flow_process_vars',
'as ',
' /********************************************************************************',
'**',
'**        PROCESS VARIABLE SYSTEM (get / set / etc)',
'**',
'********************************************************************************/ ',
' ',
'',
'procedure set_var',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_vc2_value in flow_process_variables.prov_var_vc2%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type default null',
', pi_objt_bpmn_id in flow_objects.objt_bpmn_id%type default null ',
', pi_expr_set in flow_object_expressions.expr_set%type default null',
');',
'',
'procedure set_var',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_num_value in flow_process_variables.prov_var_num%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type default null',
', pi_objt_bpmn_id in flow_objects.objt_bpmn_id%type default null ',
', pi_expr_set in flow_object_expressions.expr_set%type default null',
');',
'',
'procedure set_var',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_date_value in flow_process_variables.prov_var_date%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type default null',
', pi_objt_bpmn_id in flow_objects.objt_bpmn_id%type default null ',
', pi_expr_set in flow_object_expressions.expr_set%type default null',
');',
'',
'procedure set_var',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_clob_value in flow_process_variables.prov_var_clob%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type default null',
', pi_objt_bpmn_id in flow_objects.objt_bpmn_id%type default null ',
', pi_expr_set in flow_object_expressions.expr_set%type default null',
');',
'',
'-- getters return',
'',
'function get_var_vc2',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_exception_on_null in boolean default false',
') return flow_process_variables.prov_var_vc2%type;',
'',
'function get_var_num',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_exception_on_null in boolean default false',
') return flow_process_variables.prov_var_num%type;',
'',
'function get_var_date',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_exception_on_null in boolean default false',
') return flow_process_variables.prov_var_date%type;',
'',
'function get_var_clob',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_exception_on_null in boolean default false',
') return flow_process_variables.prov_var_clob%type;',
'',
'function get_var_type',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
', pi_exception_on_null in boolean default false',
') return flow_process_variables.prov_var_type%type;',
'',
'procedure delete_var',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_var_name in flow_process_variables.prov_var_name%type',
');',
'',
'/********************************************************************************',
'**',
'**        SPECIAL CASE / BUILT-IN PROCESS VARIABLES',
'**',
'********************************************************************************/ ',
'',
'procedure set_business_ref',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_vc2_value in flow_process_variables.prov_var_vc2%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type default null',
', pi_objt_bpmn_id in flow_objects.objt_bpmn_id%type default null ',
', pi_expr_set in flow_object_expressions.expr_set%type default null',
');',
'',
'function get_business_ref',
'( pi_prcs_id in flow_processes.prcs_id%type)',
'return flow_process_variables.prov_var_vc2%type;',
'',
' /********************************************************************************',
'**',
'**        FOR FLOW_ENGINE USE',
'**',
'********************************************************************************/ ',
'',
'procedure delete_all_for_process',
'( pi_prcs_id in flow_processes.prcs_id%type',
', pi_retain_builtins in boolean default false',
');',
'',
'procedure do_substitution',
'(',
'  pi_prcs_id in flow_processes.prcs_id%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type',
', pi_step_key in flow_subflows.sbfl_step_key%type default null',
', pio_string in out nocopy varchar2',
');',
'',
'procedure do_substitution',
'(',
'  pi_prcs_id in flow_processes.prcs_id%type',
', pi_sbfl_id in flow_subflows.sbfl_id%type',
', pi_step_key in flow_subflows.sbfl_step_key%type default null',
', pio_string in out nocopy clob',
');',
'',
'end flow_process_vars;',
'/',
'',
'create or replace package flow_expressions',
'  authid current_user',
'  -- accessible by flow_engine, flow_process_vars ??',
'as ',
'  e_var_exp_date_format_error exception;',
'',
'  -- Call using objt_id if you have available',
'  procedure process_expressions',
'  ( pi_objt_id      flow_objects.objt_id%type default null',
'  , pi_set          flow_object_expressions.expr_set%type',
'  , pi_prcs_id      flow_processes.prcs_id%type',
'  , pi_sbfl_id      flow_subflows.sbfl_id%type',
'  );',
'',
'  -- oterwise overload provided, usung objt_bpmn_id...',
'  procedure process_expressions',
'  ( pi_objt_bpmn_id flow_objects.objt_bpmn_id%type',
'  , pi_set          flow_object_expressions.expr_set%type',
'  , pi_prcs_id      flow_processes.prcs_id%type',
'  , pi_sbfl_id      flow_subflows.sbfl_id%type',
'  );',
'',
'end flow_expressions;',
'/',
'',
'create or replace package flow_usertask_pkg',
'  authid definer',
'as',
'',
'  function get_url',
'  (',
'    pi_prcs_id in flow_processes.prcs_id%type',
'  , pi_sbfl_id in flow_subflows.sbfl_id%type',
'  , pi_objt_id in flow_objects.objt_id%type',
'  , pi_step_key in flow_subflows.sbfl_step_key%type default null',
'  ) return varchar2;',
'',
'end flow_usertask_pkg;',
'/',
'',
'create or replace package flow_plsql_runner_pkg',
'  authid current_user',
'as',
'',
'  e_plsql_script_requested_stop exception;',
'  e_plsql_script_failed exception;',
'',
'  pragma deprecate (get_current_prcs_id, ''flow_plsql_runner_pkg.get_current_prcs_id is deprecated.  Use flow_globals.process_id instead'');',
'  pragma deprecate (get_current_sbfl_id, ''flow_plsql_runner_pkg.get_current_sbfl_id is deprecated.  Use flow_globals.subflow_id instead'');',
'',
'  function get_current_prcs_id',
'    return flow_processes.prcs_id%type',
'  ;',
'',
'  function get_current_sbfl_id',
'    return flow_subflows.sbfl_id%type',
'  ;',
'  ',
'  procedure run_task_script',
'  (',
'    pi_prcs_id  in flow_processes.prcs_id%type',
'  , pi_sbfl_id  in flow_subflows.sbfl_id%type',
'  , pi_objt_id  in flow_objects.objt_id%type',
'  , pi_step_key in flow_subflows.sbfl_step_key%type default null',
'  );',
'',
'end flow_plsql_runner_pkg;',
'/',
'',
'create or replace package flow_logging',
'accessible by ( flow_engine, flow_instances, flow_process_vars, flow_expressions ',
'              , flow_boundary_events, flow_gateways, flow_tasks, flow_errors, flow_timers_pkg',
'              )',
'as',
'',
'  procedure log_instance_event',
'  ( p_process_id        in flow_subflow_log.sflg_prcs_id%type',
'  , p_objt_bpmn_id      in flow_objects.objt_bpmn_id%type default null',
'  , p_event             in flow_instance_event_log.lgpr_prcs_event%type ',
'  , p_comment           in flow_instance_event_log.lgpr_comment%type default null',
'  , p_error_info        in flow_instance_event_log.lgpr_error_info%type default null',
'  );',
'',
'  procedure log_step_completion',
'  ( p_process_id        in flow_subflow_log.sflg_prcs_id%type',
'  , p_subflow_id        in flow_subflow_log.sflg_sbfl_id%type',
'  , p_completed_object  in flow_subflow_log.sflg_objt_id%type',
'  , p_notes             in flow_subflow_log.sflg_notes%type default null',
'  );',
'',
'  procedure log_variable_event -- logs process variable set events',
'  ( p_process_id        in flow_subflow_log.sflg_prcs_id%type',
'  , p_var_name          in flow_process_variables.prov_var_name%type',
'  , p_objt_bpmn_id      in flow_objects.objt_bpmn_id%type default null',
'  , p_subflow_id        in flow_subflow_log.sflg_sbfl_id%type default null',
'  , p_expr_set          in flow_object_expressions.expr_set%type default null',
'  , p_var_type          in flow_process_variables.prov_var_type%type',
'  , p_var_vc2           in flow_process_variables.prov_var_vc2%type default null',
'  , p_var_num           in flow_process_variables.prov_var_num%type default null',
'  , p_var_date          in flow_process_variables.prov_var_date%type default null',
'  , p_var_clob          in flow_process_variables.prov_var_clob%type default null',
'  );',
'',
'end flow_logging;',
'/',
'',
'create or replace package flow_globals',
'as',
'',
'  process_id flow_processes.prcs_id%type;',
'  subflow_id flow_subflows.sbfl_id%type;',
'  step_key   flow_subflows.sbfl_step_key%type;',
'',
'  procedure set_context',
'  ( pi_prcs_id  in flow_processes.prcs_id%type',
'  , pi_sbfl_id  in flow_subflows.sbfl_id%type default null',
'  , pi_step_key in flow_subflows.sbfl_step_key%type default null',
'  );',
'',
'  procedure set_step_error',
'  ( p_has_error  in boolean default false',
'  );',
'',
'  function get_step_error',
'  return boolean;',
'',
'  procedure set_is_recursive_step',
'  ( p_is_recursive_step  in boolean default false',
'  );',
'',
'  function get_is_recursive_step',
'  return boolean;',
'',
'end flow_globals;',
'/',
'',
'create or replace package flow_errors',
'as',
'',
'  procedure handle_instance_error',
'  ( pi_prcs_id        in flow_processes.prcs_id%type',
'  , pi_sbfl_id        in flow_subflows.sbfl_id%type default null',
'  , pi_message_key    in varchar2',
'  , p0                in varchar2 default null',
'  , p1                in varchar2 default null',
'  , p2                in varchar2 default null',
'  , p3                in varchar2 default null',
'  , p4                in varchar2 default null',
'  , p5                in varchar2 default null',
'  , p6                in varchar2 default null',
'  , p7                in varchar2 default null',
'  , p8                in varchar2 default null',
'  , p9                in varchar2 default null',
'  );',
'',
'  procedure handle_general_error',
'  ( pi_message_key    in varchar2',
'  , p0                in varchar2 default null',
'  , p1                in varchar2 default null',
'  , p2                in varchar2 default null',
'  , p3                in varchar2 default null',
'  , p4                in varchar2 default null',
'  , p5                in varchar2 default null',
'  , p6                in varchar2 default null',
'  , p7                in varchar2 default null',
'  , p8                in varchar2 default null',
'  , p9                in varchar2 default null',
'  );',
'  procedure set_error_status',
'  ( pi_prcs_id        in flow_processes.prcs_id%type',
'  , pi_sbfl_id        in flow_subflows.sbfl_id%type',
'  );',
'  ',
'  function make_error_message',
'  ( pi_message_key    in flow_messages.fmsg_message_key%type ',
'  , pi_lang           in flow_messages.fmsg_lang%type',
'  , p0                in varchar2 default null',
'  , p1                in varchar2 default null',
'  , p2                in varchar2 default null',
'  , p3                in varchar2 default null',
'  , p4                in varchar2 default null',
'  , p5                in varchar2 default null',
'  , p6                in varchar2 default null',
'  , p7                in varchar2 default null',
'  , p8                in varchar2 default null',
'  , p9                in varchar2 default null',
'  ) return flow_messages.fmsg_message_content%type;',
'',
'   e_gateway_invalid_route exception;',
'',
'end flow_errors;',
'/',
'',
'create or replace package flow_diagram',
'  authid definer',
'as',
'',
'  diagram_exists exception;',
'  diagram_not_draft exception;',
'  pragma exception_init(diagram_exists, -20001);',
'  pragma exception_init(diagram_not_draft, -20002);',
'',
'  function create_diagram(',
'    pi_dgrm_name in flow_diagrams.dgrm_name%type,',
'    pi_dgrm_category in flow_diagrams.dgrm_category%type,',
'    pi_dgrm_version in flow_diagrams.dgrm_version%type)',
'  return flow_diagrams.dgrm_id%type;',
'',
'',
'  function add_diagram_version(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type,',
'    pi_dgrm_version in flow_diagrams.dgrm_version%type)',
'  return flow_diagrams.dgrm_id%type;',
'',
'',
'  function import_diagram(',
'    pi_dgrm_name in flow_diagrams.dgrm_name%type,',
'    pi_dgrm_category in flow_diagrams.dgrm_category%type,',
'    pi_dgrm_version in flow_diagrams.dgrm_version%type,',
'    pi_dgrm_content in flow_diagrams.dgrm_content%type,',
'    pi_force_overwrite in varchar2 default flow_constants_pkg.gc_false) ',
'  return flow_diagrams.dgrm_id%type;',
'  ',
'  ',
'  function diagram_is_modifiable(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type)',
'  return boolean;',
'',
'',
'  procedure delete_diagram(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type,',
'    pi_cascade in varchar2);',
'',
'',
'  procedure edit_diagram(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type,',
'    pi_dgrm_name in flow_diagrams.dgrm_name%type,',
'    pi_dgrm_category in flow_diagrams.dgrm_category%type,',
'    pi_dgrm_version in flow_diagrams.dgrm_version%type);',
'',
'',
'  procedure release_diagram(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type);',
'',
'',
'  procedure deprecate_diagram(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type);',
'',
'',
'  procedure archive_diagram(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type);   ',
'',
'end flow_diagram;',
'/',
'',
'create or replace package flow_engine_app_api',
'  authid definer',
'as',
'',
'  procedure handle_ajax;',
'',
'  /* general */',
'  function get_objt_list(',
'    p_prcs_id in flow_processes.prcs_id%type',
'  ) return varchar2;',
'',
'  ',
'  function get_objt_list(',
'    p_dgrm_id in flow_diagrams.dgrm_id%type',
'  ) return varchar2;',
'  ',
'  ',
'  function get_objt_name(',
'    p_objt_bpmn_id in flow_objects.objt_bpmn_id%type',
'  ) return flow_objects.objt_name%type;',
'',
'  procedure set_viewport(',
'    p_display_setting in varchar2);',
'',
'  procedure add_viewport_script(',
'    p_item in varchar2',
'  );',
'',
'  procedure get_url_p13(',
'    pi_dgrm_id flow_diagrams.dgrm_id%type',
'  , pi_objt_id varchar2',
'  , pi_title varchar2',
'  );',
'',
'  procedure get_url_p13(',
'    pi_prcs_id flow_processes.prcs_id%type',
'  , pi_objt_id varchar2',
'  , pi_title varchar2',
'  );',
'',
'  /* page 2 */',
'',
'  function validate_flow_exists_bulk(',
'    '))
);
null;
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.append_to_install_script(
 p_id=>wwv_flow_api.id(35319480816885757)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'pi_dgrm_id_list in varchar2',
'  , pi_new_version  in flow_diagrams.dgrm_version%type ',
'  ) return varchar2;',
'',
'  function validate_flow_exists(',
'    pi_dgrm_id     in flow_diagrams.dgrm_id%type',
'  , pi_new_version in flow_diagrams.dgrm_version%type ',
'  ) return varchar2;',
'    ',
'  function validate_flow_copy_bulk(',
'    pi_dgrm_id_list in varchar2',
'  , pi_new_name     in flow_diagrams.dgrm_name%type ',
'  ) return varchar2;',
'    ',
'  function validate_flow_copy(',
'    pi_new_name in flow_diagrams.dgrm_name%type ',
'  ) return varchar2;',
'',
'  procedure copy_selection_to_collection;',
'',
'  procedure add_new_version(',
'    pi_dgrm_id_list in varchar2',
'  , pi_new_version  in flow_diagrams.dgrm_version%type ',
'  );',
'  ',
'  procedure copy_model(',
'    pi_dgrm_id_list in varchar2',
'  , pi_new_name     in flow_diagrams.dgrm_name%type ',
'  );',
'',
'  /* page 4 */',
'',
'  function get_region_title(',
'    pi_dgrm_id in flow_diagrams.dgrm_id%type',
'  )',
'  return varchar2;',
'',
'  /* page 5 */',
'',
'  function get_file_name(',
'      p_dgrm_id                  in number,',
'      p_include_version          in varchar2,',
'      p_include_status           in varchar2,',
'      p_include_category         in varchar2,',
'      p_include_last_change_date in varchar2,',
'      p_download_as              in varchar2',
'  ) return varchar2;',
'',
'  procedure download_file(',
'      p_dgrm_id     in number,',
'      p_file_name   in varchar2,',
'      p_download_as in varchar2,',
'      p_multi_file  in boolean default false',
'  );',
'',
'  /* page 6 */',
'',
'  function is_file_uploaded(',
'      pi_file_name in varchar2',
'  )',
'  return boolean;',
'    ',
'  function is_valid_xml(',
'      pi_import_from  in varchar2,',
'      pi_dgrm_content in flow_diagrams.dgrm_content%type,',
'      pi_file_name    in varchar2',
'  )',
'  return boolean;',
'  ',
'  function is_valid_multi_file_archive(',
'      pi_file_name in varchar2',
'  )',
'  return varchar2;',
'',
'  function upload_and_parse(',
'      pi_import_from     in varchar2,',
'      pi_dgrm_name       in flow_diagrams.dgrm_name%type,',
'      pi_dgrm_category   in flow_diagrams.dgrm_category%type,',
'      pi_dgrm_version    in flow_diagrams.dgrm_version%type,',
'      pi_dgrm_content    in flow_diagrams.dgrm_content%type,',
'      pi_file_name       in varchar2,',
'      pi_force_overwrite in varchar2',
'  )',
'  return flow_diagrams.dgrm_id%type;',
'  ',
'  procedure multiple_flow_import(',
'      pi_file_name       in varchar2,',
'      pi_force_overwrite in varchar2',
'  );',
'',
'  /* page 7 */',
'  ',
'  function validate_new_version(',
'    pi_dgrm_name    in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version in flow_diagrams.dgrm_version%type',
'  )',
'  return varchar2;',
'    ',
'  procedure process_page_p7',
'  (',
'    pio_dgrm_id      in out nocopy flow_diagrams.dgrm_id%type',
'  , pi_dgrm_name     in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version  in flow_diagrams.dgrm_version%type',
'  , pi_dgrm_category in flow_diagrams.dgrm_category%type',
'  , pi_new_version   in flow_diagrams.dgrm_version%type',
'  , pi_cascade       in varchar2',
'  , pi_request       in varchar2',
'  );',
'  ',
'  function get_page_title(',
'    pi_dgrm_id      in flow_diagrams.dgrm_id%type',
'  , pi_dgrm_name    in flow_diagrams.dgrm_name%type',
'  , pi_dgrm_version in flow_diagrams.dgrm_version%type',
'  )',
'  return varchar2;',
'',
'  /* page 8 */',
'',
'  function check_is_date(',
'    pi_value       in varchar2,',
'    pi_format_mask in varchar2)',
'    return varchar2;',
'',
'  function check_is_number(',
'    pi_value in varchar2)',
'    return varchar2;',
'    ',
'  procedure pass_variable;',
'  ',
'  function get_connection_select_option(',
'    pi_gateway in flow_objects.objt_bpmn_id%type',
'  , pi_prcs_id in flow_processes.prcs_id%type',
'  )',
'  return varchar2;',
'',
'  /* page 9 */',
'',
'  procedure set_settings(',
'    pi_logging_language          in flow_configuration.cfig_value%type',
'  , pi_logging_level             in flow_configuration.cfig_value%type',
'  , pi_logging_hide_userid       in flow_configuration.cfig_value%type',
'  , pi_engine_app_mode           in flow_configuration.cfig_value%type',
'  , pi_duplicate_step_prevention in flow_configuration.cfig_value%type',
'  );',
'',
'  /* page 11 */',
'',
'  function create_instance(',
'    pi_dgrm_id      in flow_diagrams.dgrm_id%type',
'  , pi_prcs_name    in flow_processes.prcs_name%type',
'  , pi_business_ref in flow_process_variables.prov_var_vc2%type',
'  )',
'  return flow_processes.prcs_id%type;',
'',
'  /* page 12 */',
'  ',
'  function get_prcs_name(',
'    pi_prcs_id in flow_processes.prcs_id%type',
'  )',
'  return flow_processes.prcs_name%type;',
'',
'  /* page 13 */',
'',
'  function has_error(',
'    pi_prcs_id in flow_processes.prcs_id%type,',
'    pi_objt_id in flow_subflows.sbfl_current%type)',
'  return boolean;',
'',
'end flow_engine_app_api;',
'/',
'',
'create or replace package flow_theme_api',
'  authid definer',
'as',
'',
'  procedure switch_theme_mode(',
'    pi_request in varchar2',
'  );  ',
'',
'  procedure reset_theme_mode(',
'    pi_request in varchar2',
'  );  ',
'  ',
'  procedure set_init_theme_mode;',
'    ',
'  procedure css_tricks(',
'    pi_theme_plugin_class in varchar2',
'  );',
'  ',
'end flow_theme_api;',
'/',
'create or replace package flow_plugin_manage_instance authid current_user as',
'   function execution (',
'      p_process  in  apex_plugin.t_process',
'    , p_plugin   in  apex_plugin.t_plugin',
'   ) return apex_plugin.t_process_exec_result;',
'',
'end flow_plugin_manage_instance;',
'/',
'',
'create or replace package flow_plugin_manage_instance_step authid current_user as',
'   function execution (',
'      p_process  in  apex_plugin.t_process',
'    , p_plugin   in  apex_plugin.t_plugin',
'   ) return apex_plugin.t_process_exec_result;',
'',
'end flow_plugin_manage_instance_step;',
'/',
'',
'create or replace package flow_plugin_manage_instance_variables authid current_user as',
'',
'   function execution (',
'      p_process  in  apex_plugin.t_process',
'    , p_plugin   in  apex_plugin.t_plugin',
'   ) return apex_plugin.t_process_exec_result;',
'',
'end flow_plugin_manage_instance_variables;',
'/',
'',
'create or replace package flow_modeler',
'as',
'',
'  function render',
'  (',
'    p_region              in  apex_plugin.t_region',
'  , p_plugin              in  apex_plugin.t_plugin',
'  , p_is_printer_friendly in  boolean',
'  )',
'    return apex_plugin.t_region_render_result;',
'',
'  function ajax',
'  (',
'    p_region              in  apex_plugin.t_region',
'  , p_plugin              in  apex_plugin.t_plugin',
'  )',
'    return apex_plugin.t_region_ajax_result;',
'',
'end flow_modeler;',
'/',
'',
'create or replace package flow_viewer',
'as',
'',
'  function render',
'  (',
'    p_region              in  apex_plugin.t_region',
'  , p_plugin              in  apex_plugin.t_plugin',
'  , p_is_printer_friendly in  boolean',
'  )',
'    return apex_plugin.t_region_render_result;',
'',
'  function ajax',
'  (',
'    p_region              in  apex_plugin.t_region',
'  , p_plugin              in  apex_plugin.t_plugin',
'  )',
'    return apex_plugin.t_region_ajax_result;',
'',
'end flow_viewer;',
'/',
''))
);
null;
wwv_flow_api.component_end;
end;
/
