prompt --application/deployment/install/install_data
begin
--   Manifest
--     INSTALL: INSTALL-Data
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(35319232029883995)
,p_install_id=>wwv_flow_api.id(17031066408817192)
,p_name=>'Data'
,p_sequence=>20
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'insert into flow_configuration (cfig_key, cfig_value) values (''logging_level'', ''standard'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''logging_hide_userid'', ''false'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''logging_language'',''en'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''engine_app_mode'',''production'');',
'-- put new systems into strict mode for step keys (migrated systems are in legacy mode)',
'insert into flow_configuration (cfig_key, cfig_value) values (''duplicate_step_prevention'',''strict'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''version_initial_installed'',''22.1'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''version_now_installed'',''22.1'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''default_workspace'', ''FLOWS4APEX'');',
'insert into flow_configuration (cfig_key, cfig_value) values (''default_email_sender'', '''');',
'insert into flow_configuration (cfig_key, cfig_value) values (''timer_max_cycles'',''1000'');',
'',
'PROMPT >> Loading Exported Messages',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''ITE-unsupported-type'',',
'''en'',',
'''Currently unsupported type of Intermediate Throw Event encountered at %0 .''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-child-lock-to'',',
'''en'',',
'''Child Boundary Subflows or Timers of %0 currently locked by another user.  Retry your transaction later.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-no-catch-found'',',
'''en'',',
'''No boundaryEvent of type %0 found to catch event.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-too-many'',',
'''en'',',
'''More than one %0 boundaryEvent found on sub process.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''eng_handle_event_int'',',
'''en'',',
'''Flow Engine Internal Error: Process %0 Subflow %1 Module %2 Current %4 Current Tag %3''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-unsupported-object'',',
'''en'',',
'''Model Error: Process BPMN model next step uses unsupported object %0''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-prcs-not-found'',',
'''en'',',
'''Application Error: Process ID %0 not found.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-sbfl-not-in-prcs'',',
'''en'',',
'''Application Error: Subflow ID supplied ( %0 ) exists but is not child of Process ID Supplied ( %1 ).''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-sbfl-not-found'',',
'''en'',',
'''Subflow ID supplied ( %0 ) not found. Check for process events that changed process flow (timeouts, errors, escalations).''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-invalid-route'',',
'''en'',',
'''Error at gateway %0. Supplied variable %1 contains invalid route: %2''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-merge-error'',',
'''en'',',
'''Internal error processing merging gateway on subflow %0''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-no-route'',',
'''en'',',
'''No gateway routing instruction provided in variable %0 and model contains no default route.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-too-many-defaults'',',
'''en'',',
'''More than one default route specified in model for Gateway %0.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''link-no-catch'',',
'''en'',',
'''Unable to find matching link catch event named %0.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''link-too-many-catches'',',
'''en'',',
'''More than one matching link catch event named %0.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-instance-event'',',
'''en'',',
'''Flows - Internal error while logging an Instance Event''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-step-event'',',
'''en'',',
'''Flows - Internal error while logging a Step Event''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-variable-event'',',
'''en'',',
'''Flows - Internal error while logging a Variable Event''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''process-lock-timeout'',',
'''en'',',
'''Process objects for %0 currently locked by another user.  Try again later.''',
');',
'  ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''more_than_1_forward_path'',',
'''en'',',
'''More than 1 forward path found when only 1 allowed.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''no_next_step_found'',',
'''en'',',
'''No Next Step Found on subflow %0.  Check your process diagram.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plsql_script_failed'',',
'''en'',',
'''Process %0: Task %1 failed due to PL/SQL error - see event log.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plsql_script_requested_stop'',',
'''en'',',
'''Process %0: Task %1 requested processing stop - see event log.''										  ',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timeout_locking_subflow'',',
'''en'',',
'''Unable to lock subflow %0 as currently locked by another user.  Try again later.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-already-placed'',',
'''en'',',
'''Reservation already placed on next task for you.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-by-other_user'',',
'''en'',',
'''Reservation for %0 unsuccessful.  Step already reserved by another user (%1).''',
'); ',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-failed-not-found'',',
'''en'',',
'''Reservation for %2 unsuccessful.  Subflow %0 in Process %1 not found.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-incorrect-step-key'',',
'''en'',',
'''Task is no longer current, probably already completed.  Please refresh your Inbox.''',
'); ',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-lock-timeout'',',
'''en'',',
'''Subflow currently locked (not reserved) by another user.  Try your reservation again later.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-release-not-found'',',
'''en'',',
'''Reservation release unsuccessful.  Subflow %0 in Process %1 not found.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''restart-no-error'',',
'''en'',',
'''No Current Error Found.  Check your process diagram.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-already-running'',',
'''en'',',
'''You tried to start a process (id %0)that is already running.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-multiple-already-running'',',
'''en'',',
'''You tried to start a process (id %0) with multiple copies already running.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-multiple-start-events'',',
'''en'',',
'''You have multiple starting events defined. Make sure your diagram has only one start event.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-no-start-event'',',
'''en'',',
'''No starting event is defined in the Flow diagram.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-not-created'',',
'''en'',',
'''You tried to start a process (id %0) that does not exist.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-type-unsupported'',',
'''en'',',
'''Unsupported start event type (%0). Only None (standard) Start Event and Timer Start Event are currently supported.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''startwork-sbfl-not-found'',',
'''en'',',
'''Start Work time recording unsuccessful.  Subflow %0 in Process %1 not found.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''step-key-incorrect'',',
'''en'',',
'''This Process Step has already occurred.  (Incorrect step key %0 supplied while expecting step key %1).''',
'); ',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''subProcess-no-start'',',
'''en'',',
'''Unable to find Sub-Process Start Event.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''subProcess-too-many-starts'',',
'''en'',',
'''More than one Sub-Process Start found.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-broken'',',
'''en'',',
'''Timer %0 Run %4 broken in process %1 , subflow : %2.  See error_info.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-cycle-unsupported'',',
'''en'',',
'''Cycle Timer defined for object %0 not currently supported.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-incomplete-definition'',',
'''en'',',
'''Incomplete timer definitions for object %0. Type: %1; Value1: %2 Value2: %3  Value3: %4''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-lock-timeout'',',
'''en'',',
'''Timer for subflow %0 currently locked by another user.  Try again later.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-object-not-found'',',
'''en'',',
'''Object with timer not found in get_timer_definition. Subflow %0.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timers-lock-timeout'',',
'''en'',',
'''Timers for process %0 currently locked by another user.  Try again later.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-set-error'',',
'''en'',',
'''Error creating process variable %0 for process id %1.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-get-error'',',
'''en'',',
'''Error getting process variable %0 for process id %1.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-update-error'',',
'''en'',',
'''Error updating process variable %0 for process id %1.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-delete-error'',',
'''en'',',
'''Error deleting process variable %0 for process id %1.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-lock-error'',',
'''en'',',
'''Error locking process variable %0 for process id %1.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_datatype'',',
'''en'',',
'''Error setting process variable.  Incorrect datatype for variable %0.  SQL error shown in debug output.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_date_format'',',
'''en'',',
'''Error setting Process Variable %1: Incorrect Date Format (Subflow: %0, Set: %3.)''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_object_not_found'',',
'''en'',',
'''Internal error looking up object %0 in process_expressions.  SQL error shown in debug output.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_plsql_error'',',
'''en'',',
'''Subflow : %0 Error in %2 expression for Variable : %1''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_no_data'',',
'''en'',',
'''Error setting %2 process variable %1 in process id %0.  No data found in query.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_other'',',
'''en'',',
'''Error setting %2 process variable %1 in process id %0.  SQL error shown in event log.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_too_many_rows'',',
'''en'',',
'''Error setting %2 process variable %1 in process id %0.  Query returns multiple rows.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_static_general'',',
'''en'',',
'''Error setting %2 process variable %1 in process id %0.  See error in event log.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''version-no-rel-or-draft-v0'',',
'''en'',',
'''Cannot find released diagram or draft version 0 of diagram - please specify a version or diagram_id''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
'  values (',
' ''timer_definition_error'',',
' ''en'',',
' ''Error parsing timer definition in process %0, subflow %1. Timer Type: %2, Definition: %3''',
' );',
' ',
'/* Plug-ins */',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-model-no-version'',',
'''en'',',
'''Version not defined.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-parsing-json-variables'',',
'''en'',',
'''Error during parsing process variables.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-route-not-define'',',
'''en'',',
'''Gateway is not define for routing.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-gateway-not-exist'',',
'''en'',',
'''Gateway define does not exists for this flow.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-no-instance-subflow-id'',',
'''en'',',
'''Unable to get Flow Instance Id and or subflow Id to manage the step.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-wrong-variable-number'',',
'''en'',',
'''Wrong number of APEX item(s) or process variable(s).''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-wrong-variable-type'',',
'''en'',',
'''One or more process variable(s) are a different type than the one defined in the JSON.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-variable-not-a-number'',',
'''en'',',
'''%0 is not a valid number.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-variable-not-a-date'',',
'''en'',',
'''%0 is not a valid date.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-modeler-id-not-found'',',
'''en'',',
'''No data found. Check if Diagram with given ID exists.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-unexpected-error'',',
'''en'',',
'''Unexpected error, please contact your administrator.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-not-parsable'',',
'''en'',',
'''Diagram could not be parsed.<br />Please review your diagram to ensure that it is supported.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-saved'',',
'''en'',',
'''Changes saved!''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-has-changed'',',
'''en'',',
'''Model has changed. Discard changes?''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''wrong-default-workspace'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: the default workspace defined in the configuration parameter is not valid.''',
' );',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''workspace-not-found'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: unable to find the workspace associated with the application id defined in the diagram. Please check the model.''',
' );',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-from'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: attribute "From" and default email sender are not defined. Please check the model and or the configuration parameter.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-to'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: attribute "To" not defined. Please check the model.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-template'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: attribute "Template" not defined. Please check the model.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-body'',',
'''en'',',
'''Process %0: ServiceTask %1 failed: attribute "Body" not defined. Please check the model.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-failed'',',
'''en'',',
'''Process %0: ServiceTask %1 failed see error log and check the model.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-placeholder-json-invalid'',',
'''en'',',
'''Process %0: ServiceTask %1 placeholder JSON is invalid.Please check the model.''',
');',
'',
'PROMPT >> Loading Exported Messages',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''ITE-unsupported-type'',',
'''fr'',',
unistr('''Type d''''\00E9v\00E9nement de lancer interm\00E9diaire actuellement non pris en charge rencontr\00E9 \00E0 %0.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-child-lock-to'',',
'''fr'',',
unistr('''Sous-flux enfant ou minuteur de %0 sont actuellement verrouill\00E9s par un autre utilisateur. . R\00E9essayez votre transaction plus tard.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-no-catch-found'',',
'''fr'',',
unistr('''Aucun \00E9v\00E9nement de fronti\00E8re de type %0 trouv\00E9 pour capturer l''''\00E9v\00E9nement.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''boundary-event-too-many'',',
'''fr'',',
unistr('''Plus d''''un \00E9v\00E9nement de fronti\00E8re %0 trouv\00E9 sur le sous-processus.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''eng_handle_event_int'',',
'''fr'',',
'''Erreur interne du moteur de flux: Processus %0 Sous-flux %1 Module %2 Courant %4 Balise courante %3''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-unsupported-object'',',
'''fr'',',
unistr('''Erreur de mod\00E8le : L''''\00E9tape suivante du mod\00E8le de processus BPMN utilise un objet non support\00E9 %0'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-prcs-not-found'',',
'''fr'',',
unistr('''Erreur applicative : L''''ID du processus %0 n''''a pas \00E9t\00E9 trouv\00E9.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-sbfl-not-in-prcs'',',
'''fr'',',
'''Erreur applicative: L''''ID du sous-flux fourni ( %0 ) existe mais n''''est pas un enfant de l''''ID de processus fourni ( %1 ).''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''engine-util-sbfl-not-found'',',
'''fr'',',
unistr('''L''''ID du sous-flux fourni ( %0 ) est introuvable. V\00E9rifiez les \00E9v\00E9nements du processus qui ont modifi\00E9 le flux du processus (d\00E9lais, erreurs, escalades).'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-invalid-route'',',
'''fr'',',
'''Erreur au niveau de la passerelle %0. La variable fournie %1 contient une route invalide : %2''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-merge-error'',',
'''fr'',',
'''Erreur interne de traitement lors de la fusion au nivau de la passerelle sur le sous-flux %0''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-no-route'',',
'''fr'',',
unistr('''Aucune instruction de routage de passerelle n''''est fournie dans la variable %0 et le mod\00E8le ne contient pas de route par d\00E9faut.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''gateway-too-many-defaults'',',
'''fr'',',
unistr('''Plus d''''une route par d\00E9faut sp\00E9cifi\00E9e dans le mod\00E8le pour la passerelle %0.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''link-no-catch'',',
'''fr'',',
unistr('''Impossible de trouver le lien correspondant \00E0 l''''\00E9v\00E9nement %0.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''link-too-many-catches'',',
'''fr'',',
unistr('''Plus d''''un lien correspond \00E0 l''''\00E9v\00E9nement %0.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-instance-event'',',
'''fr'',',
unistr('''Flows - Erreur interne lors de l''''enregistrement d''''un \00E9v\00E8nement d''''instance'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-step-event'',',
'''fr'',',
unistr('''Flows - Erreur interne lors de l''''enregistrement d''''un \00E9v\00E8nement d''''\00E9tape'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''logging-variable-event'',',
'''fr'',',
unistr('''Flows - Erreur interne lors de l''''enregistrement d''''un \00E9v\00E8nement de variable'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''process-lock-timeout'',',
'''fr'',',
unistr('''Les objets de traitement pour %0 sont actuellement verrouill\00E9s par un autre utilisateur. R\00E9essayez plus tard.'''),
');',
'  ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''more_than_1_forward_path'',',
'''fr'',',
unistr('''Plus d''''un chemin d''''acc\00E8s trouv\00E9 alors qu''''un seul est autoris\00E9.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''no_next_step_found'',',
'''fr'',',
unistr('''Aucune \00E9tape suivante trouv\00E9e pour le sous-flux %0. V\00E9rifiez votre diagramme de processus.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plsql_script_failed'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che %1 a \00E9chou\00E9 en raison d''''une erreur PL/SQL - voir le journal des \00E9v\00E9nements.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plsql_script_requested_stop'',',
'''fr'',',
unistr('''Processus %0: T\00E2che %1 arr\00EAt du traitement demand\00E9 - voir le journal des \00E9v\00E9nements.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timeout_locking_subflow'',',
'''fr'',',
unistr('''Impossible de verrouiller le sous-flux %0, celui-ci est actuellement verrouill\00E9 par un autre utilisateur. Veuillez r\00E9essayer ult\00E9rieurement.'''),
');',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-already-placed'',',
'''fr'',',
unistr('''R\00E9servation d\00E9j\00E0 effectu\00E9e sur la prochaine t\00E2che pour vous.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-by-other_user'',',
'''fr'',',
unistr('''La r\00E9servation pour %0 est impossible. L''''\00E9tape est d\00E9j\00E0 r\00E9serv\00E9e par un autre utilisateur (%1).'''),
'); ',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-failed-not-found'',',
'''fr'',',
unistr('''La r\00E9servation pour %0 est impossible. Sous-flux %0 dans le processus %1 non trouv\00E9.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-incorrect-step-key'',',
'''fr'',',
unistr('''La t\00E2che n''''est plus en cours, elle est probablement d\00E9j\00E0 termin\00E9e.  Veuillez rafra\00EEchir votre liste de t\00E2ches.'''),
'); ',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-lock-timeout'',',
'''fr'',',
unistr('''Sous-flux actuellement verrouill\00E9 (non reserv\00E9) par un autre utilisteur. Veuillez r\00E9essayez ult\00E9rieurement.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''reservation-release-not-found'',',
'''fr'',',
unistr('''La lib\00E9ration de la r\00E9servation est impossible. Sous-flux %0 dans le processus %1 non trouv\00E9.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''restart-no-error'',',
'''fr'',',
unistr('''Aucune erreur courante trouv\00E9e. V\00E9rifiez votre diagramme de processus.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-already-running'',',
'''fr'',',
unistr('''Vous avez essay\00E9 de d\00E9marrer un processus (id %0) qui est d\00E9j\00E0 en cours d''''ex\00E9cution.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-multiple-already-running'',',
'''fr'',',
unistr('''Vous avez essay\00E9 de d\00E9marrer un processus (id %0) dont plusieurs copies sont d\00E9j\00E0 en cours d''''ex\00E9cution.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-multiple-start-events'',',
'''fr'',',
unistr('''Vous avez d\00E9fini plusieurs \00E9v\00E9nements de d\00E9but. Assurez-vous que votre diagramme n''''a qu''''un seul \00E9v\00E9nement de d\00E9but.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-no-start-event'',',
'''fr'',',
unistr('''Aucun \00E9v\00E9nement de d\00E9but n''''est d\00E9fini dans le diagramme de flux.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-not-created'',',
'''fr'',',
unistr('''Vous avez essay\00E9 de d\00E9marrer un processus (id %0) qui n''''existe pas.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''start-type-unsupported'',',
'''fr'',',
unistr('''Type d''''\00E9v\00E9nement de d\00E9but non pris en charge (%0). Seuls les \00E9v\00E9nements de d\00E9but standard et de type minuteur sont actuellement pris en charge.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''startwork-sbfl-not-found'',',
'''fr'',',
unistr('''D\00E9but de l''''enregistrement des temps de travail non r\00E9ussi. Le sous-flux %0 du processus %1 est introuvable.'''),
');',
'  ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''step-key-incorrect'',',
'''fr'',',
unistr('''Cette \00E9tape de processus a d\00E9j\00E0 \00E9t\00E9 r\00E9alis\00E9e.  (Cl\00E9 d''''\00E9tape fournie incorrecte %0, cl\00E9 d''''\00E9tape attendue %1).'''),
'); ',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''subProcess-no-start'',',
'''fr'',',
unistr('''Impossible de trouver l''''\00E9v\00E9nement de d\00E9but de sous-processus.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''subProcess-too-many-starts'',',
'''fr'',',
unistr('''Plus d''''un \00E9v\00E9nement de sous-processus trouv\00E9.'''),
');',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-broken'',',
'''fr'',',
'''Minuteur %0 cycle %4 en erreur dans le processus %1 , sous-flux : %2.  Voir error_info.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-cycle-unsupported'',',
'''fr'',',
unistr('''Minuteur de type cycle d\00E9fini pour l''''objet %0 n''''est pas pris en charge actuellement.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-incomplete-definition'',',
'''fr'',',
unistr('''D\00E9finition incompl\00E8te du minuteur de l''''objet %0. Type: %1; Valeur1: %2 Valeur2: %3 Valeur3: %4'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-lock-timeout'',',
'''fr'',',
unistr('''La minuteur du sous-flux %0 est verrouill\00E9 par un autre utilisateur. Veuillez r\00E9essayer ult\00E9rieurement.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timer-object-not-found'',',
'''fr'',',
unistr('''Objet avec minuteur non trouv\00E9 dans get_timer_definition. Sous-flux %0.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''timers-lock-timeout'',',
'''fr'',',
unistr('''Les minuteurs pour le processus %0 sont verrouill\00E9s par un autre utilisateur. Veuillez r\00E9essayer ult\00E9rieurement.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-set-error'',',
'''fr'',',
unistr('''Erreur de cr\00E9ation de la variable de processus %0 pour l''''ID de processus %1.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-get-error'',',
'''fr'',',
unistr('''Erreur de r\00E9cup\00E9ration de la variable de processus %0 pour l''''ID de processus %1.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-update-error'',',
'''fr'',',
unistr('''Erreur de mise \00E0 jour de la variable de processus %0 pour l''''ID de processus %1.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-delete-error'',',
'''fr'',',
'''Erreur de suppression de la variable de processus %0 pour l''''ID de processus %1.''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var-lock-error'',',
'''fr'',',
'''Erreur de verrouillage de la variable de processus %0 pour l''''ID de processus %1.''',
'); ',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_datatype'',',
'''fr'',',
unistr('''Erreur de d\00E9finition de la variable de processus. Type de donn\00E9es incorrect pour la variable %0. Erreur SQL affich\00E9e dans le d\00E9bogage.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_date_format'',',
'''fr'',',
unistr('''Erreur de d\00E9finition de la variable de processus %1 : format de date incorrect (Sous-flux : %0, Valeur : %3.)'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_object_not_found'',',
'''fr'',',
unistr('''Erreur interne dans la recherche de l''''objet %0 dans process_expressions. Erreur SQL affich\00E9e dans le d\00E9bogage'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_plsql_error'',',
'''fr'',',
'''Sous-flux : %0 Erreur dans l''''expression '))
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.append_to_install_script(
 p_id=>wwv_flow_api.id(35319232029883995)
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'%2 de la variable : %1''',
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_no_data'',',
'''fr'',',
unistr('''Ereur lors de la mise \00E0 jour de la variable %1 avec la valeur %2 dans le processus %0 - Aucune donn\00E9e trouv\00E9e dans la requ\00EAte.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_other'',',
'''fr'',',
unistr('''Ereur lors de la mise \00E0 jour de la variable %1 avec la valeur %2 dans le processus %0.  Erreur SQL indiqu\00E9e dans le journal des \00E9v\00E9nements.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_sql_too_many_rows'',',
'''fr'',',
unistr('''Ereur lors de la mise \00E0 jour de la variable %1 avec la valeur %2 dans le processus %0.  La requ\00EAte renvoie plusieurs lignes.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''var_exp_static_general'',',
'''fr'',',
unistr('''Erreur de d\00E9finition de la variable de processus %2 %1 dans le processus id %0. Voir l''''erreur dans le journal des \00E9v\00E9nements.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''version-no-rel-or-draft-v0'',',
'''fr'',',
unistr('''Impossible de trouver le diagramme publi\00E9 ou la version 0 du diagramme - veuillez sp\00E9cifier une version ou un num\00E9ro de diagramme.'''),
');',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
'  values (',
' ''timer_definition_error'',',
' ''fr'',',
unistr(' ''Erreur lors de l''''analyse de la d\00E9finition du minuteur dans le processus %0, sous-flux %1. Type de minuteur : %2, D\00E9finition: %3'''),
' );',
'/* Plug-ins */',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-model-no-version'',',
'''fr'',',
unistr('''La version n''''est pas d\00E9finie.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-parsing-json-variables'',',
'''fr'',',
'''Erreur lors de l''''analyse des variables du processus.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-route-not-define'',',
'''fr'',',
unistr('''La passerelle n''''est pas d\00E9finie pour le routage.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-gateway-not-exist'',',
'''fr'',',
unistr('''La d\00E9finition de la passerelle n''''existe pas pour ce flux.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-no-instance-subflow-id'',',
'''fr'',',
unistr('''Impossible d''''obtenir l''''Id de l''''Instance de flux et ou l''''Id du sous-flux pour g\00E9rer l''''\00E9tape.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-wrong-variable-number'',',
'''fr'',',
unistr('''Mauvais nombre d''''\00E9l\00E9ment(s) APEX ou de variable(s) de processus.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-wrong-variable-type'',',
'''fr'',',
unistr('''Une ou plusieurs variables de processus sont d''''un type diff\00E9rent de celui d\00E9fini dans le JSON.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-variable-not-a-number'',',
'''fr'',',
'''%0 n''''est pas un nombre valide.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-variable-not-a-date'',',
'''fr'',',
'''%0 n''''est pas une date valide.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-modeler-id-not-found'',',
'''fr'',',
unistr('''Aucune donn\00E9e trouv\00E9e.\00A0V\00E9rifiez si le Diagramme avec l''''ID fourni existe.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-unexpected-error'',',
'''fr'',',
'''Erreur inattendue, veuillez contacter votre administrateur.''',
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-not-parsable'',',
'''fr'',',
unistr('''Le diagramme n''''a pas pu \00EAtre analys\00E9.<br />Veuillez examiner votre diagramme pour vous assurer qu''''il est pris en charge.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-saved'',',
'''fr'',',
unistr('''Changements enregistr\00E9s !'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''plugin-diagram-has-changed'',',
'''fr'',',
unistr('''Le mod\00E8le a chang\00E9, annuler les changements?'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''wrong-default-workspace'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : l''''espace de travail par d\00E9faut d\00E9fini dans le param\00E8tre de configuration n''''est pas valide.'''),
' );',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''workspace-not-found'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : impossible de trouver l''''espace de travail associ\00E9 \00E0 l''''aplication d\00E9finie dans le diagramme. Veuillez v\00E9rifier le mod\00E8le.'''),
' );',
' ',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-from'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : attribut De non d\00E9fini. Veuillez v\00E9rifier le mod\00E8le.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-to'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : attribut To non d\00E9fini. Veuillez v\00E9rifier le mod\00E8le.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-template'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : attribut Template non d\00E9fini. Veuillez v\00E9rifier le mod\00E8le.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-no-body'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : attribut Corps non d\00E9fini. Veuillez v\00E9rifier le mod\00E8le.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-failed'',',
'''fr'',',
unistr('''Processus %0 : la t\00E2che de service %1 a \00E9chou\00E9 : voir le journal pour plus de d\00E9tail et v\00E9rifier le mod\00E8le.'''),
');',
'',
'insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )',
' values (',
'''email-placeholder-json-invalid'',',
'''fr'',',
unistr('''Processus %0: la t\00E2che de service %1 a \00E9chou\00E9 : l''''objet JSON des espaces r\00E9serv\00E9s est invalide. Veuillez v\00E9rifier le mod\00E8le.'''),
');',
''))
);
null;
wwv_flow_api.component_end;
end;
/
