/*
   Migration Script for Issue 581 - Add basic sendMessage and receiveMessage Support

  Created  RAllen   01 Mar 2023

  (c) Copyright Oracle Corporation and/or its affiliates.  2023.

*/


create table flow_message_subscriptions (
    msub_id         number GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER ) NOT NULL, 
    msub_name	    varchar2(200),	
    msub_key_name	varchar2(200),	
    msub_key_value	varchar2(200),	
    msub_prcs_id	number,	
    msub_sbfl_id	number,	
    msub_step_key	varchar2(20),	
    msub_created	timestamp with time zone	
);

alter table flow_message_subscriptions
    add constraint msub_prcs_fk FOREIGN KEY ( msub_prcs_id )
        references flow_processes (prcs_id)
            ON DELETE CASCADE;

alter table flow_message_subscriptions
    add constraint msub_sbfl_fk FOREIGN KEY ( msub_sbfl_id )
        references flow_subflows (sbfl_id)
            ON DELETE CASCADE;

alter table flow_message_subscriptions
    add constraint msub_uk UNIQUE (msub_name, msub_key_name, msub_key_value);
