prompt --application/shared_components/navigation/lists/p10_instance_row_action_menu
begin
--   Manifest
--     LIST: P10_INSTANCE_ROW_ACTION_MENU
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.create_list(
 p_id=>wwv_flow_api.id(40423692118997018)
,p_name=>'P10_INSTANCE_ROW_ACTION_MENU'
,p_list_status=>'PUBLIC'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40423835706997032)
,p_list_item_display_sequence=>10
,p_list_item_link_text=>'View'
,p_list_item_icon=>'fa-eye'
,p_list_text_01=>'view-flow-instance'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40424429805997034)
,p_list_item_display_sequence=>20
,p_list_item_link_text=>'Start'
,p_list_item_icon=>'fa-play'
,p_list_text_01=>'start-flow-instance'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40425672453997035)
,p_list_item_display_sequence=>30
,p_list_item_link_text=>'Reset'
,p_list_item_icon=>'fa-undo'
,p_list_text_01=>'reset-flow-instance'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40426450496997035)
,p_list_item_display_sequence=>40
,p_list_item_link_text=>'Terminate'
,p_list_item_icon=>'fa-stop-circle-o'
,p_list_text_01=>'terminate-flow-instance'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40427116551997037)
,p_list_item_display_sequence=>50
,p_list_item_link_text=>'Delete'
,p_list_item_icon=>'fa-trash-o'
,p_list_text_01=>'delete-flow-instance'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.component_end;
end;
/
