prompt --application/shared_components/navigation/lists/p2_header_action_menu
begin
--   Manifest
--     LIST: P2_HEADER_ACTION_MENU
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>2400405578329584
,p_default_application_id=>100
,p_default_id_offset=>0
,p_default_owner=>'FLOWS4APEX'
);
wwv_flow_api.create_list(
 p_id=>wwv_flow_api.id(40402255178815218)
,p_name=>'P2_HEADER_ACTION_MENU'
,p_list_status=>'PUBLIC'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40402870460815221)
,p_list_item_display_sequence=>10
,p_list_item_link_text=>'New Version'
,p_list_item_icon=>'fa-arrow-circle-o-up'
,p_list_text_01=>'bulk-new-flow-version'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40403252293815221)
,p_list_item_display_sequence=>20
,p_list_item_link_text=>'Copy'
,p_list_item_icon=>'fa-plus'
,p_list_text_01=>'bulk-copy-flow'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40416697084414268)
,p_list_item_display_sequence=>30
,p_list_item_link_text=>'-'
,p_list_item_link_target=>'separator'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40410074688263331)
,p_list_item_display_sequence=>40
,p_list_item_link_text=>'Export'
,p_list_item_link_target=>'javascript:apex.submit(''EXPORT_FLOW'');'
,p_list_item_icon=>'fa-download'
,p_list_text_01=>'export-flow'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40417487918422396)
,p_list_item_display_sequence=>50
,p_list_item_link_text=>'-'
,p_list_item_link_target=>'separator'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.create_list_item(
 p_id=>wwv_flow_api.id(40417710185424087)
,p_list_item_display_sequence=>60
,p_list_item_link_text=>'Refresh'
,p_list_item_link_target=>'javascript:apex.region(''parsed_drgm'').refresh();'
,p_list_item_icon=>'fa-refresh'
,p_list_text_01=>'refresh'
,p_list_item_current_type=>'TARGET_PAGE'
);
wwv_flow_api.component_end;
end;
/
