set define off;
@"Tutorial 1  - Getting Started_23.1.sql";
@"Tutorial 2a - Basic Navigation with Gateways_23.1.sql";
@"Tutorial 2b - Parallel Gateways_23.1.sql";
@"Tutorial 2c - Inclusive Gateways_23.1.sql";
@"Tutorial 2d - Making your process pause_23.1.sql";
@"Tutorial 3a - Setting Process Variables from your Model_23.1.sql";
@"Tutorial 3b - Substitution and Bind Syntax_23.1.sql";
@"Tutorial 4a - Tasks Get Your Work Done!_23.1.sql";
@"Tutorial 4b - Reminders and Timeouts_23.1.sql";
@"Tutorial 4c - Task Priority and Due Dates_23.1.sql";
@"Tutorial 5a - Structure your Process with Sub Processes and Calls_23.1.sql";
@"Tutorial 5b - Introducing Sub Processes_23.1.sql";
@"Tutorial 5c - Handling Sub Process Error and Escalation Events_23.1.sql";
@"Tutorial 5d - Using CallActivities to call another diagram_23.1.sql";
@"Tutorial 5e - ship Goods (Called by Tutorial 5d)_23.1.sql";
@"Tutorial 5f - Making a Diagram Callable_23.1.sql";
@"Tutorial 6a - Collaborations, Lanes and Reservations_23.1.sql";
@"Tutorial 6b - Lanes and More Lanes_23.1.sql";
@"Tutorial 6c - User Assignment - Putting it all together_23.1.sql";
@"Tutorial 7a - MessageFlow Concepts_23.1.sql";
@"Tutorial 7b - MessageFlow - Supplier Response (Start before 7c)_23.1.sql";
@"Tutorial 7c - MessageFlow - Purchasing Process (start 7b first)_23.1.sql";
@"Tutorial 8a - The Full Monty (the top half!)_23.1.sql";
@"Tutorial 8c - Background Session Configuration_23.1.sql";

