declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="23.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial_5a" name="Tutorial 5a - Sub Process and Call Intro" isExecutable="false" apex:isCallable="false" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_0n10060" name="Start 5a">]'
      ,q'[      <bpmn:outgoing>Flow_0cru3b7</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_1d5cwc2" name="Concept A&#10;SubProcesses&#10;...">]'
      ,q'[      <bpmn:incoming>Flow_0cru3b7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_00khktj</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0cru3b7" sourceRef="Event_0n10060" targetRef="Activity_1d5cwc2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_00khktj" sourceRef="Activity_1d5cwc2" targetRef="Activity_0jjqteg" />]'
      ,q'[    <bpmn:subProcess id="Activity_0jjqteg" name="SubProcess A">]'
      ,q'[      <bpmn:incoming>Flow_00khktj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1k22ii5</bpmn:outgoing>]'
      ,q'[      <bpmn:startEvent id="Event_0qpee4j" name="Start A">]'
      ,q'[        <bpmn:outgoing>Flow_02xx2rl</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_1y3kmqt" name="Task A1">]'
      ,q'[        <bpmn:incoming>Flow_02xx2rl</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_14dpou2</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_02xx2rl" sourceRef="Event_0qpee4j" targetRef="Activity_1y3kmqt" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_14dpou2" sourceRef="Activity_1y3kmqt" targetRef="Gateway_0y4slbc" />]'
      ,q'[      <bpmn:task id="Activity_1qp5186" name="Task A2">]'
      ,q'[        <bpmn:incoming>Flow_0pxde3t</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0dd8rfg</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0pxde3t" sourceRef="Gateway_0y4slbc" targetRef="Activity_1qp5186" apex:sequence="10" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0dd8rfg" sourceRef="Activity_1qp5186" targetRef="Gateway_1hmr8e8" />]'
      ,q'[      <bpmn:task id="Activity_1rzmas6" name="Task A4">]'
      ,q'[        <bpmn:incoming>Flow_0d3u52u</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1c8xsz0</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0d3u52u" sourceRef="Gateway_1hmr8e8" targetRef="Activity_1rzmas6" apex:sequence="10" />]'
      ,q'[      <bpmn:endEvent id="Event_0k2oo0k" name="End A">]'
      ,q'[        <bpmn:incoming>Flow_1c8xsz0</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1c8xsz0" sourceRef="Activity_1rzmas6" targetRef="Event_0k2oo0k" />]'
      ,q'[      <bpmn:task id="Activity_1cajrr6" name="Task A3">]'
      ,q'[        <bpmn:incoming>Flow_0z14f0l</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1ga6zxf</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0z14f0l" sourceRef="Gateway_0y4slbc" targetRef="Activity_1cajrr6" apex:sequence="20" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1ga6zxf" sourceRef="Activity_1cajrr6" targetRef="Gateway_1hmr8e8" />]'
      ,q'[      <bpmn:parallelGateway id="Gateway_0y4slbc">]'
      ,q'[        <bpmn:incoming>Flow_14dpou2</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0pxde3t</bpmn:outgoing>]'
      ,q'[        <bpmn:outgoing>Flow_0z14f0l</bpmn:outgoing>]'
      ,q'[      </bpmn:parallelGateway>]'
      ,q'[      <bpmn:parallelGateway id="Gateway_1hmr8e8">]'
      ,q'[        <bpmn:incoming>Flow_0dd8rfg</bpmn:incoming>]'
      ,q'[        <bpmn:incoming>Flow_1ga6zxf</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0d3u52u</bpmn:outgoing>]'
      ,q'[      </bpmn:parallelGateway>]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:boundaryEvent id="Event_Reminder" name="Reminder Timer 2 Days  (Tutorial: 20 sec)" cancelActivity="false" attachedToRef="Activity_0jjqteg">]'
      ,q'[      <bpmn:outgoing>Flow_0tlzczp</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0i1mhte">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT30S</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0tlzczp" sourceRef="Event_Reminder" targetRef="Activity_1di1p0i" />]'
      ,q'[    <bpmn:endEvent id="Event_0uzx2t9" name="Reminder Sent">]'
      ,q'[      <bpmn:incoming>Flow_0fcs7xz</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0fcs7xz" sourceRef="Activity_1di1p0i" targetRef="Event_0uzx2t9" />]'
      ,q'[    <bpmn:scriptTask id="Activity_1di1p0i" name="Reminder Email" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0tlzczp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0fcs7xz</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:task id="Activity_1nwkvy9" name="Concept 2&#10;Call Activities">]'
      ,q'[      <bpmn:incoming>Flow_1k22ii5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1uwqiy2</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1k22ii5" sourceRef="Activity_0jjqteg" targetRef="Activity_1nwkvy9" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1uwqiy2" sourceRef="Activity_1nwkvy9" targetRef="Activity_0wtd4in" />]'
      ,q'[    <bpmn:callActivity id="Activity_1xsihhy" name="Call Another Process Diagram" apex:manualInput="false" apex:calledDiagramVersionSelection="latestVersion">]'
      ,q'[      <bpmn:incoming>Flow_156het6</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_18q8g04</bpmn:outgoing>]'
      ,q'[    </bpmn:callActivity>]'
      ,q'[    <bpmn:endEvent id="Event_0mwru4k" name="End Introduction">]'
      ,q'[      <bpmn:incoming>Flow_18q8g04</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_18q8g04" sourceRef="Activity_1xsihhy" targetRef="Event_0mwru4k" />]'
      ,q'[    <bpmn:task id="Activity_0fgll5t" name="Concept 3 &#10;CallActivities">]'
      ,q'[      <bpmn:incoming>Flow_1at7slz</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_156het6</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_156het6" sourceRef="Activity_0fgll5t" targetRef="Activity_1xsihhy" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1at7slz" sourceRef="Activity_0wtd4in" targetRef="Activity_0fgll5t" />]'
      ,q'[    <bpmn:subProcess id="Activity_0wtd4in" name="SubProcess B">]'
      ,q'[      <bpmn:incoming>Flow_1uwqiy2</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1at7slz</bpmn:outgoing>]'
      ,q'[      <bpmn:startEvent id="Event_0tshfdq" name="SubStart">]'
      ,q'[        <bpmn:outgoing>Flow_0w45tev</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_0g0btwm" name="This SubProcess Detail is Hidden">]'
      ,q'[        <bpmn:incoming>Flow_0w45tev</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0q1id54</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0w45tev" sourceRef="Event_0tshfdq" targetRef="Activity_0g0btwm" />]'
      ,q'[      <bpmn:task id="Activity_0hbv0hb" name="Use the Breadcrumb Above to Return to the Main Diagram">]'
      ,q'[        <bpmn:incoming>Flow_0q1id54</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_04k6cvo</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0q1id54" sourceRef="Activity_0g0btwm" targetRef="Activity_0hbv0hb" />]'
      ,q'[      <bpmn:task id="Activity_1onwrnf" name="A SubProcess Never has its own lanes">]'
      ,q'[        <bpmn:incoming>Flow_04k6cvo</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_12wr52q</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_04k6cvo" sourceRef="Activity_0hbv0hb" targetRef="Activity_1onwrnf" />]'
      ,q'[      <bpmn:task id="Activity_08zmfgf" name="You can nest subProcesses&#10;Inside others like this...">]'
      ,q'[        <bpmn:incoming>Flow_12wr52q</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1p57na4</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_12wr52q" sourceRef="Activity_1onwrnf" targetRef="Activity_08zmfgf" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1p57na4" sourceRef="Activity_08zmfgf" targetRef="Activity_1cj3hot" />]'
      ,q'[      <bpmn:subProcess id="Activity_1cj3hot" name="My SubSubProcess">]'
      ,q'[        <bpmn:incoming>Flow_1p57na4</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_06oiels</bpmn:outgoing>]'
      ,q'[        <bpmn:startEvent id="Event_08nvmz3">]'
      ,q'[          <bpmn:outgoing>Flow_0pz16z7</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:task id="Activity_02afphd" name="This is a Nested Sub Process">]'
      ,q'[          <bpmn:incoming>Flow_0pz16z7</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_1j8d366</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0pz16z7" sourceRef="Event_08nvmz3" targetRef="Activity_02afphd" />]'
      ,q'[        <bpmn:task id="Activity_1d8wtbd" name="There are no restrictions on how deep you can nest">]'
      ,q'[          <bpmn:incoming>Flow_1j8d366</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0d9al95</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_1j8d366" sourceRef="Activity_02afphd" targetRef="Activity_1d8wtbd" />]'
      ,q'[        <bpmn:endEvent id="Event_0e6f3lf">]'
      ,q'[          <bpmn:incoming>Flow_0d9al95</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0d9al95" sourceRef="Activity_1d8wtbd" targetRef="Event_0e6f3lf" />]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[      <bpmn:endEvent id="Event_118ei9i" name="SubEnd">]'
      ,q'[        <bpmn:incoming>Flow_06oiels</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_06oiels" sourceRef="Activity_1cj3hot" targetRef="Event_118ei9i" />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1xxo0g1">]'
      ,q'[      <bpmn:text>Tutorial Section 5:  Introduction to SubProcesses and Call Activities]'
      ,q'[]'
      ,q'[Both Sub Processes and Call Activities allow you to break your process down into subprocesses.  with bpmn:subProcesses, those sub Processes are defined as part of your diagram and are only callable from within the diagram they are contained on.  ]'
      ,q'[]'
      ,q'[CallActivities allow you to call a different diagram as the detail of your subProcess.  This allows you to reuse process components across different processes.   For example, a bank could define a model for its 'Know Your Client' process.   This process could then be built into many other process diagrams -- as a call - rather than being contained in each diagram.]'
      ,q'[]'
      ,q'[The tutorials in this section look at some of the details of Sub Processes and Call activities...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1i1gbpg" sourceRef="Event_0n10060" targetRef="TextAnnotation_1xxo0g1" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1uz56tw">]'
      ,q'[      <bpmn:text>This is a SubProcess]'
      ,q'[]'
      ,q'[Once the subProcess becomes the current task on the main path, processing starts inside the subProcess -- starting at its Start event.  When The Sub Process is complete, processing returns to the main path.]'
      ,q'[]'
      ,q'[Sub Processes can have Boundary Events set on them -- so just like a Task could have a Reminder or a TimeOut Set with Timer Boundary Events (see Tutorial 2d), so can a Sub Procedure.  We'll look at other Boundary Events in Tutorial 4c.]'
      ,q'[]'
      ,q'[A Sub Process can only be accessed from the diagram that contains it.]'
      ,q'[]'
      ,q'[This SubProcess is 'expanded' - you can see all of the details of the subProcess from the main diagram.  The next subprocess in Concet 2 shows a 'collapsed' SubProcess.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_07bb3i9" sourceRef="Activity_0jjqteg" targetRef="TextAnnotation_1uz56tw" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0u7euj0">]'
      ,q'[      <bpmn:text>This is a Call Activity]'
      ,q'[]'
      ,q'[A Call activity is a link to another Process Diagram.]'
      ,q'[]'
      ,q'[When the Call Activity becomes the current object in the workflow, the process then executes the process defined in that other diagram;   When the called diagram is complete, the process returns to the calling diagram and continues.]'
      ,q'[]'
      ,q'[Adding Call Activities allows processes to be shared and reused by other processes.   We'll look into this in more detail in Tutorial 4c...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_03losbj" sourceRef="Activity_1xsihhy" targetRef="TextAnnotation_0u7euj0" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0u2xfsn">]'
      ,q'[      <bpmn:text>Sub Processes can have their detail hidden in a 'Collapsed SubProcess'.]'
      ,q'[]'
      ,q'[Click on the Blue Arrow Widget to open the SubProcess Details...]'
      ,q'[]'
      ,q'[Before v23.1, we discouraged use of Collapsed SubProcesses because it was hard to see the detail.   Now that you are able to drill down into the subprocess, they are a very useful tool to keep your models de-cluttered.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1k5eseb" sourceRef="Activity_0wtd4in" targetRef="TextAnnotation_0u2xfsn" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial_5a">]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1xxo0g1_di" bpmnElement="TextAnnotation_1xxo0g1">]'
      ,q'[        <dc:Bounds x="480" y="150" width="463" height="250" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1uz56tw_di" bpmnElement="TextAnnotation_1uz56tw">]'
      ,q'[        <dc:Bounds x="1040" y="140" width="370" height="264" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0u7euj0_di" bpmnElement="TextAnnotation_0u7euj0">]'
      ,q'[        <dc:Bounds x="2050" y="130" width="350" height="181" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0u2xfsn_di" bpmnElement="TextAnnotation_0u2xfsn">]'
      ,q'[        <dc:Bounds x="1580" y="150" width="340" height="166" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0n10060_di" bpmnElement="Event_0n10060">]'
      ,q'[        <dc:Bounds x="382" y="532" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="381" y="575" width="38" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1d5cwc2_di" bpmnElement="Activity_1d5cwc2">]'
      ,q'[        <dc:Bounds x="470" y="510" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0mwru4k_di" bpmnElement="Event_0mwru4k">]'
      ,q'[        <dc:Bounds x="2182" y="532" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="2160" y="575" width="81" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0vnal3w_di" bpmnElement="Activity_1xsihhy">]'
      ,q'[        <dc:Bounds x="2020" y="510" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1nwkvy9_di" bpmnElement="Activity_1nwkvy9">]'
      ,q'[        <dc:Bounds x="1600" y="510" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0fgll5t_di" bpmnElement="Activity_0fgll5t">]'
      ,q'[        <dc:Bounds x="1880" y="510" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0i0x4v2_di" bpmnElement="Activity_0jjqteg" isExpanded="true">]'
      ,q'[        <dc:Bounds x="630" y="510" width="900" height="280" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0qpee4j_di" bpmnElement="Event_0qpee4j">]'
      ,q'[        <dc:Bounds x="671.6666666666666" y="582" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="673" y="625" width="33" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1y3kmqt_di" bpmnElement="Activity_1y3kmqt">]'
      ,q'[        <dc:Bounds x="760" y="560" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1qp5186_di" bpmnElement="Activity_1qp5186">]'
      ,q'[        <dc:Bounds x="1020" y="560" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1rzmas6_di" bpmnElement="Activity_1rzmas6">]'
      ,q'[        <dc:Bounds x="1280" y="560" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0k2oo0k_di" bpmnElement="Event_0k2oo0k">]'
      ,q'[        <dc:Bounds x="1442" y="582" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1446" y="625" width="29" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1cajrr6_di" bpmnElement="Activity_1cajrr6">]'
      ,q'[        <dc:Bounds x="1020" y="670" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0e1ttb1_di" bpmnElement="Gateway_0y4slbc">]'
      ,q'[        <dc:Bounds x="915" y="575" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0ghj7i1_di" bpmnElement="Gateway_1hmr8e8">]'
      ,q'[        <dc:Bounds x="1175" y="575" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02xx2rl_di" bpmnElement="Flow_02xx2rl">]'
      ,q'[        <di:waypoint x="708" y="600" />]'
      ,q'[        <di:waypoint x="760" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_14dpou2_di" bpmnElement="Flow_14dpou2">]'
      ,q'[        <di:waypoint x="860" y="600" />]'
      ,q'[        <di:waypoint x="915" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0pxde3t_di" bpmnElement="Flow_0pxde3t">]'
      ,q'[        <di:waypoint x="965" y="600" />]'
      ,q'[        <di:waypoint x="1020" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0dd8rfg_di" bpmnElement="Flow_0dd8rfg">]'
      ,q'[        <di:waypoint x="1120" y="600" />]'
      ,q'[        <di:waypoint x="1175" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0d3u52u_di" bpmnElement="Flow_0d3u52u">]'
      ,q'[        <di:waypoint x="1225" y="600" />]'
      ,q'[        <di:waypoint x="1280" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1c8xsz0_di" bpmnElement="Flow_1c8xsz0">]'
      ,q'[        <di:waypoint x="1380" y="600" />]'
      ,q'[        <di:waypoint x="1442" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0z14f0l_di" bpmnElement="Flow_0z14f0l">]'
      ,q'[        <di:waypoint x="940" y="625" />]'
      ,q'[        <di:waypoint x="940" y="710" />]'
      ,q'[        <di:waypoint x="1020" y="710" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ga6zxf_di" bpmnElement="Flow_1ga6zxf">]'
      ,q'[        <di:waypoint x="1120" y="710" />]'
      ,q'[        <di:waypoint x="1200" y="710" />]'
      ,q'[        <di:waypoint x="1200" y="625" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0uzx2t9_di" bpmnElement="Event_0uzx2t9">]'
      ,q'[        <dc:Bounds x="1082" y="852" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1065" y="895" width="71" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1vz8iyg_di" bpmnElement="Activity_1di1p0i">]'
      ,q'[        <dc:Bounds x="930" y="830" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1i1gbpg_di" bpmnElement="Association_1i1gbpg">]'
      ,q'[        <di:waypoint x="403" y="533" />]'
      ,q'[        <di:waypoint x="460" y="240" />]'
      ,q'[        <di:waypoint x="480" y="240" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_07bb3i9_di" bpmnElement="Association_07bb3i9">]'
      ,q'[        <di:waypoint x="1023" y="510" />]'
      ,q'[        <di:waypoint x="990" y="430" />]'
      ,q'[        <di:waypoint x="990" y="252" />]'
      ,q'[        <di:waypoint x="1011" y="273" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_03losbj_di" bpmnElement="Association_03losbj">]'
      ,q'[        <di:waypoint x="2064" y="510" />]'
      ,q'[        <di:waypoint x="2010" y="220" />]'
      ,q'[        <di:waypoint x="2050" y="220" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1xm8cev_di" bpmnElement="Activity_0wtd4in">]'
      ,q'[        <dc:Bounds x="1740" y="510" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1k5eseb_di" bpmnElement="Association_1k5eseb">]'
      ,q'[        <di:waypoint x="1773" y="510" />]'
      ,q'[        <di:waypoint x="1693" y="316" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Event_18tk28b_di" bpmnElement="Event_Reminder">]'
      ,q'[        <dc:Bounds x="842" y="772" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="767" y="815" width="85" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0cru3b7_di" bpmnElement="Flow_0cru3b7">]'
      ,q'[        <di:waypoint x="418" y="550" />]'
      ,q'[        <di:waypoint x="470" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_00khktj_di" bpmnElement="Flow_00khktj">]'
      ,q'[        <di:waypoint x="570" y="550" />]'
      ,q'[        <di:waypoint x="630" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0tlzczp_di" bpmnElement="Flow_0tlzczp">]'
      ,q'[        <di:waypoint x="860" y="808" />]'
      ,q'[        <di:waypoint x="860" y="870" />]'
      ,q'[        <di:waypoint x="930" y="870" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0fcs7xz_di" bpmnElement="Flow_0fcs7xz">]'
      ,q'[        <di:waypoint x="1030" y="870" />]'
      ,q'[        <di:waypoint x="1082" y="870" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1k22ii5_di" bpmnElement="Flow_1k22ii5">]'
      ,q'[        <di:waypoint x="1530" y="550" />]'
      ,q'[        <di:waypoint x="1600" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1uwqiy2_di" bpmnElement="Flow_1uwqiy2">]'
      ,q'[        <di:waypoint x="1700" y="550" />]'
      ,q'[        <di:waypoint x="1740" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_18q8g04_di" bpmnElement="Flow_18q8g04">]'
      ,q'[        <di:waypoint x="2120" y="550" />]'
      ,q'[        <di:waypoint x="2182" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_156het6_di" bpmnElement="Flow_156het6">]'
      ,q'[        <di:waypoint x="1980" y="550" />]'
      ,q'[        <di:waypoint x="2020" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1at7slz_di" bpmnElement="Flow_1at7slz">]'
      ,q'[        <di:waypoint x="1840" y="550" />]'
      ,q'[        <di:waypoint x="1880" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1fi6zbm">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0p5b20p" bpmnElement="Activity_0wtd4in">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0tshfdq_di" bpmnElement="Event_0tshfdq">]'
      ,q'[        <dc:Bounds x="-838" y="-218" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-841" y="-175" width="43" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0g0btwm_di" bpmnElement="Activity_0g0btwm">]'
      ,q'[        <dc:Bounds x="-750" y="-240" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0hbv0hb_di" bpmnElement="Activity_0hbv0hb">]'
      ,q'[        <dc:Bounds x="-590" y="-240" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1onwrnf_di" bpmnElement="Activity_1onwrnf">]'
      ,q'[        <dc:Bounds x="-430" y="-240" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_08zmfgf_di" bpmnElement="Activity_08zmfgf">]'
      ,q'[        <dc:Bounds x="-270" y="-240" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_118ei9i_di" bpmnElement="Event_118ei9i">]'
      ,q'[        <dc:Bounds x="52" y="-218" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="50" y="-175" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1dmnljq_di" bpmnElement="Activity_1cj3hot">]'
      ,q'[        <dc:Bounds x="-110" y="-240" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0w45tev_di" bpmnElement="Flow_0w45tev">]'
      ,q'[        <di:waypoint x="-802" y="-200" />]'
      ,q'[        <di:waypoint x="-750" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0q1id54_di" bpmnElement="Flow_0q1id54">]'
      ,q'[        <di:waypoint x="-650" y="-200" />]'
      ,q'[        <di:waypoint x="-590" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_04k6cvo_di" bpmnElement="Flow_04k6cvo">]'
      ,q'[        <di:waypoint x="-490" y="-200" />]'
      ,q'[        <di:waypoint x="-430" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12wr52q_di" bpmnElement="Flow_12wr52q">]'
      ,q'[        <di:waypoint x="-330" y="-200" />]'
      ,q'[        <di:waypoint x="-270" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1p57na4_di" bpmnElement="Flow_1p57na4">]'
      ,q'[        <di:waypoint x="-170" y="-200" />]'
      ,q'[        <di:waypoint x="-110" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_06oiels_di" bpmnElement="Flow_06oiels">]'
      ,q'[        <di:waypoint x="-10" y="-200" />]'
      ,q'[        <di:waypoint x="52" y="-200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1wj8tqa">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1f6wxmv" bpmnElement="Activity_1cj3hot">]'
      ,q'[      <bpmndi:BPMNShape id="Event_08nvmz3_di" bpmnElement="Event_08nvmz3">]'
      ,q'[        <dc:Bounds x="-738" y="-198" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_02afphd_di" bpmnElement="Activity_02afphd">]'
      ,q'[        <dc:Bounds x="-650" y="-220" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1d8wtbd_di" bpmnElement="Activity_1d8wtbd">]'
      ,q'[        <dc:Bounds x="-490" y="-220" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0e6f3lf_di" bpmnElement="Event_0e6f3lf">]'
      ,q'[        <dc:Bounds x="-328" y="-198" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0pz16z7_di" bpmnElement="Flow_0pz16z7">]'
      ,q'[        <di:waypoint x="-702" y="-180" />]'
      ,q'[        <di:waypoint x="-650" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1j8d366_di" bpmnElement="Flow_1j8d366">]'
      ,q'[        <di:waypoint x="-550" y="-180" />]'
      ,q'[        <di:waypoint x="-490" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0d9al95_di" bpmnElement="Flow_0d9al95">]'
      ,q'[        <di:waypoint x="-390" y="-180" />]'
      ,q'[        <di:waypoint x="-328" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 5a - Structure your Process with Sub Processes and Calls',
    pi_dgrm_version => '23.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
