declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial_2D" name="Tutorial 2D Simple Timers" isExecutable="true" apex:isCallable="false" apex:isStartable="true" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_1li3yuj" name="start 2d Timers">]'
      ,q'[      <bpmn:outgoing>Flow_00rz550</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_16kndlc" name="Concept 1&#10;Adding a Timer">]'
      ,q'[      <bpmn:incoming>Flow_00rz550</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ntun9k</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_00rz550" sourceRef="Event_1li3yuj" targetRef="Activity_16kndlc" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ntun9k" sourceRef="Activity_16kndlc" targetRef="Event_0s12ekd" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_0s12ekd">]'
      ,q'[      <bpmn:incoming>Flow_1ntun9k</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_08iv23e</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0cngawg">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT10S</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:task id="Activity_1hz3cyg" name="Concept 2:&#10;Specifying a Timer">]'
      ,q'[      <bpmn:incoming>Flow_08iv23e</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0qppozd</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_08iv23e" sourceRef="Event_0s12ekd" targetRef="Activity_1hz3cyg" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0qppozd" sourceRef="Activity_1hz3cyg" targetRef="Gateway_0vx9hk2" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_0vx9hk2">]'
      ,q'[      <bpmn:incoming>Flow_0qppozd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_04zw2uj</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0sdhfsr</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_12q3n8x</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0d6n996</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_1dpg3fy" name="Wait for a Fixed Duration (Oracle Method)">]'
      ,q'[      <bpmn:incoming>Flow_04zw2uj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1otethy</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_04zw2uj" sourceRef="Gateway_0vx9hk2" targetRef="Activity_1dpg3fy" />]'
      ,q'[    <bpmn:task id="Activity_17qqrdj" name="Wait for a fixed Duration (ISO 8601 Style)">]'
      ,q'[      <bpmn:incoming>Flow_0sdhfsr</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0wjbipz</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0sdhfsr" sourceRef="Gateway_0vx9hk2" targetRef="Activity_17qqrdj" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1otethy" sourceRef="Activity_1dpg3fy" targetRef="Event_Ora_Duration" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0wjbipz" sourceRef="Activity_17qqrdj" targetRef="Event_ISO_Duration" />]'
      ,q'[    <bpmn:task id="Activity_0xk8wss" name="Wait until a Fixed Time (Oracle Method)">]'
      ,q'[      <bpmn:incoming>Flow_12q3n8x</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_187vjjj</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12q3n8x" sourceRef="Gateway_0vx9hk2" targetRef="Activity_0xk8wss" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_187vjjj" sourceRef="Activity_0xk8wss" targetRef="Event_Oracle_Time" />]'
      ,q'[    <bpmn:task id="Activity_0g0gn3b" name="Wait for a Fixed Time (ISO 8601 Method">]'
      ,q'[      <bpmn:incoming>Flow_0d6n996</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0exp2j4</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0d6n996" sourceRef="Gateway_0vx9hk2" targetRef="Activity_0g0gn3b" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0exp2j4" sourceRef="Activity_0g0gn3b" targetRef="Event_ISO_Date" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_Ora_Duration" name="Oracle Duration">]'
      ,q'[      <bpmn:documentation>15 Seconds delay.]'
      ,q'[]'
      ,q'[The formatting here is important....]'
      ,q'[</bpmn:documentation>]'
      ,q'[      <bpmn:incoming>Flow_1otethy</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_054vnaw</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_1fs1p10" apex:timerType="oracleDuration">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:oracleDuration>]'
      ,q'[            <apex:intervalYM>00-00</apex:intervalYM>]'
      ,q'[            <apex:intervalDS>000 00:00:15</apex:intervalDS>]'
      ,q'[          </apex:oracleDuration>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:endEvent id="Event_0sqqq5d">]'
      ,q'[      <bpmn:incoming>Flow_054vnaw</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_054vnaw" sourceRef="Event_Ora_Duration" targetRef="Event_0sqqq5d" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_ISO_Duration" name="ISO Duration">]'
      ,q'[      <bpmn:documentation>ISO 8601 Duration.]'
      ,q'[]'
      ,q'[Durations start with P (for period).]'
      ,q'[]'
      ,q'[Then you could add 2M3W4D for 2 Months, 3 Weeks and 4 Days.]'
      ,q'[]'
      ,q'[Then comes a T for Time]'
      ,q'[Then something like 2H20M15S]'
      ,q'[- for 2 Hours, 20 Minutes and 15 seconds.]'
      ,q'[]'
      ,q'[]'
      ,q'[</bpmn:documentation>]'
      ,q'[      <bpmn:incoming>Flow_0wjbipz</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0fhxihw</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_1epki1c">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT20S</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:endEvent id="Event_0kwb0k6">]'
      ,q'[      <bpmn:incoming>Flow_0fhxihw</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0fhxihw" sourceRef="Event_ISO_Duration" targetRef="Event_0kwb0k6" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_Oracle_Time" name="Oracle Time">]'
      ,q'[      <bpmn:documentation>You can specify an Oracle Date (optionally including a time) along with the format mask used for that date.]'
      ,q'[]'
      ,q'[In practicing, hard coding a fixed Date into your model is not often very useful.]'
      ,q'[]'
      ,q'[If you specify Just a Time (no date), the timer will go off next time that timer occurs (later today, or tomorrow if the time has already passed today).]'
      ,q'[]'
      ,q'[Or you can use substitution of a process variable --- more on that later in the tutorials....]'
      ,q'[]'
      ,q'[]'
      ,q'[]'
      ,q'[]'
      ,q'[</bpmn:documentation>]'
      ,q'[      <bpmn:incoming>Flow_187vjjj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1xtmf5p</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_04zedwp" apex:timerType="oracleDate">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:oracleDate>]'
      ,q'[            <apex:date>24-JUN-2023 09:15:00</apex:date>]'
      ,q'[            <apex:formatMask>DD-MON-YYYY HH24:MI:SS</apex:formatMask>]'
      ,q'[          </apex:oracleDate>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:endEvent id="Event_1p9psxw">]'
      ,q'[      <bpmn:incoming>Flow_1xtmf5p</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1xtmf5p" sourceRef="Event_Oracle_Time" targetRef="Event_1p9psxw" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_ISO_Date" name="ISO Date">]'
      ,q'[      <bpmn:documentation>This uses an ISO 8601 date Time String to specify a fixed future time.]'
      ,q'[]'
      ,q'[See documentation for ISO 8601 Time specs - or Google 'ISO 8601'.]'
      ,q'[</bpmn:documentation>]'
      ,q'[      <bpmn:incoming>Flow_0exp2j4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_083i9d5</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0kqfp2i">]'
      ,q'[        <bpmn:timeDate xsi:type="bpmn:tFormalExpression">20230901H13:30:20</bpmn:timeDate>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:endEvent id="Event_0dozg9s">]'
      ,q'[      <bpmn:incoming>Flow_083i9d5</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_083i9d5" sourceRef="Event_ISO_Date" targetRef="Event_0dozg9s" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0b87nxd">]'
      ,q'[      <bpmn:text>If you want to make your process wait for some period of time before it continues, you can add a Timer.]'
      ,q'[]'
      ,q'[To add a Timer, start by adding an Intermediate Event (the double circle), then change it with the Spanner Tool to an Intermediate Timer Catch Event.]'
      ,q'[]'
      ,q'[A timer delay / pause can be specified as either:]'
      ,q'[ - a DURATION -- how long you want to pause the process  (e.g., wait for 2 Hours),or ]'
      ,q'[ - a TIME that the process flow should wait before restarting  (e.g., wait until 31-DEC-2025 23:59:59 ).]'
      ,q'[]'
      ,q'[This First Timer is set for 10 seconds.  Move onto the timer event.    After a few seconds, select the Refresh option on the Actions menu to refresh the screen.   The timer actually checks to see which processes should proceed every 10 seconds -- so you might need to wait unto an additional 10 seconds for the timer to fire.   If it still hasn't fired after 30 seconds, timers might not be enabled currently on your system - ask to your system administrator or read the documentation on setting up theScheduler...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_07h0he2" sourceRef="Activity_16kndlc" targetRef="TextAnnotation_0b87nxd" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0pb1xw1">]'
      ,q'[      <bpmn:text>This is set up using IS0 8601 format for a 10 Second delay</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1ex81lj" sourceRef="Event_0s12ekd" targetRef="TextAnnotation_0pb1xw1" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0uwfxws">]'
      ,q'[      <bpmn:text>15 Seconds delay.]'
      ,q'[]'
      ,q'[The formatting here is important....</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_09dzds0" sourceRef="Event_Ora_Duration" targetRef="TextAnnotation_0uwfxws" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1defw8d">]'
      ,q'[      <bpmn:text>ISO 8601 Duration.]'
      ,q'[]'
      ,q'[Durations start with P (for period).]'
      ,q'[]'
      ,q'[Then you could add 2M3W4D for 2 Months, 3 Weeks and 4 Days.]'
      ,q'[]'
      ,q'[Then comes a T for Time]'
      ,q'[Then something like 2H20M15S]'
      ,q'[- for 2 Hours, 20 Minutes and 15 seconds.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1q8z07t" sourceRef="Event_ISO_Duration" targetRef="TextAnnotation_1defw8d" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_15qukwy">]'
      ,q'[      <bpmn:text>You can specify an Oracle Date (optionally including a time) along with the format mask used for that date.]'
      ,q'[]'
      ,q'[In practicing, hard coding a fixed Date into your model is not often very useful.]'
      ,q'[]'
      ,q'[If you specify Just a Time (no date), the timer will go off next time that timer occurs (later today, or tomorrow if the time has already passed today).]'
      ,q'[]'
      ,q'[Or you can use substitution of a process variable --- more on that later in the tutorials....</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0073qme" sourceRef="Event_Oracle_Time" targetRef="TextAnnotation_15qukwy" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1grdtja">]'
      ,q'[      <bpmn:text>This uses an ISO 8601 date Time String to specify a fixed future time.]'
      ,q'[]'
      ,q'[See documentation for ISO 8601 Time specs - or Google 'ISO 8601'.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0xnxta8" sourceRef="Event_ISO_Date" targetRef="TextAnnotation_1grdtja" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0jw7law">]'
      ,q'[      <bpmn:text>We'll cover more advanced uses of timers in later sections, including Tutorial 4d on Timer Boundary Events.]'
      ,q'[]'
      ,q'[You can also add a Timer to a process Start Event if you want to delay it's start.]'
      ,q'[]'
      ,q'[We'll also look at how to make a process wait for a message from another process or from an outside program in Message Flow...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1c34puf" sourceRef="Event_0dozg9s" targetRef="TextAnnotation_0jw7law" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial_2D">]'
      ,q'[      <bpmndi:BPMNShape id="Event_1li3yuj_di" bpmnElement="Event_1li3yuj">]'
      ,q'[        <dc:Bounds x="252" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="235" y="475" width="71" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_16kndlc_di" bpmnElement="Activity_16kndlc" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="340" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1lu07kr_di" bpmnElement="Event_0s12ekd" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="492" y="432" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1hz3cyg_di" bpmnElement="Activity_1hz3cyg">]'
      ,q'[        <dc:Bounds x="580" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0l4626v_di" bpmnElement="Gateway_0vx9hk2">]'
      ,q'[        <dc:Bounds x="735" y="425" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1dpg3fy_di" bpmnElement="Activity_1dpg3fy" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="840" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_17qqrdj_di" bpmnElement="Activity_17qqrdj" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="840" y="520" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0xk8wss_di" bpmnElement="Activity_0xk8wss" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="840" y="630" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0g0gn3b_di" bpmnElement="Activity_0g0gn3b" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="840" y="740" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1x38y3l_di" bpmnElement="Event_Ora_Duration" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1002" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="983" y="475" width="78" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0sqqq5d_di" bpmnElement="Event_0sqqq5d" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1102" y="432" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0e46wtj_di" bpmnElement="Event_ISO_Duration" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="1002" y="542" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="989" y="585" width="64" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0kwb0k6_di" bpmnElement="Event_0kwb0k6" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="1102" y="542" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_01l560j_di" bpmnElement="Event_Oracle_Time" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1002" y="652" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="991" y="695" width="60" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1p9psxw_di" bpmnElement="Event_1p9psxw" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1102" y="652" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_124r45a_di" bpmnElement="Event_ISO_Date" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1002" y="762" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="998" y="805" width="46" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0dozg9s_di" bpmnElement="Event_0dozg9s" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1102" y="762" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0b87nxd_di" bpmnElement="TextAnnotation_0b87nxd">]'
      ,q'[        <dc:Bounds x="330" y="60" width="599.9631958007812" height="236.9852752685547" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0pb1xw1_di" bpmnElement="TextAnnotation_0pb1xw1">]'
      ,q'[        <dc:Bounds x="520" y="330" width="99.99999237060547" height="67.99632263183594" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0uwfxws_di" bpmnElement="TextAnnotation_0uwfxws">]'
      ,q'[        <dc:Bounds x="1190" y="270" width="320" height="60" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1defw8d_di" bpmnElement="TextAnnotation_1defw8d">]'
      ,q'[        <dc:Bounds x="1190" y="380" width="486.9852600097656" height="139.9816131591797" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_15qukwy_di" bpmnElement="TextAnnotation_15qukwy">]'
      ,q'[        <dc:Bounds x="1190" y="540" width="450" height="150" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1grdtja_di" bpmnElement="TextAnnotation_1grdtja">]'
      ,q'[        <dc:Bounds x="1190" y="710" width="440" height="60" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0jw7law_di" bpmnElement="TextAnnotation_0jw7law">]'
      ,q'[        <dc:Bounds x="1190" y="830" width="370" height="124" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_00rz550_di" bpmnElement="Flow_00rz550">]'
      ,q'[        <di:waypoint x="288" y="450" />]'
      ,q'[        <di:waypoint x="340" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ntun9k_di" bpmnElement="Flow_1ntun9k">]'
      ,q'[        <di:waypoint x="440" y="450" />]'
      ,q'[        <di:waypoint x="492" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_08iv23e_di" bpmnElement="Flow_08iv23e">]'
      ,q'[        <di:waypoint x="528" y="450" />]'
      ,q'[        <di:waypoint x="580" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0qppozd_di" bpmnElement="Flow_0qppozd">]'
      ,q'[        <di:waypoint x="680" y="450" />]'
      ,q'[        <di:waypoint x="735" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_04zw2uj_di" bpmnElement="Flow_04zw2uj">]'
      ,q'[        <di:waypoint x="785" y="450" />]'
      ,q'[        <di:waypoint x="840" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0sdhfsr_di" bpmnElement="Flow_0sdhfsr">]'
      ,q'[        <di:waypoint x="760" y="475" />]'
      ,q'[        <di:waypoint x="760" y="560" />]'
      ,q'[        <di:waypoint x="840" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1otethy_di" bpmnElement="Flow_1otethy">]'
      ,q'[        <di:waypoint x="940" y="450" />]'
      ,q'[        <di:waypoint x="1002" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0wjbipz_di" bpmnElement="Flow_0wjbipz">]'
      ,q'[        <di:waypoint x="940" y="560" />]'
      ,q'[        <di:waypoint x="1002" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12q3n8x_di" bpmnElement="Flow_12q3n8x">]'
      ,q'[        <di:waypoint x="760" y="475" />]'
      ,q'[        <di:waypoint x="760" y="670" />]'
      ,q'[        <di:waypoint x="840" y="670" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_187vjjj_di" bpmnElement="Flow_187vjjj">]'
      ,q'[        <di:waypoint x="940" y="670" />]'
      ,q'[        <di:waypoint x="1002" y="670" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0d6n996_di" bpmnElement="Flow_0d6n996">]'
      ,q'[        <di:waypoint x="760" y="475" />]'
      ,q'[        <di:waypoint x="760" y="780" />]'
      ,q'[        <di:waypoint x="840" y="780" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0exp2j4_di" bpmnElement="Flow_0exp2j4">]'
      ,q'[        <di:waypoint x="940" y="780" />]'
      ,q'[        <di:waypoint x="1002" y="780" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_054vnaw_di" bpmnElement="Flow_054vnaw">]'
      ,q'[        <di:waypoint x="1038" y="450" />]'
      ,q'[        <di:waypoint x="1102" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0fhxihw_di" bpmnElement="Flow_0fhxihw">]'
      ,q'[        <di:waypoint x="1038" y="560" />]'
      ,q'[        <di:waypoint x="1102" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1xtmf5p_di" bpmnElement="Flow_1xtmf5p">]'
      ,q'[        <di:waypoint x="1038" y="670" />]'
      ,q'[        <di:waypoint x="1102" y="670" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_083i9d5_di" bpmnElement="Flow_083i9d5">]'
      ,q'[        <di:waypoint x="1038" y="780" />]'
      ,q'[        <di:waypoint x="1102" y="780" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_07h0he2_di" bpmnElement="Association_07h0he2">]'
      ,q'[        <di:waypoint x="388" y="410" />]'
      ,q'[        <di:waypoint x="381" y="297" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1ex81lj_di" bpmnElement="Association_1ex81lj">]'
      ,q'[        <di:waypoint x="519" y="435" />]'
      ,q'[        <di:waypoint x="540" y="398" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_09dzds0_di" bpmnElement="Association_09dzds0">]'
      ,q'[        <di:waypoint x="1032" y="437" />]'
      ,q'[        <di:waypoint x="1160" y="300" />]'
      ,q'[        <di:waypoint x="1190" y="300" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1q8z07t_di" bpmnElement="Association_1q8z07t">]'
      ,q'[        <di:waypoint x="1035" y="550" />]'
      ,q'[        <di:waypoint x="1160" y="470" />]'
      ,q'[        <di:waypoint x="1190" y="470" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0073qme_di" bpmnElement="Association_0073qme">]'
      ,q'[        <di:waypoint x="1036" y="662" />]'
      ,q'[        <di:waypoint x="1150" y="600" />]'
      ,q'[        <di:waypoint x="1190" y="600" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0xnxta8_di" bpmnElement="Association_0xnxta8">]'
      ,q'[        <di:waypoint x="1037" y="774" />]'
      ,q'[        <di:waypoint x="1150" y="730" />]'
      ,q'[        <di:waypoint x="1190" y="730" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1c34puf_di" bpmnElement="Association_1c34puf">]'
      ,q'[        <di:waypoint x="1120" y="798" />]'
      ,q'[        <di:waypoint x="1120" y="880" />]'
      ,q'[        <di:waypoint x="1190" y="880" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 2d - Making your process pause',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
