declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Flows for APEX" exporterVersion="25.1.0">]'
      ,q'[  <bpmn:process id="Process_Get_Started" name="Getting Started" isExecutable="true" apex:isStartable="true" apex:instanceName="BPMN Tutorial 1" apex:minLoggingLevel="2" apex:manualInput="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Ltd</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_1h6hi8k" name="Process Start">]'
      ,q'[      <bpmn:outgoing>Flow_16vwtz6</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0i4a27g" name="Task A">]'
      ,q'[      <bpmn:incoming>Flow_16vwtz6</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1j6b5h7</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_16vwtz6" sourceRef="Event_1h6hi8k" targetRef="Activity_0i4a27g" />]'
      ,q'[    <bpmn:task id="Activity_0k99i8a" name="Task B">]'
      ,q'[      <bpmn:incoming>Flow_1j6b5h7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_16n8dwi</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1j6b5h7" sourceRef="Activity_0i4a27g" targetRef="Activity_0k99i8a" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_16n8dwi" sourceRef="Activity_0k99i8a" targetRef="Gateway_1nhkn7p" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_1nhkn7p" name="Split Paths">]'
      ,q'[      <bpmn:incoming>Flow_16n8dwi</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1cxgzbp</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_11kyyj5</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_1gpoou5" name="Task C">]'
      ,q'[      <bpmn:incoming>Flow_1cxgzbp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_11oncpd</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1cxgzbp" sourceRef="Gateway_1nhkn7p" targetRef="Activity_1gpoou5" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_1ef89m3" name="Re-Merge &#38; Synchronize">]'
      ,q'[      <bpmn:incoming>Flow_11oncpd</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0x0prhl</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0wcqldc</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_11oncpd" sourceRef="Activity_1gpoou5" targetRef="Gateway_1ef89m3" />]'
      ,q'[    <bpmn:endEvent id="Event_0aiip5h" name="Process End">]'
      ,q'[      <bpmn:incoming>Flow_0wcqldc</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0wcqldc" sourceRef="Gateway_1ef89m3" targetRef="Event_0aiip5h" />]'
      ,q'[    <bpmn:task id="Activity_1uvn0o8" name="Task D">]'
      ,q'[      <bpmn:incoming>Flow_11kyyj5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0x0prhl</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_11kyyj5" sourceRef="Gateway_1nhkn7p" targetRef="Activity_1uvn0o8" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0x0prhl" sourceRef="Activity_1uvn0o8" targetRef="Gateway_1ef89m3" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0s1apks">]'
      ,q'[      <bpmn:text>Welcome to the Flows for APEX Tutorials.]'
      ,q'[]'
      ,q'[We've left a few tutorial and demo models here for you to get started!]'
      ,q'[]'
      ,q'[To create a new model, use the Flow Management page then the +Create Flow button to create or edit a model.  If you edit the tutorials, please save them into your own model so that others can start from a clean model!]'
      ,q'[- select or create a new category - e.g., 'my tests']'
      ,q'[- give your model a name 'my first model'    - version 0 is fine.]'
      ,q'[]'
      ,q'[To execute a model, go to Flow Monitor.]'
      ,q'[Using + Create New Instance button, select the Process Diagram that you want to execute an Instance of.  Give the instance a Name.]'
      ,q'[]'
      ,q'[In Flow Monitor, the Process Instances tab shows you all of the current process instances.  Find your process instance and then using the row menu, select Start to begin executing your process.]'
      ,q'[]'
      ,q'[Select Details.  Then move to the Subflows tab to see the individual routes (subflows) through your process.  Use the Complete option to move the subflow forwards.]'
      ,q'[]'
      ,q'[Other tabs include ]'
      ,q'[- Variables - this shows you the current state / contents of any process variables set for the process instance.  We'll explore that in the Gateway Tutorial model.]'
      ,q'[- Subscriptions - this shows you any MessageFlow messages that the process instance is waiting for.  We'll explain that later in Tutorial 7, which is all about message flow.]'
      ,q'[- Task List Entries - shows you what entries the current process is putting into user's Task Lists at present.]'
      ,q'[]'
      ,q'[This model has a parallel section, but is otherwise very simple.  Step through the model using the Complete icon to show progress.]'
      ,q'[]'
      ,q'[When the process has completed, you can go back to Process Instances and either reset it, to execute it again, or delete it.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1qmz32s" sourceRef="Event_1h6hi8k" targetRef="TextAnnotation_0s1apks" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1ooxxc0">]'
      ,q'[      <bpmn:text>When you're happy with this, move on to  Tutorial 1,  about Gateways....]'
      ,q'[]'
      ,q'[You can also look at our sample applications - access them from http://flowsforapex.org/</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1tltpuk" sourceRef="Event_0aiip5h" targetRef="TextAnnotation_1ooxxc0" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1w4dn1z">]'
      ,q'[      <bpmn:text>These are Tasks that have to be performed in your process.   Each Task is a Process Step.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1gei2vd" sourceRef="Activity_0i4a27g" targetRef="TextAnnotation_1w4dn1z" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Get_Started">]'
      ,q'[      <bpmndi:BPMNShape id="Event_1h6hi8k_di" bpmnElement="Event_1h6hi8k">]'
      ,q'[        <dc:Bounds x="312" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="297" y="475" width="67" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0i4a27g_di" bpmnElement="Activity_0i4a27g" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="400" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0k99i8a_di" bpmnElement="Activity_0k99i8a" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="560" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1ye0z4z_di" bpmnElement="Gateway_1nhkn7p" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="725" y="425" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="724" y="395" width="53" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1gpoou5_di" bpmnElement="Activity_1gpoou5" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="840" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1ef89m3_di" bpmnElement="Gateway_1ef89m3" isMarkerVisible="true" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1005" y="425" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1000" y="395" width="61" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0aiip5h_di" bpmnElement="Event_0aiip5h">]'
      ,q'[        <dc:Bounds x="1122" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1078" y="483" width="63" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1uvn0o8_di" bpmnElement="Activity_1uvn0o8" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="840" y="520" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0s1apks_di" bpmnElement="TextAnnotation_0s1apks">]'
      ,q'[        <dc:Bounds x="480" y="-30" width="810" height="420" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1ooxxc0_di" bpmnElement="TextAnnotation_1ooxxc0">]'
      ,q'[        <dc:Bounds x="1160" y="560" width="250" height="98" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1w4dn1z_di" bpmnElement="TextAnnotation_1w4dn1z">]'
      ,q'[        <dc:Bounds x="480" y="628" width="200" height="62" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_16vwtz6_di" bpmnElement="Flow_16vwtz6">]'
      ,q'[        <di:waypoint x="348" y="450" />]'
      ,q'[        <di:waypoint x="400" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1j6b5h7_di" bpmnElement="Flow_1j6b5h7">]'
      ,q'[        <di:waypoint x="500" y="450" />]'
      ,q'[        <di:waypoint x="560" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_16n8dwi_di" bpmnElement="Flow_16n8dwi">]'
      ,q'[        <di:waypoint x="660" y="450" />]'
      ,q'[        <di:waypoint x="725" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1cxgzbp_di" bpmnElement="Flow_1cxgzbp">]'
      ,q'[        <di:waypoint x="775" y="450" />]'
      ,q'[        <di:waypoint x="840" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_11oncpd_di" bpmnElement="Flow_11oncpd">]'
      ,q'[        <di:waypoint x="940" y="450" />]'
      ,q'[        <di:waypoint x="1005" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0wcqldc_di" bpmnElement="Flow_0wcqldc">]'
      ,q'[        <di:waypoint x="1055" y="450" />]'
      ,q'[        <di:waypoint x="1122" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_11kyyj5_di" bpmnElement="Flow_11kyyj5">]'
      ,q'[        <di:waypoint x="750" y="475" />]'
      ,q'[        <di:waypoint x="750" y="560" />]'
      ,q'[        <di:waypoint x="840" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0x0prhl_di" bpmnElement="Flow_0x0prhl">]'
      ,q'[        <di:waypoint x="940" y="560" />]'
      ,q'[        <di:waypoint x="1030" y="560" />]'
      ,q'[        <di:waypoint x="1030" y="475" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1qmz32s_di" bpmnElement="Association_1qmz32s">]'
      ,q'[        <di:waypoint x="339" y="435" />]'
      ,q'[        <di:waypoint x="480" y="210" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1tltpuk_di" bpmnElement="Association_1tltpuk">]'
      ,q'[        <di:waypoint x="1149" y="465" />]'
      ,q'[        <di:waypoint x="1202" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1gei2vd_di" bpmnElement="Association_1gei2vd">]'
      ,q'[        <di:waypoint x="467" y="490" />]'
      ,q'[        <di:waypoint x="524" y="628" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 1  - Getting Started',
    pi_dgrm_short_description => 'Flows for APEX Tutorial Series - Tutorial 1 - Getting Started.  Start here to learn about BPMN for Flows for APEX.',
    pi_dgrm_description => '**Overview:**  
The Flows for APEX system is a dynamic platform designed to facilitate business process modeling using Business Process Model and Notation (BPMN) standards. The tutorial highlighted here, authored by Richard Allen at Flowquest Ltd, serves as an introductory guide to leveraging BPMN models to orchestrate and automate business processes effectively.

**Product Description:**  
This model offers users a hands-on tutorial with a pre-configured BPMN process named "Getting Started." The process begins with a "Process Start" event and progresses through a series of structured tasks—Task A, Task B, Task C, and Task D, interlinked through sequence flows. A parallel gateway introduces path bifurcation to demonstrate concurrent task execution, followed by a merging point to synchronize these paths before culminating in a "Process End" event.

**Key Features:**

*   **Executable Models:** Provides fully executable process models, allowing users to simulate and monitor real-time execution of business processes.
*   **User Guidance:** Richly annotated with documentation and text annotations to facilitate learning and understanding of BPMN constructs.
*   **Process Monitoring:** Includes a Flow Monitor feature to oversee ongoing process instances, manage subflows, and review process variables.
*   **Customization & Flexibility:** Users are encouraged to create and edit models to fit specific business needs, offering a personalized approach to process management.
*   **Instructional Support:** The model includes step-by-step instructions and support for navigating through the process, making it ideal for both beginners and experienced users.

**Target Audience:**  
This tutorial is designed for business analysts, process managers, and IT professionals interested in learning process automation using BPMN within the Flows for APEX environment. It provides foundational insights suitable for newcomers but also serves as a useful reference for experienced practitioners engaged in process optimization and workflow management.

**Strategic Application:**  
By mastering the concepts presented in this tutorial, businesses can enhance operational efficiency, improve process clarity, and foster a culture of continuous process improvement. This aligns with strategic goals of optimizing resource allocation and streamlining operations for improved organizational effectiveness.',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
