declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial7e" name="Tutorial 7e - Loops and Interators Overview" isExecutable="true" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_Start" name="Start">]'
      ,q'[      <bpmn:outgoing>Flow_00jstgp</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_PreSplit" name="Pre-Split">]'
      ,q'[      <bpmn:incoming>Flow_00jstgp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1i6fc42</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_00jstgp" sourceRef="Event_Start" targetRef="Activity_PreSplit" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1i6fc42" sourceRef="Activity_PreSplit" targetRef="Gateway_Split" />]'
      ,q'[    <bpmn:task id="Activity_A1" name="A1- List">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpList</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1ngmguv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0xh1wjg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ngmguv" sourceRef="Gateway_Split" targetRef="Activity_A1" apex:sequence="10" />]'
      ,q'[    <bpmn:task id="Activity_A2" name="A2">]'
      ,q'[      <bpmn:incoming>Flow_0xh1wjg</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1v6vync</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics isSequential="true">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableList</apex:expressionType>]'
      ,q'[            <apex:expression>EmpList</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayA</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:description>Iteration &amp;LOOP_COUNTER. - &amp;ENAME.</apex:description>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;=3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0xh1wjg" sourceRef="Activity_A1" targetRef="Activity_A2" />]'
      ,q'[    <bpmn:task id="Activity_A3" name="A3">]'
      ,q'[      <bpmn:incoming>Flow_1v6vync</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0emop6i</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1v6vync" sourceRef="Activity_A2" targetRef="Activity_A3" />]'
      ,q'[    <bpmn:endEvent id="Event_AEnd" name="AEnd">]'
      ,q'[      <bpmn:incoming>Flow_0emop6i</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0emop6i" sourceRef="Activity_A3" targetRef="Event_AEnd" />]'
      ,q'[    <bpmn:task id="Activity_B1" name="B1 - Array">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpArray</apex:varName>]'
      ,q'[            <apex:varDataType>JSON</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryArray</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename, empno]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_02y11qo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mg0jl9</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_B2" name="B2">]'
      ,q'[      <bpmn:incoming>Flow_0mg0jl9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0m8ne0j</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>EmpArray</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayB</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:description>Iteration &amp;LOOP_COUNTER. - &amp;ENAME. (&amp;EMPNO.)</apex:description>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;=3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_B3" name="B3">]'
      ,q'[      <bpmn:incoming>Flow_0m8ne0j</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0cv0t6o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_BEnd" name="BEnd">]'
      ,q'[      <bpmn:incoming>Flow_0cv0t6o</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mg0jl9" sourceRef="Activity_B1" targetRef="Activity_B2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0m8ne0j" sourceRef="Activity_B2" targetRef="Activity_B3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0cv0t6o" sourceRef="Activity_B3" targetRef="Event_BEnd" />]'
      ,q'[    <bpmn:task id="Activity_C1" name="C1 - Query">]'
      ,q'[      <bpmn:incoming>Flow_1a4xxmd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1f9kxmo</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_C2" name="C2">]'
      ,q'[      <bpmn:incoming>Flow_1f9kxmo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1dcufu5</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>sqlQueryArray</apex:expressionType>]'
      ,q'[            <apex:expression>select ename, empno]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayC</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[          <apex:description>Iteration &amp;LOOP_COUNTER. - &amp;ENAME. (&amp;EMPNO.)</apex:description>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_C3" name="C3">]'
      ,q'[      <bpmn:incoming>Flow_1dcufu5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0opd4zr</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_CEnd" name="CEnd">]'
      ,q'[      <bpmn:incoming>Flow_0opd4zr</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1f9kxmo" sourceRef="Activity_C1" targetRef="Activity_C2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1dcufu5" sourceRef="Activity_C2" targetRef="Activity_C3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0opd4zr" sourceRef="Activity_C3" targetRef="Event_CEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02y11qo" sourceRef="Gateway_Split" targetRef="Activity_B1" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1a4xxmd" sourceRef="Gateway_Split" targetRef="Activity_C1" apex:sequence="30" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split" name="Split">]'
      ,q'[      <bpmn:incoming>Flow_1i6fc42</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ngmguv</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_02y11qo</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1a4xxmd</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_14oqpn7</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_D1" name="D1 - Loop">]'
      ,q'[      <bpmn:incoming>Flow_14oqpn7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_075zpir</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_D3" name="D3">]'
      ,q'[      <bpmn:incoming>Flow_1inz4p7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_134vuwh</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_DEnd" name="DEnd">]'
      ,q'[      <bpmn:incoming>Flow_134vuwh</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_134vuwh" sourceRef="Activity_D3" targetRef="Event_DEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_14oqpn7" sourceRef="Gateway_Split" targetRef="Activity_D1" apex:sequence="40" />]'
      ,q'[    <bpmn:task id="Activity_D2" name="D2">]'
      ,q'[      <bpmn:incoming>Flow_075zpir</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1inz4p7</bpmn:outgoing>]'
      ,q'[      <bpmn:standardLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayD</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[          <apex:description>Loop &amp;LOOP_COUNTER. </apex:description>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:standardLoopCharacteristics>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1inz4p7" sourceRef="Activity_D2" targetRef="Activity_D3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_075zpir" sourceRef="Activity_D1" targetRef="Activity_D2" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0i9q5wo">]'
      ,q'[      <bpmn:text>emplist = select name ]'
      ,q'[from emp]'
      ,q'[where dept no = 20]'
      ,q'[]'
      ,q'[SMITH:JONES:SCOTT:ADAMS:FORD</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_050cm0v" sourceRef="Activity_A1" targetRef="TextAnnotation_0i9q5wo" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_06yrhts">]'
      ,q'[      <bpmn:text>sequentially iterate over emplist</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0bi9txm" sourceRef="Activity_A2" targetRef="TextAnnotation_06yrhts" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1dh1ysa">]'
      ,q'[      <bpmn:text>emparray = select name, empno from amp where dept no = 20]'
      ,q'[]'
      ,q'[[{"name":"SMITH","EMPNO":7369},]'
      ,q'[{"name":"JONES","EMPNO":7566}]'
      ,q'[...]</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0iayq8p" sourceRef="Activity_B1" targetRef="TextAnnotation_1dh1ysa" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1tdwshf">]'
      ,q'[      <bpmn:text>iterate over emparray]'
      ,q'[in parallel</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1cqii1i" sourceRef="Activity_B2" targetRef="TextAnnotation_1tdwshf" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0ehpw4n">]'
      ,q'[      <bpmn:text>iterate over query in parallel...]'
      ,q'[]'
      ,q'[select name, empno ]'
      ,q'[from emp]'
      ,q'[where dept no = 20</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0hlx4e9" sourceRef="Activity_C2" targetRef="TextAnnotation_0ehpw4n" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_003r2il">]'
      ,q'[      <bpmn:text>with completion condition]'
      ,q'[]'
      ,q'[F4A$completed_instances &gt;= 3"</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_08292lx" sourceRef="Activity_C2" targetRef="TextAnnotation_003r2il" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0uxdiqy">]'
      ,q'[      <bpmn:text>loop until completion condition]'
      ,q'[]'
      ,q'[F4A$completed_instances &gt;= 3</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_00wsf7y" sourceRef="Activity_D2" targetRef="TextAnnotation_0uxdiqy" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_186d7sa">]'
      ,q'[      <bpmn:text>Iterations* and loops* can be added to]'
      ,q'[tasks or sub processes.]'
      ,q'[]'
      ,q'[They operate in parallel or sequentially.]'
      ,q'[]'
      ,q'[Iterations have an input list.   The task occurs once for each item in the input list]'
      ,q'[]'
      ,q'[The input can be a:]'
      ,q'[- process variable containing a colon separated list]'
      ,q'[- process variable containing a json array]'
      ,q'[- or directly from a query...]'
      ,q'[]'
      ,q'[*Iterations and Loops require the Enterprise Edition.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1mf8re7" associationDirection="None" sourceRef="Activity_PreSplit" targetRef="TextAnnotation_186d7sa" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial7e">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nj6ios_di" bpmnElement="Event_Start">]'
      ,q'[        <dc:Bounds x="242" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="248" y="385" width="24" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1v4awr2_di" bpmnElement="Activity_PreSplit">]'
      ,q'[        <dc:Bounds x="330" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_06o8whk_di" bpmnElement="Activity_A1" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="600" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0v2wn2j_di" bpmnElement="Activity_A2" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="760" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1m1j7lz_di" bpmnElement="Activity_A3" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="920" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0xoy17b_di" bpmnElement="Event_AEnd" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1082" y="124" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1088" y="167" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0lsnoc7" bpmnElement="Activity_B1" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="600" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_07it2bq" bpmnElement="Activity_B2" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="760" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_12yruu2" bpmnElement="Activity_B3" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="920" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_10192cq" bpmnElement="Event_BEnd" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1082" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="385" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0dwx7ia" bpmnElement="Activity_C1" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="600" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0ethqvm" bpmnElement="Activity_C2" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="760" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1s29z1t" bpmnElement="Activity_C3" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="920" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1x8vuch" bpmnElement="Event_CEnd" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1082" y="562" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="605" width="28" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1b1nb8o_di" bpmnElement="Gateway_Split">]'
      ,q'[        <dc:Bounds x="495" y="335" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="489" y="313" width="22" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0o13huf" bpmnElement="Activity_D1" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="600" y="710" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0fnnpeb" bpmnElement="Activity_D3" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="920" y="710" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1c42z7e" bpmnElement="Event_DEnd" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="1082" y="732" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="775" width="28" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_137fa4v" bpmnElement="Activity_D2" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="760" y="710" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0i9q5wo_di" bpmnElement="TextAnnotation_0i9q5wo">]'
      ,q'[        <dc:Bounds x="570" y="-28" width="280" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_06yrhts_di" bpmnElement="TextAnnotation_06yrhts">]'
      ,q'[        <dc:Bounds x="860" y="22" width="160" height="40" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1dh1ysa_di" bpmnElement="TextAnnotation_1dh1ysa">]'
      ,q'[        <dc:Bounds x="570" y="201" width="207" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1tdwshf_di" bpmnElement="TextAnnotation_1tdwshf">]'
      ,q'[        <dc:Bounds x="860" y="231" width="160" height="40" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0ehpw4n_di" bpmnElement="TextAnnotation_0ehpw4n">]'
      ,q'[        <dc:Bounds x="770" y="413" width="159.99568083501214" height="94.33962264150944" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_003r2il_di" bpmnElement="TextAnnotation_003r2il">]'
      ,q'[        <dc:Bounds x="960" y="420" width="205" height="67" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1q3npzg" bpmnElement="TextAnnotation_0uxdiqy">]'
      ,q'[        <dc:Bounds x="837" y="630" width="265" height="59" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_186d7sa_di" bpmnElement="TextAnnotation_186d7sa">]'
      ,q'[        <dc:Bounds x="210" y="60" width="300" height="217" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_00jstgp_di" bpmnElement="Flow_00jstgp">]'
      ,q'[        <di:waypoint x="278" y="360" />]'
      ,q'[        <di:waypoint x="330" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1i6fc42_di" bpmnElement="Flow_1i6fc42">]'
      ,q'[        <di:waypoint x="430" y="360" />]'
      ,q'[        <di:waypoint x="495" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ngmguv_di" bpmnElement="Flow_1ngmguv">]'
      ,q'[        <di:waypoint x="520" y="335" />]'
      ,q'[        <di:waypoint x="520" y="142" />]'
      ,q'[        <di:waypoint x="600" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xh1wjg_di" bpmnElement="Flow_0xh1wjg">]'
      ,q'[        <di:waypoint x="700" y="142" />]'
      ,q'[        <di:waypoint x="760" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1v6vync_di" bpmnElement="Flow_1v6vync">]'
      ,q'[        <di:waypoint x="860" y="142" />]'
      ,q'[        <di:waypoint x="920" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0emop6i_di" bpmnElement="Flow_0emop6i">]'
      ,q'[        <di:waypoint x="1020" y="142" />]'
      ,q'[        <di:waypoint x="1082" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1fgochk" bpmnElement="Flow_0mg0jl9">]'
      ,q'[        <di:waypoint x="700" y="360" />]'
      ,q'[        <di:waypoint x="760" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1ipi0cl" bpmnElement="Flow_0m8ne0j">]'
      ,q'[        <di:waypoint x="860" y="370" />]'
      ,q'[        <di:waypoint x="920" y="370" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1j2m5si" bpmnElement="Flow_0cv0t6o">]'
      ,q'[        <di:waypoint x="1020" y="360" />]'
      ,q'[        <di:waypoint x="1082" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_04kv3hq" bpmnElement="Flow_1f9kxmo">]'
      ,q'[        <di:waypoint x="700" y="580" />]'
      ,q'[        <di:waypoint x="760" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0pgg5lp" bpmnElement="Flow_1dcufu5">]'
      ,q'[        <di:waypoint x="860" y="580" />]'
      ,q'[        <di:waypoint x="920" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_13nxtw3" bpmnElement="Flow_0opd4zr">]'
      ,q'[        <di:waypoint x="1020" y="580" />]'
      ,q'[        <di:waypoint x="1082" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02y11qo_di" bpmnElement="Flow_02y11qo">]'
      ,q'[        <di:waypoint x="545" y="360" />]'
      ,q'[        <di:waypoint x="600" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1a4xxmd_di" bpmnElement="Flow_1a4xxmd">]'
      ,q'[        <di:waypoint x="520" y="385" />]'
      ,q'[        <di:waypoint x="520" y="580" />]'
      ,q'[        <di:waypoint x="600" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1yzay12" bpmnElement="Flow_134vuwh">]'
      ,q'[        <di:waypoint x="1020" y="750" />]'
      ,q'[        <di:waypoint x="1082" y="750" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_14oqpn7_di" bpmnElement="Flow_14oqpn7">]'
      ,q'[        <di:waypoint x="520" y="385" />]'
      ,q'[        <di:waypoint x="520" y="750" />]'
      ,q'[        <di:waypoint x="600" y="750" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0xg75l1" bpmnElement="Flow_1inz4p7">]'
      ,q'[        <di:waypoint x="860" y="750" />]'
      ,q'[        <di:waypoint x="920" y="750" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1nd59tv" bpmnElement="Flow_075zpir">]'
      ,q'[        <di:waypoint x="700" y="750" />]'
      ,q'[        <di:waypoint x="760" y="750" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_050cm0v_di" bpmnElement="Association_050cm0v">]'
      ,q'[        <di:waypoint x="630" y="102" />]'
      ,q'[        <di:waypoint x="606" y="54" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0bi9txm_di" bpmnElement="Association_0bi9txm">]'
      ,q'[        <di:waypoint x="829" y="102" />]'
      ,q'[        <di:waypoint x="860" y="37" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0iayq8p_di" bpmnElement="Association_0iayq8p">]'
      ,q'[        <di:waypoint x="605" y="322" />]'
      ,q'[        <di:waypoint x="580" y="300" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1cqii1i_di" bpmnElement="Association_1cqii1i">]'
      ,q'[        <di:waypoint x="828" y="320" />]'
      ,q'[        <di:waypoint x="858" y="251" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hlx4e9_di" bpmnElement="Association_0hlx4e9">]'
      ,q'[        <di:waypoint x="794" y="540" />]'
      ,q'[        <di:waypoint x="782" y="507" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_08292lx_di" bpmnElement="Association_08292lx">]'
      ,q'[        <di:waypoint x="856" y="543" />]'
      ,q'[        <di:waypoint x="960" y="454" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_185yip0" bpmnElement="Association_00wsf7y">]'
      ,q'[        <di:waypoint x="790" y="710" />]'
      ,q'[        <di:waypoint x="800" y="663" />]'
      ,q'[        <di:waypoint x="837" y="663" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1mf8re7_di" bpmnElement="Association_1mf8re7">]'
      ,q'[        <di:waypoint x="330" y="346" />]'
      ,q'[        <di:waypoint x="130" y="290" />]'
      ,q'[        <di:waypoint x="130" y="180" />]'
      ,q'[        <di:waypoint x="208" y="180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7e - Introduction to Iterations and Tasks',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
