declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Flows for APEX" exporterVersion="25.1.0">]'
      ,q'[  <bpmn:process id="Tutorial4" name="Task Types Tutorial" isExecutable="true" apex:isCallable="false" apex:isStartable="true" apex:minLoggingLevel="0" apex:manualInput="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Consulting.]'
      ,q'[twitter: @FlowquestR</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_0etkrt2">]'
      ,q'[      <bpmn:outgoing>Flow_1nctu2s</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0byebb7" name="This is a standard Task">]'
      ,q'[      <bpmn:incoming>Flow_1nctu2s</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0pijurl</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1nctu2s" sourceRef="Event_0etkrt2" targetRef="Activity_0byebb7" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0pijurl" sourceRef="Activity_0byebb7" targetRef="Activity_0a6djqt" />]'
      ,q'[    <bpmn:userTask id="Activity_0srf4in" name="UserTask - I can call an APEX Human Task ( Action or Approval )" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:apexPage />]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_17qungp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_199lc3i</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_199lc3i" sourceRef="Activity_0srf4in" targetRef="Activity_0w0fi2i" />]'
      ,q'[    <bpmn:scriptTask id="Activity_0w0fi2i" name="scriptTask&#10;- I can run a&#10;PL/SQL script&#10;" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_199lc3i</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_05hp9u3</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_05hp9u3" sourceRef="Activity_0w0fi2i" targetRef="Activity_1sk9zqj" />]'
      ,q'[    <bpmn:serviceTask id="Activity_1sk9zqj" name="serviceTask&#10;- Use me to call AI or &#10;send an email" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_05hp9u3</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0kd3kyt</bpmn:outgoing>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0kd3kyt" sourceRef="Activity_1sk9zqj" targetRef="Activity_0t8licd" />]'
      ,q'[    <bpmn:manualTask id="Activity_0t8licd" name="This is a Manual Task">]'
      ,q'[      <bpmn:incoming>Flow_0kd3kyt</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_07uwsw9</bpmn:outgoing>]'
      ,q'[    </bpmn:manualTask>]'
      ,q'[    <bpmn:endEvent id="Event_1da6vg3">]'
      ,q'[      <bpmn:incoming>Flow_104w405</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1pjx0pk" sourceRef="Activity_0l6ac3x" targetRef="Activity_1wg9nda" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_104w405" sourceRef="Activity_1wg9nda" targetRef="Event_1da6vg3" apex:sequence="10" />]'
      ,q'[    <bpmn:sendTask id="Activity_0l6ac3x" name="SendTask&#10;- sends a message to another process" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0mxa79i</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1pjx0pk</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:receiveTask id="Activity_1wg9nda" name="ReceiveTask&#10;- receives a message from another process" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_1pjx0pk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_104w405</bpmn:outgoing>]'
      ,q'[    </bpmn:receiveTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0wpq0ks" sourceRef="Activity_0a6djqt" targetRef="Activity_0tt3lr5" />]'
      ,q'[    <bpmn:userTask id="Activity_0a6djqt" name="UserTask - I can call an APEX page in your app" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_0pijurl</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0wpq0ks</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_17qungp" sourceRef="Activity_0tt3lr5" targetRef="Activity_0srf4in" />]'
      ,q'[    <bpmn:userTask id="Activity_0tt3lr5" name="UserTask - I can use &#10;Simple Form to collect some data" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_0wpq0ks</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_17qungp</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:businessRuleTask id="Activity_1ysn2gx" name="&#10;BusinessRule Task - use me to run a ML model" apex:type="executePlsql">]'
      ,q'[      <bpmn:incoming>Flow_07uwsw9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mxa79i</bpmn:outgoing>]'
      ,q'[    </bpmn:businessRuleTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mxa79i" sourceRef="Activity_1ysn2gx" targetRef="Activity_0l6ac3x" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07uwsw9" sourceRef="Activity_0t8licd" targetRef="Activity_1ysn2gx" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0xw8y26">]'
      ,q'[      <bpmn:text>Tutorial 4a - Tasks - Getting your Work Done!]'
      ,q'[]'
      ,q'[So much for steering your process through gateways, etc.  How do we actually get things done?]'
      ,q'[]'
      ,q'[Flows for APEX  can now direct steps in your process.  This step introduces the task types, and how to configure them.]'
      ,q'[]'
      ,q'[This tutorial is one to look at in Flow Management / Flow Modeler, but not run in your system.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_00jab7b" sourceRef="Event_0etkrt2" targetRef="TextAnnotation_0xw8y26" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1vygfet">]'
      ,q'[      <bpmn:text>A User Task can call an APEX page, pass variables into the page, etc -- just like an APEX menu does.]'
      ,q'[]'
      ,q'[Open the APEX tab in the Properties Panel (on the right) and you can see how you specify the application and page to call, provide instructions on what action to perform, what to do with the cache, and list items to set and values to use.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1r0p5lj" sourceRef="Activity_0a6djqt" targetRef="TextAnnotation_1vygfet" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1egb903">]'
      ,q'[      <bpmn:text>Service Tasks call various services, such as GenAI, messaging, email, etc.  ]'
      ,q'[]'
      ,q'[In this release, you can use these to:]'
      ,q'[]'
      ,q'[- call a GenAI service, such as GPT, to recommend a decision or to generate a document]'
      ,q'[- run a  PL/SQL procedure that you provide (similar to a scriptTask)]'
      ,q'[- send an email (defined declaratively, optionally using an APEX Mail Template)</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_061ntp9" sourceRef="Activity_1sk9zqj" targetRef="TextAnnotation_1egb903" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1rkmr7t">]'
      ,q'[      <bpmn:text>Manual Tasks are used to model non-computer steps in your process.]'
      ,q'[]'
      ,q'[In V5 and v21.1, they behave like a standard Task.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1crb5iq" sourceRef="Activity_0t8licd" targetRef="TextAnnotation_1rkmr7t" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_02mhmae">]'
      ,q'[      <bpmn:text>A Script Task can run a piece of PL/SQL that you supply in the model.]'
      ,q'[]'
      ,q'[You can use a script task to set process variables, execute a script, Lots of useful things.]'
      ,q'[]'
      ,q'[As the modeller is not a great editor, we usually write our PL/SQL as packages that are stored in the database, and just call the procedure from the diagram.]'
      ,q'[]'
      ,q'[Optionally you can bind Process Variables  into your scripts.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1ipwm4g">]'
      ,q'[      <bpmn:text>Business Rules Tasks are used to model the use of machine learning models or credit scoring models.]'
      ,q'[]'
      ,q'[These could be models stored in the database using the SQL Models feature or something else you can call via PL/SQL script.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1ity14p" sourceRef="TextAnnotation_02mhmae" targetRef="Activity_0w0fi2i" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1qygjgj">]'
      ,q'[      <bpmn:text>SendTask and ReceiveTask (and Intermediate Message Throw and Catch Events) are used for messaging between process instances (MessageFlow).]'
      ,q'[]'
      ,q'[MessageFlow is explored further in Tutorial 7a.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0pp4g90" sourceRef="Activity_0l6ac3x" targetRef="TextAnnotation_1qygjgj" />]'
      ,q'[    <bpmn:association id="Association_13luki1" sourceRef="TextAnnotation_1qygjgj" targetRef="Activity_1wg9nda" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_004vkfx">]'
      ,q'[      <bpmn:text>Use these standard tasks early in your process modelling journey - but aim to replace them with more specific task types as you make your logical process diagram into an executable workflow...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0mbekaw" associationDirection="None" sourceRef="Activity_0byebb7" targetRef="TextAnnotation_004vkfx" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_00z1cx4">]'
      ,q'[      <bpmn:text>SimpleForm allows you to collect some data from the user without having to develop APEX</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1hnmiu8" associationDirection="None" sourceRef="Activity_0tt3lr5" targetRef="TextAnnotation_00z1cx4" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1ulqhgu">]'
      ,q'[      <bpmn:text>UserTask can also call an APEX Human Task (APEX Approval Task or Action Task), allowing high interoperability  with APEX Workflow components</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0fteof6" associationDirection="None" sourceRef="Activity_0srf4in" targetRef="TextAnnotation_1ulqhgu" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1wp6ozy">]'
      ,q'[      <bpmn:text>New in 24.1</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_12rs891" associationDirection="None" sourceRef="Activity_0tt3lr5" targetRef="TextAnnotation_1wp6ozy" />]'
      ,q'[    <bpmn:association id="Association_01wl35g" sourceRef="Activity_1ysn2gx" targetRef="TextAnnotation_1ipwm4g" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Tutorial4">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0etkrt2_di" bpmnElement="Event_0etkrt2">]'
      ,q'[        <dc:Bounds x="-28" y="362" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0byebb7_di" bpmnElement="Activity_0byebb7">]'
      ,q'[        <dc:Bounds x="60" y="340" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ok42am_di" bpmnElement="Activity_0srf4in" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="510" y="340" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1e92hqx_di" bpmnElement="Activity_0w0fi2i" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="670" y="340" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0yapt8d_di" bpmnElement="Activity_1sk9zqj" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="830" y="340" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1apqobn_di" bpmnElement="Activity_0t8licd" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="990" y="340" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1da6vg3_di" bpmnElement="Event_1da6vg3">]'
      ,q'[        <dc:Bounds x="1672" y="362" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_15lsg1n_di" bpmnElement="Activity_0l6ac3x" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1330" y="340" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0tfwzsa_di" bpmnElement="Activity_1wg9nda" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1510" y="340" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0peoakh_di" bpmnElement="Activity_0a6djqt" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="220" y="340" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ac87zw_di" bpmnElement="Activity_0tt3lr5" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="370" y="340" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0lrcet4_di" bpmnElement="Activity_1ysn2gx" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1170" y="340" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0xw8y26_di" bpmnElement="TextAnnotation_0xw8y26">]'
      ,q'[        <dc:Bounds x="-60" y="-10" width="619.9975982914127" height="125.42292188407376" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1vygfet_di" bpmnElement="TextAnnotation_1vygfet">]'
      ,q'[        <dc:Bounds x="140" y="174" width="350" height="128" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1egb903_di" bpmnElement="TextAnnotation_1egb903">]'
      ,q'[        <dc:Bounds x="950" y="490" width="390" height="152" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1rkmr7t_di" bpmnElement="TextAnnotation_1rkmr7t">]'
      ,q'[        <dc:Bounds x="1020" y="190" width="200" height="95" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_02mhmae_di" bpmnElement="TextAnnotation_02mhmae">]'
      ,q'[        <dc:Bounds x="450" y="490" width="430" height="152" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1ipwm4g_di" bpmnElement="TextAnnotation_1ipwm4g">]'
      ,q'[        <dc:Bounds x="1250" y="90" width="220" height="127" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1qygjgj_di" bpmnElement="TextAnnotation_1qygjgj">]'
      ,q'[        <dc:Bounds x="1450" y="480" width="258" height="123" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_004vkfx_di" bpmnElement="TextAnnotation_004vkfx">]'
      ,q'[        <dc:Bounds x="-20" y="670" width="377.9476876986229" height="56.481825833940235" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_00z1cx4_di" bpmnElement="TextAnnotation_00z1cx4">]'
      ,q'[        <dc:Bounds x="510" y="174" width="110" height="127" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1ulqhgu_di" bpmnElement="TextAnnotation_1ulqhgu">]'
      ,q'[        <dc:Bounds x="680" y="150" width="150" height="108" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1wp6ozy_di" bpmnElement="TextAnnotation_1wp6ozy">]'
      ,q'[        <dc:Bounds x="320" y="450" width="99.98485463283065" height="29.99861315152371" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1nctu2s_di" bpmnElement="Flow_1nctu2s">]'
      ,q'[        <di:waypoint x="8" y="380" />]'
      ,q'[        <di:waypoint x="60" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0pijurl_di" bpmnElement="Flow_0pijurl">]'
      ,q'[        <di:waypoint x="160" y="380" />]'
      ,q'[        <di:waypoint x="220" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_199lc3i_di" bpmnElement="Flow_199lc3i">]'
      ,q'[        <di:waypoint x="610" y="380" />]'
      ,q'[        <di:waypoint x="670" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_05hp9u3_di" bpmnElement="Flow_05hp9u3">]'
      ,q'[        <di:waypoint x="770" y="380" />]'
      ,q'[        <di:waypoint x="830" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0kd3kyt_di" bpmnElement="Flow_0kd3kyt">]'
      ,q'[        <di:waypoint x="930" y="380" />]'
      ,q'[        <di:waypoint x="990" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1pjx0pk_di" bpmnElement="Flow_1pjx0pk">]'
      ,q'[        <di:waypoint x="1430" y="380" />]'
      ,q'[        <di:waypoint x="1510" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_104w405_di" bpmnElement="Flow_104w405">]'
      ,q'[        <di:waypoint x="1610" y="380" />]'
      ,q'[        <di:waypoint x="1672" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0wpq0ks_di" bpmnElement="Flow_0wpq0ks">]'
      ,q'[        <di:waypoint x="320" y="380" />]'
      ,q'[        <di:waypoint x="370" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_17qungp_di" bpmnElement="Flow_17qungp">]'
      ,q'[        <di:waypoint x="470" y="380" />]'
      ,q'[        <di:waypoint x="510" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0mxa79i_di" bpmnElement="Flow_0mxa79i">]'
      ,q'[        <di:waypoint x="1270" y="380" />]'
      ,q'[        <di:waypoint x="1330" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07uwsw9_di" bpmnElement="Flow_07uwsw9">]'
      ,q'[        <di:waypoint x="1090" y="380" />]'
      ,q'[        <di:waypoint x="1170" y="380" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_00jab7b_di" bpmnElement="Association_00jab7b">]'
      ,q'[        <di:waypoint x="-13" y="363" />]'
      ,q'[        <di:waypoint x="-60" y="92" />]'
      ,q'[        <di:waypoint x="-60" y="92" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1r0p5lj_di" bpmnElement="Association_1r0p5lj">]'
      ,q'[        <di:waypoint x="240" y="340" />]'
      ,q'[        <di:waypoint x="100" y="310" />]'
      ,q'[        <di:waypoint x="80" y="238" />]'
      ,q'[        <di:waypoint x="140" y="238" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_061ntp9_di" bpmnElement="Association_061ntp9">]'
      ,q'[        <di:waypoint x="918" y="420" />]'
      ,q'[        <di:waypoint x="986" y="490" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1crb5iq_di" bpmnElement="Association_1crb5iq">]'
      ,q'[        <di:waypoint x="1044" y="340" />]'
      ,q'[        <di:waypoint x="1049" y="285" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1ity14p_di" bpmnElement="Association_1ity14p">]'
      ,q'[        <di:waypoint x="699" y="490" />]'
      ,q'[        <di:waypoint x="717" y="420" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0pp4g90_di" bpmnElement="Association_0pp4g90">]'
      ,q'[        <di:waypoint x="1421" y="420" />]'
      ,q'[        <di:waypoint x="1484" y="480" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_13luki1_di" bpmnElement="Association_13luki1">]'
      ,q'[        <di:waypoint x="1510" y="480" />]'
      ,q'[        <di:waypoint x="1553" y="420" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0mbekaw_di" bpmnElement="Association_0mbekaw">]'
      ,q'[        <di:waypoint x="100" y="420" />]'
      ,q'[        <di:waypoint x="34" y="670" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1hnmiu8_di" bpmnElement="Association_1hnmiu8">]'
      ,q'[        <di:waypoint x="454" y="340" />]'
      ,q'[        <di:waypoint x="510" y="275" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0fteof6_di" bpmnElement="Association_0fteof6">]'
      ,q'[        <di:waypoint x="591" y="340" />]'
      ,q'[        <di:waypoint x="680" y="225" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_12rs891_di" bpmnElement="Association_12rs891">]'
      ,q'[        <di:waypoint x="396" y="420" />]'
      ,q'[        <di:waypoint x="379" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_01wl35g_di" bpmnElement="Association_01wl35g">]'
      ,q'[        <di:waypoint x="1230" y="340" />]'
      ,q'[        <di:waypoint x="1260" y="217" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 4a - Tasks Get Your Work Done!',
    pi_dgrm_short_description => 'Flows for APEX BPMN Tutorial - part 4a - Introduces BPMN Tasks and task types',
    pi_dgrm_description => 'The provided Business Process Model and Notation (BPMN) XML represents a process named “Task Types Tutorial”. The model illustrates various types of tasks in a business process, with an educational focus on how these tasks can be configured within a workflow system called "Flows for APEX." Below is a business summary of the model as it appears in the XML:

### Business Summary of the Model

**Overview:**  
The "Task Types Tutorial" is a business process model developed for instructional purposes to demonstrate different task types and their applications within business process management using APEX. This model is aimed at individuals or organizations that are learning about automating workflows using APEX, a tool for low-code application development.

**Key Features:**

**Standard Task:** Introduces basic task configurations that serve as placeholders before replacing them with more specific task types during the evolution of the process model into an executable workflow.

**User Task:** Demonstrates the capability to call an APEX page, or integrate with APEX Human Task components, enabling high interoperability with APEX Workflow components by passing variables, setting actions, and managing user interactions like approvals or data entry.

**Script Task:** Allows running PL/SQL scripts to perform necessary logic or database operations within the process. Emphasizes using stored procedures for efficiency and reusability.

**Service Task:** Describes service interactions such as using Gen AI to make recommendations or draft documents, sending emails and running PL/SQL procedures, leveraging APEX Mail Templates for communication tasks.

**Manual Task:** Represents non-automated, human-centric tasks within the process workflow that are not directly managed by the system, illustrating their behavior akin to standard tasks in earlier software versions.

**Send and Receive Task:** Facilitates message exchanges between different process instances, enabling inter-process communication modeled through message flows.

**Business Rule Task:** Integrates machine learning models or credit scoring logic through stored SQL Models or PL/SQL scripts for decision-making tasks within the business process.

**Annotations:** The model is extensively annotated with educational tips to guide users on how to configure each task type, emphasizing best practices for implementing executable workflows in APEX.

**Target Audience:**  
This tutorial is aimed at business analysts, process designers, and APEX developers interested in integrating business logic and automation into workflows using the Flows for APEX platform.

**Version:**  
Leveraging features from the latest Flows for APEX version, this tutorial incorporates the newest functionalities available to users for effective workflow management and task execution.

This comprehensive demonstration of task types within a business process offers valuable insights for optimizing and designing efficient workflows ready for digital transformation.',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
