declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="22.1.0">]'
      ,q'[  <bpmn:process id="Process_0rxermh" isExecutable="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Consulting.]'
      ,q'[twitter: @FlowquestR</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_07kduq4" name="Start">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:onEvent>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Originator</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>coalesce  ( sys_context(&apos;apex$session&apos;,&apos;app_user&apos;) ]'
      ,q'[                        , sys_context(&apos;userenv&apos;,&apos;os_user&apos;)]'
      ,q'[                        , sys_context(&apos;userenv&apos;,&apos;session_user&apos;))</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:onEvent>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:outgoing>Flow_1mu28br</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0f3qzi7" name="Intro">]'
      ,q'[      <bpmn:incoming>Flow_1mu28br</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_18wa8fy</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1mu28br" sourceRef="Event_07kduq4" targetRef="Activity_0f3qzi7"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_18wa8fy" sourceRef="Activity_0f3qzi7" targetRef="Gateway_Split"/>]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_Split" name="Split">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeSplit>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Gateway_Split:route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>Flow_A:Flow_C</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeSplit>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_18wa8fy</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_A</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_B</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_C</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_07qs6zg" name="A">]'
      ,q'[      <bpmn:incoming>Flow_A</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0v2gxnx</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_A" name="Path A" sourceRef="Gateway_Split" targetRef="Activity_07qs6zg"/>]'
      ,q'[    <bpmn:task id="Activity_1ncqgha" name="B">]'
      ,q'[      <bpmn:incoming>Flow_B</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12ant4j</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_B" name="Path B" sourceRef="Gateway_Split" targetRef="Activity_1ncqgha"/>]'
      ,q'[    <bpmn:task id="Activity_04g7z25" name="C">]'
      ,q'[      <bpmn:incoming>Flow_C</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0q16wkh</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_C" name="Path C" sourceRef="Gateway_Split" targetRef="Activity_04g7z25"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0v2gxnx" sourceRef="Activity_07qs6zg" targetRef="Gateway_Merge"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12ant4j" sourceRef="Activity_1ncqgha" targetRef="Gateway_Merge"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0q16wkh" sourceRef="Activity_04g7z25" targetRef="Gateway_Merge"/>]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_Merge" name="Merge">]'
      ,q'[      <bpmn:incoming>Flow_0v2gxnx</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_12ant4j</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0q16wkh</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1umd44r</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_Check_EMP_DEPT" name="Check if EMP/DEPT exists">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EMP_DEPT_exists</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlFunctionBody</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>declare]'
      ,q'[  l_table varchar2(30);]'
      ,q'[begin]'
      ,q'[  select table_name into l_table from user_tables where table_name = &apos;EMP&apos;;]'
      ,q'[     return &apos;yes&apos;;]'
      ,q'[exception]'
      ,q'[  when no_data_found then]'
      ,q'[    return &apos;no&apos;;]'
      ,q'[  when others then ]'
      ,q'[   return &apos;some other problem&apos;;]'
      ,q'[end;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1umd44r</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02gbfxv</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1umd44r" sourceRef="Gateway_Merge" targetRef="Activity_Check_EMP_DEPT"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02gbfxv" sourceRef="Activity_Check_EMP_DEPT" targetRef="Gateway_Split2"/>]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split2" name="Split for Expression Types">]'
      ,q'[      <bpmn:incoming>Flow_02gbfxv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1lf75u4</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0n99kf7</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_09wlg86</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_Static" name="Static Assignment">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Static_before</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>This gets set to your Static String Content Before the Task</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Static_After</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>And this one gets set after the task completes.</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1lf75u4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12jbalk</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1lf75u4" sourceRef="Gateway_Split2" targetRef="Activity_Static"/>]'
      ,q'[    <bpmn:task id="Activity_Copy" name="Copy of another Process Variable">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>BeforeTask_CopyofEMP_DEPT_route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>processVariable</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>EMP_DEPT_exists</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0n99kf7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_048t0de</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0n99kf7" sourceRef="Gateway_Split2" targetRef="Activity_Copy"/>]'
      ,q'[    <bpmn:task id="Activity_SQLSingle" name="Single SQL Query">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>KingJob</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQuerySingle</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select job]'
      ,q'[from emp]'
      ,q'[where ename = &apos;KING&apos;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>NoDataFoundItem</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQuerySingle</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select job]'
      ,q'[from emp]'
      ,q'[where ename = &apos;Fred&apos;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1ncsvvk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0uhb1gg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_SQLMulti" name="Colon Delimited SQL Query">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>SALESstaff</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[join dept on dept.deptno = emp.deptno]'
      ,q'[where dname = &apos;SALES&apos;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>NoDataResult</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 60</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_19owlyu</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_11xbqtl</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_Expression" name="expression">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>expression_number</apex:varName>]'
      ,q'[            <apex:varDataType>NUMBER</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>7 * 6</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>this_month</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>to_char(sysdate,&apos;Month&apos;)</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0h2z2w4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0v3onte</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:exclusiveGateway id="EMP_DEPT_exists" name="EMP and DEPT Exist?">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeSplit>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EMP_DEPT_exists:route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>processVariable</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>EMP_DEPT_exists</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeSplit>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_09wlg86</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>yes</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>no</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_09wlg86" sourceRef="Gateway_Split2" targetRef="EMP_DEPT_exists"/>]'
      ,q'[    <bpmn:sequenceFlow id="yes" name="yes" sourceRef="EMP_DEPT_exists" targetRef="Gateway_Split_EMP_exists"/>]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split_EMP_exists" name="Paths using EMP">]'
      ,q'[      <bpmn:incoming>yes</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ncsvvk</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_19owlyu</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0h2z2w4</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_19qdo14</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ncsvvk" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_SQLSingle"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_19owlyu" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_SQLMulti"/>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0h2z2w4" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_Expression"/>]'
      ,q'[    <bpmn:task id="Activity_FuncBody" name="function body">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>BeforeTask_FuncBody</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlFunctionBody</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>declare]'
      ,q'[  l_month varchar2(20);]'
      ,q'[begin]'
      ,q'[  l_month := to_char( to_date(&apos;24-12-1970&apos;,&apos;DD-MM-YYYY&apos;) , &apos;MM&apos;);]'
      ,q'[ return l_month;]'
      ,q'[end;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_19qdo14</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0494hmn</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_19qdo14" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_FuncBody"/>]'
      ,q'[    <bpmn:endEvent id="Event_0sttahj" name="Static End">]'
      ,q'[      <bpmn:incoming>Flow_12jbalk</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12jbalk" sourceRef="Activity_Static" targetRef="Event_0sttahj"/>]'
      ,q'[    <bpmn:endEvent id="Event_1323y7h" name="Copy End">]'
      ,q'[      <bpmn:incoming>Flow_048t0de</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_048t0de" sourceRef="Activity_Copy" targetRef="Event_1323y7h"/>]'
      ,q'[    <bpmn:endEvent id="Event_0yhvzko" name="SQL End">]'
      ,q'[      <bpmn:incoming>Flow_0uhb1gg</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0uhb1gg" sourceRef="Activity_SQLSingle" targetRef="Event_0yhvzko"/>]'
      ,q'[    <bpmn:endEvent id="Event_0nmox7s" name="SQL Multi End">]'
      ,q'[      <bpmn:incoming>Flow_11xbqtl</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_11xbqtl" sourceRef="Activity_SQLMulti" targetRef="Event_0nmox7s"/>]'
      ,q'[    <bpmn:endEvent id="Event_0mmc47q" name="Expression End">]'
      ,q'[      <bpmn:incoming>Flow_0v3onte</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0v3onte" sourceRef="Activity_Expression" targetRef="Event_0mmc47q"/>]'
      ,q'[    <bpmn:endEvent id="Event_1sjraqb" name="Function Body End">]'
      ,q'[      <bpmn:incoming>Flow_0494hmn</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0494hmn" sourceRef="Activity_FuncBody" targetRef="Event_1sjraqb"/>]'
      ,q'[    <bpmn:endEvent id="Event_1g6u9dx" name="No EMP/DEPT End">]'
      ,q'[      <bpmn:incoming>no</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="no" name="no" sourceRef="EMP_DEPT_exists" targetRef="Event_1g6u9dx"/>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0saz0u3">]'
      ,q'[      <bpmn:text>So you can set the routing instruction in a declarative variable expression, now defined inside the gateway definition in the model - rather than by a scriptTask.  Click in this gateway, then look at the Variables tab in the properties panel.]'
      ,q'[You can see that the routing instruction is set up in a &apos;Before Split&apos; expression set to route the process to Task A and Task C.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1njps2n" sourceRef="Gateway_Split" targetRef="TextAnnotation_0saz0u3"/>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0hdt28j">]'
      ,q'[      <bpmn:text>This tutorial introduces Declarative Variable Expressions, new in V21.1]'
      ,q'[]'
      ,q'[Each object in the Flow diagram can set a group of Process Variables before and after* it executes - so you can use this to keep track of process state, set gateway routing variables, hand keep track of things like who started the process, when you need it to finish, its priority or sensitivity, as well as run counters or other control variables.]'
      ,q'[]'
      ,q'[Variable Expressions can set process variables to static values, copy another variable, do a SQL query, evaluate an expression or a PL/SL function body.]'
      ,q'[]'
      ,q'[This tutorial works best if you have the standard EMP &amp; DEPT tables installed in your workspace - but you can see how we test whether they are there before running the parts of the model that rely on them.]'
      ,q'[]'
      ,q'[This tutorial runs through the key features.  Variable expression definitions are shown in the &apos;Variables&apos; tab of the properties panel.]'
      ,q'[]'
      ,q'[* Task objects (task, script task, user task, etc) can have expressions that execute BEFORE TASK and AFTER TASK.]'
      ,q'[Event Objects (Start, End, Intermediate Throws and Catches, Boundary Events) ON EVENT and sometimes BEFORE EVENT.]'
      ,q'[Gateway Objects have expressions that execute BEFORE SPLIT and AFTER MERGE, depending upon the gateway usage.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1nkd87f" sourceRef="Activity_0f3qzi7" targetRef="TextAnnotation_0hdt28j"/>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_04rgdnn">]'
      ,q'[      <bpmn:text>Use your start event to initialise any standard variables that you want to use for all of your running instances...]'
      ,q'[]'
      ,q'[We set &apos;Originator&apos; here to your userid...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0tqwtb7" sourceRef="Event_07kduq4" targetRef="TextAnnotation_04rgdnn"/>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0y91707">]'
      ,q'[      <bpmn:text>This executes a function body, returning &apos;yes&apos; if EMP exists in your workspace, and &apos;no&apos; if it doesn&apos;t -- as a before task activity. ]'
      ,q'[]'
      ,q'[This is then used to set the routing for the &apos;EMP and DEPT exist?&apos; gateway 2 steps later...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0vlxnu9" sourceRef="Activity_Check_EMP_DEPT" targetRef="TextAnnotation_0y91707"/>]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0rxermh">]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0m65uty_di" bpmnElement="no">]'
      ,q'[        <di:waypoint x="1230" y="635"/>]'
      ,q'[        <di:waypoint x="1230" y="1110"/>]'
      ,q'[        <di:waypoint x="1642" y="1110"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1239" y="870" width="13" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0494hmn_di" bpmnElement="Flow_0494hmn">]'
      ,q'[        <di:waypoint x="1540" y="980"/>]'
      ,q'[        <di:waypoint x="1642" y="980"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0v3onte_di" bpmnElement="Flow_0v3onte">]'
      ,q'[        <di:waypoint x="1540" y="870"/>]'
      ,q'[        <di:waypoint x="1642" y="870"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_11xbqtl_di" bpmnElement="Flow_11xbqtl">]'
      ,q'[        <di:waypoint x="1540" y="740"/>]'
      ,q'[        <di:waypoint x="1642" y="740"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0uhb1gg_di" bpmnElement="Flow_0uhb1gg">]'
      ,q'[        <di:waypoint x="1540" y="610"/>]'
      ,q'[        <di:waypoint x="1642" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_048t0de_di" bpmnElement="Flow_048t0de">]'
      ,q'[        <di:waypoint x="1540" y="480"/>]'
      ,q'[        <di:waypoint x="1642" y="480"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12jbalk_di" bpmnElement="Flow_12jbalk">]'
      ,q'[        <di:waypoint x="1540" y="340"/>]'
      ,q'[        <di:waypoint x="1642" y="340"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_19qdo14_di" bpmnElement="Flow_19qdo14">]'
      ,q'[        <di:waypoint x="1320" y="635"/>]'
      ,q'[        <di:waypoint x="1320" y="980"/>]'
      ,q'[        <di:waypoint x="1440" y="980"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0h2z2w4_di" bpmnElement="Flow_0h2z2w4">]'
      ,q'[        <di:waypoint x="1320" y="635"/>]'
      ,q'[        <di:waypoint x="1320" y="870"/>]'
      ,q'[        <di:waypoint x="1440" y="870"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_19owlyu_di" bpmnElement="Flow_19owlyu">]'
      ,q'[        <di:waypoint x="1320" y="635"/>]'
      ,q'[        <di:waypoint x="1320" y="740"/>]'
      ,q'[        <di:waypoint x="1440" y="740"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ncsvvk_di" bpmnElement="Flow_1ncsvvk">]'
      ,q'[        <di:waypoint x="1345" y="610"/>]'
      ,q'[        <di:waypoint x="1440" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ndh330_di" bpmnElement="yes">]'
      ,q'[        <di:waypoint x="1255" y="610"/>]'
      ,q'[        <di:waypoint x="1295" y="610"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1266" y="592" width="18" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_09wlg86_di" bpmnElement="Flow_09wlg86">]'
      ,q'[        <di:waypoint x="1165" y="610"/>]'
      ,q'[        <di:waypoint x="1205" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0n99kf7_di" bpmnElement="Flow_0n99kf7">]'
      ,q'[        <di:waypoint x="1140" y="585"/>]'
      ,q'[        <di:waypoint x="1140" y="480"/>]'
      ,q'[        <di:waypoint x="1440" y="480"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1lf75u4_di" bpmnElement="Flow_1lf75u4">]'
      ,q'[        <di:waypoint x="1140" y="585"/>]'
      ,q'[        <di:waypoint x="1140" y="340"/>]'
      ,q'[        <di:waypoint x="1440" y="340"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02gbfxv_di" bpmnElement="Flow_02gbfxv">]'
      ,q'[        <di:waypoint x="1060" y="610"/>]'
      ,q'[        <di:waypoint x="1115" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1umd44r_di" bpmnElement="Flow_1umd44r">]'
      ,q'[        <di:waypoint x="875" y="610"/>]'
      ,q'[        <di:waypoint x="960" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0q16wkh_di" bpmnElement="Flow_0q16wkh">]'
      ,q'[        <di:waypoint x="740" y="720"/>]'
      ,q'[        <di:waypoint x="850" y="720"/>]'
      ,q'[        <di:waypoint x="850" y="635"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12ant4j_di" bpmnElement="Flow_12ant4j">]'
      ,q'[        <di:waypoint x="740" y="610"/>]'
      ,q'[        <di:waypoint x="825" y="610"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0v2gxnx_di" bpmnElement="Flow_0v2gxnx">]'
      ,q'[        <di:waypoint x="740" y="500"/>]'
      ,q'[        <di:waypoint x="850" y="500"/>]'
      ,q'[        <di:waypoint x="850" y="585"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ztr3iy_di" bpmnElement="Flow_C">]'
      ,q'[        <di:waypoint x="510" y="525"/>]'
      ,q'[        <di:waypoint x="510" y="720"/>]'
      ,q'[        <di:waypoint x="640" y="720"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="542" y="693" width="34" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_045akdd_di" bpmnElement="Flow_B">]'
      ,q'[        <di:waypoint x="510" y="525"/>]'
      ,q'[        <di:waypoint x="510" y="610"/>]'
      ,q'[        <di:waypoint x="640" y="610"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="541" y="583" width="33" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0my1j3h_di" bpmnElement="Flow_A">]'
      ,q'[        <di:waypoint x="535" y="500"/>]'
      ,q'[        <di:waypoint x="640" y="500"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="573" y="482" width="34" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_18wa8fy_di" bpmnElement="Flow_18wa8fy">]'
      ,q'[        <di:waypoint x="430" y="500"/>]'
      ,q'[        <di:waypoint x="485" y="500"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mu28br_di" bpmnElement="Flow_1mu28br">]'
      ,q'[        <di:waypoint x="278" y="500"/>]'
      ,q'[        <di:waypoint x="330" y="500"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Event_07kduq4_di" bpmnElement="Event_07kduq4">]'
      ,q'[        <dc:Bounds x="242" y="482" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="248" y="525" width="24" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0f3qzi7_di" bpmnElement="Activity_0f3qzi7">]'
      ,q'[        <dc:Bounds x="330" y="460" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0befb5k_di" bpmnElement="Gateway_Split">]'
      ,q'[        <dc:Bounds x="485" y="475" width="50" height="50"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="500" y="445" width="22" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07qs6zg_di" bpmnElement="Activity_07qs6zg">]'
      ,q'[        <dc:Bounds x="640" y="460" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ncqgha_di" bpmnElement="Activity_1ncqgha">]'
      ,q'[        <dc:Bounds x="640" y="570" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_04g7z25_di" bpmnElement="Activity_04g7z25">]'
      ,q'[        <dc:Bounds x="640" y="680" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0xexztv_di" bpmnElement="Gateway_Merge">]'
      ,q'[        <dc:Bounds x="825" y="585" width="50" height="50"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="884" y="573" width="32" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ymetlw_di" bpmnElement="Activity_Check_EMP_DEPT">]'
      ,q'[        <dc:Bounds x="960" y="570" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_03bnkja_di" bpmnElement="Gateway_Split2">]'
      ,q'[        <dc:Bounds x="1115" y="585" width="50" height="50"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1098" y="642" width="87" height="27"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07hns5v_di" bpmnElement="Activity_Static">]'
      ,q'[        <dc:Bounds x="1440" y="300" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_17wunpk_di" bpmnElement="Activity_Copy">]'
      ,q'[        <dc:Bounds x="1440" y="440" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ikwbj4_di" bpmnElement="Activity_SQLSingle">]'
      ,q'[        <dc:Bounds x="1440" y="570" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ov9j10_di" bpmnElement="Activity_SQLMulti">]'
      ,q'[        <dc:Bounds x="1440" y="700" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1s8xbrn_di" bpmnElement="Activity_Expression">]'
      ,q'[        <dc:Bounds x="1440" y="830" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0qmyt5q_di" bpmnElement="EMP_DEPT_exists" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1205" y="585" width="50" height="50"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1192" y="555" width="78" height="27"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1meehlq_di" bpmnElement="Gateway_Split_EMP_exists">]'
      ,q'[        <dc:Bounds x="1295" y="585" width="50" height="50"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1317" y="562" width="85" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ltt770_di" bpmnElement="Activity_FuncBody">]'
      ,q'[        <dc:Bounds x="1440" y="940" width="100" height="80"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0sttahj_di" bpmnElement="Event_0sttahj">]'
      ,q'[        <dc:Bounds x="1642" y="322" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1635" y="365" width="51" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1323y7h_di" bpmnElement="Event_1323y7h">]'
      ,q'[        <dc:Bounds x="1642" y="462" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1636" y="505" width="49" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0yhvzko_di" bpmnElement="Event_0yhvzko">]'
      ,q'[        <dc:Bounds x="1642" y="592" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1638" y="635" width="45" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nmox7s_di" bpmnElement="Event_0nmox7s">]'
      ,q'[        <dc:Bounds x="1642" y="722" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1625" y="765" width="71" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0mmc47q_di" bpmnElement="Event_0mmc47q">]'
      ,q'[        <dc:Bounds x="1642" y="852" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1622" y="895" width="77" height="14"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1sjraqb_di" bpmnElement="Event_1sjraqb">]'
      ,q'[        <dc:Bounds x="1642" y="962" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1625" y="1005" width="71" height="27"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1g6u9dx_di" bpmnElement="Event_1g6u9dx">]'
      ,q'[        <dc:Bounds x="1642" y="1092" width="36" height="36"/>]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1623" y="1135" width="74" height="27"/>]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0saz0u3_di" bpmnElement="TextAnnotation_0saz0u3">]'
      ,q'[        <dc:Bounds x="510" y="260" width="520" height="98"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0hdt28j_di" bpmnElement="TextAnnotation_0hdt28j">]'
      ,q'[        <dc:Bounds x="330" y="-60" width="760" height="270"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_04rgdnn_di" bpmnElement="TextAnnotation_04rgdnn">]'
      ,q'[        <dc:Bounds x="260" y="595" width="189.99231763033313" height="111"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0y91707_di" bpmnElement="TextAnnotation_0y91707">]'
      ,q'[        <dc:Bounds x="820" y="855" width="345.0000305175781" height="91.99652862548828"/>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1njps2n_di" bpmnElement="Association_1njps2n">]'
      ,q'[        <di:waypoint x="515" y="480"/>]'
      ,q'[        <di:waypoint x="542" y="358"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1nkd87f_di" bpmnElement="Association_1nkd87f">]'
      ,q'[        <di:waypoint x="379" y="460"/>]'
      ,q'[        <di:waypoint x="374" y="210"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0tqwtb7_di" bpmnElement="Association_0tqwtb7">]'
      ,q'[        <di:waypoint x="267" y="516"/>]'
      ,q'[        <di:waypoint x="303" y="595"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0vlxnu9_di" bpmnElement="Association_0vlxnu9">]'
      ,q'[        <di:waypoint x="988" y="650"/>]'
      ,q'[        <di:waypoint x="878" y="855"/>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 3a - Setting Process Variables from your Model',
    pi_dgrm_version => '22.2',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
