declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="25.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial7f" name="A7f - Sequential Iterations with SubProcesses and Completions" isExecutable="true" apex:isStartable="true" apex:minLoggingLevel="0" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_Start" name="Start">]'
      ,q'[      <bpmn:outgoing>Flow_00jstgp</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_PreSplit" name="Pre-Split">]'
      ,q'[      <bpmn:incoming>Flow_00jstgp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1i6fc42</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_00jstgp" sourceRef="Event_Start" targetRef="Activity_PreSplit" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1i6fc42" sourceRef="Activity_PreSplit" targetRef="Gateway_Split" />]'
      ,q'[    <bpmn:task id="Activity_A1" name="A1- List">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpList</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1ngmguv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0xh1wjg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ngmguv" sourceRef="Gateway_Split" targetRef="Activity_A1" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0xh1wjg" sourceRef="Activity_A1" targetRef="Activity_A2" />]'
      ,q'[    <bpmn:task id="Activity_A3" name="A3">]'
      ,q'[      <bpmn:incoming>Flow_1v6vync</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0emop6i</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1v6vync" sourceRef="Activity_A2" targetRef="Activity_A3" />]'
      ,q'[    <bpmn:endEvent id="Event_AEnd" name="AEnd">]'
      ,q'[      <bpmn:incoming>Flow_0emop6i</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0emop6i" sourceRef="Activity_A3" targetRef="Event_AEnd" />]'
      ,q'[    <bpmn:task id="Activity_B1" name="B1 - Array">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpArray</apex:varName>]'
      ,q'[            <apex:varDataType>JSON</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryArray</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename, empno]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_02y11qo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mg0jl9</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_B3" name="B3">]'
      ,q'[      <bpmn:incoming>Flow_0m8ne0j</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0cv0t6o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_BEnd" name="BEnd">]'
      ,q'[      <bpmn:incoming>Flow_0cv0t6o</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mg0jl9" sourceRef="Activity_B1" targetRef="Activity_B2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0m8ne0j" sourceRef="Activity_B2" targetRef="Activity_B3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0cv0t6o" sourceRef="Activity_B3" targetRef="Event_BEnd" />]'
      ,q'[    <bpmn:task id="Activity_C1" name="C1 - Query">]'
      ,q'[      <bpmn:incoming>Flow_1a4xxmd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1f9kxmo</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_C3" name="C3">]'
      ,q'[      <bpmn:incoming>Flow_1dcufu5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0opd4zr</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_CEnd" name="CEnd">]'
      ,q'[      <bpmn:incoming>Flow_0opd4zr</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1f9kxmo" sourceRef="Activity_C1" targetRef="Activity_C2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1dcufu5" sourceRef="Activity_C2" targetRef="Activity_C3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0opd4zr" sourceRef="Activity_C3" targetRef="Event_CEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02y11qo" sourceRef="Gateway_Split" targetRef="Activity_B1" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1a4xxmd" sourceRef="Gateway_Split" targetRef="Activity_C1" apex:sequence="30" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split" name="Split">]'
      ,q'[      <bpmn:incoming>Flow_1i6fc42</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ngmguv</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_02y11qo</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1a4xxmd</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1qgior9</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:subProcess id="Activity_A2" name="A2">]'
      ,q'[      <bpmn:incoming>Flow_0xh1wjg</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1v6vync</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics isSequential="true">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:description>Instance &amp;LOOP_COUNTER. : Employee &amp;ENAME.</apex:description>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableList</apex:expressionType>]'
      ,q'[            <apex:expression>EmpList</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayA</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_A2Start" name="A2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_0xcd6m0</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_A2a" name="A2a">]'
      ,q'[        <bpmn:incoming>Flow_0xcd6m0</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1alq874</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0xcd6m0" sourceRef="Event_A2Start" targetRef="Activity_A2a" />]'
      ,q'[      <bpmn:task id="Activity_A2b" name="A2b">]'
      ,q'[        <bpmn:incoming>Flow_1alq874</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0cvzkj3</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1alq874" sourceRef="Activity_A2a" targetRef="Activity_A2b" />]'
      ,q'[      <bpmn:endEvent id="Event_A2End" name="A2 End">]'
      ,q'[        <bpmn:incoming>Flow_0cvzkj3</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0cvzkj3" sourceRef="Activity_A2b" targetRef="Event_A2End" />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:subProcess id="Activity_B2" name="B2">]'
      ,q'[      <bpmn:incoming>Flow_0mg0jl9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0m8ne0j</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:description>Instance &amp;LOOP_COUNTER. : Employee &amp;ENAME. (&amp;EMPNO.).</apex:description>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>EmpArray</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayB</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_B2Start" name="B2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_0pvftkr</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_B2a" name="B2a">]'
      ,q'[        <bpmn:incoming>Flow_0pvftkr</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1l3p7hs</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0pvftkr" sourceRef="Event_B2Start" targetRef="Activity_B2a" />]'
      ,q'[      <bpmn:task id="Activity_B2b" name="B2b">]'
      ,q'[        <bpmn:incoming>Flow_1l3p7hs</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0macjlk</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1l3p7hs" sourceRef="Activity_B2a" targetRef="Activity_B2b" />]'
      ,q'[      <bpmn:endEvent id="Event_B2End" name="B2 End">]'
      ,q'[        <bpmn:incoming>Flow_0macjlk</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0macjlk" sourceRef="Activity_B2b" targetRef="Event_B2End" />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:subProcess id="Activity_C2" name="C2">]'
      ,q'[      <bpmn:incoming>Flow_1f9kxmo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1dcufu5</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:description>Instance &amp;LOOP_COUNTER. : Employee &amp;ENAME. (&amp;EMPNO.).</apex:description>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>sqlQueryArray</apex:expressionType>]'
      ,q'[            <apex:expression>select ename, empno]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayC</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt; 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_C2Start" name="C2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_1dcanwo</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_C2a" name="C2a">]'
      ,q'[        <bpmn:incoming>Flow_1dcanwo</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1ot6t0q</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:task id="Activity_C2b" name="C2b">]'
      ,q'[        <bpmn:incoming>Flow_1ot6t0q</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0t5f62e</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:endEvent id="Event_C2End" name="C2 End">]'
      ,q'[        <bpmn:incoming>Flow_0t5f62e</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1dcanwo" sourceRef="Event_C2Start" targetRef="Activity_C2a" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1ot6t0q" sourceRef="Activity_C2a" targetRef="Activity_C2b" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0t5f62e" sourceRef="Activity_C2b" targetRef="Event_C2End" />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:task id="Activity_D1" name="D1 - Loop Query">]'
      ,q'[      <bpmn:incoming>Flow_1qgior9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_01x54dq</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_D3" name="D3">]'
      ,q'[      <bpmn:incoming>Flow_1xv59ld</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1da9m66</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_DEnd" name="DEnd">]'
      ,q'[      <bpmn:incoming>Flow_1da9m66</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:subProcess id="Activity_D2" name="D2">]'
      ,q'[      <bpmn:incoming>Flow_01x54dq</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1xv59ld</bpmn:outgoing>]'
      ,q'[      <bpmn:standardLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:description>Loop &amp;LOOP_COUNTER.</apex:description>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayD</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt; 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:standardLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_D2Start" name="D2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_19abxc6</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_D2a" name="D2a">]'
      ,q'[        <bpmn:incoming>Flow_19abxc6</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1n9349j</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:task id="Activity_D2b" name="D2b">]'
      ,q'[        <bpmn:incoming>Flow_1n9349j</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0130kla</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:endEvent id="Event_D2End" name="D2 End">]'
      ,q'[        <bpmn:incoming>Flow_0130kla</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_19abxc6" sourceRef="Event_D2Start" targetRef="Activity_D2a" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1n9349j" sourceRef="Activity_D2a" targetRef="Activity_D2b" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0130kla" sourceRef="Activity_D2b" targetRef="Event_D2End" />]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_01x54dq" sourceRef="Activity_D1" targetRef="Activity_D2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1xv59ld" sourceRef="Activity_D2" targetRef="Activity_D3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1da9m66" sourceRef="Activity_D3" targetRef="Event_DEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1qgior9" sourceRef="Gateway_Split" targetRef="Activity_D1" apex:sequence="40" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0i9q5wo">]'
      ,q'[      <bpmn:text>emplist = select name ]'
      ,q'[from emp]'
      ,q'[where dept no = 20]'
      ,q'[]'
      ,q'[SMITH:JONES:SCOTT:ADAMS:FORD</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_050cm0v" sourceRef="Activity_A1" targetRef="TextAnnotation_0i9q5wo" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_06yrhts">]'
      ,q'[      <bpmn:text>iterate over emplist until 3 completed</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0bi9txm" sourceRef="Activity_A2" targetRef="TextAnnotation_06yrhts" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1dh1ysa">]'
      ,q'[      <bpmn:text>emparray = select name, empno from amp where dept no = 20]'
      ,q'[]'
      ,q'[[{"name":"SMITH","EMPNO":7369},]'
      ,q'[{"name":"JONES","EMPNO":7566}]'
      ,q'[...]</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0iayq8p" sourceRef="Activity_B1" targetRef="TextAnnotation_1dh1ysa" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1tdwshf">]'
      ,q'[      <bpmn:text>iterate over emparray until 3 completed</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1cqii1i" sourceRef="Activity_B2" targetRef="TextAnnotation_1tdwshf" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0ehpw4n">]'
      ,q'[      <bpmn:text>iterate over query until 3 completed]'
      ,q'[]'
      ,q'[select name, empno ]'
      ,q'[from emp]'
      ,q'[where dept no = 20</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0hlx4e9" sourceRef="Activity_C2" targetRef="TextAnnotation_0ehpw4n" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1dxh1gv">]'
      ,q'[      <bpmn:text>loop until 3 completed</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_03r5hig" sourceRef="Activity_D2" targetRef="TextAnnotation_1dxh1gv" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0hgci3t">]'
      ,q'[      <bpmn:text>This time, we're iterating sub processes, rather than]'
      ,q'[tasks.   But the idea is pretty similar.]'
      ,q'[]'
      ,q'[Again, this requires the Enterprise Edition.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0jy3m4z" associationDirection="None" sourceRef="Activity_PreSplit" targetRef="TextAnnotation_0hgci3t" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1h4yyjp">]'
      ,q'[      <bpmn:text>Hint:  If you are struggling to remember which is parallel &amp; which is sequential.... paraLLeL has three l's in it, which looks a bit like the three vertical lines!]'
      ,q'[Now you won't forget...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0iaq5us" associationDirection="None" sourceRef="Event_Start" targetRef="TextAnnotation_1h4yyjp" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial7f">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nj6ios_di" bpmnElement="Event_Start">]'
      ,q'[        <dc:Bounds x="242" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="248" y="318" width="24" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1v4awr2_di" bpmnElement="Activity_PreSplit">]'
      ,q'[        <dc:Bounds x="330" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_06o8whk_di" bpmnElement="Activity_A1" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="600" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1m1j7lz_di" bpmnElement="Activity_A3" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="920" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0xoy17b_di" bpmnElement="Event_AEnd" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1082" y="124" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1088" y="167" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0lsnoc7" bpmnElement="Activity_B1" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="600" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_12yruu2" bpmnElement="Activity_B3" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="920" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_10192cq" bpmnElement="Event_BEnd" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1082" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="385" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0dwx7ia" bpmnElement="Activity_C1" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="600" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1s29z1t" bpmnElement="Activity_C3" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="920" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1x8vuch" bpmnElement="Event_CEnd" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="1082" y="562" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="605" width="28" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1b1nb8o_di" bpmnElement="Gateway_Split" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="495" y="335" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="489" y="313" width="22" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_109mvy1_di" bpmnElement="Activity_A2" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="760" y="102" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1mmigx9_di" bpmnElement="Activity_B2" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="760" y="320" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1xa0r7w_di" bpmnElement="Activity_C2" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="760" y="540" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0gpln1r" bpmnElement="Activity_D1" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="600" y="760" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_14d44fs" bpmnElement="Activity_D3" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="920" y="760" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_144ziin" bpmnElement="Event_DEnd" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="1082" y="782" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="825" width="28" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1t67ock" bpmnElement="Activity_D2" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="760" y="760" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0i9q5wo_di" bpmnElement="TextAnnotation_0i9q5wo">]'
      ,q'[        <dc:Bounds x="570" y="-28" width="280" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_06yrhts_di" bpmnElement="TextAnnotation_06yrhts">]'
      ,q'[        <dc:Bounds x="860" y="22" width="160" height="39" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1dh1ysa_di" bpmnElement="TextAnnotation_1dh1ysa">]'
      ,q'[        <dc:Bounds x="570" y="201" width="207" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1tdwshf_di" bpmnElement="TextAnnotation_1tdwshf">]'
      ,q'[        <dc:Bounds x="860" y="231" width="160" height="39" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0ehpw4n_di" bpmnElement="TextAnnotation_0ehpw4n">]'
      ,q'[        <dc:Bounds x="850" y="430" width="160" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0ghoryq" bpmnElement="TextAnnotation_1dxh1gv">]'
      ,q'[        <dc:Bounds x="850" y="650" width="160" height="30" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0hgci3t_di" bpmnElement="TextAnnotation_0hgci3t">]'
      ,q'[        <dc:Bounds x="190" y="124" width="339.99094645182294" height="66.66667090521918" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1h4yyjp_di" bpmnElement="TextAnnotation_1h4yyjp">]'
      ,q'[        <dc:Bounds x="90" y="470" width="220" height="128" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_00jstgp_di" bpmnElement="Flow_00jstgp">]'
      ,q'[        <di:waypoint x="278" y="360" />]'
      ,q'[        <di:waypoint x="330" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1i6fc42_di" bpmnElement="Flow_1i6fc42">]'
      ,q'[        <di:waypoint x="430" y="360" />]'
      ,q'[        <di:waypoint x="495" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ngmguv_di" bpmnElement="Flow_1ngmguv">]'
      ,q'[        <di:waypoint x="520" y="335" />]'
      ,q'[        <di:waypoint x="520" y="142" />]'
      ,q'[        <di:waypoint x="600" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xh1wjg_di" bpmnElement="Flow_0xh1wjg">]'
      ,q'[        <di:waypoint x="700" y="142" />]'
      ,q'[        <di:waypoint x="760" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1v6vync_di" bpmnElement="Flow_1v6vync">]'
      ,q'[        <di:waypoint x="860" y="142" />]'
      ,q'[        <di:waypoint x="920" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0emop6i_di" bpmnElement="Flow_0emop6i">]'
      ,q'[        <di:waypoint x="1020" y="142" />]'
      ,q'[        <di:waypoint x="1082" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1fgochk" bpmnElement="Flow_0mg0jl9">]'
      ,q'[        <di:waypoint x="700" y="360" />]'
      ,q'[        <di:waypoint x="760" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1ipi0cl" bpmnElement="Flow_0m8ne0j">]'
      ,q'[        <di:waypoint x="860" y="360" />]'
      ,q'[        <di:waypoint x="920" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1j2m5si" bpmnElement="Flow_0cv0t6o">]'
      ,q'[        <di:waypoint x="1020" y="360" />]'
      ,q'[        <di:waypoint x="1082" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_04kv3hq" bpmnElement="Flow_1f9kxmo">]'
      ,q'[        <di:waypoint x="700" y="580" />]'
      ,q'[        <di:waypoint x="760" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0pgg5lp" bpmnElement="Flow_1dcufu5">]'
      ,q'[        <di:waypoint x="860" y="580" />]'
      ,q'[        <di:waypoint x="920" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_13nxtw3" bpmnElement="Flow_0opd4zr">]'
      ,q'[        <di:waypoint x="1020" y="580" />]'
      ,q'[        <di:waypoint x="1082" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02y11qo_di" bpmnElement="Flow_02y11qo">]'
      ,q'[        <di:waypoint x="545" y="360" />]'
      ,q'[        <di:waypoint x="600" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1a4xxmd_di" bpmnElement="Flow_1a4xxmd">]'
      ,q'[        <di:waypoint x="520" y="385" />]'
      ,q'[        <di:waypoint x="520" y="580" />]'
      ,q'[        <di:waypoint x="600" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_162qrx2" bpmnElement="Flow_01x54dq">]'
      ,q'[        <di:waypoint x="700" y="800" />]'
      ,q'[        <di:waypoint x="760" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1325uez" bpmnElement="Flow_1xv59ld">]'
      ,q'[        <di:waypoint x="860" y="800" />]'
      ,q'[        <di:waypoint x="920" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0e7p0q5" bpmnElement="Flow_1da9m66">]'
      ,q'[        <di:waypoint x="1020" y="800" />]'
      ,q'[        <di:waypoint x="1082" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1qgior9_di" bpmnElement="Flow_1qgior9">]'
      ,q'[        <di:waypoint x="520" y="385" />]'
      ,q'[        <di:waypoint x="520" y="800" />]'
      ,q'[        <di:waypoint x="600" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_050cm0v_di" bpmnElement="Association_050cm0v">]'
      ,q'[        <di:waypoint x="630" y="102" />]'
      ,q'[        <di:waypoint x="606" y="54" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0bi9txm_di" bpmnElement="Association_0bi9txm">]'
      ,q'[        <di:waypoint x="829" y="102" />]'
      ,q'[        <di:waypoint x="860" y="37" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0iayq8p_di" bpmnElement="Association_0iayq8p">]'
      ,q'[        <di:waypoint x="605" y="322" />]'
      ,q'[        <di:waypoint x="580" y="300" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1cqii1i_di" bpmnElement="Association_1cqii1i">]'
      ,q'[        <di:waypoint x="828" y="320" />]'
      ,q'[        <di:waypoint x="858" y="251" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hlx4e9_di" bpmnElement="Association_0hlx4e9">]'
      ,q'[        <di:waypoint x="823" y="540" />]'
      ,q'[        <di:waypoint x="842" y="478" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0mr2vpy" bpmnElement="Association_03r5hig">]'
      ,q'[        <di:waypoint x="819" y="760" />]'
      ,q'[        <di:waypoint x="842" y="665" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0jy3m4z_di" bpmnElement="Association_0jy3m4z">]'
      ,q'[        <di:waypoint x="330" y="334" />]'
      ,q'[        <di:waypoint x="150" y="240" />]'
      ,q'[        <di:waypoint x="120" y="160" />]'
      ,q'[        <di:waypoint x="190" y="160" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0iaq5us_di" bpmnElement="Association_0iaq5us">]'
      ,q'[        <di:waypoint x="260" y="378" />]'
      ,q'[        <di:waypoint x="260" y="470" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_15ubg12">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0a722e0" bpmnElement="Activity_A2">]'
      ,q'[      <bpmndi:BPMNShape id="Event_03m23u4_di" bpmnElement="Event_A2Start">]'
      ,q'[        <dc:Bounds x="-498" y="-168" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-500" y="-125" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0h2vez0_di" bpmnElement="Activity_A2a" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="-410" y="-190" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_032mmho_di" bpmnElement="Activity_A2b" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="-250" y="-190" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_05xh4ts_di" bpmnElement="Event_A2End">]'
      ,q'[        <dc:Bounds x="-88" y="-168" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-88" y="-125" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xcd6m0_di" bpmnElement="Flow_0xcd6m0">]'
      ,q'[        <di:waypoint x="-462" y="-150" />]'
      ,q'[        <di:waypoint x="-410" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1alq874_di" bpmnElement="Flow_1alq874">]'
      ,q'[        <di:waypoint x="-310" y="-150" />]'
      ,q'[        <di:waypoint x="-250" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0cvzkj3_di" bpmnElement="Flow_0cvzkj3">]'
      ,q'[        <di:waypoint x="-150" y="-150" />]'
      ,q'[        <di:waypoint x="-88" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0872cwf">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_10x527o" bpmnElement="Activity_B2">]'
      ,q'[      <bpmndi:BPMNShape id="Event_03ss5oz_di" bpmnElement="Event_B2Start">]'
      ,q'[        <dc:Bounds x="-438" y="-198" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-440" y="-155" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1lwnb6a_di" bpmnElement="Activity_B2a" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="-350" y="-220" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0knio13_di" bpmnElement="Activity_B2b" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="-190" y="-220" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_06jlt4r_di" bpmnElement="Event_B2End">]'
      ,q'[        <dc:Bounds x="-28" y="-198" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-28" y="-155" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0pvftkr_di" bpmnElement="Flow_0pvftkr">]'
      ,q'[        <di:waypoint x="-402" y="-180" />]'
      ,q'[        <di:waypoint x="-350" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1l3p7hs_di" bpmnElement="Flow_1l3p7hs">]'
      ,q'[        <di:waypoint x="-250" y="-180" />]'
      ,q'[        <di:waypoint x="-190" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0macjlk_di" bpmnElement="Flow_0macjlk">]'
      ,q'[        <di:waypoint x="-90" y="-180" />]'
      ,q'[        <di:waypoint x="-28" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0j6lzkt">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0nkaeke" bpmnElement="Activity_C2">]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_15oxsja" bpmnElement="Event_C2Start">]'
      ,q'[        <dc:Bounds x="-308" y="-158" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-310" y="-115" width="41" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0ftvn1o" bpmnElement="Activity_C2a" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-220" y="-180" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1xikkj1" bpmnElement="Activity_C2b" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-60" y="-180" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1dtzoyy" bpmnElement="Event_C2End">]'
      ,q'[        <dc:Bounds x="102" y="-158" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="102" y="-115" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1q3grve" bpmnElement="Flow_1dcanwo">]'
      ,q'[        <di:waypoint x="-272" y="-140" />]'
      ,q'[        <di:waypoint x="-220" y="-140" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0l3l8oi" bpmnElement="Flow_1ot6t0q">]'
      ,q'[        <di:waypoint x="-120" y="-140" />]'
      ,q'[        <di:waypoint x="-60" y="-140" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0vae546" bpmnElement="Flow_0t5f62e">]'
      ,q'[        <di:waypoint x="40" y="-140" />]'
      ,q'[        <di:waypoint x="102" y="-140" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0l1ty2n">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1fl0smv" bpmnElement="Activity_D2">]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0yofx6o" bpmnElement="Event_D2Start">]'
      ,q'[        <dc:Bounds x="182" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="180" y="225" width="41" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0ued6ad" bpmnElement="Activity_D2a" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="270" y="160" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_12o2sz8" bpmnElement="Activity_D2b" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="430" y="160" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1qp6eop" bpmnElement="Event_D2End">]'
      ,q'[        <dc:Bounds x="592" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="592" y="225" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1a5wirs" bpmnElement="Flow_19abxc6">]'
      ,q'[        <di:waypoint x="218" y="200" />]'
      ,q'[        <di:waypoint x="270" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0nea0zb" bpmnElement="Flow_1n9349j">]'
      ,q'[        <di:waypoint x="370" y="200" />]'
      ,q'[        <di:waypoint x="430" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1ughvqb" bpmnElement="Flow_0130kla">]'
      ,q'[        <di:waypoint x="530" y="200" />]'
      ,q'[        <di:waypoint x="592" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7f - Iterations and Looped Sub Processes',
    pi_dgrm_short_description => 'Flows for APEX BPMN Tutorial - Part 7f - extends multi-instance activities to include sub processes... Again, this requires the Enterprise Edition.',
    pi_dgrm_description => '#### Tutorial Overview

In this tutorial, we will explore how to utilize Flows for APEX to implement multi-instance and looping constructs within subprocesses, enhancing your business process capabilities. This approach is particularly useful for handling repetitive tasks and processing lists or arrays of data efficiently.

#### Process Objective

The goal is to demonstrate a business process where we sequentially iterate over employee data, executing various operations using multiple instances and looping within subprocesses. This setup will enable you to handle large datasets effectively by processing them in manageable, automated chunks.

#### Key Components of the Process

**Start Event:** The process initiates with a "Start" event, serving as the entry point into the workflow.

**Pre-Split Task:** A "Pre-Split" activity performs initial data setup, preparing for downstream operations.

**Parallel Gateway (Split):** This gateway divides the workflow into four distinct, parallel paths (A, B, C, and D), each handling different data processing methods but following a similar iteration strategy.

#### Individual Paths

**Path A - List Processing:**

*   **Objective:** Retrieve and process a list of employee names.
*   **SubProcess (A2):** Implements multi-instance looping over a list obtained via SQL query, terminating after processing three records.

**Path B - Array Processing:**

*   **Objective:** Work with JSON arrays containing employee names and numbers.
*   **SubProcess (B2):** Uses multi-instance looping to iterate over an array structure with a similar completion condition to Path A.

**Path C - Query-Based Processing:**

*   **Objective:** Execute a direct SQL query to fetch and process employee details.
*   **SubProcess (C2):** Engages in query-based iteration, ensuring at least three records are processed before completion.

**Path D - Loop Query Processing:**

*   **Objective:** Perform iterative data retrieval through looping queries.
*   **SubProcess (D2):** Similar looping logic is applied as in other paths, focusing on sequential completeness.

#### Execution and Completion

Each path concludes with an end event indicating the completion of that subprocess. The execution model ensures parallel processing, thereby increasing throughput without compromising on process integrity.

#### Learning Points

*   **Multi-Instance SubProcesses:** Enable processing of multiple data items in parallel or sequence, with shared logic and completion conditions.
*   **Looping Constructs:** Allow repetitive execution of subprocesses until specific criteria are satisfied, adaptable to changing business needs.
*   **Data Handling:** Demonstrates SQL and JSON integration for dynamic data manipulation within workflows.

#### Practical Application

By the end of this tutorial, participants will understand how to design and deploy advanced subprocesses capable of handling repetitive data manipulation tasks efficiently. This methodology not only streamlines operations but also provides a scalable solution suitable for enterprise environments using Flows for APEX.

#### Tips

*   **Parallel vs. Sequential Execution:** Remember that "paraLLeL" has three ''L''s which can be visualized as three parallel lines—a mnemonic to distinguish parallel processing from sequential.
*   **Enterprise Edition Requirements:** Certain features may only be available with the Enterprise Edition, so verify your environment''s capabilities.

Explore this model in your Flows for APEX environment to grasp the power of multi-instance and looping constructs in subprocesses!',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
