declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="23.1.0">]'
      ,q'[  <bpmn:collaboration id="Collaboration_0g9lgkn">]'
      ,q'[    <bpmn:participant id="Participant_0whbbt7" name="OrderingProcess" processRef="Process_1qvz266" />]'
      ,q'[    <bpmn:participant id="Participant_0t5pyah" name="Supplier&#39;s Ordering Process (Empty Pool / black Box) (this is the Process in Tutorial 7b)" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1mhnxug" name="Send Order" sourceRef="Activity_1kiolhv" targetRef="Participant_0t5pyah" />]'
      ,q'[    <bpmn:messageFlow id="Flow_0rbamsj" name="Receive Acknowledement" sourceRef="Participant_0t5pyah" targetRef="Event_Rx_Confirmation" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0xxeo4v">]'
      ,q'[      <bpmn:text>Study this Tutorial before. you run it.]'
      ,q'[]'
      ,q'[Note how the Correlation Keys and Message Names are built using real entity values - rather than using pseudo values like process ID or a GUID to coordinate a transaction across the two processes.]'
      ,q'[]'
      ,q'[The example is a little simplified for understanding.]'
      ,q'[]'
      ,q'[Start this process.  Look at the Process Variables being sent to and from the other process.]'
      ,q'[]'
      ,q'[MessageFlow will become more useful in a future release when we allow a message to start a process, also message catch boundary events to interrupt a subProcess, and message throw end events to signal when a process has completed.  Also the ability to decouple sender and receiver across different workspaces or different servers.  This is just a taster.....</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0is679k" sourceRef="Participant_0t5pyah" targetRef="TextAnnotation_0xxeo4v" />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id="Process_1qvz266">]'
      ,q'[    <bpmn:extensionElements>]'
      ,q'[      <apex:customExtension>{"mytask":"mytaskmessage"}</apex:customExtension>]'
      ,q'[    </bpmn:extensionElements>]'
      ,q'[    <bpmn:laneSet id="LaneSet_1o73f33">]'
      ,q'[      <bpmn:lane id="Lane_1prtuuy" name="Sales" apex:isRole="true" apex:role="SALES">]'
      ,q'[        <bpmn:flowNodeRef>Event_1925gah</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0uij13c</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1kiolhv</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1y3nrel</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_Rx_Confirmation</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1i00eqo</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_0nondgq</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_08bqvjs</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1tpgaxx</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_TimeOut_5m</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[    </bpmn:laneSet>]'
      ,q'[    <bpmn:startEvent id="Event_1925gah">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"mytask":"mytaskmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:outgoing>Flow_1n4muoi</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0uij13c" name="get data">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"mytask":"mytaskmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1n4muoi</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0fewogt</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1n4muoi" sourceRef="Event_1925gah" targetRef="Activity_0uij13c" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0fewogt" sourceRef="Activity_0uij13c" targetRef="Activity_1kiolhv" />]'
      ,q'[    <bpmn:sendTask id="Activity_1kiolhv" name="place order" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:endpoint>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>local</apex:expression>]'
      ,q'[        </apex:endpoint>]'
      ,q'[        <apex:messageName>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>SendPO</apex:expression>]'
      ,q'[        </apex:messageName>]'
      ,q'[        <apex:correlationKey>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>CustomerID</apex:expression>]'
      ,q'[        </apex:correlationKey>]'
      ,q'[        <apex:correlationValue>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>100</apex:expression>]'
      ,q'[        </apex:correlationValue>]'
      ,q'[        <apex:customExtension>{"mySendtask":"mySendtaskmessage"}</apex:customExtension>]'
      ,q'[        <apex:payload>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>BUSINESS_REF</apex:expression>]'
      ,q'[        </apex:payload>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0fewogt</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0rqi2lg</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0rqi2lg" name="MyFlow" sourceRef="Activity_1kiolhv" targetRef="Gateway_1y3nrel" apex:sequence="10">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"test":"seqFlow"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:eventBasedGateway id="Gateway_1y3nrel">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"myEBGtask":"myEBGmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0rqi2lg</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0rkz3tu</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1n3p80m</bpmn:outgoing>]'
      ,q'[    </bpmn:eventBasedGateway>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_Rx_Confirmation" name="Receive Supplier Confirmation" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"myICEtask":"myICEmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0rkz3tu</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_17nxy1b</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0ozlcqv">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>OrderConfirmation</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>PONumber</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[            <apex:expression>BUSINESS_REF</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payloadVariable>SuppliersSORef</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0rkz3tu" sourceRef="Gateway_1y3nrel" targetRef="Event_Rx_Confirmation" />]'
      ,q'[    <bpmn:task id="Activity_1i00eqo" name="A">]'
      ,q'[      <bpmn:incoming>Flow_17nxy1b</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0t46fc2</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_17nxy1b" sourceRef="Event_Rx_Confirmation" targetRef="Activity_1i00eqo" apex:sequence="10">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"mytask":"mytaskmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:endEvent id="Event_0nondgq">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:customExtension>{"myend":"myendmessage"}</apex:customExtension>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0t46fc2</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0t46fc2" sourceRef="Activity_1i00eqo" targetRef="Event_0nondgq" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1n3p80m" sourceRef="Gateway_1y3nrel" targetRef="Event_TimeOut_5m" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0birqg8" sourceRef="Event_TimeOut_5m" targetRef="Activity_1tpgaxx" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1cj17tx" sourceRef="Activity_1tpgaxx" targetRef="Event_08bqvjs" />]'
      ,q'[    <bpmn:endEvent id="Event_08bqvjs">]'
      ,q'[      <bpmn:incoming>Flow_1cj17tx</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:task id="Activity_1tpgaxx" name="B">]'
      ,q'[      <bpmn:incoming>Flow_0birqg8</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1cj17tx</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_TimeOut_5m" name="TimeOut (5m)">]'
      ,q'[      <bpmn:incoming>Flow_1n3p80m</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0birqg8</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0vyum3w">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT5M</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1qij4jn">]'
      ,q'[      <bpmn:text>Sends the Order to the Supplier (in Tutorial 7b) - who must be already waiting for an order.]'
      ,q'[]'
      ,q'[The Message sends the Customer Number as a correlation key, with the Purchase Order in the Payload]'
      ,q'[]'
      ,q'[For simplicity - the Payload here only contains our PO number (= the Business Ref of this process)</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1uhi33h" sourceRef="Activity_1kiolhv" targetRef="TextAnnotation_1qij4jn" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1ku4brw">]'
      ,q'[      <bpmn:text>We then wait for an Acknowledgement from the supplier, along with the Suppliers Sales Order ID.]'
      ,q'[]'
      ,q'[The Supplier will usually respond in 10-20 seconds - so examine variables, and hit refresh after 20 sec...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0e2y9pw" sourceRef="Event_Rx_Confirmation" targetRef="TextAnnotation_1ku4brw" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0wdxv9l">]'
      ,q'[      <bpmn:text>Note this pattern of a Message Catch Event (rather than a ReceiveTask) following on from an Event Based Gateway, and with a Timer Catch Event in parallel to act as a timeout timer.]'
      ,q'[]'
      ,q'[Its much more common to use this pattern, rather than a Receive Task with a Timer Boundary Event, to model message events...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1fflm4b" sourceRef="Event_TimeOut_5m" targetRef="TextAnnotation_0wdxv9l" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_0g9lgkn">]'
      ,q'[      <bpmndi:BPMNShape id="Participant_0whbbt7_di" bpmnElement="Participant_0whbbt7" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="210" y="230" width="1028" height="480" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_1prtuuy_di" bpmnElement="Lane_1prtuuy" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="240" y="230" width="998" height="480" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1qij4jn_di" bpmnElement="TextAnnotation_1qij4jn">]'
      ,q'[        <dc:Bounds x="440" y="530" width="250" height="166" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1ku4brw_di" bpmnElement="TextAnnotation_1ku4brw">]'
      ,q'[        <dc:Bounds x="860" y="280" width="310" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0wdxv9l_di" bpmnElement="TextAnnotation_0wdxv9l">]'
      ,q'[        <dc:Bounds x="830" y="598" width="370" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1925gah_di" bpmnElement="Event_1925gah">]'
      ,q'[        <dc:Bounds x="292" y="392" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0uij13c_di" bpmnElement="Activity_0uij13c">]'
      ,q'[        <dc:Bounds x="380" y="370" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0tmm9k5_di" bpmnElement="Activity_1kiolhv">]'
      ,q'[        <dc:Bounds x="540" y="370" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0witrck_di" bpmnElement="Gateway_1y3nrel">]'
      ,q'[        <dc:Bounds x="705" y="385" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0kaz3ec_di" bpmnElement="Event_Rx_Confirmation">]'
      ,q'[        <dc:Bounds x="822" y="392" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="788" y="435" width="84" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1i00eqo_di" bpmnElement="Activity_1i00eqo">]'
      ,q'[        <dc:Bounds x="930" y="370" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nondgq_di" bpmnElement="Event_0nondgq">]'
      ,q'[        <dc:Bounds x="1102" y="392" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_08bqvjs_di" bpmnElement="Event_08bqvjs">]'
      ,q'[        <dc:Bounds x="1102" y="512" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1tpgaxx_di" bpmnElement="Activity_1tpgaxx">]'
      ,q'[        <dc:Bounds x="930" y="490" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1ydcxct_di" bpmnElement="Event_TimeOut_5m">]'
      ,q'[        <dc:Bounds x="822" y="512" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="808" y="555" width="68" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1uhi33h_di" bpmnElement="Association_1uhi33h">]'
      ,q'[        <di:waypoint x="568" y="450" />]'
      ,q'[        <di:waypoint x="525" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0e2y9pw_di" bpmnElement="Association_0e2y9pw">]'
      ,q'[        <di:waypoint x="851" y="396" />]'
      ,q'[        <di:waypoint x="880" y="362" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1fflm4b_di" bpmnElement="Association_1fflm4b">]'
      ,q'[        <di:waypoint x="848" y="546" />]'
      ,q'[        <di:waypoint x="873" y="598" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1n4muoi_di" bpmnElement="Flow_1n4muoi">]'
      ,q'[        <di:waypoint x="328" y="410" />]'
      ,q'[        <di:waypoint x="380" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0fewogt_di" bpmnElement="Flow_0fewogt">]'
      ,q'[        <di:waypoint x="480" y="410" />]'
      ,q'[        <di:waypoint x="540" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0rqi2lg_di" bpmnElement="Flow_0rqi2lg">]'
      ,q'[        <di:waypoint x="640" y="410" />]'
      ,q'[        <di:waypoint x="705" y="410" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="654" y="392" width="38" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0rkz3tu_di" bpmnElement="Flow_0rkz3tu">]'
      ,q'[        <di:waypoint x="755" y="410" />]'
      ,q'[        <di:waypoint x="822" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_17nxy1b_di" bpmnElement="Flow_17nxy1b">]'
      ,q'[        <di:waypoint x="858" y="410" />]'
      ,q'[        <di:waypoint x="930" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0t46fc2_di" bpmnElement="Flow_0t46fc2">]'
      ,q'[        <di:waypoint x="1030" y="410" />]'
      ,q'[        <di:waypoint x="1102" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1n3p80m_di" bpmnElement="Flow_1n3p80m">]'
      ,q'[        <di:waypoint x="730" y="435" />]'
      ,q'[        <di:waypoint x="730" y="530" />]'
      ,q'[        <di:waypoint x="822" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0birqg8_di" bpmnElement="Flow_0birqg8">]'
      ,q'[        <di:waypoint x="858" y="530" />]'
      ,q'[        <di:waypoint x="930" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1cj17tx_di" bpmnElement="Flow_1cj17tx">]'
      ,q'[        <di:waypoint x="1030" y="530" />]'
      ,q'[        <di:waypoint x="1102" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_03p6awf_di" bpmnElement="Participant_0t5pyah" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="210" y="150" width="1028" height="60" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0xxeo4v_di" bpmnElement="TextAnnotation_0xxeo4v">]'
      ,q'[        <dc:Bounds x="420" y="-50" width="760" height="180" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0is679k_di" bpmnElement="Association_0is679k">]'
      ,q'[        <di:waypoint x="538" y="150" />]'
      ,q'[        <di:waypoint x="290" y="110" />]'
      ,q'[        <di:waypoint x="290" y="14" />]'
      ,q'[        <di:waypoint x="420" y="-8" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mhnxug_di" bpmnElement="Flow_1mhnxug">]'
      ,q'[        <di:waypoint x="590" y="370" />]'
      ,q'[        <di:waypoint x="590" y="210" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="511" y="253" width="57" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0rbamsj_di" bpmnElement="Flow_0rbamsj">]'
      ,q'[        <di:waypoint x="840" y="210" />]'
      ,q'[        <di:waypoint x="840" y="392" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="848" y="246" width="84" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7c - MessageFlow - Purchasing Process (start 7b first)',
    pi_dgrm_version => '23.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
