declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:collaboration id="Collaboration_0w37ggk">]'
      ,q'[    <bpmn:participant id="Participant_1lsw9xv" name="Expense Reimbursement Process" processRef="Process_f78hz1j5" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1w8l7jz">]'
      ,q'[      <bpmn:text>In this Model, See how we use various mechanisms to assign tasks to people...]'
      ,q'[]'
      ,q'[Any employee can file an expense claim -- but once they do, any rework goes to the originator.  And Approving the Expenses has to be done by the originator's manager, not by just any manager.  And paying the expenses can be done by anyone holding the Accts Payable Expenses role in the Finance Team.]'
      ,q'[]'
      ,q'[Look at this model to see how we use Lanes, Lane Roles, Process Variables, and Task Assignment settings based on an SQL Query to get all of these tasks performed by the correct person or people.]'
      ,q'[]'
      ,q'[Having the workflow definition tied to the database enables you to build very powerful process models....</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1rb8dv3" sourceRef="Event_07h3npi" targetRef="TextAnnotation_1w8l7jz" />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id="Process_f78hz1j5" isExecutable="false">]'
      ,q'[    <bpmn:laneSet id="LaneSet_1wckkhm">]'
      ,q'[      <bpmn:lane id="Lane_1heaz13" name="Employee" apex:isRole="false">]'
      ,q'[        <bpmn:flowNodeRef>Event_07h3npi</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_17d1qse</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1xfh2o5</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[      <bpmn:lane id="Lane_0jqrewd" name="Line Manager" apex:isRole="false">]'
      ,q'[        <bpmn:flowNodeRef>Activity_05irww6</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_0g8imb3</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:childLaneSet id="LaneSet_0b0q9rm" />]'
      ,q'[      </bpmn:lane>]'
      ,q'[      <bpmn:lane id="Lane_1cdvys2" name="Finance - ACCts Payable" apex:isRole="true" apex:role="FINANCE-AP-EXPENSES">]'
      ,q'[        <bpmn:flowNodeRef>Activity_1d0x2un</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_048i897</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1rxtwce</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[    </bpmn:laneSet>]'
      ,q'[    <bpmn:startEvent id="Event_07h3npi">]'
      ,q'[      <bpmn:outgoing>Flow_10x7qam</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_10x7qam" sourceRef="Event_07h3npi" targetRef="Activity_17d1qse" />]'
      ,q'[    <bpmn:userTask id="Activity_17d1qse" name="Make Expense Claim" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>ORIGINATOR</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQuerySingle</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select exp_empno]'
      ,q'[  from expense_claim]'
      ,q'[ where exp_claim_id = :F4A$BUSINESS_REF</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_10x7qam</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1utt5ar</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0hyv87c</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0hyv87c" sourceRef="Activity_17d1qse" targetRef="Activity_05irww6" />]'
      ,q'[    <bpmn:userTask id="Activity_05irww6" name="Manager Review" apex:type="apexApproval" apex:manualInput="true">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:apexApproval>]'
      ,q'[          <apex:applicationId>100</apex:applicationId>]'
      ,q'[          <apex:resultVariable>EXP_APPROVED</apex:resultVariable>]'
      ,q'[        </apex:apexApproval>]'
      ,q'[        <apex:potentialUsers>]'
      ,q'[          <apex:expressionType>sqlQuerySingle</apex:expressionType>]'
      ,q'[          <apex:expression>select mgr.ename]'
      ,q'[  from emp mgr]'
      ,q'[  join emp originator]'
      ,q'[    on originator.mgr = mgr.empno]'
      ,q'[ where originator.empn0 = :F4A$ORIGINATOR</apex:expression>]'
      ,q'[        </apex:potentialUsers>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0hyv87c</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0b8ltiw</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_0g8imb3" name="Approved?">]'
      ,q'[      <bpmn:incoming>Flow_0b8ltiw</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0rghka5</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_07qvq2z</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0b8ltiw" sourceRef="Activity_05irww6" targetRef="Gateway_0g8imb3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0rghka5" name=":F4A$EXP_APPROVED = &#39;Y&#39;" sourceRef="Gateway_0g8imb3" targetRef="Activity_1rxtwce" apex:sequence="10">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$EXP_APPROVED = 'Y'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:task id="Activity_1d0x2un" name="Make Payment">]'
      ,q'[      <bpmn:incoming>Flow_0fp9ehs</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_10mx95n</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0fp9ehs" sourceRef="Activity_1rxtwce" targetRef="Activity_1d0x2un" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_10mx95n" sourceRef="Activity_1d0x2un" targetRef="Activity_048i897" />]'
      ,q'[    <bpmn:serviceTask id="Activity_048i897" name="Notify Employee" apex:type="executePlsql">]'
      ,q'[      <bpmn:incoming>Flow_10mx95n</bpmn:incoming>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07qvq2z" name=":F4A$EXP_APPROVED = &#39;N&#39;" sourceRef="Gateway_0g8imb3" targetRef="Activity_1xfh2o5" apex:sequence="20">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$EXP_APPROVED = 'N'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1utt5ar" sourceRef="Activity_1xfh2o5" targetRef="Activity_17d1qse" apex:sequence="10" />]'
      ,q'[    <bpmn:userTask id="Activity_1xfh2o5" name="Rework Claim" apex:type="apexPage" apex:manualInput="true">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:potentialUsers>]'
      ,q'[          <apex:expressionType>sqlQuerySingle</apex:expressionType>]'
      ,q'[          <apex:expression>select ename]'
      ,q'[  from emp]'
      ,q'[ where empno = :F4A$ORIGINATOR</apex:expression>]'
      ,q'[        </apex:potentialUsers>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_07qvq2z</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1utt5ar</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:userTask id="Activity_1rxtwce" name="Arrange Payment" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_0rghka5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0fp9ehs</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1j723td">]'
      ,q'[      <bpmn:text>Claim sets Process Variable 'ORIGINATOR' to the Employee ID (empno) of the Employee</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1luyp15" sourceRef="Activity_17d1qse" targetRef="TextAnnotation_1j723td" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0rornk9">]'
      ,q'[      <bpmn:text>See that This Task is Assigned to the Employee who originated the process.]'
      ,q'[]'
      ,q'[Look at Task Assignment - set by a SQL Query to the user who oriented the process...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_136oa8m" sourceRef="Activity_1xfh2o5" targetRef="TextAnnotation_0rornk9" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0spwhxv">]'
      ,q'[      <bpmn:text>See how the Task for the Manager's. Review is assigned to their manager set by a SQL query to get the Originator's Manager from the EMPLOYEE table...]'
      ,q'[]'
      ,q'[And Manager needs be the Claiming Employee's Manager, not just any manager in the company.  So we don't map the Manager Lane to a role - but instead use the Task Assignment by SQL Query to look up the appropriate manager and assign them the approval task.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1ka600q" sourceRef="Activity_05irww6" targetRef="TextAnnotation_0spwhxv" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0xje0fi">]'
      ,q'[      <bpmn:text>This task is assigned to a Role - the Finance - Accts Payable _ Expenses Clerk role.  Anyone holding that role can perform this task...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_17p3o3l" sourceRef="Activity_1rxtwce" targetRef="TextAnnotation_0xje0fi" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_0w37ggk">]'
      ,q'[      <bpmndi:BPMNShape id="Participant_1lsw9xv_di" bpmnElement="Participant_1lsw9xv" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="270" y="90" width="1600" height="820" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_1cdvys2_di" bpmnElement="Lane_1cdvys2" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="300" y="650" width="1570" height="260" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_0jqrewd_di" bpmnElement="Lane_0jqrewd" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="300" y="420" width="1570" height="230" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_1heaz13_di" bpmnElement="Lane_1heaz13" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="300" y="90" width="1570" height="330" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_07h3npi_di" bpmnElement="Event_07h3npi" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="412" y="252" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0we3s6f_di" bpmnElement="Activity_17d1qse" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="500" y="230" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_143ubv9_di" bpmnElement="Activity_05irww6" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="670" y="490" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0g8imb3_di" bpmnElement="Gateway_0g8imb3" isMarkerVisible="true" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="845" y="505" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="783" y="493" width="54" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1d0x2un_di" bpmnElement="Activity_1d0x2un" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1130" y="740" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0yxt9tw_di" bpmnElement="Activity_048i897" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1300" y="740" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1wpm7mn_di" bpmnElement="Activity_1xfh2o5" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="820" y="230" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0pbfrvi_di" bpmnElement="Activity_1rxtwce" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="960" y="740" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1j723td_di" bpmnElement="TextAnnotation_1j723td">]'
      ,q'[        <dc:Bounds x="670" y="130" width="190" height="90" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0rornk9_di" bpmnElement="TextAnnotation_0rornk9">]'
      ,q'[        <dc:Bounds x="980" y="134" width="340" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0spwhxv_di" bpmnElement="TextAnnotation_0spwhxv" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="440" y="710" width="330" height="180" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0xje0fi_di" bpmnElement="TextAnnotation_0xje0fi">]'
      ,q'[        <dc:Bounds x="1060" y="660" width="500" height="70" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_10x7qam_di" bpmnElement="Flow_10x7qam">]'
      ,q'[        <di:waypoint x="448" y="270" />]'
      ,q'[        <di:waypoint x="500" y="270" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0hyv87c_di" bpmnElement="Flow_0hyv87c">]'
      ,q'[        <di:waypoint x="550" y="310" />]'
      ,q'[        <di:waypoint x="550" y="530" />]'
      ,q'[        <di:waypoint x="670" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0b8ltiw_di" bpmnElement="Flow_0b8ltiw">]'
      ,q'[        <di:waypoint x="770" y="530" />]'
      ,q'[        <di:waypoint x="845" y="530" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0rghka5_di" bpmnElement="Flow_0rghka5" bioc:stroke="#205022" color:border-color="#205022">]'
      ,q'[        <di:waypoint x="870" y="555" />]'
      ,q'[        <di:waypoint x="870" y="780" />]'
      ,q'[        <di:waypoint x="960" y="780" />]'
      ,q'[        <bpmndi:BPMNLabel color:color="#205022">]'
      ,q'[          <dc:Bounds x="880" y="566" width="80" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0fp9ehs_di" bpmnElement="Flow_0fp9ehs">]'
      ,q'[        <di:waypoint x="1060" y="780" />]'
      ,q'[        <di:waypoint x="1130" y="780" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_10mx95n_di" bpmnElement="Flow_10mx95n">]'
      ,q'[        <di:waypoint x="1230" y="780" />]'
      ,q'[        <di:waypoint x="1300" y="780" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07qvq2z_di" bpmnElement="Flow_07qvq2z" bioc:stroke="#831311" color:border-color="#831311">]'
      ,q'[        <di:waypoint x="870" y="505" />]'
      ,q'[        <di:waypoint x="870" y="310" />]'
      ,q'[        <bpmndi:BPMNLabel color:color="#831311">]'
      ,q'[          <dc:Bounds x="876" y="462" width="88" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1utt5ar_di" bpmnElement="Flow_1utt5ar" bioc:stroke="#831311" color:border-color="#831311">]'
      ,q'[        <di:waypoint x="820" y="270" />]'
      ,q'[        <di:waypoint x="600" y="270" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1luyp15_di" bpmnElement="Association_1luyp15">]'
      ,q'[        <di:waypoint x="598" y="235" />]'
      ,q'[        <di:waypoint x="670" y="182" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_136oa8m_di" bpmnElement="Association_136oa8m">]'
      ,q'[        <di:waypoint x="918" y="234" />]'
      ,q'[        <di:waypoint x="980" y="187" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1ka600q_di" bpmnElement="Association_1ka600q">]'
      ,q'[        <di:waypoint x="678" y="569" />]'
      ,q'[        <di:waypoint x="526" y="710" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_17p3o3l_di" bpmnElement="Association_17p3o3l">]'
      ,q'[        <di:waypoint x="1048" y="740" />]'
      ,q'[        <di:waypoint x="1060" y="728" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1w8l7jz_di" bpmnElement="TextAnnotation_1w8l7jz">]'
      ,q'[        <dc:Bounds x="680" y="-90" width="670" height="170" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1rb8dv3_di" bpmnElement="Association_1rb8dv3">]'
      ,q'[        <di:waypoint x="442" y="257" />]'
      ,q'[        <di:waypoint x="680" y="-17" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 6c - User Assignment - Putting it all together',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
