declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="25.1.0">]'
      ,q'[  <bpmn:process id="Process_14di6413" name="Tutorial 4d - Adding AI" isExecutable="true" apex:isStartable="true" apex:minLoggingLevel="4" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_0646sg2">]'
      ,q'[      <bpmn:outgoing>Flow_1vn0dvm</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_12au1m9" name="Set up Data">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>pv_prompt</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>You are part of a fraud detection workflow. Given the taxpayer's details, evaluate whether the declared income is suspicious.]'
      ,q'[]'
      ,q'[Respond with JSON using one or more of the following labels, separated by colons in field result:]'
      ,q'[]'
      ,q'[- ok (no suspicion)]'
      ,q'[- email (request more information)]'
      ,q'[- human (flag for human review)]'
      ,q'[- fraud (confirmed fraud based on inconsistencies)]'
      ,q'[]'
      ,q'[And add an additional field called rationale into the JSON with the reason for the labels. Only return the plain JSON object without any extra decoration.]'
      ,q'[here is an example of the return:]'
      ,q'[{ "result": "human:email", "rationale": "The expenses seem to outweigh the declared income." }]'
      ,q'[Here is a taxpayer info:  ]'
      ,q'[{]'
      ,q'[ "name" : "Fritz Mustermann", ]'
      ,q'[  "age": 33,]'
      ,q'[  "occupation": "Consultant",]'
      ,q'[  "annual_salary": 90000,]'
      ,q'[  "declared_income": 25000,]'
      ,q'[  "major_purchases": ["Luxury SUV", "Vacation home"]]'
      ,q'[}</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>pv_ai_service</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>F4A_AI_SERVICE</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>2</apex:varSequence>]'
      ,q'[            <apex:varName>pv_temperature</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>1.0</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1vn0dvm</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_05qnht9</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1vn0dvm" sourceRef="Event_0646sg2" targetRef="Activity_12au1m9" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_05qnht9" sourceRef="Activity_12au1m9" targetRef="Activity_1yar0ho" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_10phqxo" sourceRef="Activity_1yar0ho" targetRef="Gateway_1u610zw" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_1u610zw">]'
      ,q'[      <bpmn:incoming>Flow_10phqxo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0bi081q</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0de1jz6</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_076iph2</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1lhxrq3</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0bi081q" name="EMAIL" sourceRef="Gateway_1u610zw" targetRef="Activity_0btyuds" apex:sequence="10">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$OUTCOME like '%email%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0de1jz6" name="HUMAN" sourceRef="Gateway_1u610zw" targetRef="Activity_10cuv9y" apex:sequence="20">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$OUTCOME like '%human%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_076iph2" name="OK" sourceRef="Gateway_1u610zw" targetRef="Event_0gy3lwh" apex:sequence="40">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$OUTCOME like '%ok%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1dmj7mo" sourceRef="Activity_0btyuds" targetRef="Activity_0dhdt0o" />]'
      ,q'[    <bpmn:endEvent id="Event_1yaifr5">]'
      ,q'[      <bpmn:incoming>Flow_0yvq80l</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0yvq80l" sourceRef="Activity_0dhdt0o" targetRef="Event_1yaifr5" />]'
      ,q'[    <bpmn:endEvent id="Event_0gy3lwh" name="No Fraud Found">]'
      ,q'[      <bpmn:incoming>Flow_076iph2</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1lhxrq3" name="FRAUD" sourceRef="Gateway_1u610zw" targetRef="Event_01gdynj" apex:sequence="30">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$OUTCOME like '%fraud%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:endEvent id="Event_01gdynj" name="Fraud Found">]'
      ,q'[      <bpmn:incoming>Flow_1lhxrq3</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:userTask id="Activity_10cuv9y" name="Human Review" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_0de1jz6</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ppfquf</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:endEvent id="Event_09iid5a">]'
      ,q'[      <bpmn:incoming>Flow_1ppfquf</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ppfquf" sourceRef="Activity_10cuv9y" targetRef="Event_09iid5a" />]'
      ,q'[    <bpmn:serviceTask id="Activity_1yar0ho" name="Assess Likelihood of Fraud&#10; (Gen AI)" apex:type="apexAIGeneration">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:aiService>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>pv_ai_service</apex:expression>]'
      ,q'[        </apex:aiService>]'
      ,q'[        <apex:aiTemperature>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>pv_temperature</apex:expression>]'
      ,q'[        </apex:aiTemperature>]'
      ,q'[        <apex:aiPrompt>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>pv_prompt</apex:expression>]'
      ,q'[        </apex:aiPrompt>]'
      ,q'[        <apex:resultVariable>OUTCOME</apex:resultVariable>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_05qnht9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_10phqxo</bpmn:outgoing>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:serviceTask id="Activity_0btyuds" name="Generate Request for More Info &#10;(Gen AI)" apex:type="apexAIGeneration">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>pv_email_prompt</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>You are part of a fraud detection workflow. Erlier we have you information about a taxpaper which was:]'
      ,q'[]'
      ,q'[Here is a taxpayer info:  ]'
      ,q'[{]'
      ,q'[  "name" : "Fritz Mustermann", ]'
      ,q'[   "age": 33,]'
      ,q'[  "occupation": "Consultant",]'
      ,q'[  "annual_salary": 90000,]'
      ,q'[  "declared_income": 25000,]'
      ,q'[  "major_purchases": ["Luxury SUV", "Vacation home"]]'
      ,q'[}]'
      ,q'[]'
      ,q'[Your rationale for requiring more information is the rationale item in below data:]'
      ,q'[&amp;F4A$OUTCOME.]'
      ,q'[]'
      ,q'[Please generate a detailed email to this taxpayer asking for clarification about his situation, asking for details of items that you think are suspicious.  Return the email text.  </apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[        <apex:aiService>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>PV_AI_SERVICE</apex:expression>]'
      ,q'[        </apex:aiService>]'
      ,q'[        <apex:aiTemperature>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>1</apex:expression>]'
      ,q'[        </apex:aiTemperature>]'
      ,q'[        <apex:aiPrompt>]'
      ,q'[          <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[          <apex:expression>PV_EMAIL_PROMPT</apex:expression>]'
      ,q'[        </apex:aiPrompt>]'
      ,q'[        <apex:resultVariable>EMAIL_OUTCOME</apex:resultVariable>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0bi081q</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1dmj7mo</bpmn:outgoing>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:serviceTask id="Activity_0dhdt0o" name="Send Email" apex:type="sendMail">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:sendMail>]'
      ,q'[          <apex:emailFrom>info@flowsforapex.com</apex:emailFrom>]'
      ,q'[          <apex:emailTo>rallen2010@gmail.com</apex:emailTo>]'
      ,q'[          <apex:useTemplate>false</apex:useTemplate>]'
      ,q'[          <apex:subject>Your Tax Information</apex:subject>]'
      ,q'[          <apex:bodyText>&amp;F4A$EMAIL_OUTCOME.</apex:bodyText>]'
      ,q'[          <apex:immediately>true</apex:immediately>]'
      ,q'[        </apex:sendMail>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1dmj7mo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0yvq80l</bpmn:outgoing>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_058w0s8">]'
      ,q'[      <bpmn:text>Set Up Step.  This Step uses BEFORE TASK variable expressions to:]'
      ,q'[- set the APEX AI Service to be used to 'F4A_AI_SERVICE'.  Change this before proceeding if you need to...]'
      ,q'[- set the AI temperature to 0 to get a repeatable, accurate result]'
      ,q'[- sets up the system prompt including data about a taxpayer with high salary, high spending, and low declared taxable income - clearly questionable tax evasion....</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0b3hkyw" associationDirection="None" sourceRef="Activity_12au1m9" targetRef="TextAnnotation_058w0s8" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_03mqdgn">]'
      ,q'[      <bpmn:text>Our first AI Service Call.]'
      ,q'[We ask the AI Service to look at the taxpayer information, and return (as a Colon separated list) one or more of ]'
      ,q'[- EMAIL (for more info)]'
      ,q'[- refer to a HUMAN]'
      ,q'[- definitely FRAUD]'
      ,q'[- or looks OK]'
      ,q'[along with a rationale for that decision</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1f3ma9h" associationDirection="None" sourceRef="Activity_1yar0ho" targetRef="TextAnnotation_03mqdgn" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_05fynd6">]'
      ,q'[      <bpmn:text>Our Second AI Service Call]'
      ,q'[If we need to send an email to the taxpayer asking for more info, we pass the taxpayer info and the rationale back to GenAI, and request it generates an Email to the taxpayer</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0brcgjv" associationDirection="None" sourceRef="Activity_0btyuds" targetRef="TextAnnotation_05fynd6" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_12nn9q9">]'
      ,q'[      <bpmn:text>AI Service Task in your process]'
      ,q'[Use an AI service task to call a Generative AI service such as GPT, Lamma or Cohere using the APEX_AI api (more services coming)]'
      ,q'[Use process variables to build your system prompt - you can query relevant data to do RAG, or add relevant data through vector searches - then pass your prompt to GenAI.]'
      ,q'[]'
      ,q'[In this example we call AI once to get process routing instructions - which paths should the process take.  Then call it again to generate documents.]'
      ,q'[]'
      ,q'[You can use techniques like this to build Agentic processes...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0a8ohh8" associationDirection="None" sourceRef="Event_0646sg2" targetRef="TextAnnotation_12nn9q9" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_14di6413">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0646sg2_di" bpmnElement="Event_0646sg2">]'
      ,q'[        <dc:Bounds x="-468" y="-58" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_12au1m9_di" bpmnElement="Activity_12au1m9">]'
      ,q'[        <dc:Bounds x="-380" y="-80" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_18lfd4h_di" bpmnElement="Gateway_1u610zw">]'
      ,q'[        <dc:Bounds x="-55" y="-65" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1yaifr5_di" bpmnElement="Event_1yaifr5">]'
      ,q'[        <dc:Bounds x="362" y="-178" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0gy3lwh_di" bpmnElement="Event_0gy3lwh">]'
      ,q'[        <dc:Bounds x="252" y="162" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="230" y="205" width="81" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_01gdynj_di" bpmnElement="Event_01gdynj">]'
      ,q'[        <dc:Bounds x="252" y="52" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="239" y="95" width="63" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0dkotdb_di" bpmnElement="Activity_10cuv9y">]'
      ,q'[        <dc:Bounds x="70" y="-80" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_09iid5a_di" bpmnElement="Event_09iid5a">]'
      ,q'[        <dc:Bounds x="252" y="-58" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_09gmme9_di" bpmnElement="Activity_1yar0ho" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-220" y="-80" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07ywlpv_di" bpmnElement="Activity_0btyuds" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="70" y="-200" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07j78d7_di" bpmnElement="Activity_0dhdt0o">]'
      ,q'[        <dc:Bounds x="210" y="-200" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0b3hkyw_di" bpmnElement="Association_0b3hkyw">]'
      ,q'[        <di:waypoint x="-376" y="-2" />]'
      ,q'[        <di:waypoint x="-512" y="110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1f3ma9h_di" bpmnElement="Association_1f3ma9h">]'
      ,q'[        <di:waypoint x="-177" y="-80" />]'
      ,q'[        <di:waypoint x="-183" y="-112" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0brcgjv_di" bpmnElement="Association_0brcgjv">]'
      ,q'[        <di:waypoint x="128" y="-200" />]'
      ,q'[        <di:waypoint x="144" y="-284" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0a8ohh8_di" bpmnElement="Association_0a8ohh8">]'
      ,q'[        <di:waypoint x="-452" y="-58" />]'
      ,q'[        <di:waypoint x="-510" y="-505" />]'
      ,q'[        <di:waypoint x="-410" y="-505" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1vn0dvm_di" bpmnElement="Flow_1vn0dvm">]'
      ,q'[        <di:waypoint x="-432" y="-40" />]'
      ,q'[        <di:waypoint x="-380" y="-40" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_05qnht9_di" bpmnElement="Flow_05qnht9">]'
      ,q'[        <di:waypoint x="-280" y="-40" />]'
      ,q'[        <di:waypoint x="-220" y="-40" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_10phqxo_di" bpmnElement="Flow_10phqxo">]'
      ,q'[        <di:waypoint x="-120" y="-40" />]'
      ,q'[        <di:waypoint x="-55" y="-40" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0bi081q_di" bpmnElement="Flow_0bi081q">]'
      ,q'[        <di:waypoint x="-30" y="-65" />]'
      ,q'[        <di:waypoint x="-30" y="-160" />]'
      ,q'[        <di:waypoint x="70" y="-160" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-9" y="-187" width="34" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0de1jz6_di" bpmnElement="Flow_0de1jz6">]'
      ,q'[        <di:waypoint x="-5" y="-40" />]'
      ,q'[        <di:waypoint x="70" y="-40" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="14" y="-58" width="41" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_076iph2_di" bpmnElement="Flow_076iph2">]'
      ,q'[        <di:waypoint x="-30" y="-15" />]'
      ,q'[        <di:waypoint x="-30" y="180" />]'
      ,q'[        <di:waypoint x="252" y="180" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-8" y="153" width="16" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1dmj7mo_di" bpmnElement="Flow_1dmj7mo">]'
      ,q'[        <di:waypoint x="170" y="-160" />]'
      ,q'[        <di:waypoint x="210" y="-160" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0yvq80l_di" bpmnElement="Flow_0yvq80l">]'
      ,q'[        <di:waypoint x="310" y="-160" />]'
      ,q'[        <di:waypoint x="362" y="-160" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1lhxrq3_di" bpmnElement="Flow_1lhxrq3">]'
      ,q'[        <di:waypoint x="-30" y="-15" />]'
      ,q'[        <di:waypoint x="-30" y="70" />]'
      ,q'[        <di:waypoint x="252" y="70" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-2" y="43" width="38" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ppfquf_di" bpmnElement="Flow_1ppfquf">]'
      ,q'[        <di:waypoint x="170" y="-40" />]'
      ,q'[        <di:waypoint x="252" y="-40" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_058w0s8_di" bpmnElement="TextAnnotation_058w0s8">]'
      ,q'[        <dc:Bounds x="-580" y="110" width="410" height="110" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_03mqdgn_di" bpmnElement="TextAnnotation_03mqdgn">]'
      ,q'[        <dc:Bounds x="-350" y="-250" width="230" height="138" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_05fynd6_di" bpmnElement="TextAnnotation_05fynd6">]'
      ,q'[        <dc:Bounds x="110" y="-380" width="230" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_12nn9q9_di" bpmnElement="TextAnnotation_12nn9q9">]'
      ,q'[        <dc:Bounds x="-410" y="-520" width="500" height="170" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 4d - Using an AI Service Task',
    pi_dgrm_short_description => 'Flows for APEX BPMN Tutorial - Part 4d - shows how to use a Gen AI Service Task to make decisions and to generate documents as part of your business process.  Requires an AI service to be configured to run.',
    pi_dgrm_description => 'This tutorial workflow demonstrates how to integrate Generative AI, such as GPT, into a Business Process Model and Notation (BPMN) framework to both direct process flow and generate document content. The workflow exemplifies how AI can be leveraged to automate decision-making and content creation within a business process.

Key Features:

AI Integration via BPMN Service Tasks:

Utilizes BPMN Service Tasks to effectively interface with Generative AI, such as GPT, throughout the process.  
Demonstrates how to set up AI Service Tasks to interpret data and generate outcomes that dictate subsequent process paths.  
Process Flow Direction:

AI is used to evaluate input data, producing results that guide the process through different decision branches.  
Depending on the AI assessment, the process can take multiple paths, such as requiring additional information (email), directing to human review, confirming an action (fraud detection), or concluding that everything is in order (OK).

Document Content Generation:

Illustrates the use of AI to generate tailored content such as emails, based on insights derived from process data and AI-inferred conclusions.  
This capability streamlines communication by auto-generating personalized messages or documents which can be dispatched without manual drafting.  
Enhanced Workflow Efficiency:

By employing AI, the tutorial highlights how complex decision-making and document generation can be automated, reducing manual workload and process time.  AI-driven instructions enable the workflow to adapt dynamically to a variety of inputs, ensuring scalability and robustness.

Setting Up AI Service Tasks:

Provides a step-by-step guide on configuring AI Service Tasks, defining prompt variables, and establishing conditions for AI engagement in the workflow.  
Emphasizes variable setup for prompts and temperature to control AI behavior, ensuring accurate and repeatable processes.  
Outcome:

Participants will learn how to configure and utilize AI within a BPMN workflow to automatically determine process pathways and generate necessary documentation. This tutorial not only provides insight into technical setup but also highlights the potential efficiencies and flexibility brought on by integrating AI into business processes.

Conclusion:

This tutorial serves as a practical guide for embedding Generative AI into BPMN processes, showcasing its dual capability to provide process direction and generate content. By illustrating these applications, the tutorial fosters an understanding of how AI can be a powerful tool in creating intelligent, responsive business workflows.',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
