declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="23.1.0">]'
      ,q'[  <bpmn:collaboration id="Collaboration_7b">]'
      ,q'[    <bpmn:participant id="Participant_7b" name="Supplier&#39;s Process" processRef="Process_7c" />]'
      ,q'[    <bpmn:participant id="Participant_102lqrd" name="Customers Ordering Process" />]'
      ,q'[    <bpmn:messageFlow id="Flow_PO" name="Purchase Order" sourceRef="Participant_102lqrd" targetRef="Activity_133cc7v" />]'
      ,q'[    <bpmn:messageFlow id="Flow_07evyuq" name="Order Confirmation" sourceRef="Event_Send_Order_Conf" targetRef="Participant_102lqrd" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0v42vrb">]'
      ,q'[      <bpmn:text>This Process is a Supplier's Process.]'
      ,q'[]'
      ,q'[Essentially, once started, the Supplier's Process creates a Message Subscription for an incoming PO from Supplier No 100, then sits and waits for an incoming message that meets the subscription's definition.]'
      ,q'[]'
      ,q'[In this (simple) example, it then stores the incoming message payload into Process Variable 'IncomingPO'.]'
      ,q'[An after task variable expression calculates the Suppliers Sales Order Number (by adding 1234 to the incoming PO number).]'
      ,q'[]'
      ,q'[It waits 10 seconds (so you have time to look at the variables in the Suppliers Process in Tutorial 7c) - then sends the Order Confirmation back to the purchaser using the PO Number as the Correlation Key.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1i11l3k" sourceRef="Participant_102lqrd" targetRef="TextAnnotation_0v42vrb" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0lxkz3b">]'
      ,q'[      <bpmn:text>All you need to do is Start this Process - then move to Tutorial 7c.]'
      ,q'[]'
      ,q'[7c will send a message to this process, and receive a reply...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0gxxtlt" sourceRef="Participant_102lqrd" targetRef="TextAnnotation_0lxkz3b" />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id="Process_7c" isExecutable="false">]'
      ,q'[    <bpmn:intermediateThrowEvent id="Event_Send_Order_Conf" name="Send Order Confirmation" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0ogqyre</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1et9ql9</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0ueukib">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:endpoint>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>local</apex:expression>]'
      ,q'[          </apex:endpoint>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>OrderConfirmation</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>PONumber</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[            <apex:expression>IncomingPONumber</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payload>]'
      ,q'[            <apex:expressionType>plsqlRawExpression</apex:expressionType>]'
      ,q'[            <apex:expression>'{"SupplierSalesOrder":"' || &amp;F4A$SupplierSalesOrder.||'"}'</apex:expression>]'
      ,q'[          </apex:payload>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateThrowEvent>]'
      ,q'[    <bpmn:eventBasedGateway id="Gateway_0d18ckl">]'
      ,q'[      <bpmn:incoming>Flow_1et9ql9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ip3bnb</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_07z9swi</bpmn:outgoing>]'
      ,q'[    </bpmn:eventBasedGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0tgqz99" sourceRef="Event_0yj6hva" targetRef="Activity_133cc7v" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1r1hys3" sourceRef="Activity_133cc7v" targetRef="Event_Delay_10s" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1et9ql9" sourceRef="Event_Send_Order_Conf" targetRef="Gateway_0d18ckl" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ip3bnb" sourceRef="Gateway_0d18ckl" targetRef="Event_0fto84i" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07z9swi" sourceRef="Gateway_0d18ckl" targetRef="Activity_133cc7v" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0nrqcna" sourceRef="Event_0fto84i" targetRef="Event_1854woy" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_0fto84i" name="PT1H (Timeout)">]'
      ,q'[      <bpmn:incoming>Flow_1ip3bnb</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0nrqcna</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0rztt84">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT1H</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:startEvent id="Event_0yj6hva" name="Start">]'
      ,q'[      <bpmn:outgoing>Flow_0tgqz99</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:receiveTask id="Activity_133cc7v" name="Receive Orders" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:messageName>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>SendPO</apex:expression>]'
      ,q'[        </apex:messageName>]'
      ,q'[        <apex:correlationKey>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>CustomerID</apex:expression>]'
      ,q'[        </apex:correlationKey>]'
      ,q'[        <apex:correlationValue>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>100</apex:expression>]'
      ,q'[        </apex:correlationValue>]'
      ,q'[        <apex:payloadVariable>IncomingPONumber</apex:payloadVariable>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>SupplierSalesOrder</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>:F4A$IncomingPONumber + 1234</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_07z9swi</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0tgqz99</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1r1hys3</bpmn:outgoing>]'
      ,q'[    </bpmn:receiveTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0ogqyre" sourceRef="Event_Delay_10s" targetRef="Event_Send_Order_Conf" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_Delay_10s" name="Delay 10s">]'
      ,q'[      <bpmn:incoming>Flow_1r1hys3</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0ogqyre</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0kpq7ei">]'
      ,q'[        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">PT10S</bpmn:timeDuration>]'
      ,q'[      </bpmn:timerEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:endEvent id="Event_1854woy">]'
      ,q'[      <bpmn:incoming>Flow_0nrqcna</bpmn:incoming>]'
      ,q'[      <bpmn:terminateEventDefinition id="TerminateEventDefinition_07lx9b7">]'
      ,q'[        <apex:processStatus>completed</apex:processStatus>]'
      ,q'[      </bpmn:terminateEventDefinition>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1ab1f97">]'
      ,q'[      <bpmn:text>This will Timeout after an Hour</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_06nlslw" sourceRef="Event_0fto84i" targetRef="TextAnnotation_1ab1f97" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_7b">]'
      ,q'[      <bpmndi:BPMNShape id="Participant_0xgfe49_di" bpmnElement="Participant_7b" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="230" y="350" width="1020" height="320" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1ab1f97_di" bpmnElement="TextAnnotation_1ab1f97">]'
      ,q'[        <dc:Bounds x="1040" y="490" width="100" height="54" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1prr8po_di" bpmnElement="Event_Send_Order_Conf">]'
      ,q'[        <dc:Bounds x="832" y="392" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="820" y="435" width="63" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0srrbg5_di" bpmnElement="Gateway_0d18ckl">]'
      ,q'[        <dc:Bounds x="945" y="385" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0fto84i_di" bpmnElement="Event_0fto84i">]'
      ,q'[        <dc:Bounds x="1022" y="392" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1002" y="435" width="79" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1mwfy0f_di" bpmnElement="Event_0yj6hva">]'
      ,q'[        <dc:Bounds x="282" y="392" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="288" y="435" width="24" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_133cc7v_di" bpmnElement="Activity_133cc7v">]'
      ,q'[        <dc:Bounds x="390" y="370" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0hzxegf_di" bpmnElement="Event_Delay_10s">]'
      ,q'[        <dc:Bounds x="642" y="392" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="637" y="435" width="49" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_09o4ko7_di" bpmnElement="Event_1854woy">]'
      ,q'[        <dc:Bounds x="1192" y="392" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_06nlslw_di" bpmnElement="Association_06nlslw">]'
      ,q'[        <di:waypoint x="1048" y="426" />]'
      ,q'[        <di:waypoint x="1082" y="490" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0tgqz99_di" bpmnElement="Flow_0tgqz99">]'
      ,q'[        <di:waypoint x="318" y="410" />]'
      ,q'[        <di:waypoint x="390" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1r1hys3_di" bpmnElement="Flow_1r1hys3">]'
      ,q'[        <di:waypoint x="490" y="410" />]'
      ,q'[        <di:waypoint x="642" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1et9ql9_di" bpmnElement="Flow_1et9ql9">]'
      ,q'[        <di:waypoint x="868" y="410" />]'
      ,q'[        <di:waypoint x="945" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ip3bnb_di" bpmnElement="Flow_1ip3bnb">]'
      ,q'[        <di:waypoint x="995" y="410" />]'
      ,q'[        <di:waypoint x="1022" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07z9swi_di" bpmnElement="Flow_07z9swi">]'
      ,q'[        <di:waypoint x="970" y="435" />]'
      ,q'[        <di:waypoint x="970" y="590" />]'
      ,q'[        <di:waypoint x="440" y="590" />]'
      ,q'[        <di:waypoint x="440" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0nrqcna_di" bpmnElement="Flow_0nrqcna">]'
      ,q'[        <di:waypoint x="1058" y="410" />]'
      ,q'[        <di:waypoint x="1192" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ogqyre_di" bpmnElement="Flow_0ogqyre">]'
      ,q'[        <di:waypoint x="678" y="410" />]'
      ,q'[        <di:waypoint x="832" y="410" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_0s6jps3_di" bpmnElement="Participant_102lqrd" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="230" y="160" width="1020" height="90" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0v42vrb_di" bpmnElement="TextAnnotation_0v42vrb">]'
      ,q'[        <dc:Bounds x="490" y="-140" width="330" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0lxkz3b_di" bpmnElement="TextAnnotation_0lxkz3b">]'
      ,q'[        <dc:Bounds x="950" y="-60" width="300" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1i11l3k_di" bpmnElement="Association_1i11l3k">]'
      ,q'[        <di:waypoint x="707" y="160" />]'
      ,q'[        <di:waypoint x="671" y="110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0gxxtlt_di" bpmnElement="Association_0gxxtlt">]'
      ,q'[        <di:waypoint x="782" y="160" />]'
      ,q'[        <di:waypoint x="950" y="-19" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_17dc1xg_di" bpmnElement="Flow_PO">]'
      ,q'[        <di:waypoint x="440" y="250" />]'
      ,q'[        <di:waypoint x="440" y="370" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="451" y="293" width="78" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07evyuq_di" bpmnElement="Flow_07evyuq">]'
      ,q'[        <di:waypoint x="850" y="392" />]'
      ,q'[        <di:waypoint x="850" y="250" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="858" y="286" width="63" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7b - MessageFlow - Supplier Response (Start before 7c)',
    pi_dgrm_version => '23.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
