declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial7g" name="Tutorial 7g - Nested Parallel SubProcess Iterations" isExecutable="true" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_Start" name="Start">]'
      ,q'[      <bpmn:outgoing>Flow_00jstgp</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_PreSplit" name="Pre-Split">]'
      ,q'[      <bpmn:incoming>Flow_00jstgp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1i6fc42</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_00jstgp" sourceRef="Event_Start" targetRef="Activity_PreSplit" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1i6fc42" sourceRef="Activity_PreSplit" targetRef="Gateway_Split" />]'
      ,q'[    <bpmn:task id="Activity_A1" name="A1- List">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpList</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1ngmguv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0xh1wjg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ngmguv" sourceRef="Gateway_Split" targetRef="Activity_A1" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0xh1wjg" sourceRef="Activity_A1" targetRef="Activity_A2" />]'
      ,q'[    <bpmn:task id="Activity_A3" name="A3">]'
      ,q'[      <bpmn:incoming>Flow_1v6vync</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0emop6i</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1v6vync" sourceRef="Activity_A2" targetRef="Activity_A3" />]'
      ,q'[    <bpmn:endEvent id="Event_AEnd" name="AEnd">]'
      ,q'[      <bpmn:incoming>Flow_0emop6i</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0emop6i" sourceRef="Activity_A3" targetRef="Event_AEnd" />]'
      ,q'[    <bpmn:task id="Activity_B1" name="B1 - Array">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EmpArray</apex:varName>]'
      ,q'[            <apex:varDataType>JSON</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryArray</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename, empno]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_02y11qo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mg0jl9</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_B3" name="B3">]'
      ,q'[      <bpmn:incoming>Flow_0m8ne0j</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0cv0t6o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_BEnd" name="BEnd">]'
      ,q'[      <bpmn:incoming>Flow_0cv0t6o</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mg0jl9" sourceRef="Activity_B1" targetRef="Activity_B2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0m8ne0j" sourceRef="Activity_B2" targetRef="Activity_B3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0cv0t6o" sourceRef="Activity_B3" targetRef="Event_BEnd" />]'
      ,q'[    <bpmn:task id="Activity_C1" name="C1 - Query">]'
      ,q'[      <bpmn:incoming>Flow_1a4xxmd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1f9kxmo</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_C3" name="C3">]'
      ,q'[      <bpmn:incoming>Flow_1dcufu5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0opd4zr</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_CEnd" name="CEnd">]'
      ,q'[      <bpmn:incoming>Flow_0opd4zr</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1f9kxmo" sourceRef="Activity_C1" targetRef="Activity_C2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1dcufu5" sourceRef="Activity_C2" targetRef="Activity_C3" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0opd4zr" sourceRef="Activity_C3" targetRef="Event_CEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02y11qo" sourceRef="Gateway_Split" targetRef="Activity_B1" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1a4xxmd" sourceRef="Gateway_Split" targetRef="Activity_C1" apex:sequence="30" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split" name="Split">]'
      ,q'[      <bpmn:incoming>Flow_1i6fc42</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ngmguv</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_02y11qo</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1a4xxmd</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:subProcess id="Activity_A2" name="A2">]'
      ,q'[      <bpmn:incoming>Flow_0xh1wjg</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1v6vync</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:description>Iteration A2 - iteration &amp;LOOP_COUNTER. (&amp;ENAME.)</apex:description>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableList</apex:expressionType>]'
      ,q'[            <apex:expression>EmpList</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>iterationArrayA2</apex:expression>]'
      ,q'[            <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_A2Start" name="A2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_0xcd6m0</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_A2a" name="A2a">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:beforeTask>]'
      ,q'[            <apex:processVariable>]'
      ,q'[              <apex:varSequence>0</apex:varSequence>]'
      ,q'[              <apex:varName>NewEmpList</apex:varName>]'
      ,q'[              <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[              <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[              <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 30</apex:varExpression>]'
      ,q'[            </apex:processVariable>]'
      ,q'[          </apex:beforeTask>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[        <bpmn:incoming>Flow_0xcd6m0</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1alq874</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0xcd6m0" sourceRef="Event_A2Start" targetRef="Activity_A2a" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1alq874" sourceRef="Activity_A2a" targetRef="Activity_A2b" />]'
      ,q'[      <bpmn:endEvent id="Event_A2End" name="A2 End">]'
      ,q'[        <bpmn:incoming>Flow_0uihkyr</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0cvzkj3" sourceRef="Activity_A2b" targetRef="Activity_A2c" />]'
      ,q'[      <bpmn:task id="Activity_A2c" name="A2c">]'
      ,q'[        <bpmn:incoming>Flow_0cvzkj3</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0uihkyr</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0uihkyr" sourceRef="Activity_A2c" targetRef="Event_A2End" />]'
      ,q'[      <bpmn:subProcess id="Activity_A2b" name="A2b">]'
      ,q'[        <bpmn:incoming>Flow_1alq874</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0cvzkj3</bpmn:outgoing>]'
      ,q'[        <bpmn:multiInstanceLoopCharacteristics isSequential="true">]'
      ,q'[          <bpmn:extensionElements>]'
      ,q'[            <apex:inputCollection>]'
      ,q'[              <apex:expressionType>processVariableList</apex:expressionType>]'
      ,q'[              <apex:expression>NewEmpList</apex:expression>]'
      ,q'[              <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[            </apex:inputCollection>]'
      ,q'[            <apex:description>Sub Iteration A2b - iteration &amp;LOOP_COUNTER. (&amp;ENAME.)</apex:description>]'
      ,q'[            <apex:outputCollection>]'
      ,q'[              <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[              <apex:expression>iterationArrayA2b</apex:expression>]'
      ,q'[              <apex:insideVariable>ename</apex:insideVariable>]'
      ,q'[            </apex:outputCollection>]'
      ,q'[            <apex:completionCondition>]'
      ,q'[              <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[              <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[            </apex:completionCondition>]'
      ,q'[          </bpmn:extensionElements>]'
      ,q'[        </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:startEvent id="Event_A2bStart" name="A2bStart">]'
      ,q'[          <bpmn:outgoing>Flow_1mh25vb</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:task id="Activity_A2b1" name="A2b1">]'
      ,q'[          <bpmn:incoming>Flow_1mh25vb</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_135tn8v</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_1mh25vb" sourceRef="Event_A2bStart" targetRef="Activity_A2b1" />]'
      ,q'[        <bpmn:task id="Activity_A2b2" name="A2b2">]'
      ,q'[          <bpmn:incoming>Flow_135tn8v</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0ipy053</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_135tn8v" sourceRef="Activity_A2b1" targetRef="Activity_A2b2" />]'
      ,q'[        <bpmn:endEvent id="Event_A2bEnd" name="A2bEnd">]'
      ,q'[          <bpmn:incoming>Flow_0ipy053</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0ipy053" sourceRef="Activity_A2b2" targetRef="Event_A2bEnd" />]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:subProcess id="Activity_B2" name="B2">]'
      ,q'[      <bpmn:incoming>Flow_0mg0jl9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0m8ne0j</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>EmpArray</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayB</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_B2Start" name="B2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_0pvftkr</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_B2a" name="B2a">]'
      ,q'[        <bpmn:incoming>Flow_0pvftkr</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1l3p7hs</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0pvftkr" sourceRef="Event_B2Start" targetRef="Activity_B2a" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1l3p7hs" sourceRef="Activity_B2a" targetRef="Activity_B2b" />]'
      ,q'[      <bpmn:endEvent id="Event_B2End" name="B2 End">]'
      ,q'[        <bpmn:incoming>Flow_0macjlk</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0macjlk" sourceRef="Activity_B2b" targetRef="Event_B2End" />]'
      ,q'[      <bpmn:subProcess id="Activity_B2b" name="B2b">]'
      ,q'[        <bpmn:incoming>Flow_1l3p7hs</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0macjlk</bpmn:outgoing>]'
      ,q'[        <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[          <bpmn:extensionElements>]'
      ,q'[            <apex:completionCondition>]'
      ,q'[              <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[              <apex:expression>:F4A$completed_instances &gt;= 3</apex:expression>]'
      ,q'[            </apex:completionCondition>]'
      ,q'[            <apex:outputCollection>]'
      ,q'[              <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[              <apex:expression>iterArrayNestedB</apex:expression>]'
      ,q'[              <apex:insideVariable>dname:deptno</apex:insideVariable>]'
      ,q'[            </apex:outputCollection>]'
      ,q'[            <apex:inputCollection>]'
      ,q'[              <apex:expressionType>sqlQueryArray</apex:expressionType>]'
      ,q'[              <apex:expression>Select dname, deptno from dept</apex:expression>]'
      ,q'[            </apex:inputCollection>]'
      ,q'[            <apex:description>Sub Iteration of B2b: Department &amp;DNAME. (Loop &amp;LOOP_COUNTER.)</apex:description>]'
      ,q'[          </bpmn:extensionElements>]'
      ,q'[        </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:startEvent id="Event_B2BStart" name="B2b start">]'
      ,q'[          <bpmn:outgoing>Flow_0kc9rpm</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:task id="Activity_B2B1" name="B2B1">]'
      ,q'[          <bpmn:incoming>Flow_0kc9rpm</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0cktw33</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0kc9rpm" sourceRef="Event_B2BStart" targetRef="Activity_B2B1" />]'
      ,q'[        <bpmn:task id="Activity_B2B2" name="B2B2">]'
      ,q'[          <bpmn:incoming>Flow_0cktw33</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_0xopiv5</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0cktw33" sourceRef="Activity_B2B1" targetRef="Activity_B2B2" />]'
      ,q'[        <bpmn:endEvent id="Event_B2BEnd" name="B2bEnd">]'
      ,q'[          <bpmn:incoming>Flow_0xopiv5</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0xopiv5" sourceRef="Activity_B2B2" targetRef="Event_B2BEnd" />]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:subProcess id="Activity_C2" name="C2">]'
      ,q'[      <bpmn:incoming>Flow_1f9kxmo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1dcufu5</bpmn:outgoing>]'
      ,q'[      <bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:inputCollection>]'
      ,q'[            <apex:expressionType>sqlQueryArray</apex:expressionType>]'
      ,q'[            <apex:expression>select ename, empno ]'
      ,q'[from emp]'
      ,q'[where deptno = 20</apex:expression>]'
      ,q'[          </apex:inputCollection>]'
      ,q'[          <apex:outputCollection>]'
      ,q'[            <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[            <apex:expression>IterationArrayC</apex:expression>]'
      ,q'[            <apex:insideVariable>ename:empno</apex:insideVariable>]'
      ,q'[          </apex:outputCollection>]'
      ,q'[          <apex:completionCondition>]'
      ,q'[            <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[            <apex:expression>:F4A$completed_instances &gt; 3</apex:expression>]'
      ,q'[          </apex:completionCondition>]'
      ,q'[          <apex:description>Instance &amp;LOOP_COUNTER. (&amp;ENAME.)</apex:description>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:multiInstanceLoopCharacteristics>]'
      ,q'[      <bpmn:startEvent id="Event_C2Start" name="C2 Start">]'
      ,q'[        <bpmn:outgoing>Flow_0l9o9as</bpmn:outgoing>]'
      ,q'[      </bpmn:startEvent>]'
      ,q'[      <bpmn:task id="Activity_C2a" name="C2a">]'
      ,q'[        <bpmn:incoming>Flow_0l9o9as</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_0v9gdmc</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0l9o9as" sourceRef="Event_C2Start" targetRef="Activity_C2a" />]'
      ,q'[      <bpmn:sequenceFlow id="Flow_0v9gdmc" sourceRef="Activity_C2a" targetRef="Activity_C2b" />]'
      ,q'[      <bpmn:task id="Activity_C2c" name="C2c">]'
      ,q'[        <bpmn:incoming>Flow_1r97bug</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1buzp0p</bpmn:outgoing>]'
      ,q'[      </bpmn:task>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1r97bug" sourceRef="Activity_C2b" targetRef="Activity_C2c" />]'
      ,q'[      <bpmn:endEvent id="Event_C2End" name="C2End">]'
      ,q'[        <bpmn:incoming>Flow_1buzp0p</bpmn:incoming>]'
      ,q'[      </bpmn:endEvent>]'
      ,q'[      <bpmn:sequenceFlow id="Flow_1buzp0p" sourceRef="Activity_C2c" targetRef="Event_C2End" />]'
      ,q'[      <bpmn:subProcess id="Activity_C2b" name="C2b">]'
      ,q'[        <bpmn:incoming>Flow_0v9gdmc</bpmn:incoming>]'
      ,q'[        <bpmn:outgoing>Flow_1r97bug</bpmn:outgoing>]'
      ,q'[        <bpmn:standardLoopCharacteristics>]'
      ,q'[          <bpmn:extensionElements>]'
      ,q'[            <apex:description>C2b Loop - &amp;LOOP_COUNTER.</apex:description>]'
      ,q'[            <apex:completionCondition>]'
      ,q'[              <apex:expressionType>plsqlExpression</apex:expressionType>]'
      ,q'[              <apex:expression>:F4A$LOOP_COUNTER &gt;= 3</apex:expression>]'
      ,q'[            </apex:completionCondition>]'
      ,q'[            <apex:outputCollection>]'
      ,q'[              <apex:expressionType>processVariableArray</apex:expressionType>]'
      ,q'[              <apex:expression>C2b_output_array</apex:expression>]'
      ,q'[              <apex:insideVariable>ENAME</apex:insideVariable>]'
      ,q'[            </apex:outputCollection>]'
      ,q'[          </bpmn:extensionElements>]'
      ,q'[        </bpmn:standardLoopCharacteristics>]'
      ,q'[        <bpmn:startEvent id="Event_1pr19p3" name="C2bStart">]'
      ,q'[          <bpmn:outgoing>Flow_0nxnzrr</bpmn:outgoing>]'
      ,q'[        </bpmn:startEvent>]'
      ,q'[        <bpmn:task id="Activity_08nour2" name="C2BTask">]'
      ,q'[          <bpmn:incoming>Flow_0nxnzrr</bpmn:incoming>]'
      ,q'[          <bpmn:outgoing>Flow_066o4bv</bpmn:outgoing>]'
      ,q'[        </bpmn:task>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_0nxnzrr" sourceRef="Event_1pr19p3" targetRef="Activity_08nour2" />]'
      ,q'[        <bpmn:endEvent id="Event_13t68ia" name="C2bEnd">]'
      ,q'[          <bpmn:incoming>Flow_066o4bv</bpmn:incoming>]'
      ,q'[        </bpmn:endEvent>]'
      ,q'[        <bpmn:sequenceFlow id="Flow_066o4bv" sourceRef="Activity_08nour2" targetRef="Event_13t68ia" />]'
      ,q'[      </bpmn:subProcess>]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0i9q5wo">]'
      ,q'[      <bpmn:text>emplist = select name ]'
      ,q'[from emp]'
      ,q'[where dept no = 20]'
      ,q'[]'
      ,q'[SMITH:JONES:SCOTT:ADAMS:FORD</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_050cm0v" sourceRef="Activity_A1" targetRef="TextAnnotation_0i9q5wo" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_06yrhts">]'
      ,q'[      <bpmn:text>iterate over emplist]'
      ,q'[]'
      ,q'[contains subprocess with nested SEQUENTIAL iteration</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0bi9txm" sourceRef="Activity_A2" targetRef="TextAnnotation_06yrhts" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1dh1ysa">]'
      ,q'[      <bpmn:text>emparray = select name, empno from emp where dept no = 20]'
      ,q'[]'
      ,q'[[{"name":"SMITH","EMPNO":7369},]'
      ,q'[{"name":"JONES","EMPNO":7566}]'
      ,q'[...]</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1tdwshf">]'
      ,q'[      <bpmn:text>iterate over emparray ]'
      ,q'[]'
      ,q'[contains subprocess with nested PARALEL iteration</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1cqii1i" sourceRef="Activity_B2" targetRef="TextAnnotation_1tdwshf" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0ehpw4n">]'
      ,q'[      <bpmn:text>iterate over query...]'
      ,q'[]'
      ,q'[select name, empno ]'
      ,q'[from emp]'
      ,q'[where dept no = 20</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0hlx4e9" sourceRef="Activity_C2" targetRef="TextAnnotation_0ehpw4n" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0p3j9kh">]'
      ,q'[      <bpmn:text>And in this example, we have Nested]'
      ,q'[iterating Sub Processes.]'
      ,q'[]'
      ,q'[this is where it starts to get difficult to]'
      ,q'[keep track of what's going on.]'
      ,q'[]'
      ,q'[Use the Iteration Selector in the Viewer  to choose which iteration to look at.]'
      ,q'[]'
      ,q'[And look at the product documentation (Iteration concepts)</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1c83hs4" associationDirection="None" sourceRef="Activity_PreSplit" targetRef="TextAnnotation_0p3j9kh" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial7g">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nj6ios_di" bpmnElement="Event_Start">]'
      ,q'[        <dc:Bounds x="242" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="248" y="385" width="24" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1v4awr2_di" bpmnElement="Activity_PreSplit">]'
      ,q'[        <dc:Bounds x="330" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_06o8whk_di" bpmnElement="Activity_A1" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="600" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1m1j7lz_di" bpmnElement="Activity_A3" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="920" y="102" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0xoy17b_di" bpmnElement="Event_AEnd" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="1082" y="124" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1088" y="167" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0lsnoc7" bpmnElement="Activity_B1" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="600" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_12yruu2" bpmnElement="Activity_B3" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="920" y="320" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_10192cq" bpmnElement="Event_BEnd" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1082" y="342" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="385" width="27" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_0dwx7ia" bpmnElement="Activity_C1" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="600" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1s29z1t" bpmnElement="Activity_C3" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="920" y="540" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="BPMNShape_1x8vuch" bpmnElement="Event_CEnd" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1082" y="562" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1087" y="605" width="28" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1b1nb8o_di" bpmnElement="Gateway_Split">]'
      ,q'[        <dc:Bounds x="495" y="335" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="489" y="313" width="22" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_109mvy1_di" bpmnElement="Activity_A2" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="760" y="102" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1mmigx9_di" bpmnElement="Activity_B2" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="760" y="320" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07xqvgw_di" bpmnElement="Activity_C2" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="760" y="540" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1c83hs4_di" bpmnElement="Association_1c83hs4">]'
      ,q'[        <di:waypoint x="330" y="329" />]'
      ,q'[        <di:waypoint x="210" y="255" />]'
      ,q'[        <di:waypoint x="278" y="255" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0i9q5wo_di" bpmnElement="TextAnnotation_0i9q5wo">]'
      ,q'[        <dc:Bounds x="570" y="-28" width="280" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_06yrhts_di" bpmnElement="TextAnnotation_06yrhts">]'
      ,q'[        <dc:Bounds x="860" y="-28" width="257.9963073730469" height="81.98529052734375" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1dh1ysa_di" bpmnElement="TextAnnotation_1dh1ysa">]'
      ,q'[        <dc:Bounds x="570" y="201" width="207" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1tdwshf_di" bpmnElement="TextAnnotation_1tdwshf">]'
      ,q'[        <dc:Bounds x="860" y="231" width="180" height="68" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0ehpw4n_di" bpmnElement="TextAnnotation_0ehpw4n">]'
      ,q'[        <dc:Bounds x="850" y="430" width="160" height="82" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_00jstgp_di" bpmnElement="Flow_00jstgp">]'
      ,q'[        <di:waypoint x="278" y="360" />]'
      ,q'[        <di:waypoint x="330" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1i6fc42_di" bpmnElement="Flow_1i6fc42">]'
      ,q'[        <di:waypoint x="430" y="360" />]'
      ,q'[        <di:waypoint x="495" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ngmguv_di" bpmnElement="Flow_1ngmguv">]'
      ,q'[        <di:waypoint x="520" y="335" />]'
      ,q'[        <di:waypoint x="520" y="142" />]'
      ,q'[        <di:waypoint x="600" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xh1wjg_di" bpmnElement="Flow_0xh1wjg">]'
      ,q'[        <di:waypoint x="700" y="142" />]'
      ,q'[        <di:waypoint x="760" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1v6vync_di" bpmnElement="Flow_1v6vync">]'
      ,q'[        <di:waypoint x="860" y="142" />]'
      ,q'[        <di:waypoint x="920" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0emop6i_di" bpmnElement="Flow_0emop6i">]'
      ,q'[        <di:waypoint x="1020" y="142" />]'
      ,q'[        <di:waypoint x="1082" y="142" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1fgochk" bpmnElement="Flow_0mg0jl9">]'
      ,q'[        <di:waypoint x="700" y="360" />]'
      ,q'[        <di:waypoint x="760" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1ipi0cl" bpmnElement="Flow_0m8ne0j">]'
      ,q'[        <di:waypoint x="860" y="360" />]'
      ,q'[        <di:waypoint x="920" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_1j2m5si" bpmnElement="Flow_0cv0t6o">]'
      ,q'[        <di:waypoint x="1020" y="360" />]'
      ,q'[        <di:waypoint x="1082" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_04kv3hq" bpmnElement="Flow_1f9kxmo">]'
      ,q'[        <di:waypoint x="700" y="580" />]'
      ,q'[        <di:waypoint x="760" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_0pgg5lp" bpmnElement="Flow_1dcufu5">]'
      ,q'[        <di:waypoint x="860" y="580" />]'
      ,q'[        <di:waypoint x="920" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="BPMNEdge_13nxtw3" bpmnElement="Flow_0opd4zr">]'
      ,q'[        <di:waypoint x="1020" y="580" />]'
      ,q'[        <di:waypoint x="1082" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02y11qo_di" bpmnElement="Flow_02y11qo">]'
      ,q'[        <di:waypoint x="545" y="360" />]'
      ,q'[        <di:waypoint x="600" y="360" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1a4xxmd_di" bpmnElement="Flow_1a4xxmd">]'
      ,q'[        <di:waypoint x="520" y="385" />]'
      ,q'[        <di:waypoint x="520" y="580" />]'
      ,q'[        <di:waypoint x="600" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_050cm0v_di" bpmnElement="Association_050cm0v">]'
      ,q'[        <di:waypoint x="630" y="102" />]'
      ,q'[        <di:waypoint x="606" y="54" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0bi9txm_di" bpmnElement="Association_0bi9txm">]'
      ,q'[        <di:waypoint x="823" y="102" />]'
      ,q'[        <di:waypoint x="860" y="-13" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1cqii1i_di" bpmnElement="Association_1cqii1i">]'
      ,q'[        <di:waypoint x="830" y="320" />]'
      ,q'[        <di:waypoint x="858" y="265" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hlx4e9_di" bpmnElement="Association_0hlx4e9">]'
      ,q'[        <di:waypoint x="822" y="540" />]'
      ,q'[        <di:waypoint x="842" y="471" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0p3j9kh_di" bpmnElement="TextAnnotation_0p3j9kh">]'
      ,q'[        <dc:Bounds x="278" y="80" width="222" height="188" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_15ubg12">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0a722e0" bpmnElement="Activity_A2">]'
      ,q'[      <bpmndi:BPMNShape id="Event_03m23u4_di" bpmnElement="Event_A2Start">]'
      ,q'[        <dc:Bounds x="-498" y="-168" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-500" y="-125" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0h2vez0_di" bpmnElement="Activity_A2a" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-410" y="-190" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_05xh4ts_di" bpmnElement="Event_A2End">]'
      ,q'[        <dc:Bounds x="32" y="-168" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="32" y="-125" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1miaqnq_di" bpmnElement="Activity_A2c" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-110" y="-190" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1v7o18t_di" bpmnElement="Activity_A2b" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-250" y="-190" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xcd6m0_di" bpmnElement="Flow_0xcd6m0">]'
      ,q'[        <di:waypoint x="-462" y="-150" />]'
      ,q'[        <di:waypoint x="-410" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1alq874_di" bpmnElement="Flow_1alq874">]'
      ,q'[        <di:waypoint x="-310" y="-150" />]'
      ,q'[        <di:waypoint x="-250" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0cvzkj3_di" bpmnElement="Flow_0cvzkj3">]'
      ,q'[        <di:waypoint x="-150" y="-150" />]'
      ,q'[        <di:waypoint x="-110" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0uihkyr_di" bpmnElement="Flow_0uihkyr">]'
      ,q'[        <di:waypoint x="-10" y="-150" />]'
      ,q'[        <di:waypoint x="32" y="-150" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0872cwf">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_10x527o" bpmnElement="Activity_B2">]'
      ,q'[      <bpmndi:BPMNShape id="Event_03ss5oz_di" bpmnElement="Event_B2Start">]'
      ,q'[        <dc:Bounds x="-438" y="-198" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-440" y="-155" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1lwnb6a_di" bpmnElement="Activity_B2a">]'
      ,q'[        <dc:Bounds x="-350" y="-220" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_06jlt4r_di" bpmnElement="Event_B2End">]'
      ,q'[        <dc:Bounds x="-28" y="-198" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-28" y="-155" width="37" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1c4d1sg_di" bpmnElement="Activity_B2b">]'
      ,q'[        <dc:Bounds x="-190" y="-220" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0pvftkr_di" bpmnElement="Flow_0pvftkr">]'
      ,q'[        <di:waypoint x="-402" y="-180" />]'
      ,q'[        <di:waypoint x="-350" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1l3p7hs_di" bpmnElement="Flow_1l3p7hs">]'
      ,q'[        <di:waypoint x="-250" y="-180" />]'
      ,q'[        <di:waypoint x="-190" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0macjlk_di" bpmnElement="Flow_0macjlk">]'
      ,q'[        <di:waypoint x="-90" y="-180" />]'
      ,q'[        <di:waypoint x="-28" y="-180" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_148ytf9">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0zczjb2" bpmnElement="Activity_A2b">]'
      ,q'[      <bpmndi:BPMNShape id="Event_10m6kpa_di" bpmnElement="Event_A2bStart">]'
      ,q'[        <dc:Bounds x="-438" y="-88" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-441" y="-45" width="43" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1woa0md_di" bpmnElement="Activity_A2b1" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-350" y="-110" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0m0g7ri_di" bpmnElement="Activity_A2b2" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="-190" y="-110" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_01fvnpp_di" bpmnElement="Event_A2bEnd">]'
      ,q'[        <dc:Bounds x="-28" y="-88" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-30" y="-45" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mh25vb_di" bpmnElement="Flow_1mh25vb">]'
      ,q'[        <di:waypoint x="-402" y="-70" />]'
      ,q'[        <di:waypoint x="-350" y="-70" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_135tn8v_di" bpmnElement="Flow_135tn8v">]'
      ,q'[        <di:waypoint x="-250" y="-70" />]'
      ,q'[        <di:waypoint x="-190" y="-70" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ipy053_di" bpmnElement="Flow_0ipy053">]'
      ,q'[        <di:waypoint x="-90" y="-70" />]'
      ,q'[        <di:waypoint x="-28" y="-70" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0cmoet0">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_13wwlah" bpmnElement="Activity_B2b">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0lyr3gn_di" bpmnElement="Event_B2BStart">]'
      ,q'[        <dc:Bounds x="-528" y="-128" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-532" y="-85" width="45" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0qdf4xi_di" bpmnElement="Activity_B2B1">]'
      ,q'[        <dc:Bounds x="-440" y="-150" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1wf3c1q_di" bpmnElement="Activity_B2B2">]'
      ,q'[        <dc:Bounds x="-280" y="-150" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1l0ot67_di" bpmnElement="Event_B2BEnd">]'
      ,q'[        <dc:Bounds x="-118" y="-128" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-120" y="-85" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0kc9rpm_di" bpmnElement="Flow_0kc9rpm">]'
      ,q'[        <di:waypoint x="-492" y="-110" />]'
      ,q'[        <di:waypoint x="-440" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0cktw33_di" bpmnElement="Flow_0cktw33">]'
      ,q'[        <di:waypoint x="-340" y="-110" />]'
      ,q'[        <di:waypoint x="-280" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xopiv5_di" bpmnElement="Flow_0xopiv5">]'
      ,q'[        <di:waypoint x="-180" y="-110" />]'
      ,q'[        <di:waypoint x="-118" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_0ncf303">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_0tcn2n9" bpmnElement="Activity_C2">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0gc0w7u_di" bpmnElement="Event_C2Start">]'
      ,q'[        <dc:Bounds x="-558" y="-128" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-560" y="-85" width="41" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1th265y_di" bpmnElement="Activity_C2a">]'
      ,q'[        <dc:Bounds x="-470" y="-150" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0nplyt3_di" bpmnElement="Activity_C2c">]'
      ,q'[        <dc:Bounds x="-150" y="-150" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1yeizp8_di" bpmnElement="Event_C2End">]'
      ,q'[        <dc:Bounds x="12" y="-128" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="13" y="-85" width="34" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_152bw7m_di" bpmnElement="Activity_C2b">]'
      ,q'[        <dc:Bounds x="-310" y="-150" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0l9o9as_di" bpmnElement="Flow_0l9o9as">]'
      ,q'[        <di:waypoint x="-522" y="-110" />]'
      ,q'[        <di:waypoint x="-470" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0v9gdmc_di" bpmnElement="Flow_0v9gdmc">]'
      ,q'[        <di:waypoint x="-370" y="-110" />]'
      ,q'[        <di:waypoint x="-310" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1r97bug_di" bpmnElement="Flow_1r97bug">]'
      ,q'[        <di:waypoint x="-210" y="-110" />]'
      ,q'[        <di:waypoint x="-150" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1buzp0p_di" bpmnElement="Flow_1buzp0p">]'
      ,q'[        <di:waypoint x="-50" y="-110" />]'
      ,q'[        <di:waypoint x="12" y="-110" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1u6oxd8">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1hygx4m" bpmnElement="Activity_C2b">]'
      ,q'[      <bpmndi:BPMNShape id="Event_1pr19p3_di" bpmnElement="Event_1pr19p3">]'
      ,q'[        <dc:Bounds x="-398" y="-138" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-402" y="-95" width="44" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_08nour2_di" bpmnElement="Activity_08nour2">]'
      ,q'[        <dc:Bounds x="-310" y="-160" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_13t68ia_di" bpmnElement="Event_13t68ia">]'
      ,q'[        <dc:Bounds x="-158" y="-138" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="-160" y="-95" width="40" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0nxnzrr_di" bpmnElement="Flow_0nxnzrr">]'
      ,q'[        <di:waypoint x="-362" y="-120" />]'
      ,q'[        <di:waypoint x="-310" y="-120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_066o4bv_di" bpmnElement="Flow_066o4bv">]'
      ,q'[        <di:waypoint x="-210" y="-120" />]'
      ,q'[        <di:waypoint x="-158" y="-120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7g - Iterations and Looped Nested Sub Processes',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
