declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="22.2.0">]'
      ,q'[  <bpmn:process id="ShipGoods_Tut5e" name="Ship Goods - Called by Tutorial 5d" isExecutable="false" apex:isCallable="true" apex:manualInput="false">]'
      ,q'[    <bpmn:extensionElements>]'
      ,q'[      <apex:inVariables>]'
      ,q'[        <apex:processVariable>]'
      ,q'[          <apex:varName>OrderRef</apex:varName>]'
      ,q'[          <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[          <apex:varDescription>Order requiring Shipping</apex:varDescription>]'
      ,q'[        </apex:processVariable>]'
      ,q'[        <apex:processVariable>]'
      ,q'[          <apex:varName>ShippingPriority</apex:varName>]'
      ,q'[          <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[          <apex:varDescription>URGENT or ROUTINE</apex:varDescription>]'
      ,q'[        </apex:processVariable>]'
      ,q'[      </apex:inVariables>]'
      ,q'[      <apex:outVariables>]'
      ,q'[        <apex:processVariable>]'
      ,q'[          <apex:varName>ShipperName</apex:varName>]'
      ,q'[          <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[          <apex:varDescription>Shipper Used</apex:varDescription>]'
      ,q'[        </apex:processVariable>]'
      ,q'[        <apex:processVariable>]'
      ,q'[          <apex:varName>ShippedDate</apex:varName>]'
      ,q'[          <apex:varDataType>DATE</apex:varDataType>]'
      ,q'[          <apex:varDescription>Date Order Shipped</apex:varDescription>]'
      ,q'[        </apex:processVariable>]'
      ,q'[        <apex:processVariable>]'
      ,q'[          <apex:varName>TrackingID:</apex:varName>]'
      ,q'[          <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[          <apex:varDescription>Tracking Reference for Shipment</apex:varDescription>]'
      ,q'[        </apex:processVariable>]'
      ,q'[      </apex:outVariables>]'
      ,q'[    </bpmn:extensionElements>]'
      ,q'[    <bpmn:startEvent id="Event_Ship_Start" name="Goods to Ship">]'
      ,q'[      <bpmn:outgoing>Flow_06qz5ww</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_06qz5ww" sourceRef="Event_Ship_Start" targetRef="Activity_19f7o06" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_1e2h6le" name="ShipPriority?" default="Flow_08yk7ka">]'
      ,q'[      <bpmn:incoming>Flow_1pd2q97</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_URGENT</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_08yk7ka</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1pd2q97" sourceRef="Activity_19f7o06" targetRef="Gateway_1e2h6le" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_URGENT" name="ShippingPriority = &#39;URGENT&#39;" sourceRef="Gateway_1e2h6le" targetRef="Activity_Book_Urgent" apex:sequence="10">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$ShippingPriority = 'URGENT'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_08yk7ka" name="Non Urgent" sourceRef="Gateway_1e2h6le" targetRef="Activity_Find_Routine" apex:sequence="20">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$ShipPriority = 'ROUTINE'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:businessRuleTask id="Activity_Find_Routine" name="Find Cheapest 48hr Service" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>ShipperName</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlFunctionBody</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>declare]'
      ,q'[  l_rand number;]'
      ,q'[  l_carrier varchar2(20);]'
      ,q'[begin]'
      ,q'[  l_rand := sys.dbms_random.value (0,1);]'
      ,q'[  if l_rand &lt; 0.4 then]'
      ,q'[    return 'UPS';]'
      ,q'[  else]'
      ,q'[    return 'DHL';]'
      ,q'[  end if;]'
      ,q'[end;]'
      ,q'[</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_08yk7ka</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0k2vk16</bpmn:outgoing>]'
      ,q'[    </bpmn:businessRuleTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0k2vk16" sourceRef="Activity_Find_Routine" targetRef="Activity_Book_routine" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_0xh1d35">]'
      ,q'[      <bpmn:incoming>Flow_1mqm8p6</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1xjwnbj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_08qzca3</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1mqm8p6" sourceRef="Activity_Book_Urgent" targetRef="Gateway_0xh1d35" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1xjwnbj" sourceRef="Activity_Book_routine" targetRef="Gateway_0xh1d35" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_08qzca3" sourceRef="Gateway_0xh1d35" targetRef="Activity_Pick" apex:sequence="10" />]'
      ,q'[    <bpmn:userTask id="Activity_Pick" name="Pick Goods" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_08qzca3</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1vf2z9i</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:userTask id="Activity_Pack" name="Pack Goods" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>ShippedDate</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>to_date(sysdate,'YYYY-MM-DD HH24:MI:SS')</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1vf2z9i</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_18mfexs</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_18mfexs" sourceRef="Activity_Pack" targetRef="Activity_Mail" />]'
      ,q'[    <bpmn:serviceTask id="Activity_Mail" name="Email Customer Tracking Info" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_18mfexs</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1v4skc4</bpmn:outgoing>]'
      ,q'[    </bpmn:serviceTask>]'
      ,q'[    <bpmn:scriptTask id="Activity_Book_routine" name="Book Shipment" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>TrackingID</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>sys.dbms_random.string(opt=&gt;'U',len=&gt;8)</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0k2vk16</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1xjwnbj</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:scriptTask id="Activity_Book_Urgent" name="Book FedEx NextDay Shipment" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>ShipperName</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>FedEx</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>TrackingID:</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>sys.dbms_random.string(opt=&gt;'U',len=&gt;8)</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_URGENT</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1mqm8p6</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:scriptTask id="Activity_19f7o06" name="Get Order Details and Check Priority" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>null;</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_06qz5ww</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1pd2q97</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:endEvent id="Event_ShipEnd" name="Shipment Complete">]'
      ,q'[      <bpmn:incoming>Flow_1v4skc4</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1v4skc4" sourceRef="Activity_Mail" targetRef="Event_ShipEnd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1vf2z9i" sourceRef="Activity_Pick" targetRef="Activity_Pack" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="ShipGoods_Tut5e">]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1vf2z9i_di" bpmnElement="Flow_1vf2z9i">]'
      ,q'[        <di:waypoint x="1910" y="450" />]'
      ,q'[        <di:waypoint x="1990" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1v4skc4_di" bpmnElement="Flow_1v4skc4">]'
      ,q'[        <di:waypoint x="2270" y="450" />]'
      ,q'[        <di:waypoint x="2352" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_18mfexs_di" bpmnElement="Flow_18mfexs">]'
      ,q'[        <di:waypoint x="2090" y="450" />]'
      ,q'[        <di:waypoint x="2170" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_08qzca3_di" bpmnElement="Flow_08qzca3">]'
      ,q'[        <di:waypoint x="1745" y="450" />]'
      ,q'[        <di:waypoint x="1810" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1xjwnbj_di" bpmnElement="Flow_1xjwnbj">]'
      ,q'[        <di:waypoint x="1630" y="560" />]'
      ,q'[        <di:waypoint x="1720" y="560" />]'
      ,q'[        <di:waypoint x="1720" y="475" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mqm8p6_di" bpmnElement="Flow_1mqm8p6">]'
      ,q'[        <di:waypoint x="1450" y="340" />]'
      ,q'[        <di:waypoint x="1720" y="340" />]'
      ,q'[        <di:waypoint x="1720" y="425" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0k2vk16_di" bpmnElement="Flow_0k2vk16">]'
      ,q'[        <di:waypoint x="1450" y="560" />]'
      ,q'[        <di:waypoint x="1530" y="560" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_08yk7ka_di" bpmnElement="Flow_08yk7ka">]'
      ,q'[        <di:waypoint x="1250" y="475" />]'
      ,q'[        <di:waypoint x="1250" y="560" />]'
      ,q'[        <di:waypoint x="1350" y="560" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1272" y="533" width="55" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_149rygf_di" bpmnElement="Flow_URGENT">]'
      ,q'[        <di:waypoint x="1250" y="425" />]'
      ,q'[        <di:waypoint x="1250" y="340" />]'
      ,q'[        <di:waypoint x="1350" y="340" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1248" y="306" width="84" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1pd2q97_di" bpmnElement="Flow_1pd2q97">]'
      ,q'[        <di:waypoint x="1170" y="450" />]'
      ,q'[        <di:waypoint x="1225" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_06qz5ww_di" bpmnElement="Flow_06qz5ww">]'
      ,q'[        <di:waypoint x="1018" y="450" />]'
      ,q'[        <di:waypoint x="1070" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1w9cwmv_di" bpmnElement="Event_Ship_Start">]'
      ,q'[        <dc:Bounds x="982" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="966" y="475" width="68" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1e2h6le_di" bpmnElement="Gateway_1e2h6le" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1225" y="425" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1179" y="393" width="61" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ep4ycz_di" bpmnElement="Activity_Find_Routine">]'
      ,q'[        <dc:Bounds x="1350" y="520" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0xh1d35_di" bpmnElement="Gateway_0xh1d35" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1695" y="425" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0izavb0_di" bpmnElement="Activity_Pick">]'
      ,q'[        <dc:Bounds x="1810" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_11flad3_di" bpmnElement="Activity_Pack">]'
      ,q'[        <dc:Bounds x="1990" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ez2lb8_di" bpmnElement="Activity_Mail">]'
      ,q'[        <dc:Bounds x="2170" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_10fqo30_di" bpmnElement="Activity_Book_routine">]'
      ,q'[        <dc:Bounds x="1530" y="520" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1eh78qu_di" bpmnElement="Activity_Book_Urgent">]'
      ,q'[        <dc:Bounds x="1350" y="300" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0r8rmow_di" bpmnElement="Activity_19f7o06">]'
      ,q'[        <dc:Bounds x="1070" y="410" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_10evpe0_di" bpmnElement="Event_ShipEnd">]'
      ,q'[        <dc:Bounds x="2352" y="432" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="2347" y="475" width="46" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 5e - ship Goods (Called by Tutorial 5d)',
    pi_dgrm_version => '23.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
