declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:collaboration id="Collaboration_7a">]'
      ,q'[    <bpmn:participant id="Participant_11y0cdc" name="My Process" processRef="Tutorial_7a" />]'
      ,q'[    <bpmn:participant id="Participant_1n4c4l0" name="This is an &#39;Empty Pool&#39; and represents another process as a &#39;Black Box&#39; - i.e., we don&#39;t know about the internal implementation details." />]'
      ,q'[    <bpmn:participant id="Participant_0qabxrw" name="Another Process" processRef="Process_0u5as8x" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1mf0t72" sourceRef="Activity_0izlkl1" targetRef="Participant_1n4c4l0" />]'
      ,q'[    <bpmn:messageFlow id="Flow_19l2sy0" sourceRef="Participant_1n4c4l0" targetRef="Activity_0izlkl1" />]'
      ,q'[    <bpmn:messageFlow id="Flow_0hqqiiu" sourceRef="Activity_0mhkzh2" targetRef="Participant_1n4c4l0" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1rtp00p" sourceRef="Participant_1n4c4l0" targetRef="Activity_0zzol2u" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1h2ekkn" sourceRef="Event_0m1a6k2" targetRef="Event_1k9dkfm" />]'
      ,q'[    <bpmn:messageFlow id="Flow_13gq3gc" sourceRef="Event_1m4gahw" targetRef="Event_02gdru8" />]'
      ,q'[    <bpmn:messageFlow id="Flow_07c9y3f" sourceRef="Activity_1w25uqw" targetRef="Event_1qhlqtm" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0gyba6i">]'
      ,q'[      <bpmn:text>We can also put ]'
      ,q'[message boundary events*  onto tasks, subProcesses, and Call Activities.  These can interrupt or be non-interrupting</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1nxz8a7">]'
      ,q'[      <bpmn:text>This is another process, which gets  started by an incoming message</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0igizeg" associationDirection="None" sourceRef="Event_1qhlqtm" targetRef="TextAnnotation_1nxz8a7" />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id="Tutorial_7a" name="Tutorial 7a - MessageFlow Basics" isExecutable="false">]'
      ,q'[    <bpmn:laneSet id="LaneSet_0zv5eda">]'
      ,q'[      <bpmn:lane id="Lane_136ry9p" apex:isRole="false">]'
      ,q'[        <bpmn:flowNodeRef>Event_0s323xl</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0mhkzh2</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_12krons</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0zzol2u</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1cmxdp7</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0s2za6d</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0izlkl1</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_0zba19v</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1u4gq6u</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Gateway_1gb2wji</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1w25uqw</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[      <bpmn:lane id="Lane_0uo74go" apex:isRole="false">]'
      ,q'[        <bpmn:flowNodeRef>Activity_04nvebw</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0t1ev9d</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_1id6b5x</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Activity_0fixygu</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_0m1a6k2</bpmn:flowNodeRef>]'
      ,q'[        <bpmn:flowNodeRef>Event_02gdru8</bpmn:flowNodeRef>]'
      ,q'[      </bpmn:lane>]'
      ,q'[    </bpmn:laneSet>]'
      ,q'[    <bpmn:startEvent id="Event_0s323xl">]'
      ,q'[      <bpmn:outgoing>Flow_17b6g1h</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_17b6g1h" sourceRef="Event_0s323xl" targetRef="Activity_0izlkl1" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0xtgyk0" sourceRef="Activity_0izlkl1" targetRef="Activity_1u4gq6u" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1bw7mvj" sourceRef="Activity_1u4gq6u" targetRef="Activity_1w25uqw" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0a9vat2" sourceRef="Gateway_1gb2wji" targetRef="Activity_0mhkzh2" apex:sequence="10" />]'
      ,q'[    <bpmn:sendTask id="Activity_0mhkzh2" name="SendTask" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0a9vat2</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1co4h5b</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_111ldh8" sourceRef="Gateway_1gb2wji" targetRef="Activity_0zzol2u" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0wa3yvx" sourceRef="Gateway_1gb2wji" targetRef="Event_0m1a6k2" apex:sequence="30" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1u9z9zl" sourceRef="Gateway_1gb2wji" targetRef="Event_02gdru8" apex:sequence="40" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02w8qhh" sourceRef="Gateway_1gb2wji" targetRef="Activity_0fixygu" apex:sequence="50" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1co4h5b" sourceRef="Activity_0mhkzh2" targetRef="Gateway_12krons" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_12krons">]'
      ,q'[      <bpmn:incoming>Flow_1co4h5b</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_149xi7o</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1pxnz40</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0umsd4h</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0vmcx38</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0g67vgs</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_149xi7o" sourceRef="Activity_0zzol2u" targetRef="Gateway_12krons" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1pxnz40" sourceRef="Activity_0fixygu" targetRef="Gateway_12krons" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0umsd4h" sourceRef="Event_0m1a6k2" targetRef="Gateway_12krons" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0vmcx38" sourceRef="Event_02gdru8" targetRef="Gateway_12krons" apex:sequence="10" />]'
      ,q'[    <bpmn:receiveTask id="Activity_0zzol2u" name="ReceiveTask" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_111ldh8</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_149xi7o</bpmn:outgoing>]'
      ,q'[    </bpmn:receiveTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1inbmjx" sourceRef="Gateway_0zba19v" targetRef="Activity_1cmxdp7" apex:sequence="10" />]'
      ,q'[    <bpmn:task id="Activity_1cmxdp7" name="A Message Has to exactly match the subscription created for it">]'
      ,q'[      <bpmn:incoming>Flow_1inbmjx</bpmn:incoming>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0g67vgs" sourceRef="Gateway_12krons" targetRef="Gateway_0zba19v" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0p4dldk" sourceRef="Gateway_0zba19v" targetRef="Activity_0s2za6d" />]'
      ,q'[    <bpmn:task id="Activity_0s2za6d" name="A subscription must be created by the receiver before the message is sent">]'
      ,q'[      <bpmn:incoming>Flow_0p4dldk</bpmn:incoming>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_05lb32a" sourceRef="Gateway_0zba19v" targetRef="Activity_04nvebw" />]'
      ,q'[    <bpmn:task id="Activity_04nvebw" name="in 23.1 message flow is only between processes in the same workspace">]'
      ,q'[      <bpmn:incoming>Flow_05lb32a</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0vmjyh0</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0vmjyh0" sourceRef="Activity_04nvebw" targetRef="Activity_0t1ev9d" />]'
      ,q'[    <bpmn:task id="Activity_0t1ev9d" name="....but we hope to add more capabilities soon!">]'
      ,q'[      <bpmn:incoming>Flow_0vmjyh0</bpmn:incoming>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_1id6b5x" name="Tutorials 7b and 7c can be run to show message flow..">]'
      ,q'[      <bpmn:incoming>Flow_1h798dh</bpmn:incoming>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1h798dh" sourceRef="Gateway_0zba19v" targetRef="Activity_1id6b5x" />]'
      ,q'[    <bpmn:task id="Activity_0fixygu" name="..or you can use message Events (better practice)">]'
      ,q'[      <bpmn:incoming>Flow_02w8qhh</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1pxnz40</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_0izlkl1" name="Messageflow allows you to pass messages into or out of a process">]'
      ,q'[      <bpmn:incoming>Flow_17b6g1h</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0xtgyk0</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:parallelGateway id="Gateway_0zba19v">]'
      ,q'[      <bpmn:incoming>Flow_0g67vgs</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1inbmjx</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0p4dldk</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_05lb32a</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1h798dh</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_09nusca" sourceRef="Activity_1w25uqw" targetRef="Gateway_1gb2wji" />]'
      ,q'[    <bpmn:task id="Activity_1u4gq6u" name="A Receiver subscribes to a message then waits for it to arrive">]'
      ,q'[      <bpmn:incoming>Flow_0xtgyk0</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1bw7mvj</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_1gb2wji">]'
      ,q'[      <bpmn:incoming>Flow_09nusca</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0a9vat2</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_111ldh8</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0wa3yvx</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1u9z9zl</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_02w8qhh</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sendTask id="Activity_1w25uqw" name="Send Task" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_1bw7mvj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_09nusca</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:intermediateThrowEvent id="Event_0m1a6k2" name="Message Throw Event" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0wa3yvx</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0umsd4h</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0v9snn7" />]'
      ,q'[    </bpmn:intermediateThrowEvent>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_02gdru8" name="Message Catch Event" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_1u9z9zl</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0vmcx38</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_10qaiem" />]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0iqi3gb">]'
      ,q'[      <bpmn:text>MessageFlow only works BETWEEN processes and CANNOT be used WITHIN a process - where you use Sequence Flow (solid lines)</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0g76b8t">]'
      ,q'[      <bpmn:text>Don't run this tutorial</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_055qq8e" sourceRef="Event_0s323xl" targetRef="TextAnnotation_0g76b8t" />]'
      ,q'[    <bpmn:association id="Association_10wi0mu" sourceRef="Activity_0izlkl1" targetRef="TextAnnotation_0iqi3gb" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmn:process id="Process_0u5as8x">]'
      ,q'[    <bpmn:startEvent id="Event_1qhlqtm" name="Message Start Event *" apex:type="simpleMessage">]'
      ,q'[      <bpmn:outgoing>Flow_1ksryuz</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0nlo0kb" />]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ksryuz" sourceRef="Event_1qhlqtm" targetRef="Activity_064bqdb" />]'
      ,q'[    <bpmn:task id="Activity_064bqdb" name="This process was started by the incoming message">]'
      ,q'[      <bpmn:incoming>Flow_1ksryuz</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_14l9gvf</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_14l9gvf" sourceRef="Activity_064bqdb" targetRef="Event_1k9dkfm" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0j888id" sourceRef="Event_1k9dkfm" targetRef="Event_1m4gahw" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_03pslu3" sourceRef="Event_1m4gahw" targetRef="Event_0bqx3lb" />]'
      ,q'[    <bpmn:task id="Activity_1k56x55" name="Task">]'
      ,q'[      <bpmn:outgoing>Flow_07deqwm</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:boundaryEvent id="Event_1bft1qt" name="Non-Interrupting Message Boundary Event*" apex:type="simpleMessage" cancelActivity="false" attachedToRef="Activity_1k56x55">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1nlcya3" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:boundaryEvent id="Event_12pdldq" name="Interrupting Message Boundary Event*" apex:type="simpleMessage" attachedToRef="Activity_1k56x55">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0pz73ap" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07deqwm" sourceRef="Activity_1k56x55" targetRef="Activity_0zw04ka" />]'
      ,q'[    <bpmn:subProcess id="Activity_0zw04ka" name="Sub Process">]'
      ,q'[      <bpmn:incoming>Flow_07deqwm</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0twpz2i</bpmn:outgoing>]'
      ,q'[    </bpmn:subProcess>]'
      ,q'[    <bpmn:boundaryEvent id="Event_1y7gbua" name="Non-Interrupting Message Boundary Event*" apex:type="simpleMessage" cancelActivity="false" attachedToRef="Activity_0zw04ka">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_04uruif" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:boundaryEvent id="Event_03560w5" name="Interrupting Message Boundary Event*" apex:type="simpleMessage" attachedToRef="Activity_0zw04ka">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1fqemmv" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_1k9dkfm" name="Message Catch &#10;- waits for &#10;matched incoming message" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_14l9gvf</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0j888id</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1fmx7hd" />]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:intermediateThrowEvent id="Event_1m4gahw" name="Message Throw Sends a Message" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0j888id</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_03pslu3</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_07ab261" />]'
      ,q'[    </bpmn:intermediateThrowEvent>]'
      ,q'[    <bpmn:endEvent id="Event_0bqx3lb" name="Message End Event *&#10;- throws a &#10;message when it ends" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_03pslu3</bpmn:incoming>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0381hmv" />]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:callActivity id="Activity_17locw8" name="Call Activity" apex:manualInput="false" apex:calledDiagramVersionSelection="latestVersion">]'
      ,q'[      <bpmn:incoming>Flow_0twpz2i</bpmn:incoming>]'
      ,q'[    </bpmn:callActivity>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0twpz2i" sourceRef="Activity_0zw04ka" targetRef="Activity_17locw8" />]'
      ,q'[    <bpmn:boundaryEvent id="Event_16ppomb" name="Interrupting Message Boundary Event*" apex:type="simpleMessage" attachedToRef="Activity_17locw8">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1ao7gro" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:boundaryEvent id="Event_15i3bqd" name="Non-Interrupting Message Boundary Event*" apex:type="simpleMessage" cancelActivity="false" attachedToRef="Activity_17locw8">]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0s312sl" />]'
      ,q'[    </bpmn:boundaryEvent>]'
      ,q'[    <bpmn:association id="Association_0hbfzmk" associationDirection="None" sourceRef="Event_0bqx3lb" targetRef="TextAnnotation_0gyba6i" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_7a">]'
      ,q'[      <bpmndi:BPMNShape id="Participant_11y0cdc_di" bpmnElement="Participant_11y0cdc" isHorizontal="true" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="210" y="340" width="1430" height="570" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_0uo74go_di" bpmnElement="Lane_0uo74go" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="240" y="615" width="1400" height="295" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Lane_136ry9p_di" bpmnElement="Lane_136ry9p" isHorizontal="true">]'
      ,q'[        <dc:Bounds x="240" y="340" width="1400" height="275" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0s323xl_di" bpmnElement="Event_0s323xl">]'
      ,q'[        <dc:Bounds x="282" y="502" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1cxnaxb_di" bpmnElement="Activity_0mhkzh2">]'
      ,q'[        <dc:Bounds x="780" y="360" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_12krons_di" bpmnElement="Gateway_12krons" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="955" y="495" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1jcn5z7_di" bpmnElement="Activity_0zzol2u">]'
      ,q'[        <dc:Bounds x="830" y="480" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1cmxdp7_di" bpmnElement="Activity_1cmxdp7">]'
      ,q'[        <dc:Bounds x="1220" y="410" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0s2za6d_di" bpmnElement="Activity_0s2za6d">]'
      ,q'[        <dc:Bounds x="1220" y="530" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_04nvebw_di" bpmnElement="Activity_04nvebw">]'
      ,q'[        <dc:Bounds x="1220" y="650" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0t1ev9d_di" bpmnElement="Activity_0t1ev9d">]'
      ,q'[        <dc:Bounds x="1360" y="650" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1id6b5x_di" bpmnElement="Activity_1id6b5x">]'
      ,q'[        <dc:Bounds x="1220" y="810" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0fixygu_di" bpmnElement="Activity_0fixygu">]'
      ,q'[        <dc:Bounds x="780" y="580" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0izlkl1_di" bpmnElement="Activity_0izlkl1">]'
      ,q'[        <dc:Bounds x="350" y="480" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_04a3o2p_di" bpmnElement="Gateway_0zba19v">]'
      ,q'[        <dc:Bounds x="1105" y="495" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1u4gq6u_di" bpmnElement="Activity_1u4gq6u">]'
      ,q'[        <dc:Bounds x="470" y="480" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1gb2wji_di" bpmnElement="Gateway_1gb2wji" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="725" y="495" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_052ti0x_di" bpmnElement="Activity_1w25uqw" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="600" y="480" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1euj7p8_di" bpmnElement="Event_0m1a6k2" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="782" y="722" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="830" y="746" width="79" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0vatlax_di" bpmnElement="Event_02gdru8" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="902" y="812" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="901" y="776" width="77" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0iqi3gb_di" bpmnElement="TextAnnotation_0iqi3gb">]'
      ,q'[        <dc:Bounds x="340" y="660" width="160" height="96" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0g76b8t_di" bpmnElement="TextAnnotation_0g76b8t">]'
      ,q'[        <dc:Bounds x="260" y="380" width="99.9875821019153" height="41.337466732851176" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_17b6g1h_di" bpmnElement="Flow_17b6g1h">]'
      ,q'[        <di:waypoint x="318" y="520" />]'
      ,q'[        <di:waypoint x="350" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xtgyk0_di" bpmnElement="Flow_0xtgyk0">]'
      ,q'[        <di:waypoint x="450" y="520" />]'
      ,q'[        <di:waypoint x="470" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1bw7mvj_di" bpmnElement="Flow_1bw7mvj">]'
      ,q'[        <di:waypoint x="570" y="520" />]'
      ,q'[        <di:waypoint x="600" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0a9vat2_di" bpmnElement="Flow_0a9vat2">]'
      ,q'[        <di:waypoint x="750" y="495" />]'
      ,q'[        <di:waypoint x="750" y="400" />]'
      ,q'[        <di:waypoint x="780" y="400" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_111ldh8_di" bpmnElement="Flow_111ldh8">]'
      ,q'[        <di:waypoint x="775" y="520" />]'
      ,q'[        <di:waypoint x="830" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0wa3yvx_di" bpmnElement="Flow_0wa3yvx">]'
      ,q'[        <di:waypoint x="750" y="545" />]'
      ,q'[        <di:waypoint x="750" y="740" />]'
      ,q'[        <di:waypoint x="782" y="740" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1u9z9zl_di" bpmnElement="Flow_1u9z9zl">]'
      ,q'[        <di:waypoint x="750" y="545" />]'
      ,q'[        <di:waypoint x="750" y="830" />]'
      ,q'[        <di:waypoint x="902" y="830" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02w8qhh_di" bpmnElement="Flow_02w8qhh">]'
      ,q'[        <di:waypoint x="750" y="545" />]'
      ,q'[        <di:waypoint x="750" y="620" />]'
      ,q'[        <di:waypoint x="780" y="620" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1co4h5b_di" bpmnElement="Flow_1co4h5b">]'
      ,q'[        <di:waypoint x="880" y="400" />]'
      ,q'[        <di:waypoint x="980" y="400" />]'
      ,q'[        <di:waypoint x="980" y="495" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_149xi7o_di" bpmnElement="Flow_149xi7o">]'
      ,q'[        <di:waypoint x="930" y="520" />]'
      ,q'[        <di:waypoint x="955" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1pxnz40_di" bpmnElement="Flow_1pxnz40">]'
      ,q'[        <di:waypoint x="880" y="620" />]'
      ,q'[        <di:waypoint x="980" y="620" />]'
      ,q'[        <di:waypoint x="980" y="545" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0umsd4h_di" bpmnElement="Flow_0umsd4h">]'
      ,q'[        <di:waypoint x="818" y="740" />]'
      ,q'[        <di:waypoint x="980" y="740" />]'
      ,q'[        <di:waypoint x="980" y="545" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0vmcx38_di" bpmnElement="Flow_0vmcx38">]'
      ,q'[        <di:waypoint x="938" y="830" />]'
      ,q'[        <di:waypoint x="980" y="830" />]'
      ,q'[        <di:waypoint x="980" y="545" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1inbmjx_di" bpmnElement="Flow_1inbmjx">]'
      ,q'[        <di:waypoint x="1130" y="495" />]'
      ,q'[        <di:waypoint x="1130" y="450" />]'
      ,q'[        <di:waypoint x="1220" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0g67vgs_di" bpmnElement="Flow_0g67vgs">]'
      ,q'[        <di:waypoint x="1005" y="520" />]'
      ,q'[        <di:waypoint x="1105" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0p4dldk_di" bpmnElement="Flow_0p4dldk">]'
      ,q'[        <di:waypoint x="1130" y="545" />]'
      ,q'[        <di:waypoint x="1130" y="570" />]'
      ,q'[        <di:waypoint x="1220" y="570" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_05lb32a_di" bpmnElement="Flow_05lb32a">]'
      ,q'[        <di:waypoint x="1130" y="545" />]'
      ,q'[        <di:waypoint x="1130" y="690" />]'
      ,q'[        <di:waypoint x="1220" y="690" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0vmjyh0_di" bpmnElement="Flow_0vmjyh0">]'
      ,q'[        <di:waypoint x="1320" y="690" />]'
      ,q'[        <di:waypoint x="1360" y="690" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1h798dh_di" bpmnElement="Flow_1h798dh">]'
      ,q'[        <di:waypoint x="1130" y="545" />]'
      ,q'[        <di:waypoint x="1130" y="850" />]'
      ,q'[        <di:waypoint x="1220" y="850" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_09nusca_di" bpmnElement="Flow_09nusca">]'
      ,q'[        <di:waypoint x="700" y="520" />]'
      ,q'[        <di:waypoint x="725" y="520" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_055qq8e_di" bpmnElement="Association_055qq8e">]'
      ,q'[        <di:waypoint x="293" y="503" />]'
      ,q'[        <di:waypoint x="260" y="421" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_10wi0mu_di" bpmnElement="Association_10wi0mu">]'
      ,q'[        <di:waypoint x="397" y="560" />]'
      ,q'[        <di:waypoint x="388" y="660" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_0wxmvig_di" bpmnElement="Participant_1n4c4l0" isHorizontal="true" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="210" y="230" width="1240" height="60" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_1ruoh75_di" bpmnElement="Participant_0qabxrw" isHorizontal="true" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="210" y="990" width="1420" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1m5awsm_di" bpmnElement="Event_1qhlqtm" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="392" y="1102" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="375" y="1145" width="71" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_064bqdb_di" bpmnElement="Activity_064bqdb">]'
      ,q'[        <dc:Bounds x="500" y="1080" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1k56x55_di" bpmnElement="Activity_1k56x55" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1180" y="1080" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1c0y1rf_di" bpmnElement="Activity_0zw04ka" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1330" y="1080" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_10689f2_di" bpmnElement="Event_1k9dkfm" bioc:stroke="#5b176d" bioc:fill="#e1bee7" color:background-color="#e1bee7" color:border-color="#5b176d">]'
      ,q'[        <dc:Bounds x="702" y="1102" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="680" y="1145" width="80" height="66" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_06jzlam_di" bpmnElement="Event_1m4gahw" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="832" y="1102" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="806" y="1145" width="89" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0ppnav5_di" bpmnElement="Event_0bqx3lb">]'
      ,q'[        <dc:Bounds x="932" y="1102" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="909" y="1145" width="83" height="66" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1p1t10d_di" bpmnElement="Activity_17locw8" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1480" y="1080" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_02xknjy_di" bpmnElement="Event_15i3bqd">]'
      ,q'[        <dc:Bounds x="1512" y="1062" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1488" y="1010" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1aq7eka_di" bpmnElement="Event_16ppomb">]'
      ,q'[        <dc:Bounds x="1482" y="1142" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1459" y="1185" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0wkpvzk_di" bpmnElement="Event_03560w5">]'
      ,q'[        <dc:Bounds x="1332" y="1142" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1309" y="1185" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1a2pfey_di" bpmnElement="Event_1y7gbua">]'
      ,q'[        <dc:Bounds x="1362" y="1062" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1338" y="1010" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0p9k8lt_di" bpmnElement="Event_12pdldq">]'
      ,q'[        <dc:Bounds x="1212" y="1142" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1189" y="1185" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0i3hcnq_di" bpmnElement="Event_1bft1qt">]'
      ,q'[        <dc:Bounds x="1212" y="1062" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1189" y="1010" width="83" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ksryuz_di" bpmnElement="Flow_1ksryuz">]'
      ,q'[        <di:waypoint x="428" y="1120" />]'
      ,q'[        <di:waypoint x="500" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_14l9gvf_di" bpmnElement="Flow_14l9gvf">]'
      ,q'[        <di:waypoint x="600" y="1120" />]'
      ,q'[        <di:waypoint x="702" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0j888id_di" bpmnElement="Flow_0j888id">]'
      ,q'[        <di:waypoint x="738" y="1120" />]'
      ,q'[        <di:waypoint x="832" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_03pslu3_di" bpmnElement="Flow_03pslu3">]'
      ,q'[        <di:waypoint x="868" y="1120" />]'
      ,q'[        <di:waypoint x="932" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07deqwm_di" bpmnElement="Flow_07deqwm">]'
      ,q'[        <di:waypoint x="1280" y="1120" />]'
      ,q'[        <di:waypoint x="1330" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0twpz2i_di" bpmnElement="Flow_0twpz2i">]'
      ,q'[        <di:waypoint x="1430" y="1120" />]'
      ,q'[        <di:waypoint x="1480" y="1120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hbfzmk_di" bpmnElement="Association_0hbfzmk">]'
      ,q'[        <di:waypoint x="966" y="1112" />]'
      ,q'[        <di:waypoint x="1020" y="1085" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0igizeg_di" bpmnElement="Association_0igizeg">]'
      ,q'[        <di:waypoint x="393" y="1124" />]'
      ,q'[        <di:waypoint x="250" y="1160" />]'
      ,q'[        <di:waypoint x="250" y="1075" />]'
      ,q'[        <di:waypoint x="270" y="1075" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0gyba6i_di" bpmnElement="TextAnnotation_0gyba6i">]'
      ,q'[        <dc:Bounds x="1020" y="1020" width="150" height="130" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mf0t72_di" bpmnElement="Flow_1mf0t72">]'
      ,q'[        <di:waypoint x="380" y="480" />]'
      ,q'[        <di:waypoint x="380" y="290" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_19l2sy0_di" bpmnElement="Flow_19l2sy0">]'
      ,q'[        <di:waypoint x="420" y="290" />]'
      ,q'[        <di:waypoint x="420" y="480" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0hqqiiu_di" bpmnElement="Flow_0hqqiiu">]'
      ,q'[        <di:waypoint x="830" y="360" />]'
      ,q'[        <di:waypoint x="830" y="290" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1rtp00p_di" bpmnElement="Flow_1rtp00p">]'
      ,q'[        <di:waypoint x="900" y="290" />]'
      ,q'[        <di:waypoint x="900" y="480" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1h2ekkn_di" bpmnElement="Flow_1h2ekkn">]'
      ,q'[        <di:waypoint x="800" y="758" />]'
      ,q'[        <di:waypoint x="800" y="930" />]'
      ,q'[        <di:waypoint x="720" y="930" />]'
      ,q'[        <di:waypoint x="720" y="1100" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_13gq3gc_di" bpmnElement="Flow_13gq3gc">]'
      ,q'[        <di:waypoint x="850" y="1102" />]'
      ,q'[        <di:waypoint x="850" y="975" />]'
      ,q'[        <di:waypoint x="920" y="975" />]'
      ,q'[        <di:waypoint x="920" y="848" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07c9y3f_di" bpmnElement="Flow_07c9y3f">]'
      ,q'[        <di:waypoint x="650" y="560" />]'
      ,q'[        <di:waypoint x="650" y="1020" />]'
      ,q'[        <di:waypoint x="410" y="1020" />]'
      ,q'[        <di:waypoint x="410" y="1102" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1nxz8a7_di" bpmnElement="TextAnnotation_1nxz8a7">]'
      ,q'[        <dc:Bounds x="270" y="1020" width="100" height="110" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_01egisp">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1lz6x7p" bpmnElement="Activity_0zw04ka" />]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7a - MessageFlow Basics',
    pi_dgrm_short_description => 'Flows for APEX BPMN Tutorial - part 7a - introduces inter-process communication between collaborating processes - using BPMN message flow.  Executing this tutorial requires the Flows for APEX Enterprise Edition.',
    pi_dgrm_description => '**Overview:**  
The BPMN (Business Process Model and Notation) diagram focuses on complex interactions between multiple business processes through message flows. The model captures key scenarios where processes communicate and coordinate by exchanging messages. This efficient messaging system allows for seamless interaction, streamlining operations while ensuring clarity on process roles.  
  
Executing this diagram requires the Flows for APEX Enterprise Edition, which supports all of the message flow tasks and events in this diagram.  If you only have the Community Edition but are curious to see how this works, you can still look at the model and try to understand it from the process definition.

**Key Components:**

**Collaboration & Participants:**

*   Three main processes are involved:
    *   **My Process:** The core process depicted.
    *   **Another Process:** Shows the interaction with another known process.
    *   **Empty Pool (Black Box):** Represents an external process with unknown internal workings but engages in message exchanges.

**Message Flows:**

*   Highlight the communication channels between processes.
*   Message flows connect activities across different pools (process boundaries), enabling synchronization and coordination between independent processes.

**Task Elements:**

*   **Send and Receive Tasks:** Tasks that send or receive messages, indicating an essential part of process communication.
*   **Gateway Controls:** Manage decision-making and the routing of message flows between processes.
*   **Boundary Events:** Indicate specific events interrupting or not interrupting associated tasks based on message receipt.

**Integration Features:**

*   **Intermediate Events and Catch/Throw Mechanisms:** Facilitate asynchronous interactions allowing processes to pause execution until a required message is received or to initiate an action once a message is sent.
*   **Call Activities:** Allow reusability and integration of subprocesses across distinct process structures.

**Implementation Benefits:**

*   **Efficiency Improvement:** Streamlined communication paths cut down the need for manual interventions and reduce potential errors in process interactions.
*   **Scalability:** The modular design ensures easy adaptation and scaling by adding or modifying existing message flows and task sequences.
*   **Transparency and Control:** Provides visibility into the interactions among various processes and numerous decision points, aiding in quick identification and resolution of bottlenecks or issues.

This BPMN model effectively demonstrates how message flow strategies can be employed to improve process efficiency, ensuring seamless and real-time communication between diverse processes within an organization.',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
