declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial3b" name="Tutorial 3b - Substitution and Bind Syntax" isExecutable="false" apex:isCallable="false" apex:manualInput="false">]'
      ,q'[    <bpmn:startEvent id="Event_1plpgom">]'
      ,q'[      <bpmn:outgoing>Flow_1ec73q3</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0ozxsb9" name="Concept 1:&#10;Using Process Variables">]'
      ,q'[      <bpmn:incoming>Flow_1ec73q3</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0r29a9k</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ec73q3" sourceRef="Event_1plpgom" targetRef="Activity_0ozxsb9" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0r29a9k" sourceRef="Activity_0ozxsb9" targetRef="Gateway_0k7wwo7" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_0k7wwo7">]'
      ,q'[      <bpmn:incoming>Flow_0r29a9k</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1gcfz9u</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0k2h11g</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_08olq9m</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0inf8qr</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0vsy08g</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1rz8nif</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_10y1yso" name="In a Timer Definition">]'
      ,q'[      <bpmn:incoming>Flow_1gcfz9u</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_048u5lq</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1gcfz9u" sourceRef="Gateway_0k7wwo7" targetRef="Activity_10y1yso" />]'
      ,q'[    <bpmn:task id="Activity_0j6pujb" name="In a Gateway">]'
      ,q'[      <bpmn:incoming>Flow_0k2h11g</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0klopa5</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0k2h11g" sourceRef="Gateway_0k7wwo7" targetRef="Activity_0j6pujb" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0klopa5" sourceRef="Activity_0j6pujb" targetRef="Gateway_04509o5" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_048u5lq" sourceRef="Activity_10y1yso" targetRef="Event_0iob1po" />]'
      ,q'[    <bpmn:task id="Activity_0946wwh" name="In a Task">]'
      ,q'[      <bpmn:incoming>Flow_08olq9m</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1vdold9</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_08olq9m" sourceRef="Gateway_0k7wwo7" targetRef="Activity_0946wwh" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1vdold9" sourceRef="Activity_0946wwh" targetRef="Gateway_11x8qex" />]'
      ,q'[    <bpmn:task id="Activity_1w8et0w" name="In a UserTask - APEX Page call">]'
      ,q'[      <bpmn:incoming>Flow_0inf8qr</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1hk6xxp</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0inf8qr" sourceRef="Gateway_0k7wwo7" targetRef="Activity_1w8et0w" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1hk6xxp" sourceRef="Activity_1w8et0w" targetRef="Activity_025ghr0" />]'
      ,q'[    <bpmn:task id="Activity_1wyrdke" name="In a UserTask - APEX Approval call">]'
      ,q'[      <bpmn:incoming>Flow_0vsy08g</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1vqhn5f</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0vsy08g" sourceRef="Gateway_0k7wwo7" targetRef="Activity_1wyrdke" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1vqhn5f" sourceRef="Activity_1wyrdke" targetRef="Activity_00ikjar" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_11x8qex">]'
      ,q'[      <bpmn:incoming>Flow_1vdold9</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_01ahvyv</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1nhbi01</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0ngmayk</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0yg5gl0</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0zkr82p</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_16cbzmb</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02zdkhv</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_0uu2coh" name="Concept 2; How?">]'
      ,q'[      <bpmn:incoming>Flow_02zdkhv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ylq0wi</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02zdkhv" sourceRef="Gateway_11x8qex" targetRef="Activity_0uu2coh" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ylq0wi" sourceRef="Activity_0uu2coh" targetRef="Gateway_0but2hg" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_0but2hg">]'
      ,q'[      <bpmn:incoming>Flow_1ylq0wi</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_07bi894</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0n5ncld</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_109wr9z" name="Substitution Syntax">]'
      ,q'[      <bpmn:incoming>Flow_07bi894</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_18ek31f</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07bi894" sourceRef="Gateway_0but2hg" targetRef="Activity_109wr9z" />]'
      ,q'[    <bpmn:task id="Activity_0l3xwhd" name="Bind Syntax">]'
      ,q'[      <bpmn:incoming>Flow_0n5ncld</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0tljhpd</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0n5ncld" sourceRef="Gateway_0but2hg" targetRef="Activity_0l3xwhd" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_18ek31f" sourceRef="Activity_109wr9z" targetRef="Gateway_066hu8c" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_066hu8c">]'
      ,q'[      <bpmn:incoming>Flow_18ek31f</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0tljhpd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0bfhz6m</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0tljhpd" sourceRef="Activity_0l3xwhd" targetRef="Gateway_066hu8c" />]'
      ,q'[    <bpmn:task id="Activity_064ohbq" name="Concept 3:&#10;Things to Remember">]'
      ,q'[      <bpmn:incoming>Flow_0bfhz6m</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_024p93z</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0bfhz6m" sourceRef="Gateway_066hu8c" targetRef="Activity_064ohbq" />]'
      ,q'[    <bpmn:task id="Activity_1krbaa9" name="Substitution is always VARCHAR2 only">]'
      ,q'[      <bpmn:incoming>Flow_040sz4v</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1yoridh</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_024p93z" sourceRef="Activity_064ohbq" targetRef="Gateway_0oiud3h" />]'
      ,q'[    <bpmn:endEvent id="Event_1d8h7t2">]'
      ,q'[      <bpmn:incoming>Flow_1yoridh</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1yoridh" sourceRef="Activity_1krbaa9" targetRef="Event_1d8h7t2" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_040sz4v" sourceRef="Gateway_0oiud3h" targetRef="Activity_1krbaa9" apex:sequence="10" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_0oiud3h">]'
      ,q'[      <bpmn:incoming>Flow_024p93z</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_040sz4v</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_07ut43o</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1bedtbq</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0h58bew</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1yn9h9h</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_04jc012" name="Dates always use the format YYYY-MM-DD HH24MI:SS">]'
      ,q'[      <bpmn:incoming>Flow_07ut43o</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1en3v8m</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_07ut43o" sourceRef="Gateway_0oiud3h" targetRef="Activity_04jc012" />]'
      ,q'[    <bpmn:endEvent id="Event_0epw44y">]'
      ,q'[      <bpmn:incoming>Flow_1en3v8m</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1en3v8m" sourceRef="Activity_04jc012" targetRef="Event_0epw44y" />]'
      ,q'[    <bpmn:task id="Activity_1543y23" name="Binding can be used in all expressions, function bodies, scripts in 23.1">]'
      ,q'[      <bpmn:incoming>Flow_1bedtbq</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1bw826o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1bedtbq" sourceRef="Gateway_0oiud3h" targetRef="Activity_1543y23" />]'
      ,q'[    <bpmn:endEvent id="Event_08bp25i">]'
      ,q'[      <bpmn:incoming>Flow_1bw826o</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1bw826o" sourceRef="Activity_1543y23" targetRef="Event_08bp25i" />]'
      ,q'[    <bpmn:task id="Activity_19cz6nm" name="Using Call Activities?&#10;See Tutorial 8d (scoping)">]'
      ,q'[      <bpmn:incoming>Flow_0h58bew</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_08fk99d</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0h58bew" sourceRef="Gateway_0oiud3h" targetRef="Activity_19cz6nm" />]'
      ,q'[    <bpmn:endEvent id="Event_End5">]'
      ,q'[      <bpmn:incoming>Flow_08fk99d</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_08fk99d" sourceRef="Activity_19cz6nm" targetRef="Event_End5" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_01ahvyv" sourceRef="Event_0iob1po" targetRef="Gateway_11x8qex" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_0iob1po">]'
      ,q'[      <bpmn:incoming>Flow_048u5lq</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_01ahvyv</bpmn:outgoing>]'
      ,q'[      <bpmn:timerEventDefinition id="TimerEventDefinition_0pde5i3" />]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_04509o5">]'
      ,q'[      <bpmn:incoming>Flow_0klopa5</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1nhbi01</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0ngmayk</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1nhbi01" sourceRef="Gateway_04509o5" targetRef="Gateway_11x8qex" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0ngmayk" sourceRef="Gateway_04509o5" targetRef="Gateway_11x8qex" apex:sequence="20" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0yg5gl0" sourceRef="Activity_025ghr0" targetRef="Gateway_11x8qex" />]'
      ,q'[    <bpmn:userTask id="Activity_025ghr0" name="All Page inputs can be substituted" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_1hk6xxp</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0yg5gl0</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0zkr82p" sourceRef="Activity_00ikjar" targetRef="Gateway_11x8qex" />]'
      ,q'[    <bpmn:userTask id="Activity_00ikjar" name="All Approval Task inputs can be substituted" apex:type="apexPage" apex:manualInput="false">]'
      ,q'[      <bpmn:incoming>Flow_1vqhn5f</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0zkr82p</bpmn:outgoing>]'
      ,q'[    </bpmn:userTask>]'
      ,q'[    <bpmn:task id="Activity_0b9bskz" name="In fact, most parameters can be substituted...">]'
      ,q'[      <bpmn:incoming>Flow_1rz8nif</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_16cbzmb</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1rz8nif" sourceRef="Gateway_0k7wwo7" targetRef="Activity_0b9bskz" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_16cbzmb" sourceRef="Activity_0b9bskz" targetRef="Gateway_11x8qex" />]'
      ,q'[    <bpmn:task id="Activity_14jn3ja" name="Timestamps  always use YYYY-MM-DD HH24:MI:SS TZR">]'
      ,q'[      <bpmn:incoming>Flow_1yn9h9h</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1d9orfq</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1yn9h9h" sourceRef="Gateway_0oiud3h" targetRef="Activity_14jn3ja" />]'
      ,q'[    <bpmn:endEvent id="Event_173ws7k">]'
      ,q'[      <bpmn:incoming>Flow_1d9orfq</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1d9orfq" sourceRef="Activity_14jn3ja" targetRef="Event_173ws7k" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0y2my1c">]'
      ,q'[      <bpmn:text>Substitution Syntax - ]'
      ,q'[]'
      ,q'[Just like APEX, but we add F4A$ in front of the variable name to separate Process Variables from Page Items, etc.  So refer to the 'MyVar' variable as]'
      ,q'[]'
      ,q'[&amp;F4A$MyVar.]'
      ,q'[]'
      ,q'[Note the '&amp;' and the '.' at the end.]'
      ,q'[]'
      ,q'[Substitution puts a VARCHAR2-formatted copy of the Process Variable contents into whatever is being substituted.  For Dates and Timestamps, you have to be careful about how the format it gets converted with...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0tujo7w" sourceRef="Activity_109wr9z" targetRef="TextAnnotation_0y2my1c" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1jczv9c">]'
      ,q'[      <bpmn:text>Bind Syntax - ]'
      ,q'[]'
      ,q'[Just like APEX, but we add F4A$ in front of the variable name to separate Process Variables from Page Items, etc. So refer to the 'MyVar' variable as]'
      ,q'[]'
      ,q'[:F4A$MyVar]'
      ,q'[]'
      ,q'[When we BIND a variable into an expression or a script, the content of the variable is used directly - without having to worry about converting dates or timestamps into character strings first.]'
      ,q'[]'
      ,q'[Binding is also safer &amp; prevents SQL Injection attacks -- so n general, if you are referencing a process variable in a script, expression, or function body -- its better to use binds than substitutions.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1i8e0u4" sourceRef="Activity_0l3xwhd" targetRef="TextAnnotation_1jczv9c" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1fz3jj4">]'
      ,q'[      <bpmn:text>All of the parameters can be substituted - see doc.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1dq65gz" sourceRef="Event_0iob1po" targetRef="TextAnnotation_1fz3jj4" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0fcz1tf">]'
      ,q'[      <bpmn:text>Gateway Routing Expressions - Process Variables can be bound or substituted into an expression of function body.]'
      ,q'[]'
      ,q'[Gateway Routing Variables - are a process variable.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1cy1qjf" sourceRef="Gateway_04509o5" targetRef="TextAnnotation_0fcz1tf" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0frra4d">]'
      ,q'[      <bpmn:text>Don't Run this tutorial - just read the model!</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1tve32h" associationDirection="None" sourceRef="Activity_0ozxsb9" targetRef="TextAnnotation_0frra4d" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial3b">]'
      ,q'[      <bpmndi:BPMNShape id="Event_1plpgom_di" bpmnElement="Event_1plpgom">]'
      ,q'[        <dc:Bounds x="372" y="592" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ozxsb9_di" bpmnElement="Activity_0ozxsb9" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="460" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0lauwst_di" bpmnElement="Gateway_0k7wwo7" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="615" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_10y1yso_di" bpmnElement="Activity_10y1yso" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="450" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0j6pujb_di" bpmnElement="Activity_0j6pujb" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0946wwh_di" bpmnElement="Activity_0946wwh" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="680" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1w8et0w_di" bpmnElement="Activity_1w8et0w" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="790" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1wyrdke_di" bpmnElement="Activity_1wyrdke" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="900" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1cfykx0_di" bpmnElement="Gateway_11x8qex" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1045" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0uu2coh_di" bpmnElement="Activity_0uu2coh" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1150" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0pt7ww8_di" bpmnElement="Gateway_0but2hg" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1305" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_109wr9z_di" bpmnElement="Activity_109wr9z" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1410" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0l3xwhd_di" bpmnElement="Activity_0l3xwhd" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1410" y="680" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0ll51df_di" bpmnElement="Gateway_066hu8c" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1565" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_064ohbq_di" bpmnElement="Activity_064ohbq" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1670" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1krbaa9_di" bpmnElement="Activity_1krbaa9" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1940" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1d8h7t2_di" bpmnElement="Event_1d8h7t2" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="2102" y="592" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1yv5wrk_di" bpmnElement="Gateway_0oiud3h" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1825" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_04jc012_di" bpmnElement="Activity_04jc012" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1940" y="680" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0epw44y_di" bpmnElement="Event_0epw44y" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="2112" y="702" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1543y23_di" bpmnElement="Activity_1543y23" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1940" y="880" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_08bp25i_di" bpmnElement="Event_08bp25i" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="2112" y="902" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_19cz6nm_di" bpmnElement="Activity_19cz6nm" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1940" y="980" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0lvs1ap_di" bpmnElement="Event_End5" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="2112" y="1002" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="2103" y="1045" width="58" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_08pp0hi_di" bpmnElement="Event_0iob1po" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="912" y="472" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_04509o5_di" bpmnElement="Gateway_04509o5" isMarkerVisible="true" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="865" y="585" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1e21yda_di" bpmnElement="Activity_025ghr0" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="880" y="790" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0x3d4kh_di" bpmnElement="Activity_00ikjar" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="880" y="900" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0b9bskz_di" bpmnElement="Activity_0b9bskz" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="720" y="1010" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_14jn3ja_di" bpmnElement="Activity_14jn3ja" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1940" y="780" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_173ws7k_di" bpmnElement="Event_173ws7k" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="2112" y="802" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1tve32h_di" bpmnElement="Association_1tve32h">]'
      ,q'[        <di:waypoint x="488" y="650" />]'
      ,q'[        <di:waypoint x="448" y="720" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0y2my1c_di" bpmnElement="TextAnnotation_0y2my1c">]'
      ,q'[        <dc:Bounds x="1460" y="280" width="297" height="222" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1jczv9c_di" bpmnElement="TextAnnotation_1jczv9c">]'
      ,q'[        <dc:Bounds x="1380" y="815" width="340" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1fz3jj4_di" bpmnElement="TextAnnotation_1fz3jj4">]'
      ,q'[        <dc:Bounds x="890" y="366" width="99.99999237060547" height="67.99632263183594" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0fcz1tf_di" bpmnElement="TextAnnotation_0fcz1tf">]'
      ,q'[        <dc:Bounds x="1050" y="366" width="239.99998474121094" height="95.99263763427734" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ec73q3_di" bpmnElement="Flow_1ec73q3">]'
      ,q'[        <di:waypoint x="408" y="610" />]'
      ,q'[        <di:waypoint x="460" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0r29a9k_di" bpmnElement="Flow_0r29a9k">]'
      ,q'[        <di:waypoint x="560" y="610" />]'
      ,q'[        <di:waypoint x="615" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1gcfz9u_di" bpmnElement="Flow_1gcfz9u">]'
      ,q'[        <di:waypoint x="640" y="585" />]'
      ,q'[        <di:waypoint x="640" y="490" />]'
      ,q'[        <di:waypoint x="720" y="490" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0k2h11g_di" bpmnElement="Flow_0k2h11g">]'
      ,q'[        <di:waypoint x="665" y="610" />]'
      ,q'[        <di:waypoint x="720" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0klopa5_di" bpmnElement="Flow_0klopa5">]'
      ,q'[        <di:waypoint x="820" y="610" />]'
      ,q'[        <di:waypoint x="865" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_048u5lq_di" bpmnElement="Flow_048u5lq">]'
      ,q'[        <di:waypoint x="820" y="490" />]'
      ,q'[        <di:waypoint x="912" y="490" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_08olq9m_di" bpmnElement="Flow_08olq9m">]'
      ,q'[        <di:waypoint x="640" y="635" />]'
      ,q'[        <di:waypoint x="640" y="720" />]'
      ,q'[        <di:waypoint x="720" y="720" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1vdold9_di" bpmnElement="Flow_1vdold9">]'
      ,q'[        <di:waypoint x="820" y="720" />]'
      ,q'[        <di:waypoint x="1070" y="720" />]'
      ,q'[        <di:waypoint x="1070" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0inf8qr_di" bpmnElement="Flow_0inf8qr">]'
      ,q'[        <di:waypoint x="640" y="635" />]'
      ,q'[        <di:waypoint x="640" y="830" />]'
      ,q'[        <di:waypoint x="720" y="830" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1hk6xxp_di" bpmnElement="Flow_1hk6xxp">]'
      ,q'[        <di:waypoint x="820" y="830" />]'
      ,q'[        <di:waypoint x="880" y="830" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0vsy08g_di" bpmnElement="Flow_0vsy08g">]'
      ,q'[        <di:waypoint x="640" y="635" />]'
      ,q'[        <di:waypoint x="640" y="940" />]'
      ,q'[        <di:waypoint x="720" y="940" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1vqhn5f_di" bpmnElement="Flow_1vqhn5f">]'
      ,q'[        <di:waypoint x="820" y="940" />]'
      ,q'[        <di:waypoint x="880" y="940" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02zdkhv_di" bpmnElement="Flow_02zdkhv">]'
      ,q'[        <di:waypoint x="1095" y="610" />]'
      ,q'[        <di:waypoint x="1150" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ylq0wi_di" bpmnElement="Flow_1ylq0wi">]'
      ,q'[        <di:waypoint x="1250" y="610" />]'
      ,q'[        <di:waypoint x="1305" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07bi894_di" bpmnElement="Flow_07bi894">]'
      ,q'[        <di:waypoint x="1355" y="610" />]'
      ,q'[        <di:waypoint x="1410" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0n5ncld_di" bpmnElement="Flow_0n5ncld">]'
      ,q'[        <di:waypoint x="1330" y="635" />]'
      ,q'[        <di:waypoint x="1330" y="720" />]'
      ,q'[        <di:waypoint x="1410" y="720" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_18ek31f_di" bpmnElement="Flow_18ek31f">]'
      ,q'[        <di:waypoint x="1510" y="610" />]'
      ,q'[        <di:waypoint x="1565" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0tljhpd_di" bpmnElement="Flow_0tljhpd">]'
      ,q'[        <di:waypoint x="1510" y="720" />]'
      ,q'[        <di:waypoint x="1590" y="720" />]'
      ,q'[        <di:waypoint x="1590" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0bfhz6m_di" bpmnElement="Flow_0bfhz6m">]'
      ,q'[        <di:waypoint x="1615" y="610" />]'
      ,q'[        <di:waypoint x="1670" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_024p93z_di" bpmnElement="Flow_024p93z">]'
      ,q'[        <di:waypoint x="1770" y="610" />]'
      ,q'[        <di:waypoint x="1825" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1yoridh_di" bpmnElement="Flow_1yoridh">]'
      ,q'[        <di:waypoint x="2040" y="610" />]'
      ,q'[        <di:waypoint x="2102" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_040sz4v_di" bpmnElement="Flow_040sz4v">]'
      ,q'[        <di:waypoint x="1875" y="610" />]'
      ,q'[        <di:waypoint x="1940" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07ut43o_di" bpmnElement="Flow_07ut43o">]'
      ,q'[        <di:waypoint x="1850" y="635" />]'
      ,q'[        <di:waypoint x="1850" y="720" />]'
      ,q'[        <di:waypoint x="1940" y="720" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1en3v8m_di" bpmnElement="Flow_1en3v8m">]'
      ,q'[        <di:waypoint x="2040" y="720" />]'
      ,q'[        <di:waypoint x="2112" y="720" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1bedtbq_di" bpmnElement="Flow_1bedtbq">]'
      ,q'[        <di:waypoint x="1850" y="635" />]'
      ,q'[        <di:waypoint x="1850" y="920" />]'
      ,q'[        <di:waypoint x="1940" y="920" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1bw826o_di" bpmnElement="Flow_1bw826o">]'
      ,q'[        <di:waypoint x="2040" y="920" />]'
      ,q'[        <di:waypoint x="2112" y="920" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0h58bew_di" bpmnElement="Flow_0h58bew">]'
      ,q'[        <di:waypoint x="1850" y="635" />]'
      ,q'[        <di:waypoint x="1850" y="1020" />]'
      ,q'[        <di:waypoint x="1940" y="1020" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_08fk99d_di" bpmnElement="Flow_08fk99d">]'
      ,q'[        <di:waypoint x="2040" y="1020" />]'
      ,q'[        <di:waypoint x="2112" y="1020" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_01ahvyv_di" bpmnElement="Flow_01ahvyv">]'
      ,q'[        <di:waypoint x="948" y="490" />]'
      ,q'[        <di:waypoint x="1070" y="490" />]'
      ,q'[        <di:waypoint x="1070" y="585" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1nhbi01_di" bpmnElement="Flow_1nhbi01">]'
      ,q'[        <di:waypoint x="890" y="635" />]'
      ,q'[        <di:waypoint x="890" y="660" />]'
      ,q'[        <di:waypoint x="1070" y="660" />]'
      ,q'[        <di:waypoint x="1070" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ngmayk_di" bpmnElement="Flow_0ngmayk">]'
      ,q'[        <di:waypoint x="890" y="585" />]'
      ,q'[        <di:waypoint x="890" y="560" />]'
      ,q'[        <di:waypoint x="1070" y="560" />]'
      ,q'[        <di:waypoint x="1070" y="585" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0yg5gl0_di" bpmnElement="Flow_0yg5gl0">]'
      ,q'[        <di:waypoint x="980" y="830" />]'
      ,q'[        <di:waypoint x="1070" y="830" />]'
      ,q'[        <di:waypoint x="1070" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0zkr82p_di" bpmnElement="Flow_0zkr82p">]'
      ,q'[        <di:waypoint x="980" y="940" />]'
      ,q'[        <di:waypoint x="1070" y="940" />]'
      ,q'[        <di:waypoint x="1070" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1rz8nif_di" bpmnElement="Flow_1rz8nif">]'
      ,q'[        <di:waypoint x="640" y="635" />]'
      ,q'[        <di:waypoint x="640" y="1050" />]'
      ,q'[        <di:waypoint x="720" y="1050" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_16cbzmb_di" bpmnElement="Flow_16cbzmb">]'
      ,q'[        <di:waypoint x="820" y="1050" />]'
      ,q'[        <di:waypoint x="1070" y="1050" />]'
      ,q'[        <di:waypoint x="1070" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1yn9h9h_di" bpmnElement="Flow_1yn9h9h">]'
      ,q'[        <di:waypoint x="1850" y="635" />]'
      ,q'[        <di:waypoint x="1850" y="820" />]'
      ,q'[        <di:waypoint x="1940" y="820" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1d9orfq_di" bpmnElement="Flow_1d9orfq">]'
      ,q'[        <di:waypoint x="2040" y="820" />]'
      ,q'[        <di:waypoint x="2112" y="820" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0tujo7w_di" bpmnElement="Association_0tujo7w">]'
      ,q'[        <di:waypoint x="1465" y="570" />]'
      ,q'[        <di:waypoint x="1476" y="502" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1i8e0u4_di" bpmnElement="Association_1i8e0u4">]'
      ,q'[        <di:waypoint x="1478" y="760" />]'
      ,q'[        <di:waypoint x="1503" y="815" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1dq65gz_di" bpmnElement="Association_1dq65gz">]'
      ,q'[        <di:waypoint x="917" y="477" />]'
      ,q'[        <di:waypoint x="840" y="400" />]'
      ,q'[        <di:waypoint x="890" y="400" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1cy1qjf_di" bpmnElement="Association_1cy1qjf">]'
      ,q'[        <di:waypoint x="899" y="594" />]'
      ,q'[        <di:waypoint x="1010" y="412" />]'
      ,q'[        <di:waypoint x="1050" y="412" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0frra4d_di" bpmnElement="TextAnnotation_0frra4d">]'
      ,q'[        <dc:Bounds x="390" y="720" width="190" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 3b - Substitution and Bind Syntax',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
