declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:apex="https://flowsforapex.org" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial_3" name="Inclusive Gateway Tutorial" isExecutable="true" apex:isCallable="false" apex:isStartable="true" apex:manualInput="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Consulting.]'
      ,q'[twitter: @FlowquestRehg</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_1warv4h" name="Start Tutorial 3">]'
      ,q'[      <bpmn:outgoing>Flow_166n1nj</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_1ve7i3d" name="Inspect Your Gateway Variable">]'
      ,q'[      <bpmn:incoming>Flow_0mzxaxx</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1qhovsw</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_166n1nj" sourceRef="Event_1warv4h" targetRef="Activity_Concept1" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1qhovsw" sourceRef="Activity_1ve7i3d" targetRef="Gateway_Inclusive_Opening" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_Inclusive_Opening" name="Opening Inclusive Gateway" default="Flow_C">]'
      ,q'[      <bpmn:incoming>Flow_1qhovsw</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_A</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_B</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_C</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_0buy3jb" name="A">]'
      ,q'[      <bpmn:incoming>Flow_A</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0raoa8o</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_A" name="Flow A" sourceRef="Gateway_Inclusive_Opening" targetRef="Activity_0buy3jb" apex:sequence="30" />]'
      ,q'[    <bpmn:task id="Activity_1iqxrc6" name="B">]'
      ,q'[      <bpmn:incoming>Flow_B</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0dmljno</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_B" name="Flow B" sourceRef="Gateway_Inclusive_Opening" targetRef="Activity_1iqxrc6" apex:sequence="40" />]'
      ,q'[    <bpmn:task id="Activity_1ajwcwr" name="C">]'
      ,q'[      <bpmn:incoming>Flow_C</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1hljb3z</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_C" name="Flow C" sourceRef="Gateway_Inclusive_Opening" targetRef="Activity_1ajwcwr" apex:sequence="50" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0dmljno" sourceRef="Activity_1iqxrc6" targetRef="Gateway_0008jgf" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_0008jgf" name="Merge and Resync">]'
      ,q'[      <bpmn:incoming>Flow_0dmljno</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0raoa8o</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1hljb3z</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0jbvoj2</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0raoa8o" sourceRef="Activity_0buy3jb" targetRef="Gateway_0008jgf" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1hljb3z" sourceRef="Activity_1ajwcwr" targetRef="Gateway_0008jgf" />]'
      ,q'[    <bpmn:task id="Activity_0gtcq94" name="D">]'
      ,q'[      <bpmn:incoming>Flow_0jbvoj2</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1kt6sw3</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0jbvoj2" sourceRef="Gateway_0008jgf" targetRef="Activity_0gtcq94" apex:sequence="10" />]'
      ,q'[    <bpmn:endEvent id="Event_0n1anww" name="End Tutorial 3">]'
      ,q'[      <bpmn:incoming>Flow_1kt6sw3</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1kt6sw3" sourceRef="Activity_0gtcq94" targetRef="Event_0n1anww" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mzxaxx" sourceRef="Activity_0buimbx" targetRef="Activity_1ve7i3d" />]'
      ,q'[    <bpmn:scriptTask id="Activity_0buimbx" name="ScriptTask to Set Gateway Variable" apex:type="executePlsql">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:executePlsql>]'
      ,q'[          <apex:plsqlCode>flow_process_vars.set_var ]'
      ,q'[    ( pi_prcs_id =&gt; flow_plsql_runner_pkg.get_current_prcs_id]'
      ,q'[    , pi_var_name =&gt; 'Gateway_Inclusive_Opening:route']'
      ,q'[    , pi_vc2_value =&gt; 'Flow_A:Flow_C');</apex:plsqlCode>]'
      ,q'[        </apex:executePlsql>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_080bqby</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mzxaxx</bpmn:outgoing>]'
      ,q'[    </bpmn:scriptTask>]'
      ,q'[    <bpmn:task id="Activity_Concept1" name="Concept 1:&#10;Gateway Routing Expressions">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>FoodOrdered</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>PIZZA:CHIPS</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_166n1nj</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_153ygxs</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_153ygxs" sourceRef="Activity_Concept1" targetRef="Gateway_1gp1fyn" />]'
      ,q'[    <bpmn:task id="Activity_1yp3qv8" name="Concept 2:&#10;Gateway Routing Variables">]'
      ,q'[      <bpmn:incoming>Flow_0ph2k43</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_080bqby</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_080bqby" sourceRef="Activity_1yp3qv8" targetRef="Activity_0buimbx" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_BERGER" name="FoodOrdered contains &#39;BURGER&#39;" sourceRef="Gateway_1gp1fyn" targetRef="Activity_1m4w5ac" apex:sequence="20">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression" sequence="0">:F4A$FoodOrdered like '%BURGER%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0ph2k43" sourceRef="Gateway_1d5oe5w" targetRef="Activity_1yp3qv8" apex:sequence="10" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_1gp1fyn">]'
      ,q'[      <bpmn:incoming>Flow_153ygxs</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_BERGER</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_PIZZA</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_CHIPS</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_1d5oe5w">]'
      ,q'[      <bpmn:incoming>Flow_1h80wgk</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1cr6b75</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0i4a0v0</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0ph2k43</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_1m4w5ac" name="Make Burger">]'
      ,q'[      <bpmn:incoming>Flow_BERGER</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1h80wgk</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1h80wgk" sourceRef="Activity_1m4w5ac" targetRef="Gateway_1d5oe5w" />]'
      ,q'[    <bpmn:task id="Activity_1ef33ii" name="Make Pizza">]'
      ,q'[      <bpmn:incoming>Flow_PIZZA</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1cr6b75</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_PIZZA" name="FoodOrdered contains PIZZA" sourceRef="Gateway_1gp1fyn" targetRef="Activity_1ef33ii" apex:sequence="10">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression" sequence="">:F4A$FoodOrdered like '%PIZZA%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:task id="Activity_1bt8ouh" name="Make Chips">]'
      ,q'[      <bpmn:incoming>Flow_CHIPS</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0i4a0v0</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_CHIPS" name="FoodOrdered contains &#39;CHIPS&#39;" sourceRef="Gateway_1gp1fyn" targetRef="Activity_1bt8ouh" apex:sequence="30">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$FoodOrdered like '%CHIPS%'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1cr6b75" sourceRef="Activity_1ef33ii" targetRef="Gateway_1d5oe5w" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0i4a0v0" sourceRef="Activity_1bt8ouh" targetRef="Gateway_1d5oe5w" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1w4hasz">]'
      ,q'[      <bpmn:text>Method 2: Setting a Gateway Routing Variable (the old way)...]'
      ,q'[]'
      ,q'[You can choose 1 or more (or all) of the possible routes.]'
      ,q'[]'
      ,q'[Routing is supplied to the gateway in a Process Variable named &lt;gateway id&gt;&lt;:route&gt;.]'
      ,q'[]'
      ,q'[Routes selected are listed in the variable, colon separated]'
      ,q'[]'
      ,q'[In our Example, the Gateway ID is 'Gateway_Inclusive_Opening', routes have IDs 'Flow_A', 'Flow_B', and 'Flow_C'.  So to choose A and C only, in the scriptTask we set the variable]'
      ,q'[]'
      ,q'['Gateway_Inclusive_Opening:route' with varchar2 value 'Flow_A:Flow_C'.]'
      ,q'[]'
      ,q'[In this example, we ran a scriptTask as the first task in the flow which set this variable for you.  If you look at the variables tab above, you can see the variable and it's value. ]'
      ,q'[]'
      ,q'[Step forward &amp; see routes A &amp; C become the current task.]'
      ,q'[]'
      ,q'[You can restart the model, and manually change the routing variable if you want.]'
      ,q'[]'
      ,q'[This is a tutorial, and we've set the variable using a simple script.  Obviously in your app, your pl/sql script could look at process variables, or could run a query in the database, or perform some other calculation or logic to determine and then set the routing that makes sense in your application.  These can be set in a scriptTask (as here) or using declarative variable expressions, which we will explore later....]'
      ,q'[]'
      ,q'[Note that an Inclusive Gateway also can have a default path - on Flow C in our example.  Flows for APEX will first look for a process variable with the correct name; if that doesn't exist, it will look for default routing; and it that doesn't exist, it will show an error.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0k4787z" sourceRef="Activity_1ve7i3d" targetRef="TextAnnotation_1w4hasz" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0v50lx0">]'
      ,q'[      <bpmn:text>This scriptTask sets the process variable for the Gateway.]'
      ,q'[]'
      ,q'[]'
      ,q'[We've used a scriptTask that runs a simple PL/SQL procedure that sets the routing to 'Flow_A:Flow_C'. ]'
      ,q'[]'
      ,q'[In the Properties Panel on the right side of the Flow Modeler, select the ScriptTask and select the APEX tab to see how we get the process id and then set the process variable.]'
      ,q'[]'
      ,q'[Your application could include a PL/SQL procedure that performs a query in the database &amp; which determines the route through your process. That makes this very powerful!</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0oa2eg1" sourceRef="Activity_0buimbx" targetRef="TextAnnotation_0v50lx0" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0jyiofy">]'
      ,q'[      <bpmn:text>Tutorial 2c - Inclusive Gateways]'
      ,q'[]'
      ,q'[An inclusive Gateway is a cross between a Parallel Gateway (All paths operate in parallel) and an Exclusive Gateway (where only one forward path is chosen).  An Inclusive Gateway chooses multiple forward paths that can operate in parallel.]'
      ,q'[]'
      ,q'[Like the Exclusive Gateway, the Inclusive Gateway can be controlled by:]'
      ,q'[ - Gateway Routing Expressions - giving the conditions under which a forward path should be taken]'
      ,q'[ - Gateway Routing Variables - giving the path names of all paths to be taken, ]'
      ,q'[ - Default Path, specifying the path that should be taken if no others are selected.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1fdyic0" sourceRef="Event_1warv4h" targetRef="TextAnnotation_0jyiofy" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1jcq7cx">]'
      ,q'[      <bpmn:text>Method 1: Gateway Routing Expressions,  New in v22.2]'
      ,q'[]'
      ,q'[Each forward path contains a condition for that path to be taken.  If the condition evaluates to TRUE, the path is taken.]'
      ,q'[]'
      ,q'[Conditions can be specified as either:]'
      ,q'[- PL/SQL Expressions, evaluating to a boolean (true/false) result.]'
      ,q'[- PL/SQL Function Body, returning a boolean (true/false) result.]'
      ,q'[]'
      ,q'[Conditions are evaluated in sequence order - so take care if your conditions are overlapping (not good practice).]'
      ,q'[]'
      ,q'[Conditions can use an expression or a function body to compare a process variable, perform a database query, or some other complex processing.]'
      ,q'[]'
      ,q'[In our example, we've set a variable to 'PIZZA:CHIPS' using a static assignment (you could use the SQL Query returning multiple values to do this in a real system).   Then written conditions on the forward paths to test if these values are present.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0hjn351" sourceRef="Activity_Concept1" targetRef="TextAnnotation_1jcq7cx" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial_3">]'
      ,q'[      <bpmndi:BPMNShape id="Event_1warv4h_di" bpmnElement="Event_1warv4h">]'
      ,q'[        <dc:Bounds x="412" y="482" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="395" y="525" width="70" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ve7i3d_di" bpmnElement="Activity_1ve7i3d" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1690" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_19m857j_di" bpmnElement="Gateway_Inclusive_Opening" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1845" y="475" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1766" y="416" width="90" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0buy3jb_di" bpmnElement="Activity_0buy3jb" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1950" y="330" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1iqxrc6_di" bpmnElement="Activity_1iqxrc6" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1950" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ajwcwr_di" bpmnElement="Activity_1ajwcwr" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1950" y="590" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_03knf6b_di" bpmnElement="Gateway_0008jgf" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="2105" y="475" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="2153" y="426" width="53" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0gtcq94_di" bpmnElement="Activity_0gtcq94">]'
      ,q'[        <dc:Bounds x="2210" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0n1anww_di" bpmnElement="Event_0n1anww">]'
      ,q'[        <dc:Bounds x="2372" y="482" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="2358" y="525" width="66" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0l6cpk6_di" bpmnElement="Activity_0buimbx" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1550" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_06rbtnv_di" bpmnElement="Activity_Concept1" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="520" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1yp3qv8_di" bpmnElement="Activity_1yp3qv8" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1420" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0hqskic_di" bpmnElement="Gateway_1gp1fyn" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="685" y="475" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1ahm5ft_di" bpmnElement="Gateway_1d5oe5w" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="1245" y="475" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1m4w5ac_di" bpmnElement="Activity_1m4w5ac" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="930" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ef33ii_di" bpmnElement="Activity_1ef33ii" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="930" y="330" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1bt8ouh_di" bpmnElement="Activity_1bt8ouh" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="930" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1w4hasz_di" bpmnElement="TextAnnotation_1w4hasz">]'
      ,q'[        <dc:Bounds x="1650" y="-35" width="1079.9998779296875" height="354.9999694824219" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0v50lx0_di" bpmnElement="TextAnnotation_0v50lx0">]'
      ,q'[        <dc:Bounds x="1660" y="710" width="510" height="164" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0jyiofy_di" bpmnElement="TextAnnotation_0jyiofy">]'
      ,q'[        <dc:Bounds x="460" y="-90" width="729.9985939257593" height="137.98861079865017" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1jcq7cx_di" bpmnElement="TextAnnotation_1jcq7cx">]'
      ,q'[        <dc:Bounds x="635" y="80" width="689.9815673828125" height="222.97792053222656" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_166n1nj_di" bpmnElement="Flow_166n1nj">]'
      ,q'[        <di:waypoint x="448" y="500" />]'
      ,q'[        <di:waypoint x="520" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1qhovsw_di" bpmnElement="Flow_1qhovsw">]'
      ,q'[        <di:waypoint x="1790" y="500" />]'
      ,q'[        <di:waypoint x="1845" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0raiyk0_di" bpmnElement="Flow_A">]'
      ,q'[        <di:waypoint x="1870" y="475" />]'
      ,q'[        <di:waypoint x="1870" y="370" />]'
      ,q'[        <di:waypoint x="1950" y="370" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1884" y="343" width="33" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1jj2iet_di" bpmnElement="Flow_B">]'
      ,q'[        <di:waypoint x="1895" y="500" />]'
      ,q'[        <di:waypoint x="1950" y="500" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1907" y="482" width="33" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1w4x95t_di" bpmnElement="Flow_C">]'
      ,q'[        <di:waypoint x="1870" y="525" />]'
      ,q'[        <di:waypoint x="1870" y="630" />]'
      ,q'[        <di:waypoint x="1950" y="630" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1893" y="593" width="33" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0dmljno_di" bpmnElement="Flow_0dmljno">]'
      ,q'[        <di:waypoint x="2050" y="500" />]'
      ,q'[        <di:waypoint x="2105" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0raoa8o_di" bpmnElement="Flow_0raoa8o">]'
      ,q'[        <di:waypoint x="2050" y="370" />]'
      ,q'[        <di:waypoint x="2130" y="370" />]'
      ,q'[        <di:waypoint x="2130" y="475" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1hljb3z_di" bpmnElement="Flow_1hljb3z">]'
      ,q'[        <di:waypoint x="2050" y="630" />]'
      ,q'[        <di:waypoint x="2130" y="630" />]'
      ,q'[        <di:waypoint x="2130" y="525" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0jbvoj2_di" bpmnElement="Flow_0jbvoj2">]'
      ,q'[        <di:waypoint x="2155" y="500" />]'
      ,q'[        <di:waypoint x="2210" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1kt6sw3_di" bpmnElement="Flow_1kt6sw3">]'
      ,q'[        <di:waypoint x="2310" y="500" />]'
      ,q'[        <di:waypoint x="2372" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0mzxaxx_di" bpmnElement="Flow_0mzxaxx">]'
      ,q'[        <di:waypoint x="1650" y="500" />]'
      ,q'[        <di:waypoint x="1690" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_153ygxs_di" bpmnElement="Flow_153ygxs">]'
      ,q'[        <di:waypoint x="620" y="500" />]'
      ,q'[        <di:waypoint x="685" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_080bqby_di" bpmnElement="Flow_080bqby">]'
      ,q'[        <di:waypoint x="1520" y="500" />]'
      ,q'[        <di:waypoint x="1550" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_07014fh_di" bpmnElement="Flow_BERGER">]'
      ,q'[        <di:waypoint x="735" y="500" />]'
      ,q'[        <di:waypoint x="930" y="500" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="806" y="450" width="63" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ph2k43_di" bpmnElement="Flow_0ph2k43">]'
      ,q'[        <di:waypoint x="1295" y="500" />]'
      ,q'[        <di:waypoint x="1420" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1h80wgk_di" bpmnElement="Flow_1h80wgk">]'
      ,q'[        <di:waypoint x="1030" y="500" />]'
      ,q'[        <di:waypoint x="1245" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0u2pbth_di" bpmnElement="Flow_PIZZA">]'
      ,q'[        <di:waypoint x="710" y="475" />]'
      ,q'[        <di:waypoint x="710" y="370" />]'
      ,q'[        <di:waypoint x="930" y="370" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="802" y="326" width="73" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_09h9bb8_di" bpmnElement="Flow_CHIPS">]'
      ,q'[        <di:waypoint x="710" y="525" />]'
      ,q'[        <di:waypoint x="710" y="610" />]'
      ,q'[        <di:waypoint x="930" y="610" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="790" y="565" width="79" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1cr6b75_di" bpmnElement="Flow_1cr6b75">]'
      ,q'[        <di:waypoint x="1030" y="370" />]'
      ,q'[        <di:waypoint x="1270" y="370" />]'
      ,q'[        <di:waypoint x="1270" y="475" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0i4a0v0_di" bpmnElement="Flow_0i4a0v0">]'
      ,q'[        <di:waypoint x="1030" y="610" />]'
      ,q'[        <di:waypoint x="1270" y="610" />]'
      ,q'[        <di:waypoint x="1270" y="525" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0k4787z_di" bpmnElement="Association_0k4787z">]'
      ,q'[        <di:waypoint x="1714" y="460" />]'
      ,q'[        <di:waypoint x="1470" y="90" />]'
      ,q'[        <di:waypoint x="1650" y="90" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0oa2eg1_di" bpmnElement="Association_0oa2eg1">]'
      ,q'[        <di:waypoint x="1624" y="540" />]'
      ,q'[        <di:waypoint x="1727" y="710" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1fdyic0_di" bpmnElement="Association_1fdyic0">]'
      ,q'[        <di:waypoint x="432" y="482" />]'
      ,q'[        <di:waypoint x="493" y="48" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hjn351_di" bpmnElement="Association_0hjn351">]'
      ,q'[        <di:waypoint x="577" y="460" />]'
      ,q'[        <di:waypoint x="635" y="120" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 2c - Inclusive Gateways',
    pi_dgrm_version => '24.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
