declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="24.1.0">]'
      ,q'[  <bpmn:collaboration id="Collaboration_Tutorial7b">]'
      ,q'[    <bpmn:participant id="Participant_7b_Customer" name="Customer" processRef="Process_7b_Customer" />]'
      ,q'[    <bpmn:participant id="Participant_7b_Supplier" name="Supplier" processRef="Process_7b_Supplier" />]'
      ,q'[    <bpmn:participant id="Participant_7b_Shipper" name="Shipper" processRef="Process_7b_Shipper" />]'
      ,q'[    <bpmn:messageFlow id="Flow_0qqyp6t" name="PO" sourceRef="Activity_1g5w4wf" targetRef="Event_0fqjob4" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1lagn3a" name="SO" sourceRef="Event_08o84ee" targetRef="Event_19wz3hb" />]'
      ,q'[    <bpmn:messageFlow id="Flow_1fa2d0d" name="Shipping Instructions" sourceRef="Event_0s6f6tl" targetRef="Event_1uaun7m" />]'
      ,q'[    <bpmn:messageFlow id="Flow_0jri9bb" name="Delivery Order" sourceRef="Activity_1w7qibr" targetRef="Event_1fztck2" />]'
      ,q'[    <bpmn:messageFlow id="Flow_13km3up" name="Delivery Confirmation" sourceRef="Event_0mnrcwj" targetRef="Event_02ycj50" />]'
      ,q'[    <bpmn:messageFlow id="Flow_175p4nl" name="Invoice" sourceRef="Event_10ujxv8" targetRef="Event_0hf2lpk" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_066thix">]'
      ,q'[      <bpmn:text>Message Start sends most data inc PO number in Payload as it's a new transaction...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0t0pz11" associationDirection="None" sourceRef="Event_0fqjob4" targetRef="TextAnnotation_066thix" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0kt0jjy">]'
      ,q'[      <bpmn:text>Allocate a SO number in supplier's system...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_06ooxgb" associationDirection="None" sourceRef="Activity_1657afv" targetRef="TextAnnotation_0kt0jjy" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1rzdx0j">]'
      ,q'[      <bpmn:text>So I now have the Supplier's SO Number and pricing returned in payload</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1xt7bzk" associationDirection="None" sourceRef="Event_19wz3hb" targetRef="TextAnnotation_1rzdx0j" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0bhm3wb">]'
      ,q'[      <bpmn:text>There are  sample messages for all of these transactions, to show how a process is coordinated across multiple parties only using "real world" keys &amp; without some magic shaped GUID.]'
      ,q'[]'
      ,q'[Take some time to open the message properties.]'
      ,q'[]'
      ,q'[* This model relies on messageStart and messageEnd events, which are features of the  Enterprise Edition.  To run the model must be 'released']'
      ,q'[ It's hard to do this with Community Edition...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1o8f1tb" associationDirection="None" sourceRef="Event_1uaun7m" targetRef="TextAnnotation_0bhm3wb" />]'
      ,q'[  </bpmn:collaboration>]'
      ,q'[  <bpmn:process id="Process_7b_Customer" isExecutable="true" apex:isStartable="true">]'
      ,q'[    <bpmn:extensionElements>]'
      ,q'[      <apex:customExtension>{"minLoggingLevel" : 6,]'
      ,q'[ "instanceName" : "Customer Purchasing Process - &amp;F4A$PROCESS_ID. - PO&amp;F4A$BUSINESS_REF."]'
      ,q'[}</apex:customExtension>]'
      ,q'[    </bpmn:extensionElements>]'
      ,q'[    <bpmn:startEvent id="Event_1nkrf5h" name="Need Parts">]'
      ,q'[      <bpmn:outgoing>Flow_1u809yb</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1u809yb" sourceRef="Event_1nkrf5h" targetRef="Activity_1g5w4wf" />]'
      ,q'[    <bpmn:sendTask id="Activity_1g5w4wf" name="Send PO" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:endpoint>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>local</apex:expression>]'
      ,q'[        </apex:endpoint>]'
      ,q'[        <apex:messageName>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>purchaseOrder</apex:expression>]'
      ,q'[        </apex:messageName>]'
      ,q'[        <apex:payload>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>{"customer" : "CustomerCo",]'
      ,q'[ "customerPO" : "PO&amp;F4A$BUSINESS_REF.",]'
      ,q'["dateRequired" :  2024-12-30T12:00:00,]'
      ,q'["purchaseItems" : [ {"UPC" : "24586356789",]'
      ,q'[                                "qty_reqd" : 20},]'
      ,q'[                              {"UPC" : "24586456862",]'
      ,q'[                                "qty_reqd" : 10}]]'
      ,q'[}]'
      ,q'[</apex:expression>]'
      ,q'[        </apex:payload>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1u809yb</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02x6exq</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02x6exq" sourceRef="Activity_1g5w4wf" targetRef="Event_19wz3hb" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ts8jds" sourceRef="Event_19wz3hb" targetRef="Activity_1kljmjo" />]'
      ,q'[    <bpmn:task id="Activity_1kljmjo" name="Prepare Order">]'
      ,q'[      <bpmn:incoming>Flow_1ts8jds</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1frr481</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_19wz3hb" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_02x6exq</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ts8jds</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_18afvni">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>salesOrder</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>customerPOnumber</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>PO&amp;F4A$BUSINESS_REF.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payloadVariable>SupplierSO</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1frr481" sourceRef="Activity_1kljmjo" targetRef="Event_1fztck2" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_1fztck2" name="Receive Delivery Note" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_1frr481</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_13afku8</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0pgruip">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>deliveryOrder</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>customerPO</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>PO&amp;F4A$BUSINESS_REF.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payloadVariable>MyDeliveryNote</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_13afku8" sourceRef="Event_1fztck2" targetRef="Event_0hf2lpk" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0zdvd7b" sourceRef="Event_0hf2lpk" targetRef="Event_0iewhwo" />]'
      ,q'[    <bpmn:endEvent id="Event_0iewhwo" name="Order Completed">]'
      ,q'[      <bpmn:incoming>Flow_0zdvd7b</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_0hf2lpk" name="Receive Invoice" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_13afku8</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0zdvd7b</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1nkqyag">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>sendInvoice</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>customerPO</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>PO&amp;F4A$BUSINESS_REF.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payloadVariable>MyInvoice</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmn:process id="Process_7b_Supplier">]'
      ,q'[    <bpmn:extensionElements>]'
      ,q'[      <apex:customExtension>{"minLoggingLevel" : 8,]'
      ,q'[ "instanceName" : "Supplier Process - Customer PO &amp;F4A$CUSTOMERPO. (Our &amp;F4A$SUPPLIERSO.)"]'
      ,q'[}</apex:customExtension>]'
      ,q'[    </bpmn:extensionElements>]'
      ,q'[    <bpmn:startEvent id="Event_0fqjob4" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:onEvent>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>CustomerPO</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>json_value ( flow_process_vars.get_var_clob ( pi_prcs_id =&gt; :F4A$process_id]'
      ,q'[                                            , pi_var_name =&gt; 'OrderPayload')]'
      ,q'[            , '$.customerPO' returning varchar2)]'
      ,q'[</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>SupplierSO</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>'SO'|| ( to_char(to_number(substr(flow_process_vars.get_var_vc2 ( pi_prcs_id =&gt; :F4A$process_id]'
      ,q'[                                            , pi_var_name =&gt; 'CustomerPO'), 3)) +10000))]'
      ,q'[            </apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:onEvent>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:outgoing>Flow_1c0rg1m</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1q84afy">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>purchaseOrder</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:payloadVariable>OrderPayload</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_1657afv" name="Prepare Order">]'
      ,q'[      <bpmn:incoming>Flow_1c0rg1m</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0spqr5a</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1c0rg1m" sourceRef="Event_0fqjob4" targetRef="Activity_1657afv" apex:sequence="10" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0spqr5a" sourceRef="Activity_1657afv" targetRef="Event_08o84ee" />]'
      ,q'[    <bpmn:intermediateThrowEvent id="Event_08o84ee" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0spqr5a</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0hfmmi9</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1bl3gqo">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:endpoint>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>local</apex:expression>]'
      ,q'[          </apex:endpoint>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>salesOrder</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>customerPOnumber</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>processVariable</apex:expressionType>]'
      ,q'[            <apex:expression>CustomerPO</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payload>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>{ "supplierSalesOrder" ; "&amp;F4A$SUPPLIERSO.",]'
      ,q'[ "orderItems" : []'
      ,q'[           {"UPC" : "24586356789",]'
      ,q'[             "qty_ordered" : 20,]'
      ,q'[             "unit_price" : 12.56 },]'
      ,q'[            {"UPC" : "24586456862",]'
      ,q'[              "qty_reqd" : 10,]'
      ,q'[             "unit_price" : 86.56 }]]'
      ,q'[}</apex:expression>]'
      ,q'[          </apex:payload>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateThrowEvent>]'
      ,q'[    <bpmn:task id="Activity_0wj2cv8" name="Prepare Goods">]'
      ,q'[      <bpmn:incoming>Flow_0hfmmi9</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0cy0mu1</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0hfmmi9" sourceRef="Event_08o84ee" targetRef="Activity_0wj2cv8" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0cy0mu1" sourceRef="Activity_0wj2cv8" targetRef="Event_0s6f6tl" />]'
      ,q'[    <bpmn:intermediateThrowEvent id="Event_0s6f6tl" name="Send Shipping Instructions" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0cy0mu1</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_16mzs2c</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1o2yx5r">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:endpoint>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>local</apex:expression>]'
      ,q'[          </apex:endpoint>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>shippingInstruction</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:payload>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>{ "ShipFrom" : "MySupplierCo",]'
      ,q'[  "SupplierRef" : "&amp;F4A$SUPPLIERSO.",]'
      ,q'[  "ShipTo" : "MyCustomerCo",]'
      ,q'[  "CustomerRef" : "&amp;F4A$CUSTOMERPO.",]'
      ,q'[  "DateRequired" : 2024-12-30T12:00:00,]'
      ,q'[ "orderItems" : []'
      ,q'[           {"UPC" : "24586356789",]'
      ,q'[             "qty_ordered" : 20},]'
      ,q'[            {"UPC" : "24586456862",]'
      ,q'[              "qty_reqd" : 10}]]'
      ,q'[}]'
      ,q'[  </apex:expression>]'
      ,q'[          </apex:payload>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateThrowEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_16mzs2c" sourceRef="Event_0s6f6tl" targetRef="Event_02ycj50" apex:sequence="10" />]'
      ,q'[    <bpmn:intermediateCatchEvent id="Event_02ycj50" name="Receive Delivery Confirmation" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_16mzs2c</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_15quyrs</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0aje11i">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>deliveryConfirmation</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>supplierSO</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>&amp;F4A$SUPPLIERSO.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payloadVariable>MyDeliveryConfirmation</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:intermediateCatchEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_15quyrs" sourceRef="Event_02ycj50" targetRef="Event_10ujxv8" />]'
      ,q'[    <bpmn:endEvent id="Event_10ujxv8" name="Send Invoice and Complete" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_15quyrs</bpmn:incoming>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_0h9qn96">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:endpoint>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>local</apex:expression>]'
      ,q'[          </apex:endpoint>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>sendInvoice</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>customerPO</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>&amp;F4A$CUSTOMERPO.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payload>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>{"the bill": "..."}</apex:expression>]'
      ,q'[          </apex:payload>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmn:process id="Process_7b_Shipper">]'
      ,q'[    <bpmn:extensionElements>]'
      ,q'[      <apex:customExtension>{"minLoggingLevel" : 4,]'
      ,q'[ "instanceName" : "Shipping Process - &amp;F4A$PROCESS_ID."]'
      ,q'[}</apex:customExtension>]'
      ,q'[    </bpmn:extensionElements>]'
      ,q'[    <bpmn:startEvent id="Event_1uaun7m" name="Start Delivery Process" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:onEvent>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>SupplierSO</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>json_value ( flow_process_vars.get_var_clob ( pi_prcs_id =&gt; :F4A$process_id]'
      ,q'[                                            , pi_var_name =&gt; 'MyShippingInstruction')]'
      ,q'[            , '$.SupplierRef' returning varchar2)</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>Waybill</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>'AWB'|| ( to_char(to_number(substr(flow_process_vars.get_var_vc2 ( pi_prcs_id =&gt; :F4A$process_id]'
      ,q'[                                            , pi_var_name =&gt; 'CustomerSO'), 3)) +4949560000000))]'
      ,q'[            </apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>2</apex:varSequence>]'
      ,q'[            <apex:varName>CustomerRef</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlRawExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>json_value ( flow_process_vars.get_var_clob ( pi_prcs_id =&gt; :F4A$process_id]'
      ,q'[                                            , pi_var_name =&gt; 'MyShippingInstruction')]'
      ,q'[            , '$.CustomerRef' returning varchar2)</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:onEvent>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:outgoing>Flow_1wjgsuc</bpmn:outgoing>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_1jy6i1x">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>shippingInstruction</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:payloadVariable>MyShippingInstruction</apex:payloadVariable>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_1djmvxg" name="Prepare Shipment">]'
      ,q'[      <bpmn:incoming>Flow_1wjgsuc</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0mkjf1m</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1wjgsuc" sourceRef="Event_1uaun7m" targetRef="Activity_1djmvxg" />]'
      ,q'[    <bpmn:task id="Activity_1dsrrm0" name="Process">]'
      ,q'[      <bpmn:incoming>Flow_0mkjf1m</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_01ollhu</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0mkjf1m" sourceRef="Activity_1djmvxg" targetRef="Activity_1dsrrm0" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_01ollhu" sourceRef="Activity_1dsrrm0" targetRef="Activity_1w7qibr" />]'
      ,q'[    <bpmn:sendTask id="Activity_1w7qibr" name="Send Shipping Details" apex:type="simpleMessage">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:endpoint>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>local</apex:expression>]'
      ,q'[        </apex:endpoint>]'
      ,q'[        <apex:messageName>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>deliveryOrder</apex:expression>]'
      ,q'[        </apex:messageName>]'
      ,q'[        <apex:correlationKey>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>customerPO</apex:expression>]'
      ,q'[        </apex:correlationKey>]'
      ,q'[        <apex:correlationValue>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression>&amp;F4A$CUSTOMERREF.</apex:expression>]'
      ,q'[        </apex:correlationValue>]'
      ,q'[        <apex:payload>]'
      ,q'[          <apex:expressionType>static</apex:expressionType>]'
      ,q'[          <apex:expression> { "ShipFrom" : "MySupplierCo",]'
      ,q'[ "SupplierRef" : "&amp;F4A$SUPPLIERSO.",]'
      ,q'["orderItems" : []'
      ,q'[           {"UPC" : "24586356789",]'
      ,q'[             "qty_ordered" : 20 },]'
      ,q'[            {"UPC" : "24586456862",]'
      ,q'[              "qty_reqd" : 10 }],]'
      ,q'[ "mode" ; "air",]'
      ,q'[ "waybill" : "&amp;F4A$WAYBILL."]'
      ,q'[}</apex:expression>]'
      ,q'[        </apex:payload>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_01ollhu</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0c700da</bpmn:outgoing>]'
      ,q'[    </bpmn:sendTask>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0c700da" sourceRef="Activity_1w7qibr" targetRef="Event_0mnrcwj" />]'
      ,q'[    <bpmn:endEvent id="Event_0mnrcwj" name="Send Delivery Confirmation and End" apex:type="simpleMessage">]'
      ,q'[      <bpmn:incoming>Flow_0c700da</bpmn:incoming>]'
      ,q'[      <bpmn:messageEventDefinition id="MessageEventDefinition_129h25w">]'
      ,q'[        <bpmn:extensionElements>]'
      ,q'[          <apex:endpoint>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>local</apex:expression>]'
      ,q'[          </apex:endpoint>]'
      ,q'[          <apex:messageName>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>deliveryConfirmation</apex:expression>]'
      ,q'[          </apex:messageName>]'
      ,q'[          <apex:correlationKey>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>supplierSO</apex:expression>]'
      ,q'[          </apex:correlationKey>]'
      ,q'[          <apex:correlationValue>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression>&amp;F4A$SUPPLIERSO.</apex:expression>]'
      ,q'[          </apex:correlationValue>]'
      ,q'[          <apex:payload>]'
      ,q'[            <apex:expressionType>static</apex:expressionType>]'
      ,q'[            <apex:expression> { "ShipFrom" : "MySupplierCo",]'
      ,q'[ "SupplierRef" : "SO5678",]'
      ,q'[  "ShipTo" : "MyCustomerCo",]'
      ,q'[  "CustomerRef" : "PO123",]'
      ,q'["deliveredItems" : []'
      ,q'[           {"UPC" : "24586356789",]'
      ,q'[             "qty_ordered" : 20 },]'
      ,q'[            {"UPC" : "24586456862",]'
      ,q'[              "qty_reqd" : 10 }],]'
      ,q'[ "mode" ; "air",]'
      ,q'[ "waybill" : "45673647741578",]'
      ,q'[ "dateDelivered" : 2024-10-02T08:47:00,]'
      ,q'[ "signedForBy" : "Bill Smith"]'
      ,q'[}</apex:expression>]'
      ,q'[          </apex:payload>]'
      ,q'[        </bpmn:extensionElements>]'
      ,q'[      </bpmn:messageEventDefinition>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_Tutorial7b">]'
      ,q'[      <bpmndi:BPMNShape id="Participant_15yep6c_di" bpmnElement="Participant_7b_Customer" isHorizontal="true" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="130" y="60" width="1410" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1nkrf5h_di" bpmnElement="Event_1nkrf5h">]'
      ,q'[        <dc:Bounds x="172" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="162" y="225" width="56" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1eeaz0i_di" bpmnElement="Activity_1g5w4wf">]'
      ,q'[        <dc:Bounds x="260" y="160" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1kljmjo_di" bpmnElement="Activity_1kljmjo">]'
      ,q'[        <dc:Bounds x="570" y="160" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_08urp2f_di" bpmnElement="Event_19wz3hb">]'
      ,q'[        <dc:Bounds x="482" y="182" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_16039p0_di" bpmnElement="Event_1fztck2">]'
      ,q'[        <dc:Bounds x="1122" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1099" y="152" width="83" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0iewhwo_di" bpmnElement="Event_0iewhwo">]'
      ,q'[        <dc:Bounds x="1442" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1418" y="225" width="85" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_11myztk_di" bpmnElement="Event_0hf2lpk">]'
      ,q'[        <dc:Bounds x="1342" y="182" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1321" y="152" width="78" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1u809yb_di" bpmnElement="Flow_1u809yb">]'
      ,q'[        <di:waypoint x="208" y="200" />]'
      ,q'[        <di:waypoint x="260" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02x6exq_di" bpmnElement="Flow_02x6exq">]'
      ,q'[        <di:waypoint x="360" y="200" />]'
      ,q'[        <di:waypoint x="482" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ts8jds_di" bpmnElement="Flow_1ts8jds">]'
      ,q'[        <di:waypoint x="518" y="200" />]'
      ,q'[        <di:waypoint x="570" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1frr481_di" bpmnElement="Flow_1frr481">]'
      ,q'[        <di:waypoint x="670" y="200" />]'
      ,q'[        <di:waypoint x="1122" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_13afku8_di" bpmnElement="Flow_13afku8">]'
      ,q'[        <di:waypoint x="1158" y="200" />]'
      ,q'[        <di:waypoint x="1342" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0zdvd7b_di" bpmnElement="Flow_0zdvd7b">]'
      ,q'[        <di:waypoint x="1378" y="200" />]'
      ,q'[        <di:waypoint x="1442" y="200" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_1rpty8o_di" bpmnElement="Participant_7b_Supplier" isHorizontal="true" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="130" y="370" width="1410" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0lengvb_di" bpmnElement="Event_0fqjob4">]'
      ,q'[        <dc:Bounds x="282" y="492" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1657afv_di" bpmnElement="Activity_1657afv">]'
      ,q'[        <dc:Bounds x="350" y="470" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_07bajuw_di" bpmnElement="Event_08o84ee">]'
      ,q'[        <dc:Bounds x="482" y="492" width="36" height="36" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0wj2cv8_di" bpmnElement="Activity_0wj2cv8">]'
      ,q'[        <dc:Bounds x="550" y="470" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1b2xsdh_di" bpmnElement="Event_0s6f6tl">]'
      ,q'[        <dc:Bounds x="682" y="492" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="664" y="462" width="72" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1r3kc27_di" bpmnElement="Event_02ycj50">]'
      ,q'[        <dc:Bounds x="1252" y="492" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1229" y="462" width="83" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1ggdcq9_di" bpmnElement="Event_10ujxv8">]'
      ,q'[        <dc:Bounds x="1342" y="492" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1317" y="535" width="86" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1c0rg1m_di" bpmnElement="Flow_1c0rg1m">]'
      ,q'[        <di:waypoint x="318" y="510" />]'
      ,q'[        <di:waypoint x="350" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0spqr5a_di" bpmnElement="Flow_0spqr5a">]'
      ,q'[        <di:waypoint x="450" y="510" />]'
      ,q'[        <di:waypoint x="482" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0hfmmi9_di" bpmnElement="Flow_0hfmmi9">]'
      ,q'[        <di:waypoint x="518" y="510" />]'
      ,q'[        <di:waypoint x="550" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0cy0mu1_di" bpmnElement="Flow_0cy0mu1">]'
      ,q'[        <di:waypoint x="650" y="510" />]'
      ,q'[        <di:waypoint x="682" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_16mzs2c_di" bpmnElement="Flow_16mzs2c">]'
      ,q'[        <di:waypoint x="718" y="510" />]'
      ,q'[        <di:waypoint x="1252" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_15quyrs_di" bpmnElement="Flow_15quyrs">]'
      ,q'[        <di:waypoint x="1288" y="510" />]'
      ,q'[        <di:waypoint x="1342" y="510" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="Participant_1e0if9q_di" bpmnElement="Participant_7b_Shipper" isHorizontal="true" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="130" y="670" width="1420" height="250" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_18mxl06_di" bpmnElement="Event_1uaun7m">]'
      ,q'[        <dc:Bounds x="682" y="782" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="667" y="825" width="67" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1djmvxg_di" bpmnElement="Activity_1djmvxg">]'
      ,q'[        <dc:Bounds x="770" y="760" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1dsrrm0_di" bpmnElement="Activity_1dsrrm0">]'
      ,q'[        <dc:Bounds x="930" y="760" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_00enaqu_di" bpmnElement="Activity_1w7qibr">]'
      ,q'[        <dc:Bounds x="1090" y="760" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1fxf80q_di" bpmnElement="Event_0mnrcwj">]'
      ,q'[        <dc:Bounds x="1252" y="782" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1228" y="825" width="84" height="40" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1wjgsuc_di" bpmnElement="Flow_1wjgsuc">]'
      ,q'[        <di:waypoint x="718" y="800" />]'
      ,q'[        <di:waypoint x="770" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0mkjf1m_di" bpmnElement="Flow_0mkjf1m">]'
      ,q'[        <di:waypoint x="870" y="800" />]'
      ,q'[        <di:waypoint x="930" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_01ollhu_di" bpmnElement="Flow_01ollhu">]'
      ,q'[        <di:waypoint x="1030" y="800" />]'
      ,q'[        <di:waypoint x="1090" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0c700da_di" bpmnElement="Flow_0c700da">]'
      ,q'[        <di:waypoint x="1190" y="800" />]'
      ,q'[        <di:waypoint x="1252" y="800" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_066thix_di" bpmnElement="TextAnnotation_066thix">]'
      ,q'[        <dc:Bounds x="180" y="390" width="100" height="110.00000762939453" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0kt0jjy_di" bpmnElement="TextAnnotation_0kt0jjy">]'
      ,q'[        <dc:Bounds x="230" y="550" width="100" height="67.9891357421875" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1rzdx0j_di" bpmnElement="TextAnnotation_1rzdx0j">]'
      ,q'[        <dc:Bounds x="520" y="70" width="100" height="95.99185180664062" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0bhm3wb_di" bpmnElement="TextAnnotation_0bhm3wb">]'
      ,q'[        <dc:Bounds x="190" y="690" width="269.98750728735666" height="210.2112099960983" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0t0pz11_di" bpmnElement="Association_0t0pz11">]'
      ,q'[        <di:waypoint x="283" y="504" />]'
      ,q'[        <di:waypoint x="270" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_06ooxgb_di" bpmnElement="Association_06ooxgb">]'
      ,q'[        <di:waypoint x="350" y="533" />]'
      ,q'[        <di:waypoint x="313" y="550" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1xt7bzk_di" bpmnElement="Association_1xt7bzk">]'
      ,q'[        <di:waypoint x="509" y="185" />]'
      ,q'[        <di:waypoint x="521" y="166" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1o8f1tb_di" bpmnElement="Association_1o8f1tb">]'
      ,q'[        <di:waypoint x="682" y="796" />]'
      ,q'[        <di:waypoint x="460" y="750" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0qqyp6t_di" bpmnElement="Flow_0qqyp6t">]'
      ,q'[        <di:waypoint x="300" y="240" />]'
      ,q'[        <di:waypoint x="300" y="492" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="312" y="333" width="16" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1lagn3a_di" bpmnElement="Flow_1lagn3a">]'
      ,q'[        <di:waypoint x="500" y="492" />]'
      ,q'[        <di:waypoint x="500" y="218" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="481" y="333" width="16" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1fa2d0d_di" bpmnElement="Flow_1fa2d0d">]'
      ,q'[        <di:waypoint x="700" y="528" />]'
      ,q'[        <di:waypoint x="700" y="782" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="711" y="636" width="57" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0jri9bb_di" bpmnElement="Flow_0jri9bb">]'
      ,q'[        <di:waypoint x="1140" y="760" />]'
      ,q'[        <di:waypoint x="1140" y="218" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1154" y="633" width="71" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_13km3up_di" bpmnElement="Flow_13km3up">]'
      ,q'[        <di:waypoint x="1270" y="782" />]'
      ,q'[        <di:waypoint x="1270" y="528" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1278" y="626" width="63" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_175p4nl_di" bpmnElement="Flow_175p4nl">]'
      ,q'[        <di:waypoint x="1360" y="492" />]'
      ,q'[        <di:waypoint x="1360" y="218" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1372" y="333" width="35" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 7b - Process Collaboration and MessageFlow Example',
    pi_dgrm_version => '9',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
