declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:apex="https://flowsforapex.org" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:color="http://www.omg.org/spec/BPMN/non-normative/color/1.0" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/b" exporter="Flows for APEX" exporterVersion="25.1.0">]'
      ,q'[  <bpmn:process id="Process_Tutorial3A" name="Tutorial 3A - Setting Process Variables" isExecutable="true" apex:isStartable="true" apex:minLoggingLevel="0" apex:manualInput="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Consulting.]'
      ,q'[twitter: @FlowquestR</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_07kduq4" name="Start">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:onEvent>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Originator</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>coalesce  ( sys_context('apex$session','app_user') ]'
      ,q'[                        , sys_context('userenv','os_user')]'
      ,q'[                        , sys_context('userenv','session_user'))</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:onEvent>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:outgoing>Flow_1mu28br</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_0f3qzi7" name="Intro">]'
      ,q'[      <bpmn:incoming>Flow_1mu28br</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_18wa8fy</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1mu28br" sourceRef="Event_07kduq4" targetRef="Activity_0f3qzi7" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_18wa8fy" sourceRef="Activity_0f3qzi7" targetRef="Gateway_Split" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_Split" name="Split">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeSplit>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Gateway_Split:route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>Flow_A:Flow_C</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeSplit>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_18wa8fy</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_A</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_B</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_C</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_07qs6zg" name="A">]'
      ,q'[      <bpmn:incoming>Flow_A</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0v2gxnx</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_A" name="Path A" sourceRef="Gateway_Split" targetRef="Activity_07qs6zg" />]'
      ,q'[    <bpmn:task id="Activity_1ncqgha" name="B">]'
      ,q'[      <bpmn:incoming>Flow_B</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12ant4j</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_B" name="Path B" sourceRef="Gateway_Split" targetRef="Activity_1ncqgha" />]'
      ,q'[    <bpmn:task id="Activity_04g7z25" name="C">]'
      ,q'[      <bpmn:incoming>Flow_C</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0q16wkh</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_C" name="Path C" sourceRef="Gateway_Split" targetRef="Activity_04g7z25" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0v2gxnx" sourceRef="Activity_07qs6zg" targetRef="Gateway_Merge" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12ant4j" sourceRef="Activity_1ncqgha" targetRef="Gateway_Merge" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0q16wkh" sourceRef="Activity_04g7z25" targetRef="Gateway_Merge" />]'
      ,q'[    <bpmn:inclusiveGateway id="Gateway_Merge" name="Merge">]'
      ,q'[      <bpmn:incoming>Flow_0v2gxnx</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_12ant4j</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0q16wkh</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1umd44r</bpmn:outgoing>]'
      ,q'[    </bpmn:inclusiveGateway>]'
      ,q'[    <bpmn:task id="Activity_Check_EMP_DEPT" name="Check if EMP/DEPT exists">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EMP_DEPT_exists</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlFunctionBody</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>declare]'
      ,q'[  l_table varchar2(30);]'
      ,q'[begin]'
      ,q'[  select table_name into l_table from user_tables where table_name = 'EMP';]'
      ,q'[     return 'yes';]'
      ,q'[exception]'
      ,q'[  when no_data_found then]'
      ,q'[    return 'no';]'
      ,q'[  when others then ]'
      ,q'[   return 'some other problem';]'
      ,q'[end;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1umd44r</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02gbfxv</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1umd44r" sourceRef="Gateway_Merge" targetRef="Activity_Check_EMP_DEPT" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02gbfxv" sourceRef="Activity_Check_EMP_DEPT" targetRef="Gateway_Split2" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split2" name="Split for Expression Types">]'
      ,q'[      <bpmn:incoming>Flow_02gbfxv</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1lf75u4</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0n99kf7</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_09wlg86</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:task id="Activity_Static" name="Static Assignment">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Static_before</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>This gets set to your Static String Content Before the Task</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[        <apex:afterTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>Static_After</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>And this one gets set after the task completes.</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:afterTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1lf75u4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12jbalk</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1lf75u4" sourceRef="Gateway_Split2" targetRef="Activity_Static" />]'
      ,q'[    <bpmn:task id="Activity_Copy" name="Copy of another Process Variable">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>BeforeTask_CopyofEMP_DEPT_route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>processVariable</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>EMP_DEPT_exists</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0n99kf7</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_048t0de</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0n99kf7" sourceRef="Gateway_Split2" targetRef="Activity_Copy" />]'
      ,q'[    <bpmn:task id="Activity_SQLSingle" name="Single SQL Query">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>KingJob</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQuerySingle</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select job]'
      ,q'[from emp]'
      ,q'[where ename = 'KING'</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>NoDataFoundItem</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQuerySingle</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select job]'
      ,q'[from emp]'
      ,q'[where ename = 'Fred'</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1ncsvvk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0uhb1gg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_SQLMulti" name="Colon Delimited SQL Query">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>SALESstaff</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[join dept on dept.deptno = emp.deptno]'
      ,q'[where dname = 'SALES'</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>NoDataResult</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryList</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select ename]'
      ,q'[from emp]'
      ,q'[where deptno = 60</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_19owlyu</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_11xbqtl</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:task id="Activity_Expression" name="expression">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>expression_number</apex:varName>]'
      ,q'[            <apex:varDataType>NUMBER</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>7 * 6</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>1</apex:varSequence>]'
      ,q'[            <apex:varName>this_month</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlExpression</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>to_char(sysdate,'Month')</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0h2z2w4</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0v3onte</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:exclusiveGateway id="EMP_DEPT_exists" name="EMP and DEPT Exist?">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeSplit>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>EMP_DEPT_exists:route</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>processVariable</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>EMP_DEPT_exists</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeSplit>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_09wlg86</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>yes</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>no</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_09wlg86" sourceRef="Gateway_Split2" targetRef="EMP_DEPT_exists" />]'
      ,q'[    <bpmn:sequenceFlow id="yes" name="yes" sourceRef="EMP_DEPT_exists" targetRef="Gateway_Split_EMP_exists" />]'
      ,q'[    <bpmn:parallelGateway id="Gateway_Split_EMP_exists" name="Paths using EMP">]'
      ,q'[      <bpmn:incoming>yes</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1ncsvvk</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_19owlyu</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0h2z2w4</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_19qdo14</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_0dpvv93</bpmn:outgoing>]'
      ,q'[    </bpmn:parallelGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1ncsvvk" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_SQLSingle" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_19owlyu" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_SQLMulti" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0h2z2w4" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_Expression" />]'
      ,q'[    <bpmn:task id="Activity_FuncBody" name="function body">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>BeforeTask_FuncBody</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>plsqlFunctionBody</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>declare]'
      ,q'[  l_month varchar2(20);]'
      ,q'[begin]'
      ,q'[  l_month := to_char( to_date('24-12-1970','DD-MM-YYYY') , 'MM');]'
      ,q'[ return l_month;]'
      ,q'[end;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_19qdo14</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0494hmn</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_19qdo14" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_FuncBody" />]'
      ,q'[    <bpmn:endEvent id="Event_0sttahj" name="Static End">]'
      ,q'[      <bpmn:incoming>Flow_12jbalk</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12jbalk" sourceRef="Activity_Static" targetRef="Event_0sttahj" />]'
      ,q'[    <bpmn:endEvent id="Event_1323y7h" name="Copy End">]'
      ,q'[      <bpmn:incoming>Flow_048t0de</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_048t0de" sourceRef="Activity_Copy" targetRef="Event_1323y7h" />]'
      ,q'[    <bpmn:endEvent id="Event_0yhvzko" name="SQL End">]'
      ,q'[      <bpmn:incoming>Flow_0uhb1gg</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0uhb1gg" sourceRef="Activity_SQLSingle" targetRef="Event_0yhvzko" />]'
      ,q'[    <bpmn:endEvent id="Event_0nmox7s" name="SQL Multi End">]'
      ,q'[      <bpmn:incoming>Flow_11xbqtl</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_11xbqtl" sourceRef="Activity_SQLMulti" targetRef="Event_0nmox7s" />]'
      ,q'[    <bpmn:endEvent id="Event_0mmc47q" name="Expression End">]'
      ,q'[      <bpmn:incoming>Flow_0v3onte</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0v3onte" sourceRef="Activity_Expression" targetRef="Event_0mmc47q" />]'
      ,q'[    <bpmn:endEvent id="Event_1sjraqb" name="Function Body End">]'
      ,q'[      <bpmn:incoming>Flow_0494hmn</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0494hmn" sourceRef="Activity_FuncBody" targetRef="Event_1sjraqb" />]'
      ,q'[    <bpmn:endEvent id="Event_1g6u9dx" name="No EMP/DEPT End">]'
      ,q'[      <bpmn:incoming>no</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="no" name="no" sourceRef="EMP_DEPT_exists" targetRef="Event_1g6u9dx" />]'
      ,q'[    <bpmn:task id="Activity_037o7il" name="JSON Array SQL Query">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>JSONarrayFromSQL</apex:varName>]'
      ,q'[            <apex:varDataType>JSON</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>sqlQueryArray</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>select empno, ename, (sal + comm) Compensation]'
      ,q'[from   emp]'
      ,q'[where  deptno = 20;</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_0dpvv93</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0u1yti2</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0dpvv93" sourceRef="Gateway_Split_EMP_exists" targetRef="Activity_037o7il" />]'
      ,q'[    <bpmn:endEvent id="Event_1vkpxw2" name="SQL Array End">]'
      ,q'[      <bpmn:incoming>Flow_0u1yti2</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0u1yti2" sourceRef="Activity_037o7il" targetRef="Event_1vkpxw2" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0saz0u3">]'
      ,q'[      <bpmn:text>So you can set the routing instruction in a declarative variable expression, now defined inside the gateway definition in the model - rather than by a scriptTask.  Click in this gateway, then look at the Variables tab in the properties panel.]'
      ,q'[You can see that the routing instruction is set up in a 'Before Split' expression set to route the process to Task A and Task C.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1njps2n" sourceRef="Gateway_Split" targetRef="TextAnnotation_0saz0u3" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0hdt28j">]'
      ,q'[      <bpmn:text>This tutorial introduces Declarative Variable Expressions, new in V21.1]'
      ,q'[]'
      ,q'[Each object in the Flow diagram can set a group of Process Variables before and after* it executes - so you can use this to keep track of process state, set gateway routing variables, hand keep track of things like who started the process, when you need it to finish, its priority or sensitivity, as well as run counters or other control variables.]'
      ,q'[]'
      ,q'[Variable Expressions can set process variables to static values, copy another variable, do a SQL query, evaluate an expression or a PL/SL function body.]'
      ,q'[]'
      ,q'[This tutorial works best if you have the standard EMP &amp; DEPT tables installed in your workspace - but you can see how we test whether they are there before running the parts of the model that rely on them.]'
      ,q'[]'
      ,q'[This tutorial runs through the key features.  Variable expression definitions are shown in the 'Variables' tab of the properties panel.]'
      ,q'[]'
      ,q'[* Task objects (task, script task, user task, etc) can have expressions that execute BEFORE TASK and AFTER TASK.]'
      ,q'[Event Objects (Start, End, Intermediate Throws and Catches, Boundary Events) ON EVENT and sometimes BEFORE EVENT.]'
      ,q'[Gateway Objects have expressions that execute BEFORE SPLIT and AFTER MERGE, depending upon the gateway usage.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1nkd87f" sourceRef="Activity_0f3qzi7" targetRef="TextAnnotation_0hdt28j" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_04rgdnn">]'
      ,q'[      <bpmn:text>Use your start event to initialise any standard variables that you want to use for all of your running instances...]'
      ,q'[]'
      ,q'[We set 'Originator' here to your userid...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0tqwtb7" sourceRef="Event_07kduq4" targetRef="TextAnnotation_04rgdnn" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0y91707">]'
      ,q'[      <bpmn:text>This executes a function body, returning 'yes' if EMP exists in your workspace, and 'no' if it doesn't -- as a before task activity. ]'
      ,q'[]'
      ,q'[This is then used to set the routing for the 'EMP and DEPT exist?' gateway 2 steps later...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0vlxnu9" sourceRef="Activity_Check_EMP_DEPT" targetRef="TextAnnotation_0y91707" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1w01shu">]'
      ,q'[      <bpmn:text>new in 24.1</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1vgf7fb" associationDirection="None" sourceRef="Activity_037o7il" targetRef="TextAnnotation_1w01shu" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Tutorial3A">]'
      ,q'[      <bpmndi:BPMNShape id="Event_07kduq4_di" bpmnElement="Event_07kduq4">]'
      ,q'[        <dc:Bounds x="242" y="482" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="248" y="525" width="24" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0f3qzi7_di" bpmnElement="Activity_0f3qzi7">]'
      ,q'[        <dc:Bounds x="330" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0befb5k_di" bpmnElement="Gateway_Split" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="485" y="475" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="500" y="445" width="22" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07qs6zg_di" bpmnElement="Activity_07qs6zg" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="640" y="460" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ncqgha_di" bpmnElement="Activity_1ncqgha" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="640" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_04g7z25_di" bpmnElement="Activity_04g7z25" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="640" y="680" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0xexztv_di" bpmnElement="Gateway_Merge" bioc:stroke="#6b3c00" bioc:fill="#ffe0b2" color:background-color="#ffe0b2" color:border-color="#6b3c00">]'
      ,q'[        <dc:Bounds x="825" y="585" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="884" y="573" width="32" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ymetlw_di" bpmnElement="Activity_Check_EMP_DEPT">]'
      ,q'[        <dc:Bounds x="960" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_03bnkja_di" bpmnElement="Gateway_Split2">]'
      ,q'[        <dc:Bounds x="1115" y="585" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1098" y="642" width="87" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_07hns5v_di" bpmnElement="Activity_Static" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1440" y="300" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_17wunpk_di" bpmnElement="Activity_Copy" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1440" y="440" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ikwbj4_di" bpmnElement="Activity_SQLSingle" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1440" y="570" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1ov9j10_di" bpmnElement="Activity_SQLMulti" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1440" y="700" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1s8xbrn_di" bpmnElement="Activity_Expression" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1440" y="940" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0qmyt5q_di" bpmnElement="EMP_DEPT_exists" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1205" y="585" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1192" y="555" width="78" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1meehlq_di" bpmnElement="Gateway_Split_EMP_exists">]'
      ,q'[        <dc:Bounds x="1295" y="585" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1317" y="562" width="85" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0ltt770_di" bpmnElement="Activity_FuncBody" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1440" y="1050" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0sttahj_di" bpmnElement="Event_0sttahj" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1642" y="322" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1635" y="365" width="51" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1323y7h_di" bpmnElement="Event_1323y7h" bioc:stroke="#205022" bioc:fill="#c8e6c9" color:background-color="#c8e6c9" color:border-color="#205022">]'
      ,q'[        <dc:Bounds x="1642" y="462" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1636" y="505" width="49" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0yhvzko_di" bpmnElement="Event_0yhvzko" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1642" y="592" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1638" y="635" width="45" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0nmox7s_di" bpmnElement="Event_0nmox7s" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1642" y="722" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1625" y="765" width="71" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0mmc47q_di" bpmnElement="Event_0mmc47q" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1642" y="962" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1622" y="1005" width="78" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1sjraqb_di" bpmnElement="Event_1sjraqb" bioc:stroke="#831311" bioc:fill="#ffcdd2" color:background-color="#ffcdd2" color:border-color="#831311">]'
      ,q'[        <dc:Bounds x="1642" y="1072" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1625" y="1115" width="71" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1g6u9dx_di" bpmnElement="Event_1g6u9dx">]'
      ,q'[        <dc:Bounds x="1642" y="1202" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1623" y="1245" width="74" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_037o7il_di" bpmnElement="Activity_037o7il" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="1440" y="820" width="100" height="80" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_1vkpxw2_di" bpmnElement="Event_1vkpxw2" bioc:stroke="#0d4372" bioc:fill="#bbdefb" color:background-color="#bbdefb" color:border-color="#0d4372">]'
      ,q'[        <dc:Bounds x="1642" y="842" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1623" y="885" width="74" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0saz0u3_di" bpmnElement="TextAnnotation_0saz0u3">]'
      ,q'[        <dc:Bounds x="510" y="260" width="520" height="98" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0hdt28j_di" bpmnElement="TextAnnotation_0hdt28j">]'
      ,q'[        <dc:Bounds x="330" y="-60" width="760" height="270" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_04rgdnn_di" bpmnElement="TextAnnotation_04rgdnn">]'
      ,q'[        <dc:Bounds x="260" y="595" width="189.99231763033313" height="111" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0y91707_di" bpmnElement="TextAnnotation_0y91707">]'
      ,q'[        <dc:Bounds x="820" y="855" width="345.0000305175781" height="91.99652862548828" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1w01shu_di" bpmnElement="TextAnnotation_1w01shu">]'
      ,q'[        <dc:Bounds x="1350" y="780" width="99.99473856692492" height="29.99278552634423" />]'
      ,q'[        <bpmndi:BPMNLabel />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1mu28br_di" bpmnElement="Flow_1mu28br">]'
      ,q'[        <di:waypoint x="278" y="500" />]'
      ,q'[        <di:waypoint x="330" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_18wa8fy_di" bpmnElement="Flow_18wa8fy">]'
      ,q'[        <di:waypoint x="430" y="500" />]'
      ,q'[        <di:waypoint x="485" y="500" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0my1j3h_di" bpmnElement="Flow_A">]'
      ,q'[        <di:waypoint x="535" y="500" />]'
      ,q'[        <di:waypoint x="640" y="500" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="573" y="482" width="34" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_045akdd_di" bpmnElement="Flow_B">]'
      ,q'[        <di:waypoint x="510" y="525" />]'
      ,q'[        <di:waypoint x="510" y="610" />]'
      ,q'[        <di:waypoint x="640" y="610" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="541" y="583" width="33" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ztr3iy_di" bpmnElement="Flow_C">]'
      ,q'[        <di:waypoint x="510" y="525" />]'
      ,q'[        <di:waypoint x="510" y="720" />]'
      ,q'[        <di:waypoint x="640" y="720" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="542" y="693" width="34" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0v2gxnx_di" bpmnElement="Flow_0v2gxnx">]'
      ,q'[        <di:waypoint x="740" y="500" />]'
      ,q'[        <di:waypoint x="850" y="500" />]'
      ,q'[        <di:waypoint x="850" y="585" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12ant4j_di" bpmnElement="Flow_12ant4j">]'
      ,q'[        <di:waypoint x="740" y="610" />]'
      ,q'[        <di:waypoint x="825" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0q16wkh_di" bpmnElement="Flow_0q16wkh">]'
      ,q'[        <di:waypoint x="740" y="720" />]'
      ,q'[        <di:waypoint x="850" y="720" />]'
      ,q'[        <di:waypoint x="850" y="635" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1umd44r_di" bpmnElement="Flow_1umd44r">]'
      ,q'[        <di:waypoint x="875" y="610" />]'
      ,q'[        <di:waypoint x="960" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02gbfxv_di" bpmnElement="Flow_02gbfxv">]'
      ,q'[        <di:waypoint x="1060" y="610" />]'
      ,q'[        <di:waypoint x="1115" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1lf75u4_di" bpmnElement="Flow_1lf75u4">]'
      ,q'[        <di:waypoint x="1140" y="585" />]'
      ,q'[        <di:waypoint x="1140" y="340" />]'
      ,q'[        <di:waypoint x="1440" y="340" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0n99kf7_di" bpmnElement="Flow_0n99kf7">]'
      ,q'[        <di:waypoint x="1140" y="585" />]'
      ,q'[        <di:waypoint x="1140" y="480" />]'
      ,q'[        <di:waypoint x="1440" y="480" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_09wlg86_di" bpmnElement="Flow_09wlg86">]'
      ,q'[        <di:waypoint x="1165" y="610" />]'
      ,q'[        <di:waypoint x="1205" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0ndh330_di" bpmnElement="yes">]'
      ,q'[        <di:waypoint x="1255" y="610" />]'
      ,q'[        <di:waypoint x="1295" y="610" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1266" y="592" width="18" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1ncsvvk_di" bpmnElement="Flow_1ncsvvk">]'
      ,q'[        <di:waypoint x="1345" y="610" />]'
      ,q'[        <di:waypoint x="1440" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_19owlyu_di" bpmnElement="Flow_19owlyu">]'
      ,q'[        <di:waypoint x="1320" y="635" />]'
      ,q'[        <di:waypoint x="1320" y="740" />]'
      ,q'[        <di:waypoint x="1440" y="740" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0h2z2w4_di" bpmnElement="Flow_0h2z2w4">]'
      ,q'[        <di:waypoint x="1320" y="635" />]'
      ,q'[        <di:waypoint x="1320" y="980" />]'
      ,q'[        <di:waypoint x="1440" y="980" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_19qdo14_di" bpmnElement="Flow_19qdo14">]'
      ,q'[        <di:waypoint x="1320" y="635" />]'
      ,q'[        <di:waypoint x="1320" y="1090" />]'
      ,q'[        <di:waypoint x="1440" y="1090" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12jbalk_di" bpmnElement="Flow_12jbalk">]'
      ,q'[        <di:waypoint x="1540" y="340" />]'
      ,q'[        <di:waypoint x="1642" y="340" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_048t0de_di" bpmnElement="Flow_048t0de">]'
      ,q'[        <di:waypoint x="1540" y="480" />]'
      ,q'[        <di:waypoint x="1642" y="480" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0uhb1gg_di" bpmnElement="Flow_0uhb1gg">]'
      ,q'[        <di:waypoint x="1540" y="610" />]'
      ,q'[        <di:waypoint x="1642" y="610" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_11xbqtl_di" bpmnElement="Flow_11xbqtl">]'
      ,q'[        <di:waypoint x="1540" y="740" />]'
      ,q'[        <di:waypoint x="1642" y="740" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0v3onte_di" bpmnElement="Flow_0v3onte">]'
      ,q'[        <di:waypoint x="1540" y="980" />]'
      ,q'[        <di:waypoint x="1642" y="980" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0494hmn_di" bpmnElement="Flow_0494hmn">]'
      ,q'[        <di:waypoint x="1540" y="1090" />]'
      ,q'[        <di:waypoint x="1642" y="1090" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0m65uty_di" bpmnElement="no">]'
      ,q'[        <di:waypoint x="1230" y="635" />]'
      ,q'[        <di:waypoint x="1230" y="1220" />]'
      ,q'[        <di:waypoint x="1642" y="1220" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1239" y="1062" width="13" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0dpvv93_di" bpmnElement="Flow_0dpvv93">]'
      ,q'[        <di:waypoint x="1320" y="635" />]'
      ,q'[        <di:waypoint x="1320" y="860" />]'
      ,q'[        <di:waypoint x="1440" y="860" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0u1yti2_di" bpmnElement="Flow_0u1yti2">]'
      ,q'[        <di:waypoint x="1540" y="860" />]'
      ,q'[        <di:waypoint x="1642" y="860" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1njps2n_di" bpmnElement="Association_1njps2n">]'
      ,q'[        <di:waypoint x="515" y="480" />]'
      ,q'[        <di:waypoint x="542" y="358" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1nkd87f_di" bpmnElement="Association_1nkd87f">]'
      ,q'[        <di:waypoint x="379" y="460" />]'
      ,q'[        <di:waypoint x="374" y="210" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0tqwtb7_di" bpmnElement="Association_0tqwtb7">]'
      ,q'[        <di:waypoint x="267" y="516" />]'
      ,q'[        <di:waypoint x="303" y="595" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0vlxnu9_di" bpmnElement="Association_0vlxnu9">]'
      ,q'[        <di:waypoint x="988" y="650" />]'
      ,q'[        <di:waypoint x="878" y="855" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1vgf7fb_di" bpmnElement="Association_1vgf7fb">]'
      ,q'[        <di:waypoint x="1440" y="851" />]'
      ,q'[        <di:waypoint x="1330" y="830" />]'
      ,q'[        <di:waypoint x="1330" y="795" />]'
      ,q'[        <di:waypoint x="1350" y="795" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 3a - Setting Process Variables from your Model',
    pi_dgrm_short_description => 'Flows for APEX BPMN Tutorials - Part 3a - introduces process variables, used for storing information for the duration of the process instance.',
    pi_dgrm_description => '**Process Model: Tutorial 3A - Setting Process Variables**

This business process model represents a tutorial designed by Richard Allen of Flowquest Consulting, focusing on the setting of process variables within a workflow. This model serves as an instructional guide within the Flows for APEX platform, illustrating advanced techniques for managing flow state using declarative variable expressions in a Business Process Model and Notation (BPMN) environment.

#### Key Features:

**Start Event**:

*   Initializes the process by setting a standard variable, ''Originator'', to track the user ID of the process initiator.

**Intro Task**:

*   Provides an introductory segment which leads to a key decision point in the workflow.

**Gateway & Tasks**:

*   Incorporates an inclusive gateway (Split) that allows for multiple pathways (A, B, and C), with dynamic routing based on predefined expressions.
*   Tasks labelled ''A'', ''B'', and ''C'' represent separate process paths that can be concurrently executed.

**Process Variables**:

*   Variables are dynamically set using various expression types (e.g., static, SQL queries, PL/SQL expressions) intended to simulate real-world data handling scenarios within a workflow.
*   The structure includes pathways that test for the presence of specific database tables (e.g., EMP and DEPT) to demonstrate conditional processing.

**Complex Decision-making**:

*   The model utilizes exclusive and parallel gateways to guide the process flow based on complex decision-making rules defined by variable expressions.
*   The ''EMP and DEPT exist?'' gateway determines the process continuity by checking required resource availability.

**End Events**:

*   Concludes with multiple end events, each associated with distinct pathways (Static, Copy, SQL, and JSON processing) to showcase different outcome scenarios depending on the selected process path.

#### Educational Insight:

This model is aimed at educating users on the capabilities of declarative variable expressions within BPMN, especially in the context of the Flows for APEX platform. The tutorial highlights how processes can be dynamically controlled and adjusted based on internal logic and data derivation, offering a comprehensive understanding of managing variables in process automation.

With an emphasis on practical application, this tutorial can serve as both an educational resource and a baseline for developers and business analysts to understand and implement variable manipulations in automated workflows. The tutorial suggests having standard database elements (e.g., EMP and DEPT tables) for optimal illustration of the tasks.

Overall, this process model is an instructional asset that enhances understanding of variable management within complex business processes, aiming to bolster the operational efficiency of automated workflows through insightful learning.',
    pi_dgrm_icon => 'fa-notebook fam-information fam-is-info',
    pi_dgrm_version => '25.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
