declare
  l_dgrm_content clob;
begin
  l_dgrm_content := apex_string.join_clob(
    apex_t_varchar2(
      q'[<?xml version="1.0" encoding="UTF-8"?>]'
      ,q'[<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:apex="https://flowsforapex.org" id="Definitions_1wzb475" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Flows for APEX" exporterVersion="23.1.0">]'
      ,q'[  <bpmn:process id="Process_Gateway_Tutorial" name="Gateway Routing Tutorial" isExecutable="false" apex:isCallable="false" apex:manualInput="false">]'
      ,q'[    <bpmn:documentation>Tutorials by Richard Allen.]'
      ,q'[Flowquest Consulting.]'
      ,q'[twitter: @FlowquestR</bpmn:documentation>]'
      ,q'[    <bpmn:startEvent id="Event_0rq5hjv" name="Start Tutorial">]'
      ,q'[      <bpmn:outgoing>Flow_0yr7dsk</bpmn:outgoing>]'
      ,q'[    </bpmn:startEvent>]'
      ,q'[    <bpmn:task id="Activity_Concept1" name="Concept 1:&#10;Default Routing">]'
      ,q'[      <bpmn:incoming>Flow_0yr7dsk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_02o3o4y</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0yr7dsk" sourceRef="Event_0rq5hjv" targetRef="Activity_Concept1" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_One" name="Select Route 1?" default="Flow_1h8t6bd">]'
      ,q'[      <bpmn:incoming>Flow_02o3o4y</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0jo4c98</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_1h8t6bd</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_02o3o4y" sourceRef="Activity_Concept1" targetRef="Gateway_One" />]'
      ,q'[    <bpmn:task id="Activity_1b47q7i" name="Yes Route">]'
      ,q'[      <bpmn:incoming>Flow_0jo4c98</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0xk0udg</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0jo4c98" name="Y" sourceRef="Gateway_One" targetRef="Activity_1b47q7i" apex:sequence="20" />]'
      ,q'[    <bpmn:task id="Activity_0jktnki" name="No Route&#10;(Default Path)">]'
      ,q'[      <bpmn:incoming>Flow_1h8t6bd</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1q12jx5</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1h8t6bd" name="N" sourceRef="Gateway_One" targetRef="Activity_0jktnki" apex:sequence="30" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_1d4vdv1" name="Closing&#10;Gateway 1">]'
      ,q'[      <bpmn:incoming>Flow_1q12jx5</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_0xk0udg</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_12a7a04</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1q12jx5" sourceRef="Activity_0jktnki" targetRef="Gateway_1d4vdv1" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0xk0udg" sourceRef="Activity_1b47q7i" targetRef="Gateway_1d4vdv1" />]'
      ,q'[    <bpmn:task id="Activity_0yr8k9p" name="Second Yes Route">]'
      ,q'[      <bpmn:incoming>Flow_3_Yes</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0k5jysk</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:endEvent id="Event_0uu6w6g" name="End Tutorial">]'
      ,q'[      <bpmn:incoming>Flow_0bc9nni</bpmn:incoming>]'
      ,q'[    </bpmn:endEvent>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0k5jysk" sourceRef="Activity_0yr8k9p" targetRef="Gateway_0wcdym9" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_Three" name="Gateway Three">]'
      ,q'[      <bpmn:incoming>Flow_05v09nk</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_3_Yes</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_3_No</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_3_Yes" name="3_Yes" sourceRef="Gateway_Three" targetRef="Activity_0yr8k9p" apex:sequence="20" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_0wcdym9">]'
      ,q'[      <bpmn:incoming>Flow_0k5jysk</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1lsahzw</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_0bc9nni</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_0bc9nni" sourceRef="Gateway_0wcdym9" targetRef="Event_0uu6w6g" apex:sequence="10" />]'
      ,q'[    <bpmn:task id="Activity_0jpxv7u" name="Second No Route">]'
      ,q'[      <bpmn:incoming>Flow_3_No</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1lsahzw</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_3_No" name="3_No" sourceRef="Gateway_Three" targetRef="Activity_0jpxv7u" apex:sequence="30" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1lsahzw" sourceRef="Activity_0jpxv7u" targetRef="Gateway_0wcdym9" />]'
      ,q'[    <bpmn:task id="Activity_Concept3" name="Concept 3: Gateway Routing Variables">]'
      ,q'[      <bpmn:incoming>Flow_11z8xs6</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_05v09nk</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_05v09nk" sourceRef="Activity_Concept3" targetRef="Gateway_Three" />]'
      ,q'[    <bpmn:task id="Activity_Concept2" name="Concept 2:&#10;Gateway Routing Expressions">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeTask>]'
      ,q'[          <apex:processVariable>]'
      ,q'[            <apex:varSequence>0</apex:varSequence>]'
      ,q'[            <apex:varName>DEPT</apex:varName>]'
      ,q'[            <apex:varDataType>VARCHAR2</apex:varDataType>]'
      ,q'[            <apex:varExpressionType>static</apex:varExpressionType>]'
      ,q'[            <apex:varExpression>SALES</apex:varExpression>]'
      ,q'[          </apex:processVariable>]'
      ,q'[        </apex:beforeTask>]'
      ,q'[        <apex:afterTask />]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_12a7a04</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1691lnn</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_12a7a04" sourceRef="Gateway_1d4vdv1" targetRef="Activity_Concept2" apex:sequence="10" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_Two" name="Gateway&#10; Two" default="Flow_ProdDev">]'
      ,q'[      <bpmn:extensionElements>]'
      ,q'[        <apex:beforeSplit />]'
      ,q'[      </bpmn:extensionElements>]'
      ,q'[      <bpmn:incoming>Flow_1691lnn</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_Sales</bpmn:outgoing>]'
      ,q'[      <bpmn:outgoing>Flow_ProdDev</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1691lnn" sourceRef="Activity_Concept2" targetRef="Gateway_Two" />]'
      ,q'[    <bpmn:task id="Activity_Sales" name="Process Sales Bonus">]'
      ,q'[      <bpmn:incoming>Flow_Sales</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1txhooo</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_Sales" name=":DEPT = &#39;SALES&#39;" sourceRef="Gateway_Two" targetRef="Activity_Sales" apex:sequence="10">]'
      ,q'[      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression" language="plsqlExpression">:F4A$DEPT = 'SALES'</bpmn:conditionExpression>]'
      ,q'[    </bpmn:sequenceFlow>]'
      ,q'[    <bpmn:task id="Activity_ProdDev" name="Process ProdDev Bonus">]'
      ,q'[      <bpmn:incoming>Flow_ProdDev</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_1j0axlj</bpmn:outgoing>]'
      ,q'[    </bpmn:task>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_ProdDev" name=":DEPT = &#39;PRODDEV&#39;" sourceRef="Gateway_Two" targetRef="Activity_ProdDev" apex:sequence="20" />]'
      ,q'[    <bpmn:exclusiveGateway id="Gateway_19h24z4">]'
      ,q'[      <bpmn:incoming>Flow_1j0axlj</bpmn:incoming>]'
      ,q'[      <bpmn:incoming>Flow_1txhooo</bpmn:incoming>]'
      ,q'[      <bpmn:outgoing>Flow_11z8xs6</bpmn:outgoing>]'
      ,q'[    </bpmn:exclusiveGateway>]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1j0axlj" sourceRef="Activity_ProdDev" targetRef="Gateway_19h24z4" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_1txhooo" sourceRef="Activity_Sales" targetRef="Gateway_19h24z4" />]'
      ,q'[    <bpmn:sequenceFlow id="Flow_11z8xs6" sourceRef="Gateway_19h24z4" targetRef="Activity_Concept3" apex:sequence="10" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1fvohcn">]'
      ,q'[      <bpmn:text>How to Navigate through a Gateway for a Demo Model: ]'
      ,q'[]'
      ,q'[Method 1: Default Routing.]'
      ,q'[]'
      ,q'[Note that the Lower Route has a '/' mark across the flow.  This denotes it as the default path.]'
      ,q'[To add default path:]'
      ,q'[- select the Flow between the Gateway and the next object.]'
      ,q'[- click on the 'morph' tool (the spanner)]'
      ,q'[- select default path</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0jg4oqm" sourceRef="Gateway_One" targetRef="TextAnnotation_1fvohcn" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0qhtqn5">]'
      ,q'[      <bpmn:text>This is a mini-tutorial on Gateways that will help you create a test model here and execute it.]'
      ,q'[]'
      ,q'[When you add Flows for APEX into your application, you would have some application logic helping to steer you through the gateways.  In this demo environment, we have to cheat a little.]'
      ,q'[]'
      ,q'[The first gateway pair uses default routing to force your model to always go on one path.  Obviously, to test your model you can edit the model to move the default from one path to another....]'
      ,q'[]'
      ,q'[The second gateway uses Gateway Routing Expressions (new in v22.2) - which allows you to define an expression on each of the forward paths.  These are evaluated in sequence_number order - and the first path with an expression that evaluates to 'true' is chosen.  ]'
      ,q'[]'
      ,q'[The third gateway pair shows you how a special process variable, called a Gateway Routing Variable,  can be used to instruct the gateway which route to take.  This is the 'old way' to set gateway routing -- but sometimes this can still be useful.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_1y1u9dd" sourceRef="Activity_Concept1" targetRef="TextAnnotation_0qhtqn5" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_1vzs22f">]'
      ,q'[      <bpmn:text>Method 3: Instructing the Gateway using Routing Variables]'
      ,q'[(This is useful - but a bit more complicated!)]'
      ,q'[]'
      ,q'[Click on the Gateway &amp; see that it has an ID of 'Gateway_Three' in the properties panel on the right.]'
      ,q'[Note that the two forward paths have ID's of 'Flow_3_Yes' and 'Flow_3_No']'
      ,q'[]'
      ,q'[To instruct our gateway 'Gateway_Three' which way to route the process, you would set up a Process Variable with the routing instructions somewhere in your application before you get to the Gateway. ]'
      ,q'[]'
      ,q'[You need to set a process variable with name = &lt;gateway_ID&gt;&lt;:route&gt;. The value needs to be the ID of the route you want it to take.]'
      ,q'[]'
      ,q'[So in our example, we need to set process variable 'Gateway_Three:route' with a varchar2 value of 'Flow_3_Yes' to go down the 3_Yes route, and 'Flow_3_No' to go down the 3_No route.]'
      ,q'[]'
      ,q'[In the Flow Monitor, you can set this manually or you can use the Gateway Route Tool. Run a copy of this model in Flow Control. Before you get to Gateway Three, Click on the Variables Tab. Add a row into the Interactive Grid to create our process variable named 'Gateway_Three:route' , give it a type of VARCHAR2, and set its value to 'Flow_3_No'. Don't forget to Save this. Then go to the Subflows tab, and step the process on through the gateway.]'
      ,q'[]'
      ,q'[Using the Gateway Routing Tool makes this manual process easier. Once you have the process running, select the Variables tab. This gives you a pop-up list of opening gateways, and shows you the possible route options. Select the one or ones you want, and you will see the process variable has been created and set for you. Again, don't forget to save this, then go to the Subflows tab, and step the process on through the gateway.]'
      ,q'[]'
      ,q'[In a real application you wouldn't do this through the Flow Engine console. Somewhere in your application you would set the routing based on your data. This could be a variable set call in any previous step, or you could have a scriptTask in the step immediately before that runs a PL/SQL script to set it based on some query or whatever your imagination can create, or you could use a declarative variable expression to set this in the gateway step.  We'll explore tat later...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0hx891w" sourceRef="Activity_Concept3" targetRef="TextAnnotation_1vzs22f" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_0kv1ra3">]'
      ,q'[      <bpmn:text>An Opening Gateway will first look for a process variable &lt;its name&gt;:route containing a route.  If not finds that, it uses that for its routing.]'
      ,q'[]'
      ,q'[if there is no process variable, it looks for default routing]'
      ,q'[]'
      ,q'[If there is no variable and no default routing, it will return an error to the user.</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_0jgd1xj" sourceRef="Gateway_Three" targetRef="TextAnnotation_0kv1ra3" />]'
      ,q'[    <bpmn:textAnnotation id="TextAnnotation_09eif2m">]'
      ,q'[      <bpmn:text>Method 2: Gateway Routing Expressions.  (New in v22.2)]'
      ,q'[]'
      ,q'[Here we place a condition on each of the forward paths.  The condition can be a PL/SQL Expression or a PL/SQL Function Body.  And note that the forward paths have a Sequence Number to determine theoriser of evaluation.  For an Exclusive Gateway, the first path with a condition that  evaluates to TRUE is chosen.]'
      ,q'[]'
      ,q'[We used a Variable Expression that evaluates 'Before Task' in the Concept2 Task to set a process variable called 'DEPT' equal to 'SALES'.   The demo just uses a static assignment, so it's always 'SALES' -- but the variable expression could have been set by a SQL Query or a PL/SQL Function or Expression...]'
      ,q'[]'
      ,q'[Then the Condition on the Forward path uses 'bind' syntax to compare the current value of DEPT to 'SALES' - If so, it takes this path...]'
      ,q'[]'
      ,q'[Note that we always prefix Flows for APEX variables with F4A$ -  just so they don't get confused with any APEX Page Items.]'
      ,q'[]'
      ,q'[You could also use Substitution Syntax for a process variable, so the condition would be '&amp;F4A$DEPT.' = 'SALES'.]'
      ,q'[]'
      ,q'[You can re-running the process instance and try setting DEPT to 'PRODDEV' or another value...</bpmn:text>]'
      ,q'[    </bpmn:textAnnotation>]'
      ,q'[    <bpmn:association id="Association_11qbgm5" sourceRef="Activity_Concept2" targetRef="TextAnnotation_09eif2m" />]'
      ,q'[  </bpmn:process>]'
      ,q'[  <bpmndi:BPMNDiagram id="BPMNDiagram_1">]'
      ,q'[    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_Gateway_Tutorial">]'
      ,q'[      <bpmndi:BPMNShape id="Event_0rq5hjv_di" bpmnElement="Event_0rq5hjv">]'
      ,q'[        <dc:Bounds x="222" y="332" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="209" y="375" width="63" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_135jcwt_di" bpmnElement="Activity_Concept1">]'
      ,q'[        <dc:Bounds x="340" y="310" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_11lejcq_di" bpmnElement="Gateway_One" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="495" y="325" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="523" y="273" width="76" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1b47q7i_di" bpmnElement="Activity_1b47q7i">]'
      ,q'[        <dc:Bounds x="600" y="310" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0jktnki_di" bpmnElement="Activity_0jktnki">]'
      ,q'[        <dc:Bounds x="600" y="420" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_1d4vdv1_di" bpmnElement="Gateway_1d4vdv1" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="755" y="325" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="753" y="266" width="53" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0yr8k9p_di" bpmnElement="Activity_0yr8k9p">]'
      ,q'[        <dc:Bounds x="1560" y="540" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Event_0uu6w6g_di" bpmnElement="Event_0uu6w6g">]'
      ,q'[        <dc:Bounds x="1912" y="562" width="36" height="36" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1902" y="605" width="58" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0r9iz6p_di" bpmnElement="Gateway_Three" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1395" y="555" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1306" y="570" width="73" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0wcdym9_di" bpmnElement="Gateway_0wcdym9" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1775" y="555" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0jpxv7u_di" bpmnElement="Activity_0jpxv7u">]'
      ,q'[        <dc:Bounds x="1560" y="650" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_1qvl818_di" bpmnElement="Activity_Concept3">]'
      ,q'[        <dc:Bounds x="1370" y="450" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0bimpj6_di" bpmnElement="Activity_Concept2">]'
      ,q'[        <dc:Bounds x="860" y="310" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_0a8tre1_di" bpmnElement="Gateway_Two" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1015" y="325" width="50" height="50" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="979" y="300" width="42" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0g057v7_di" bpmnElement="Activity_Sales">]'
      ,q'[        <dc:Bounds x="1170" y="250" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Activity_0nsxg9h_di" bpmnElement="Activity_ProdDev">]'
      ,q'[        <dc:Bounds x="1170" y="420" width="100" height="80" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="Gateway_19h24z4_di" bpmnElement="Gateway_19h24z4" isMarkerVisible="true">]'
      ,q'[        <dc:Bounds x="1315" y="345" width="50" height="50" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1fvohcn_di" bpmnElement="TextAnnotation_1fvohcn">]'
      ,q'[        <dc:Bounds x="410" y="570" width="539.9999389648438" height="137.996337890625" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0qhtqn5_di" bpmnElement="TextAnnotation_0qhtqn5">]'
      ,q'[        <dc:Bounds x="500" y="-50" width="544.9631958007812" height="222.99630737304688" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_1vzs22f_di" bpmnElement="TextAnnotation_1vzs22f">]'
      ,q'[        <dc:Bounds x="1970" y="50" width="790" height="391.98529052734375" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_0kv1ra3_di" bpmnElement="TextAnnotation_0kv1ra3">]'
      ,q'[        <dc:Bounds x="1890" y="660" width="470" height="96" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNShape id="TextAnnotation_09eif2m_di" bpmnElement="TextAnnotation_09eif2m">]'
      ,q'[        <dc:Bounds x="1180" y="-70" width="680" height="310" />]'
      ,q'[      </bpmndi:BPMNShape>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0yr7dsk_di" bpmnElement="Flow_0yr7dsk">]'
      ,q'[        <di:waypoint x="258" y="350" />]'
      ,q'[        <di:waypoint x="340" y="350" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_02o3o4y_di" bpmnElement="Flow_02o3o4y">]'
      ,q'[        <di:waypoint x="440" y="350" />]'
      ,q'[        <di:waypoint x="495" y="350" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0jo4c98_di" bpmnElement="Flow_0jo4c98">]'
      ,q'[        <di:waypoint x="545" y="350" />]'
      ,q'[        <di:waypoint x="600" y="350" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="569" y="332" width="8" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1h8t6bd_di" bpmnElement="Flow_1h8t6bd">]'
      ,q'[        <di:waypoint x="520" y="375" />]'
      ,q'[        <di:waypoint x="520" y="460" />]'
      ,q'[        <di:waypoint x="600" y="460" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="546" y="443" width="8" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1q12jx5_di" bpmnElement="Flow_1q12jx5">]'
      ,q'[        <di:waypoint x="700" y="460" />]'
      ,q'[        <di:waypoint x="780" y="460" />]'
      ,q'[        <di:waypoint x="780" y="375" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0xk0udg_di" bpmnElement="Flow_0xk0udg">]'
      ,q'[        <di:waypoint x="700" y="350" />]'
      ,q'[        <di:waypoint x="755" y="350" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0k5jysk_di" bpmnElement="Flow_0k5jysk">]'
      ,q'[        <di:waypoint x="1660" y="580" />]'
      ,q'[        <di:waypoint x="1775" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0qf714m_di" bpmnElement="Flow_3_Yes">]'
      ,q'[        <di:waypoint x="1445" y="580" />]'
      ,q'[        <di:waypoint x="1560" y="580" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1487" y="562" width="31" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0bc9nni_di" bpmnElement="Flow_0bc9nni">]'
      ,q'[        <di:waypoint x="1825" y="580" />]'
      ,q'[        <di:waypoint x="1912" y="580" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_0eztoqc_di" bpmnElement="Flow_3_No">]'
      ,q'[        <di:waypoint x="1420" y="605" />]'
      ,q'[        <di:waypoint x="1420" y="690" />]'
      ,q'[        <di:waypoint x="1560" y="690" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1490" y="663" width="26" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1lsahzw_di" bpmnElement="Flow_1lsahzw">]'
      ,q'[        <di:waypoint x="1660" y="690" />]'
      ,q'[        <di:waypoint x="1800" y="690" />]'
      ,q'[        <di:waypoint x="1800" y="605" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_05v09nk_di" bpmnElement="Flow_05v09nk">]'
      ,q'[        <di:waypoint x="1420" y="530" />]'
      ,q'[        <di:waypoint x="1420" y="555" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_12a7a04_di" bpmnElement="Flow_12a7a04">]'
      ,q'[        <di:waypoint x="805" y="350" />]'
      ,q'[        <di:waypoint x="860" y="350" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1691lnn_di" bpmnElement="Flow_1691lnn">]'
      ,q'[        <di:waypoint x="960" y="350" />]'
      ,q'[        <di:waypoint x="1015" y="350" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1loyk10_di" bpmnElement="Flow_Sales">]'
      ,q'[        <di:waypoint x="1040" y="325" />]'
      ,q'[        <di:waypoint x="1040" y="290" />]'
      ,q'[        <di:waypoint x="1170" y="290" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1059" y="263" width="82" height="14" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_03bj1fy_di" bpmnElement="Flow_ProdDev">]'
      ,q'[        <di:waypoint x="1040" y="375" />]'
      ,q'[        <di:waypoint x="1040" y="460" />]'
      ,q'[        <di:waypoint x="1170" y="460" />]'
      ,q'[        <bpmndi:BPMNLabel>]'
      ,q'[          <dc:Bounds x="1071" y="426" width="57" height="27" />]'
      ,q'[        </bpmndi:BPMNLabel>]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1j0axlj_di" bpmnElement="Flow_1j0axlj">]'
      ,q'[        <di:waypoint x="1270" y="460" />]'
      ,q'[        <di:waypoint x="1340" y="460" />]'
      ,q'[        <di:waypoint x="1340" y="395" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_1txhooo_di" bpmnElement="Flow_1txhooo">]'
      ,q'[        <di:waypoint x="1270" y="290" />]'
      ,q'[        <di:waypoint x="1340" y="290" />]'
      ,q'[        <di:waypoint x="1340" y="345" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Flow_11z8xs6_di" bpmnElement="Flow_11z8xs6">]'
      ,q'[        <di:waypoint x="1365" y="370" />]'
      ,q'[        <di:waypoint x="1420" y="370" />]'
      ,q'[        <di:waypoint x="1420" y="450" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0jg4oqm_di" bpmnElement="Association_0jg4oqm">]'
      ,q'[        <di:waypoint x="510" y="365" />]'
      ,q'[        <di:waypoint x="463" y="570" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_1y1u9dd_di" bpmnElement="Association_1y1u9dd">]'
      ,q'[        <di:waypoint x="403" y="310" />]'
      ,q'[        <di:waypoint x="486" y="61" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0hx891w_di" bpmnElement="Association_0hx891w">]'
      ,q'[        <di:waypoint x="1470" y="460" />]'
      ,q'[        <di:waypoint x="1970" y="174" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_0jgd1xj_di" bpmnElement="Association_0jgd1xj">]'
      ,q'[        <di:waypoint x="1400" y="600" />]'
      ,q'[        <di:waypoint x="1320" y="760" />]'
      ,q'[        <di:waypoint x="1770" y="760" />]'
      ,q'[        <di:waypoint x="1890" y="708" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[      <bpmndi:BPMNEdge id="Association_11qbgm5_di" bpmnElement="Association_11qbgm5">]'
      ,q'[        <di:waypoint x="945" y="310" />]'
      ,q'[        <di:waypoint x="1138" y="86" />]'
      ,q'[      </bpmndi:BPMNEdge>]'
      ,q'[    </bpmndi:BPMNPlane>]'
      ,q'[  </bpmndi:BPMNDiagram>]'
      ,q'[</bpmn:definitions>]'
      ,q'[]'
  ));
  flow_diagram.upload_and_parse(
    pi_dgrm_name => 'Tutorial 2a - Basic Navigation with Gateways',
    pi_dgrm_version => '23.1',
    pi_dgrm_category => 'Tutorials',
    pi_dgrm_content => l_dgrm_content
);
end;
/
