prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/credentials_for_flows_for_apex_ai_service.sql
@@workspace/remote_servers/flows_for_apex_ai_service.sql
@@application/shared_components/navigation/lists/p8_subflow_row_action_menu.sql
@@application/shared_components/navigation/lists/p10_instance_header_action_menu.sql
@@application/shared_components/navigation/lists/p9_configuration_pages.sql
@@application/shared_components/navigation/lists/p8_subflow_header_action_menu.sql
@@application/shared_components/navigation/lists/p8_action_menu.sql
@@application/shared_components/navigation/lists/p8_variable_row_action_menu.sql
@@application/shared_components/navigation/lists/p8_variable_header_action_menu.sql
@@application/shared_components/navigation/lists/p2_action_menu.sql
@@application/shared_components/navigation/lists/p7_action_menu.sql
@@application/shared_components/navigation/lists/p10_action_menu.sql
@@application/shared_components/navigation/lists/p4_action_menu.sql
@@application/shared_components/navigation/lists/p2_row_action_menu.sql
@@application/shared_components/navigation/lists/p2_header_action_menu.sql
@@application/shared_components/navigation/lists/p10_instance_row_action_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/css_flows4apex_css.sql
@@application/shared_components/files/js_flows4apex_js.sql
@@application/shared_components/files/js_flows4apex_js_map.sql
@@application/shared_components/files/css_flows4apex_css_map.sql
@@application/shared_components/files/lib_prismjs_css_prism_dark_css.sql
@@application/shared_components/files/lib_prismjs_css_prism_css.sql
@@application/shared_components/files/lib_prismjs_js_prism_js.sql
@@application/shared_components/files/lib_prismjs_css_prism_min_css.sql
@@application/shared_components/files/lib_prismjs_css_prism_css_map.sql
@@application/shared_components/files/lib_prismjs_css_prism_dark_min_css.sql
@@application/shared_components/files/lib_prismjs_css_prism_dark_css_map.sql
@@application/shared_components/files/bpmn_io_bpmn_font_css_bpmn_embedded_css.sql
@@application/shared_components/files/bpmn_io_bpmn_font_css_bpmn_embedded_min_css.sql
@@application/shared_components/files/css_flows4apex_min_css.sql
@@application/shared_components/files/js_flows4apex_min_js.sql
@@application/shared_components/files/app_100_logo_png.sql
@@application/shared_components/files/favicon_png.sql
@@application/shared_components/files/css_flows4apex_dark_css.sql
@@application/shared_components/files/css_flows4apex_dark_min_css.sql
@@application/shared_components/files/css_flows4apex_dark_css_map.sql
@@application/shared_components/files/css_flows4apex_light_css.sql
@@application/shared_components/files/css_flows4apex_light_min_css.sql
@@application/shared_components/files/css_flows4apex_light_css_map.sql
@@application/shared_components/files/workflow_black_svg.sql
@@application/shared_components/files/app_100_logo_svg.sql
@@application/shared_components/files/workflow_white_svg.sql
@@application/shared_components/files/flows_apex_svg.sql
@@application/shared_components/files/lib_prismjs_js_prism_min_js.sql
@@application/shared_components/files/lib_prismjs_js_prism_js_map.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_init_theme_mode.sql
@@application/shared_components/logic/application_processes/switch_theme_mode.sql
@@application/shared_components/logic/application_processes/reset_theme_mode.sql
@@application/shared_components/logic/application_processes/css_tricks.sql
@@application/shared_components/logic/application_processes/ajax_handler.sql
@@application/shared_components/logic/application_items/app_name_title.sql
@@application/shared_components/logic/application_items/flow_page_title.sql
@@application/shared_components/logic/application_items/fsp_language_preference.sql
@@application/shared_components/logic/application_items/process_id.sql
@@application/shared_components/logic/application_items/step_key.sql
@@application/shared_components/logic/application_items/subflow_id.sql
@@application/shared_components/logic/application_items/theme_plugin_class.sql
@@application/shared_components/logic/application_computations/p0_license_edition.sql
@@application/shared_components/logic/application_computations/app_name_title.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/apex_icons_lov.sql
@@application/shared_components/user_interface/lovs/diagrams_instanciated_lov.sql
@@application/shared_components/user_interface/lovs/diagrams_parsed_lov.sql
@@application/shared_components/user_interface/lovs/diagram_categories_lov.sql
@@application/shared_components/user_interface/lovs/flow_instance_diagrams_lov.sql
@@application/shared_components/user_interface/lovs/flow_rest_roles.sql
@@application/shared_components/user_interface/lovs/flow_simple_form_templates_lov.sql
@@application/shared_components/user_interface/lovs/logging_levels.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/p13_object_attributes.sql
@@application/shared_components/user_interface/lovs/p13_var_exp_set_on.sql
@@application/shared_components/user_interface/lovs/p13_var_exp_typ.sql
@@application/shared_components/user_interface/lovs/p44_prompt_types.sql
@@application/shared_components/user_interface/lovs/p5_download_as.sql
@@application/shared_components/user_interface/lovs/p6_import_from.sql
@@application/shared_components/user_interface/lovs/p6_mode.sql
@@application/shared_components/user_interface/lovs/p8_instance_connections_lov.sql
@@application/shared_components/user_interface/lovs/p8_instance_gateways_lov.sql
@@application/shared_components/user_interface/lovs/p8_repositionable_steps.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/automations/flows_for_apex_daily_instance_archive.sql
@@application/shared_components/automations/flows_for_apex_purge_statistics.sql
@@application/shared_components/automations/flows_for_apex_gather_daily_statistics.sql
@@application/shared_components/automations/flows_for_apex_purge_logs.sql
@@application/shared_components/automations/flows_for_apex_purge_completed_instances.sql
@@application/shared_components/security/authentications/no_auth.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/plugins/process_type/com_flows4apex_return_task_state_process.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/region_type/com_flows4apex_viewer_region_251.sql
@@application/shared_components/plugins/process_type/com_flows4apex_manage_ins_vars_process.sql
@@application/shared_components/plugins/process_type/com_flows4apex_manage_instance_process.sql
@@application/shared_components/plugins/region_type/com_flows4apex_modeler_region.sql
@@application/shared_components/plugins/process_type/com_flows4apex_manage_step_process.sql
@@application/shared_components/plugins/process_type/com_flows4apex_return_to_flows_process.sql
@@application/shared_components/plugins/region_type/com_flows4apex_viewer_region.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_09999.sql
@@application/shared_components/logic/component_groups/flows_for_apex_components.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
