/*
-- Flows for APEX - engine_messages_fr.sql
--
-- Engine Messages for language code "fr"
--
-- Generated by language-load-generator
-- Generated on Mon, 10 Oct 2022 06:07:03 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "fr"
declare
  c_load_lang constant varchar2(10) := 'fr';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, 'La tâche de workflow APEX %0 est associée à plus d&#x27;une étape de processus dans Flows for APEX.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, 'La tâche de workflow APEX %0 n&#x27;est pas la tâche courante du processus. Vous pourriez avoir déjà tout complété.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, 'La variable de processus du résultat de la tâche de workflow APEX n&#x27;est pas définie ou n&#x27;est pas valide.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, 'Erreur lors de la création de la tâche de workflow APEX %0 dans l&#x27;application %1. Pour plus de détails, reportez-vous au débogage.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, 'Erreur lors de la création de la tâche de workflow APEX - Priorité non valide %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, 'Erreur lors de la création de la session APEX. Le diagramme BPMN contient plusieurs objets de processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, 'Vous avez essayé d&#x27;appeler un diagramme %0 marqué comme ne pouvant pas être appelé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, 'Type d&#x27;événement de lancer intermédiaire actuellement non pris en charge rencontré à %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, 'Les détails de connexion asynchrone pour l&#x27;objet %0 doivent être définis dans les variables de processus, les détails de connexion asynchrone de diagramme ou les détails de configuration système.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, 'Impossible de créer une connexion asynchrone pour l&#x27;objet %0. Le nom d&#x27;utilisateur doit être la variable du processus, le diagramme du processus ou la configuration du système.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, 'Impossible de créer une connexion asynchrone pour l&#x27;objet %0. L&#x27;ID d&#x27;application doit être indiqué dans la variable de processus, le diagramme de processus ou la configuration système.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, 'Impossible de créer une connexion asynchrone pour l&#x27;objet %0. L&#x27;ID de page doit être spécifié dans la variable de processus, le diagramme de processus ou la configuration système.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, 'Sous-flux enfant ou minuteur de %0 sont actuellement verrouillés par un autre utilisateur. . Réessayez votre transaction plus tard.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, 'Aucun événement de frontière de type %0 trouvé pour capturer l&#x27;événement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, 'Plus d&#x27;un événement de frontière %0 trouvé sur le sous-processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, 'Erreur interne du moteur de flux: Processus %0 Sous-flux %1 Module %2 Courant %4 Balise courante %3' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, 'Erreur de modèle : L&#x27;étape suivante du modèle de processus BPMN utilise un objet non supporté %0' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, 'Erreur applicative : L&#x27;ID du processus %0 n&#x27;a pas été trouvé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, 'Erreur applicative: L&#x27;ID du sous-flux fourni ( %0 ) existe mais n&#x27;est pas un enfant de l&#x27;ID de processus fourni ( %1 ).' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, 'L&#x27;ID du sous-flux fourni ( %0 ) est introuvable. Vérifiez les événements du processus qui ont modifié le flux du processus (délais, erreurs, escalades).' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, 'Erreur au niveau de la passerelle %0. La variable fournie %1 contient une route invalide : %2' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, 'Erreur interne de traitement lors de la fusion au nivau de la passerelle sur le sous-flux %0' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, 'Aucune instruction de routage de passerelle n&#x27;est fournie dans la variable %0 et le modèle ne contient pas de route par défaut.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, 'Plus d&#x27;une route par défaut spécifiée dans le modèle pour la passerelle %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, 'Expression de routage de passerelle incorrecte. Cela peut se produire si vous tentez de lier une variable à l&#x27;aide du signe deux-points ( :).' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, 'Impossible de trouver le lien correspondant à l&#x27;événement %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, 'Plus d&#x27;un lien correspond à l&#x27;événement %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, 'Flows - Erreur interne lors de l&#x27;enregistrement d&#x27;un évènement d&#x27;instance' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, 'Flows - Erreur interne lors de l&#x27;enregistrement d&#x27;un évènement d&#x27;étape' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, 'Flows - Erreur interne lors de l&#x27;enregistrement d&#x27;un évènement de variable' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, 'Les objets de traitement pour %0 sont actuellement verrouillés par un autre utilisateur. Réessayez plus tard.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, 'Plus d&#x27;un chemin d&#x27;accès trouvé alors qu&#x27;un seul est autorisé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, 'Aucune étape suivante trouvée pour le sous-flux %0. Vérifiez votre diagramme de processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, 'Processus %0 : la tâche %1 a échoué en raison d&#x27;une erreur PL/SQL - voir le journal des événements.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, 'Processus %0: Tâche %1 arrêt du traitement demandé - voir le journal des événements.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, 'Impossible de verrouiller le sous-flux %0, celui-ci est actuellement verrouillé par un autre utilisateur. Veuillez réessayer ultérieurement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, 'Réservation déjà effectuée sur la prochaine tâche pour vous.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, 'Erreur de définition de la variable de processus. Type de données incorrect pour la variable %0. Erreur SQL affichée dans le débogage.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, 'Erreur de définition de la variable de processus %1 : format de date incorrect (Sous-flux : %0, Valeur : %3.)' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, 'Erreur interne dans la recherche de l&#x27;objet %0 dans process_expressions. Erreur SQL affichée dans le débogage' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, 'Sous-flux : %0 Erreur dans l&#x27;expression %2 de la variable : %1' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, 'Ereur lors de la définition de la variable %1 avec la valeur %2 dans le processus %0 - Aucune donnée trouvée dans la requête.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, 'Ereur lors de la définition de la variable %1 avec la valeur %2 dans le processus %0.  Erreur SQL indiquée dans le journal des événements.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_too_many_rows', c_load_lang, 'Ereur lors de la définition de la variable %1 avec la valeur %2 dans le processus %0.  La requête renvoie plusieurs lignes.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, 'Erreur de définition de la variable %1 (valeur : %2) dans le processus d&#x27;id %0. Voir l&#x27;erreur dans le journal des événements.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, 'Impossible de trouver le diagramme publié ou la version 0 du diagramme - veuillez spécifier une version ou un numéro de diagramme.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, 'Impossible de trouver la version spécifiée du diagramme. Veuillez vérifier la version.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, 'La réservation pour %0 est impossible. L&#x27;étape est déjà réservée par un autre utilisateur (%1).' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, 'La réservation pour %0 est impossible. Sous-flux %0 dans le processus %1 non trouvé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, 'La tâche n&#x27;est plus en cours, elle est probablement déjà terminée.  Veuillez rafraîchir votre liste de tâches.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, 'Sous-flux actuellement verrouillé (non reservé) par un autre utilisteur. Veuillez réessayez ultérieurement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, 'La libération de la réservation est impossible. Sous-flux %0 dans le processus %1 non trouvé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, 'Aucune erreur courante trouvée. Vérifiez votre diagramme de processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, 'Vous avez essayé de démarrer un processus (id %0) qui est déjà en cours d&#x27;exécution.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, 'Vous avez essayé de démarrer un processus avec un diagramme %0 qui inclut une activité d&#x27;appel s&#x27;appelant lui même.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, 'Vous avez essayé de démarrer un processus (id %0) dont plusieurs copies sont déjà en cours d&#x27;exécution.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, 'Vous avez défini plusieurs événements de début. Assurez-vous que votre diagramme n&#x27;a qu&#x27;un seul événement de début.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, 'Aucun événement de début n&#x27;est défini dans le diagramme de flux.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, 'Vous avez essayé de démarrer un processus (id %0) qui n&#x27;existe pas.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, 'Type d&#x27;événement de début non pris en charge (%0). Seuls les événements de début standard et de type minuteur sont actuellement pris en charge.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, 'Début de l&#x27;enregistrement des temps de travail non réussi. Le sous-flux %0 du processus %1 est introuvable.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, 'Cette étape de processus a déjà été réalisée.  (Clé d&#x27;étape fournie incorrecte %0, clé d&#x27;étape attendue %1).' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, 'Impossible de trouver l&#x27;événement de début de sous-processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, 'Plus d&#x27;un événement de sous-processus trouvé.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, 'Minuteur %0 cycle %4 en erreur dans le processus %1 , sous-flux : %2.  Voir error_info.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, 'Minuteur de type cycle défini pour l&#x27;objet %0 n&#x27;est pas pris en charge actuellement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, 'Définition incomplète du minuteur de l&#x27;objet %0. Type: %1; Valeur1: %2 Valeur2: %3 Valeur3: %4' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, 'La minuteur du sous-flux %0 est verrouillé par un autre utilisateur. Veuillez réessayer ultérieurement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, 'Objet avec minuteur non trouvé dans get_timer_definition. Sous-flux %0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, 'Les minuteurs pour le processus %0 sont verrouillés par un autre utilisateur. Veuillez réessayer ultérieurement.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, 'Erreur de création de la variable de processus %0 pour l&#x27;ID de processus %1 dans la portée %2' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, 'Erreur de récupération de la variable de processus %0 pour l&#x27;ID de processus %1 dans la portée %2.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, 'Erreur de mise à jour de la variable de processus %0 pour l&#x27;ID de processus %1 dans la portée %2' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, 'Erreur de suppression de la variable de processus %0 pour l&#x27;ID de processus %1 dans la portée %2' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, 'Erreur de verrouillage de la variable de processus %0 pour l&#x27;ID de processus %1 dans la portée %2' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, 'Erreur lors de l&#x27;analyse de la définition du minuteur dans le processus %0, sous-flux %1. Type de minuteur : %2, Définition: %3' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, 'La version n&#x27;est pas définie.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, 'Erreur lors de l&#x27;analyse des variables du processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, 'La passerelle n&#x27;est pas définie pour le routage.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, 'La définition de la passerelle n&#x27;existe pas pour ce flux.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, 'Impossible d&#x27;obtenir l&#x27;Id de l&#x27;Instance de flux et ou l&#x27;Id du sous-flux pour gérer l&#x27;étape.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, 'Mauvais nombre d&#x27;élément(s) APEX ou de variable(s) de processus.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, 'Une ou plusieurs variables de processus sont d&#x27;un type différent de celui défini dans le JSON.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, '%0 n&#x27;est pas un nombre valide.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, '%0 n&#x27;est pas une date valide.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, 'Le JSON fourni est invalide.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, 'Aucune donnée trouvée. Vérifiez si le Diagramme avec l&#x27;ID fourni existe.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, 'Erreur inattendue, veuillez contacter votre administrateur.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, 'Le diagramme n&#x27;a pas pu être analysé.&lt;br /&gt;Veuillez examiner votre diagramme pour vous assurer qu&#x27;il est pris en charge.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, 'Changements enregistrés !' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, 'Le modèle a changé, annuler les changements?' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : l&#x27;espace de travail par défaut défini dans le paramètre de configuration n&#x27;est pas valide.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : impossible de trouver l&#x27;espace de travail associé à l&#x27;aplication définie dans le diagramme. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : attribut De non défini. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : attribut To non défini. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : attribut Template non défini. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : attribut Corps non défini. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, 'Processus %0 : la tâche de service %1 a échoué : voir le journal pour plus de détail et vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, 'Processus %0: la tâche de service %1 a échoué : l&#x27;objet JSON des espaces réservés est invalide. Veuillez vérifier le modèle.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, 'Impossible de créer une connexion asynchrone pour l&#x27;objet %0.  Le nom d&#x27;utilisateur n&#x27;est pas valide dans l&#x27;application spécifiée' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, 'Plusieurs lignes trouvées. Activez le paramètre &quot;Activer les activités d&#x27;appel&quot; dans les attributs de plug-in de la visionneuse.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, 'Erreur lors de la tentative d&#x27;annulation de la tâche de workflow APEX (task_id : %1 ) pour l&#x27;étape de processus : %0.)' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-supported', c_load_lang, 'L&#x27;utilisation de la fonctionnalité de workflow APEX nécessite Oracle APEX v%0.' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, 'Tâche de workflow APEX %0 introuvable dans les processus Flows for APEX' );
  
  commit;
end;
/
