/*
-- Flows for APEX - engine_messages_ko.sql
--
-- Engine Messages for language code "ko"
--
-- Generated by language-load-generator
-- Generated on Mon, 26 Jun 2023 15:38:36 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "ko"
declare
  c_load_lang constant varchar2(10) := 'ko';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, q'[%0 객체에 대한 비동기 접속을 생성할 수 없습니다. 프로세스 변수, 프로세스 다이어그램 또는 시스템 구성에 애플리케이션 ID를 지정해야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, q'[%0 객체에 대한 비동기 접속을 생성할 수 없습니다. 프로세스 변수, 프로세스 다이어그램 또는 시스템 구성에 페이지 ID를 지정해야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, q'[현재 다른 사용자가 %0의 하위 경계 하위 플로우 또는 타이머를 잠갔습니다. 나중에 트랜잭션을 재시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, q'[하위 프로세스에 둘 이상의 %0 boundaryEvent이(가) 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, q'[플로우 엔진 내부 오류: 프로세스 %0 하위 플로우 %1 모듈 %2 현재 %4 현재 태그 %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, q'[모델 오류: 프로세스 BPMN 모델 다음 단계에서는 지원되지 않는 객체 %0을(를) 사용합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, q'[애플리케이션 오류: 프로세스 ID %0을(를) 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, q'[애플리케이션 오류: 제공된 하위 흐름 ID(%0)가 있지만 제공된 프로세스 ID(%1)의 하위가 아닙니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, q'[제공된 하위 플로우 ID( %0 )를 찾을 수 없습니다. 프로세스 플로우(시간 초과, 오류, 에스컬레이션)를 변경한 프로세스 이벤트를 확인합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, q'[%0 게이트웨이에서 오류가 발생했습니다. 제공된 변수 %1에 부적합한 경로 %2이(가) 포함되어 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, q'[하위 플로우 %0에서 게이트웨이 병합을 처리하는 중 내부 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, q'[%0 변수에 제공된 게이트웨이 경로 지정 지침이 없고 모델에 기본 경로가 포함되어 있지 않습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, q'[게이트웨이 경로 지정 표현식이 잘못되었습니다. 이 오류는 콜론(:)이 포함된 변수를 바인드하려고 할 때 발생할 수 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, q'[현재 다른 사용자가 %0에 대한 프로세스 객체를 잠갔습니다. 나중에 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, q'[한 개만 허용되는 경우 전달 경로가 두 개 이상 발견되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, q'[하위 플로우 %0에서 다음 단계를 찾을 수 없습니다. 프로세스 다이어그램을 확인합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, q'[%0 프로세스: PL/SQL 오류로 인해 %1 태스크가 실패했습니다. 이벤트 로그를 참조하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, q'[프로세스 %0: %1 태스크가 처리 중지를 요청했습니다. 이벤트 로그를 참조하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, q'[현재 다른 사용자가 잠갔으므로 하위 플로우 %0을(를) 잠글 수 없습니다. 나중에 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, q'[예약이 이미 다음 태스크에 지정되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, q'[%0에 대한 예약에 실패했습니다. 다른 사용자(%1)가 이미 단계를 예약했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, q'[%2 예약에 실패했습니다. 프로세스 %1의 하위 플로우 %0을(를) 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, q'[태스크가 더 이상 최신 상태가 아닙니다. 이미 완료되었을 수 있습니다. 받은 편지함을 새로 고치십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, q'[다른 사용자가 현재 하위 플로우를 잠갔습니다(예약되지 않음). 나중에 다시 예약을 시도하세요.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, q'[예약 해제에 실패했습니다. 프로세스 %1의 하위 플로우 %0을(를) 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, q'[현재 오류를 찾을 수 없습니다. 프로세스 다이어그램을 확인합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, q'[이미 실행 중인 프로세스(ID %0)를 시작하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, q'[게이트웨이 %0에 대한 모델에 둘 이상의 기본 경로가 지정되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, q'[이름이 %0인 일치하는 링크 Catch 이벤트를 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, q'[이름이 %0인 일치하는 링크 캐치 이벤트가 두 개 이상 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, q'[플로우 - 단계 이벤트를 기록하는 중 내부 오류 발생]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, q'[플로우 - 변수 이벤트를 기록하는 중 내부 오류 발생]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, q'[여러 복사본이 이미 실행 중인 프로세스(ID %0)를 시작하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, q'[정의된 시작 이벤트가 여러 개 있습니다. 다이어그램에 시작 이벤트가 하나만 있는지 확인합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, q'[플로우 다이어그램에 정의된 시작 이벤트가 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, q'[존재하지 않는 프로세스(ID %0)를 시작하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, q'[지원되지 않는 시작 이벤트 유형(%0)입니다. 없음(표준) 시작 이벤트 및 타이머 시작 이벤트만 현재 지원됩니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, q'[시작 작업 시간 기록에 실패했습니다. 프로세스 %1의 하위 플로우 %0을(를) 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, q'[이 프로세스 단계는 이미 발생했습니다. (단계 키 %1이(가) 필요한 동안 잘못된 단계 키 %0이(가) 제공되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, q'[하위 프로세스 시작 이벤트를 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, q'[둘 이상의 하위 프로세스 시작이 발견되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, q'[타이머 %0 실행 %4이(가) 프로세스 %1, 하위 플로우 %2에서 분리되었습니다. error_info를 참조하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, q'[%0 객체에 대해 정의된 주기 타이머는 현재 지원되지 않습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, q'[%0 객체에 대한 타이머 정의가 불완전합니다. 유형: %1, Value1: %2 Value2: %3  Value3: %4]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, q'[현재 다른 사용자가 하위 플로우 %0에 대한 타이머를 잠갔습니다. 나중에 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, q'[타이머가 있는 객체를 get_timer_definition에서 찾을 수 없습니다. 하위 플로우 %0입니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, q'[현재 다른 사용자가 프로세스 %0에 대한 타이머를 잠갔습니다. 나중에 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, q'[%2 범위에서 프로세스 ID %1에 대한 프로세스 변수 %0을(를) 생성하는 동안 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, q'[%2 범위의 프로세스 ID %1에 대한 프로세스 변수 %0을(를) 업데이트하는 동안 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, q'[%2 범위에서 프로세스 ID %1에 대한 프로세스 변수 %0을(를) 삭제하는 동안 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, q'[%2 범위의 프로세스 ID %1에 대한 프로세스 변수 %0을(를) 잠그는 동안 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, q'[프로세스 변수를 설정하는 중 오류가 발생했습니다. 변수 %0에 대한 데이터 유형이 잘못되었습니다. 디버그 출력에 표시된 SQL 오류입니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, q'[프로세스 변수 %1을(를) 설정하는 동안 오류가 발생했습니다. 잘못된 일자 형식(하위 플로우: %0, 세트: %3)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, q'[process_expressions에서 %0 객체를 조회하는 중 내부 오류가 발생했습니다. 디버그 출력에 표시된 SQL 오류입니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, q'[하위 플로우: %0 변수에 대한 %2 표현식에서 오류 발생: %1]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, q'[프로세스 ID %0(설정 %2)에서 프로세스 변수 %1을(를) 설정하는 동안 오류가 발생했습니다. 질의에서 데이터를 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, q'[프로세스 ID %0(설정 %2)에서 프로세스 변수 %1을(를) 설정하는 동안 오류가 발생했습니다. 이벤트 로그에 표시된 SQL 오류입니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_too_many_rows', c_load_lang, q'[프로세스 ID %0(설정 %2)에서 프로세스 변수 %1을(를) 설정하는 동안 오류가 발생했습니다. query는 여러 행을 반환합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, q'[프로세스 ID %0(설정 %2)에서 프로세스 변수 %1을(를) 설정하는 동안 오류가 발생했습니다. 이벤트 로그에서 오류를 참조하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, q'[릴리스된 다이어그램 또는 초안 버전 0 다이어그램을 찾을 수 없습니다. 버전 또는 diagram_id을 지정하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, q'[지정된 다이어그램 버전을 찾을 수 없습니다. 버전 사양을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, q'[프로세스 %0, 하위 플로우 %1에서 타이머 정의를 구문 분석하는 동안 오류가 발생했습니다. 타이머 유형: %2, 정의: %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, q'[버전이 정의되지 않았습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, q'[프로세스 변수를 구문 분석하는 중 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, q'[경로 지정에 대해 게이트웨이가 정의되지 않았습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, q'[이 플로우에 대한 게이트웨이 정의가 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, q'[단계를 관리할 플로우 인스턴스 ID 및/또는 하위 플로우 ID를 가져올 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, q'[APEX 항목 수 또는 프로세스 변수가 잘못되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, q'[하나 이상의 프로세스 변수가 JSON에 정의된 유형과 다릅니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, q'[%0은(는) 적합한 숫자가 아닙니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, q'[%0은(는) 적합한 일자가 아닙니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, q'[제공된 JSON이 부적합합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, q'[데이터를 찾을 수 없습니다. 제공된 ID를 가진 다이어그램이 존재하는지 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, q'[예상치 않은 오류입니다. 관리자에게 문의하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, q'[다이어그램의 구문을 분석할 수 없습니다.<br />다이어그램이 지원되는지 검토하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, q'[변경 내용이 저장되었습니다!]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 구성 매개변수에 정의된 기본 작업 영역이 부적합합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 다이어그램에 정의된 애플리케이션 ID와 연관된 작업영역을 찾을 수 없습니다. 모델을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 속성 "보낸 사람" 및 기본 전자메일 발신자가 정의되지 않았습니다. 모델 및/또는 구성 매개변수를 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 속성 "대상"이 정의되지 않았습니다. 모델을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 속성 "템플리트"가 정의되지 않았습니다. 모델을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, q'[프로세스 %0: ServiceTask %1 실패: 속성 "본문"이 정의되지 않았습니다. 모델을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, q'[프로세스 %0: ServiceTask %1이(가) 오류 로그를 확인하고 모델을 검사하지 못했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, q'[프로세스 %0: ServiceTask %1 위치 표시자 JSON이 invalid.Please입니다. 모델을 확인하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, q'[다중 행이 발견되었습니다. 뷰어 플러그인 속성에서 '호출 활동 사용' 설정을 사용으로 설정하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, q'[프로세스 단계 %0에 대한 APEX 워크플로우 태스크(task_id: %1)를 취소하려고 시도하는 중 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-supported', c_load_lang, q'[APEX Workflow 기능을 사용하려면 Oracle APEX v%0이(가) 필요합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, q'[APEX Workflow Task %0을(를) Flows for APEX 프로세스에서 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, q'[APEX Workflow Task %0가 APEX의 하나이상의 Flows 프로세스 단계와 연관성이 발견되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, q'[APEX Workflow Task %0이(가) 프로세스의 현재 단계가 아닙니다. 단계가 모든 준비를 완료했을 수 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, q'[APEX Workflow Task 결과 프로세스 변수가 정의되지 않았거나 부적합합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, q'[%1 애플리케이션에서 APEX 워크플로우 태스크 %0을(를) 생성하는 동안 오류가 발생했습니다. 자세한 내용은 디버그를 참조하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, q'[APEX 워크플로우 태스크를 생성하는 중 오류 발생 - 우선순위 %0이(가) 부적합합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, q'[APEX 세션을 생성하는 중 오류가 발생했습니다. BPMN 다이어그램에는 여러 Process 객체가 포함되어 있습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, q'[호출할 수 없는 것으로 표시된 %0 다이어그램을 호출하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'diagram-archive-has-instances', c_load_lang, q'[실행 중인 인스턴스가 있는 다이어그램을 아카이브하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-business-ref-null', c_load_lang, q'[승인 태스크를 생성하는 동안 오류가 발생했습니다. 비즈니스 참조/레코드 시스템 기본 키는 Null이 아니어야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-bad-json', c_load_lang, q'[아카이브 대상 구성 매개변수에서 오류가 발생했습니다. 매개변수: %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'log-archive-error', c_load_lang, q'[프로세스 인스턴스 %0에 대한 인스턴스 요약을 아카이브하는 중 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'scheduler-repeat-shared-env', c_load_lang, q'[호스트(%0) 요청된 간격 %1에 대해 타이머 반복 간격이 너무 자주 발생합니다. 1분보다 커야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-not-correlated', c_load_lang, q'[수신된 메시지가 예상된 메시지와 일치하지 않습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-no-longer-current-step', c_load_lang, q'[프로세스 단계 수신 메시지가 이미 발생했습니다(잘못된 단계 키가 제공됨).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-msub', c_load_lang, q'[다른 사용자가 메시지 가입을 잠갔습니다. 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-subflow', c_load_lang, q'[메시지 수신자가 하위 플로우를 잠글 수 없습니다. 다시 시도하십시오.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-diagram-event', c_load_lang, q'[플로우 - 다이어그램 이벤트를 기록하는 중 내부 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-interval-error', c_load_lang, q'[기한을 평가하는 중 오류가 발생했습니다. 간격 표현식이 부적합합니다. 간격: %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-error', c_load_lang, q'[기한을 평가하는 중 오류가 발생했습니다. 만기 일자 표현식이 부적합합니다. 간격 표현식: %0. 대신 systimestamp가 사용되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-priority-error', c_load_lang, q'[우선순위를 평가하는 중 오류가 발생했습니다. 우선순위 표현식이 부적합합니다. 표현식: %0. 우선 순위 3이 대신 사용됩니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-error', c_load_lang, q'[설정을 평가하는 중 오류가 발생했습니다. 표현식이 부적합합니다. 표현식: %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-endpoint-not-supported', c_load_lang, q'[MessageFlow 지정된 끝점( %0 )은 지원되지 않습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-bad-scope', c_load_lang, q'[프로세스 변수에 대해 부적합한 범위(%0)가 제공되었습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, q'[%2 범위의 프로세스 ID %1에 대한 프로세스 변수 %0을(를) 가져오는 동안 오류가 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, q'[현재 지원되지 않는 중간 Throw 이벤트 유형이 %0 에 발생했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, q'[
객체 %0에 대한 비동기 접속 세부정보는 프로세스 변수, 비동기 접속 세부정보의 다이어그램에 설정되어야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, q'[%0 객체에 대한 비동기 접속을 생성할 수 없습니다. 지정된 애플리케이션에서 사용자 이름이 부적합합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, q'[%0 객체에 대한 비동기 접속을 생성할 수 없습니다. 프로세스 변수, 프로세스 다이어그램 또는 시스템 구성에 사용자 이름을 지정해야 합니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, q'[callActivity 호출 자체를 포함하는 %0 다이어그램으로 프로세스를 시작하려고 했습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, q'[이벤트를 처리할 boundaryEvent 유형 %0을(를) 찾을 수 없습니다.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, q'[모델이 변경되었습니다. 변경사항을 무시하시겠습니까?]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, q'[플로우 - 인스턴스 이벤트를 기록하는 중 내부 오류 발생]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-procvar-no-prcs', c_load_lang, q'[설정은 프로세스 ID 없이 프로세스 변수를 지정할 수 없습니다.]' );
  
  commit;
end;
/
