/*
-- Flows for APEX - engine_messages_de.sql
--
-- Engine Messages for language code "de"
--
-- Generated by language-load-generator
-- Generated on Mon, 10 Oct 2022 12:10:54 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "de"
declare
  c_load_lang constant varchar2(10) := 'de';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: Attribut "Von" und "Standard Email Absender" nicht definiert. Bitte überprüfen sie das model und/oder die Konfigurations-Parameter.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: Attribut "An" nicht definiert. Bitte überprüfen sie das Modell.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: Attribut "Vorlage" nicht definiert. Bitte überprüfen sie das Modell.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: Attribut "Text" nicht definiert. Bitte überprüfen sie das Modell.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen. Überprüfen sie das Fehlerlog und überprüfen sie das Modell.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, q'[Aktuell wird der Typ des ausgelösten Zwischenereignisses bei %0 nicht unterstützt.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, q'[Asynchrone Verbindungs-Details für Objekt %0 müssen in den Prozessvariablen, den Diagramm Async-Verbindungsdetails oder der Systemkonfiguration definiert werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, q'[Asynchrone Verbindung für Objekt %0 kann nicht erstellt werden. Benutzername für angegebene Applikation nicht gültig.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, q'[Asynchrone Verbindung für Objekt %0 kann nicht erstellt werden. Der Benutzername muss in einer Prozessvariable, dem Prozessdiagramm oder der Systemkonfiguration angegeben werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, q'[Asynchrone Verbindung für Objekt %0 kann nicht erstellt werden. Applikations-ID muss in einer Prozessvariable, dem Prozessdiagramm oder der Systemkonfiguration angegeben werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, q'[Unable to create asyncronous connection for object %0.  Page ID needs to be specified in process variable, the process diagram, or system configuration.
Asynchrone Verbindung für Objekt %0 kann nicht erstellt werden. Die Seiten-ID muss in einer Prozessvariable, dem Prozessdiagramm oder der Systemkonfiguration angegeben werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, q'[Kind-Zwischenereignis oder Timer von %0 von einem anderen Benutzer gesperrt. Bitte versuchen sie die Transaktion zu einem späteren Zeitpunkt erneut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, q'[Kein Zwischenereignis von Typ %0 gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, q'[Mehr als ein Zwischenereignis %0 für Unterprozess gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, q'[Flow Engine Internal Error: Process %0 Subflow %1 Module %2 Current %4 Current Tag %3
Flow Engine Interner Fehler: Prozess %0 Subflow %1 Modul %2 Aktuell %4 Aktueller Eintrag %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, q'[Modellfehler: Der nächste Schritt des BPMN Modells verwendet ein nicht unterstütztes Objekt %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, q'[Applikationsfehler: Prozess ID %0 nicht gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, q'[Applikationsfehler: Angegebene Subflow-ID ( %0 ) existiert, ist aber kein Kind der angegebenen Prozess ID ( %1 ).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, q'[Angegebene Subflow-ID ( %0 ) nicht gefunden. Bitte überprüfen sie Prozess-Ereignisse die Prozess-Abläufe ändern (Timeouts, Fehler, Eskalationen).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, q'[Fehler bei Gateway %0. Angegebene Prozessvariable %1 beinhaltet ungültigen Pfad: %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, q'[Interner Fehler bei Zusammenführungs-Gateway in Subflow %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, q'[Kein vorgegebener Gateway-Pfad in Variable %0  gefunden. Modell beinhaltet keine Standard-Route.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, q'[Ungültiger Gateway-Routingausdruck. Dies kann auftreten, wenn Sie versuchen, eine Variable mit einem eingebetteten Doppelpunkt (:) zu binden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, q'[Mehr als eine Standard-Route für Gateway %0 in Modell angegeben.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, q'[Zutreffendes Link-Ereignis mit Namen %0 konnte nicht gefunden werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, q'[Mehr als ein zutreffendes Link-Ereignis mit Namen %0 gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, q'[Flows - Interner Fehler beim protokollieren (log) eines Instanz-Ereignisses.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, q'[Flows - Interner Fehler während der protokollierung (log) eines Variablenereignisses.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, q'[Prozess-Objekt %0 aktuell von einem anderem Benutzer gesperrt. Bitte versuchen sie es später erneut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, q'[Mehr als ein vorwärts gerichteter Pfad gefunden (nur ein Pfad erlaubt).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, q'[Kein weiterer Schritt für Subflow %0 gefunden. Bitte das Prozess-Diagramm überprüfen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, q'[Prozess %0: Aufgabe %1 aufgrund eines PL/SQL Fehlers fehlgeschlagen. Bitte überprüfen sie das Ereignis-Log]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, q'[Prozess %0: Aufgabe %1 Ausführungsstopp angefordert - Bitte überprüfen sie das Ereignis-Log]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, q'[Subflow %0 kann nicht gesperrt werden. Es wird aktuell bereits von einem anderen Benutzer gesperrt. Bitte versuchen sie später erneut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, q'[Reservierung für nächste Aufgabe für sie bereits vorgesehen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, q'[Reservierung für %0 nicht erfolgreich. Der Schritt ist bereits von einem anderen Benutzer reserviert.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, q'[Reservierung für %2 nicht erfolgreich. Subflow %0 in Prozess %1  nicht gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, q'[Die Aufgabe ist nicht mehr aktuell und eventuell schon abgeschlossen. Bitte aktualisieren sie ihre Inbox.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, q'[Subflow aktuell von einem anderen Benutzer gesperrt (nicht reserviert). Bitte versuchen die die Reservierung zu einem späteren Zeitpunkt noch einmal durchzuführen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, q'[Reservierung konnte nicht erfolgreich freigegeben werden. Subflow %0 in Prozess %1 nicht gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, q'[Keine aktuellen Fehler gefunden. Bitte überprüfen sie das Prozess-Diagramm.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, q'[Sie haben versucht einen bereits laufenden Prozess (ID %0) zu starten.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, q'[Beim Versuch einen Prozess für Diagramm %0 zu starten wurde eine, sich selbst aufrufende, Aktivität gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, q'[Sie haben versucht einen Prozess (%0) zu starten für den bereits mehrere Kopien gestartet wurden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, q'[Sie haben mehrfache Startereignisse definiert. Bitte stellen sie sicher, dass ihr Diagramm nur ein Startereignis beinhaltet.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, q'[Es gibt kein definiertes Startereignis im Flow-Diagramm.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, q'[Sie haben versucht einen nicht existierenden Prozess (ID %0) zu starten.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, q'[Nicht unterstützter Startereignis-Typ (%0). Nur "Kein" Startereignis (Standard) und Timer-Startereignis werden aktuell unterstützt.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, q'[Start Zeit-Aufnahme nicht erfolgreich. Subflow %0 in Prozess %1 konnte nicht gefunden werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, q'[Dieser Prozessschritt wurde bereits aufgerufen. (Ungültiger Schritt %0 angegeben, während Schritt %1 erwartet wurde).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, q'[Teil-Prozess Startereignis kann nicht gefunden werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, q'[Flows - Interner Fehler beim protokollieren (log) eines Schritt-Ereignisses.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, q'[Mehr als ein Teil-Prozess Start gefunden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, q'[Timer %0 Ausführung %4 fehlerhaft in Prozess %1, Subflow: %2. Weitere Informationen in error_info]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, q'[Zyklus-Timer für Objekt %0 wird aktuell nicht unterstützt.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, q'[Prozess %0: Aufgabe %1 Platzhalter JSON ist nicht valide. Bitte überprüfen sie das Modell.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, q'[Mehrere Zeilen gefunden. Bitte aktivieren sie die "Enable Call Activities" in den Viewer-Plugin Attributen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, q'[Fehler beim Versuch, die APEX-Workflowaufgabe (task_id: %1 ) für Prozessschritt %0 abzubrechen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-supported', c_load_lang, q'[Für die Verwendung des APEX-Workflowfeatures ist Oracle APEX v%0 erforderlich.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, q'[APEX-Workflowaufgabe %0 nicht in Flows for APEX-Prozess gefunden]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, q'[APEX-Workflowaufgabe %0 gefunden, die mehreren Flows for APEX-Prozessschritten zugeordnet ist.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, q'[APEX-Workflowaufgabe %0 ist nicht der aktuelle Schritt des Prozesses. Der Schritt ist möglicherweise bereits abgeschlossen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, q'[Ergebnisprozessvariable für APEX-Workflowaufgabe ist nicht definiert oder ungültig.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, q'[Fehler beim Erstellen der APEX-Workflowaufgabe %0 in Anwendung %1. Weitere Informationen finden Sie im Debugging.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, q'[Fehler beim Erstellen der APEX-Workflowaufgabe - ungültige Priorität %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, q'[Fehler beim Erstellen der APEX-Session. BPMN-Diagramm enthält mehrere Prozessobjekte.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, q'[Sie haben versucht, ein Diagramm %0 aufzurufen, das als nicht aufrufbar markiert ist.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, q'[Unvollständige Timerdefinition für Objekt %0. Typ: %1; Wert1: %2 Wert2: %3  Wert3: %4]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, q'[Timer für Subflow %0 aktuell von einem anderen Benutzer gesperrt. Bitte versuchen sie es später erneut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, q'[Objekt mit Timer nicht in get_timer_definition gefunden. Subflow %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, q'[Timer für Prozess %0 wird aktuell von einem anderen Benutzer blockiert. Bitte versuchen sie es später erneut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, q'[Fehler beim erstellen der Prozessvariable %0 für Prozess %1 in Bereich %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, q'[Fehler beim abfragen der Prozessvariable %0 für Prozess %1 in Bereich %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, q'[Fehler beim setzen der Prozessvariable %0 für Prozess %1 in Bereich %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, q'[Fehler beim löschen der Prozessvariable %0 für Prozess %1 in Bereich %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, q'[Fehler beim sperren der Prozessvariable %0 für Prozess %1 in Bereich %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, q'[Fehler beim setzen der Prozessvariable. Falscher Datentyp für Variable %0. Der SQL Fehler wird in der Debug-Ausgabe angezeigt]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, q'[Fehler beim setzen der Prozessvariable %1: Ungültiges Datumsformat (Teilfluss: %0, Set: %3.)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, q'[Interner Fehler bei Abfrage von Objekt %0 in Prozess-Ausdrücken. SQL Fehler in Debug-Output ersichtlich.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, q'[Subflow: %0 Fehler in Ausdruck %2 für Variable : %1]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, q'[Fehler beim setzen von Prozessvariable %1 in Prozess %0 (setze %2). Keine Daten in der Abfrage vorhanden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, q'[Fehler beim setzen von Prozessvariable %1 in Prozess %0 (setze %2). SQL Fehler in Ereignislog ersichtlich.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_too_many_rows', c_load_lang, q'[Fehler beim setzen von Prozessvariable %1 in Prozess %0 (setze %2). Abfrage liefert mehrere Zeilen zurück.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, q'[Fehler beim setzen vonProzessvariable %1 in Prozess %0 (setze %2). Fehler in Ereignislog ersichtlich.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, q'[Diagramm-Release oder Entwurf Version 0 nicht gefunden. Bitte spezifizieren sie eine Version oder Diagramm-ID]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, q'[Die angegebene Diagrammversion wurde nicht gefunden.  Bitte überprüfen Sie die Versionsangabe.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, q'[Fehler beim parsen der Timerdefinition in Prozess %0, Subflow %1. Timertyp: %2, Definition: %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, q'[Version nicht definiert]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, q'[Fehler während des Parse-Vorgangs der Prozess-Variablen.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, q'[Gateway ist nicht für Routing definiert.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, q'[Gateway Definition für diesen Flow nicht definiert]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, q'[Flow-Instanz-ID oder Subflow-ID können nicht abgerufen werden.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, q'[Falsche Anzahl von APEX-Element(en) oder Prozessvariable(n).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, q'[Eine oder mehrere Prozessvariable(n) besitzen nicht den selben, im JSON definierten Typ.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, q'[%0 ist keine gültige Zahl.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, q'[%0 ist kein gültiges Datum.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, q'[Kein valides JSON.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, q'[Keine Daten gefunden. Bitte überprüfen sie ob ein Diagramm mit dieser ID existiert.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, q'[Unerwarteter Fehler, bitte kontaktieren sie ihren Administrator.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, q'[Diagram kann nicht geparst werden.<br />Bitte überprüfen sie ob ihr Diagram unterstützt wird.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, q'[Änderungen gespeichert!]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, q'[Modell wurde geändert. Änderungen verwerfen?]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: der konfigurierte Standard-Workspace ist nicht valide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, q'[Prozess %0: Aufgabe %1 fehlgeschlagen: Der, zu der Applikations-ID, zugewiesene Workspace konnte nicht gefunden werden. Bitte überprüfen sie das Modell]' );
  
  commit;
end;
/
