/*
-- Flows for APEX - engine_messages_fr.sql
--
-- Engine Messages for language code "fr"
--
-- Generated by language-load-generator
-- Generated on Fri, 05 Sep 2025 15:22:36 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "fr"
declare
  c_load_lang constant varchar2(10) := 'fr';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, q'[Vous avez essayé de démarrer un processus (id %0) qui n'existe pas.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, q'[Type d'événement de début non pris en charge (%0). Seuls les événements Aucun (standard), Message et Début de minuteur sont actuellement pris en charge.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, q'[Sous-flux de limite enfant ou minuteries de %0 actuellement verrouillées par un autre utilisateur. Réessayez la transaction ultérieurement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, q'[Aucun événement de frontière de type %0 trouvé pour capturer l'événement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, q'[Plus d'un événement de frontière %0 trouvé sur le sous-processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, q'[Erreur interne du moteur de flux: Processus %0 Sous-flux %1 Module %2 Courant %4 Balise courante %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, q'[Erreur de modèle : L'étape suivante du modèle de processus BPMN utilise un objet non supporté %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, q'[Erreur applicative : L'ID du processus %0 n'a pas été trouvé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, q'[Erreur applicative: L'ID du sous-flux fourni ( %0 ) existe mais n'est pas un enfant de l'ID de processus fourni ( %1 ).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, q'[L'ID du sous-flux fourni ( %0 ) est introuvable. Vérifiez les événements du processus qui ont modifié le flux du processus (délais, erreurs, escalades).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, q'[Erreur au niveau de la passerelle %0. La variable fournie %1 contient une route invalide : %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, q'[Erreur interne de traitement lors de la fusion au nivau de la passerelle sur le sous-flux %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, q'[Aucune instruction de routage de passerelle n'est fournie dans la variable %0 et le modèle ne contient pas de route par défaut.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, q'[Plus d'une route par défaut spécifiée dans le modèle pour la passerelle %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, q'[Expression de routage de passerelle incorrecte. Cela peut se produire si vous essayez de lier une variable avec le signe deux-points ( :).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, q'[Impossible de trouver le lien correspondant à l'événement %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, q'[Plus d'un lien correspond à l'événement %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, q'[Flows - Erreur interne lors de l'enregistrement d'un évènement d'instance]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, q'[Echec de l'enregistrement de l'heure de début du travail. Sous-flux %0 dans le processus %1 introuvable.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, q'[Cette étape de processus s'est déjà produite. (Clé d'étape %0 incorrecte fournie alors que la clé d'étape %1 est attendue).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, q'[Impossible de trouver l'événement de début de sous-processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, q'[Plus d'un événement de sous-processus trouvé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, q'[Minuteur %0 Exécution %4 interrompue dans le processus %1, sous-flux : %2. Reportez-vous à error_info.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, q'[Minuteur de type cycle défini pour l'objet %0 n'est pas pris en charge actuellement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, q'[Définitions d'horloge incomplètes pour l'objet %0. Type : %1 ; Value1 : %2 Value2 : %3 Value3 : %4]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, q'[Minuteur pour le sous-flux %0 actuellement verrouillé par un autre utilisateur. Réessayez plus tard.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, q'[Objet avec minuteur non trouvé dans get_timer_definition. Sous-flux %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, q'[Les minuteries du processus %0 sont actuellement verrouillées par un autre utilisateur. Réessayez plus tard.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, q'[Erreur de création de la variable de processus %0 pour l'ID de processus %1 dans la portée %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, q'[Erreur lors de l'obtention de la variable de processus %0 pour l'ID de processus %1 dans la portée %2.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, q'[Erreur de mise à jour de la variable de processus %0 pour l'ID de processus %1 dans la portée %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, q'[Erreur de suppression de la variable de processus %0 pour l'ID de processus %1 dans la portée %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, q'[Erreur de verrouillage de la variable de processus %0 pour l'ID de processus %1 dans la portée %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, q'[Erreur lors de l'analyse de la définition du minuteur dans le processus %0, sous-flux %1. Type de minuteur : %2, Définition: %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, q'[La version n'est pas définie.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, q'[Erreur lors de l'analyse des variables du processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, q'[La passerelle n'est pas définie pour le routage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, q'[La définition de la passerelle n'existe pas pour ce flux.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, q'[Impossible d'obtenir l'Id de l'Instance de flux et ou l'Id du sous-flux pour gérer l'étape.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, q'[Mauvais nombre d'élément(s) APEX ou de variable(s) de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, q'[Une ou plusieurs variables de processus sont d'un type différent de celui défini dans le JSON.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, q'[%0 n'est pas un nombre valide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, q'[%0 n'est pas une date valide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, q'[Le JSON fourni est invalide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, q'[Aucune donnée trouvée. Vérifiez si le Diagramme avec l'ID fourni existe.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, q'[Erreur inattendue, veuillez contacter votre administrateur.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, q'[Le diagramme n'a pas pu être analysé.<br />Veuillez examiner votre diagramme pour vous assurer qu'il est pris en charge.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, q'[Changements enregistrés !]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, q'[Le modèle a changé, annuler les changements?]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : l'espace de travail par défaut défini dans le paramètre de configuration n'est pas valide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : impossible de trouver l'espace de travail associé à l'aplication définie dans le diagramme. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : attribut De non défini. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : attribut To non défini. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : attribut Template non défini. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : attribut Corps non défini. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, q'[Processus %0 : la tâche de service %1 a échoué : voir le journal pour plus de détail et vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, q'[Processus %0: la tâche de service %1 a échoué : l'objet JSON des espaces réservés est invalide. Veuillez vérifier le modèle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, q'[Impossible de créer une connexion asynchrone pour l'objet %0. Nom d'utilisateur non valide dans l'application indiquée]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, q'[Plusieurs lignes trouvées. Activez le paramètre "Activer les activités d'appel" dans les attributs de plug-in de la visionneuse.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, q'[Erreur lors de la tentative d'annulation de la tâche APEX (ID tâche : %1 ) pour l'étape de processus : %0.)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, q'[Tâche APEX %0 introuvable dans le processus Flows for APEX]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, q'[La tâche APEX %0 n'est pas l'étape en cours du processus. L'étape a peut-être terminé toutes les étapes prêtes.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, q'[La variable de processus de résultat de tâche APEX n'est pas définie ou n'est pas valide.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, q'[Erreur lors de la création de la tâche de workflow APEX %0 dans l'application %1. Pour plus de détails, reportez-vous au débogage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, q'[Erreur lors de l'évaluation de la priorité. La priorité doit être comprise entre 1 et 5. Priorité : %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, q'[Erreur lors de la création de la session APEX. Le diagramme BPMN contient plusieurs objets de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, q'[Vous avez essayé d'appeler un diagramme %0 marqué comme ne pouvant pas être appelé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, q'[Type d'événement de lancer intermédiaire actuellement non pris en charge rencontré à %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, q'[Les détails de connexion asynchrone pour l'objet %0 doivent être définis dans les variables de processus, les détails de connexion asynchrone de diagramme ou les détails de configuration système.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, q'[Impossible de créer une connexion asynchrone pour l'objet %0. Le nom d'utilisateur doit être la variable du processus, le diagramme du processus ou la configuration du système.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, q'[Impossible de créer une connexion asynchrone pour l'objet %0. L'ID d'application doit être indiqué dans la variable de processus, le diagramme de processus ou la configuration système.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, q'[Impossible de créer une connexion asynchrone pour l'objet %0. L'ID de page doit être spécifié dans la variable de processus, le diagramme de processus ou la configuration système.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-null', c_load_lang, q'[Aucune destination d'archivage ou de journalisation n'a été configurée. Reportez-vous à Configurations &gt; Journalisation ou Archivage]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_other', c_load_lang, q'[Erreur de définition de la variable de processus %1 dans l'ID de processus %0 (ensemble %2). Erreur PL/SQL affichée dans le journal des événements. ]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-call-act', c_load_lang, q'[Rewind : le sous-flux parent n'est pas une activité d'appel vers laquelle effectuer un rembobinage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-previous-gw', c_load_lang, q'[Aucune passerelle parallèle ou inclusive d'ouverture précédente trouvée pour le sous-flux %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'resume-invalid-status', c_load_lang, q'[Seules les instances de processus ayant actuellement le statut Suspendu peuvent être reprises.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-matched-object', c_load_lang, q'[Rembobinage - aucun objet d'ouverture correspondant trouvé pour le rembobinage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-unknown-gw-status', c_load_lang, q'[Rewind : statut de passerelle inconnu lors du rembobinage vers la passerelle précédente. ]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-previous-gateway', c_load_lang, q'[Rewind : aucune passerelle précédente vers laquelle rembobiner.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-call-act', c_load_lang, q'[Rembobinage : aucun sous-flux d'activité d'appel parent n'a été trouvé pour rembobinage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-split-event-based-gw', c_load_lang, q'[ Rembobinage : impossible de rembobiner une passerelle basée sur un événement qui est toujours en cours d'exécution. Rembobinez d'abord l'un des sous-flux vers l'avant vers la passerelle basée sur les événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_plsql_other', c_load_lang, q'[Erreur d'exécution de PL/SQL. Erreur PL/SQL affichée dans le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-matching-object-error', c_load_lang, q'[Erreur lors de l'extraction de l'objet passerelle correspondant pour le sous-flux %0, étape en cours %1.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_cols', c_load_lang, q'[Erreur lors de l'exécution de la requête SQl : la requête renvoie plusieurs colonnes.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-subflow', c_load_lang, q'[Rembobinage - aucun sous-flux parent trouvé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_rows', c_load_lang, q'[Erreur de définition de la variable de processus %1 dans l'ID de processus %0 (ensemble %2). La requête renvoie plusieurs lignes.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-cant-gway-from-event', c_load_lang, q'[Rembobinage : impossible de revenir à la passerelle précédente à partir de l'événement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-event-level', c_load_lang, q'[Flux - Erreur interne lors de l'obtention du niveau de journalisation]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-not-wait-at-gateway', c_load_lang, q'[Rembobinage : le sous-flux n'attend pas une passerelle pour revenir à la dernière étape.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_values', c_load_lang, q'[Erreur lors de l'exécution de la requête SQL : la requête renvoie plusieurs valeurs.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-internal-error', c_load_lang, q'[Erreur interne d'horloge pour l'objet %0. Type : %1 ; Valeur : %2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspend-invalid-status', c_load_lang, q'[Seules les instances de processus en cours d'exécution ou en erreur peuvent être suspendues.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-multiple-previous-gws', c_load_lang, q'[Plusieurs passerelles précédentes ouvertes parallèles ou inclusives ont été trouvées pour le sous-flux %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspended-cannot-complete-step', c_load_lang, q'[Cette instance de processus est actuellement suspendue. Veuillez réessayer plus tard.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-last-step', c_load_lang, q'[Rembobinage : aucune dernière étape terminée trouvée juste avant la passerelle vers laquelle effectuer le rembobinage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-step-reposition-error', c_load_lang, q'[Rewind : étape de repositionnement d'erreur.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-current-step', c_load_lang, q'[Rembobinage : l'étape cible demandée pour le rembobinage n'est pas une transition valide à partir de l'étape actuelle.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_other', c_load_lang, q'[Erreur lors de l'exécution de la requête SQL. Erreur SQL affichée dans le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-subproc', c_load_lang, q'[Rembobinage : le sous-flux parent n'est pas un sous-processus vers lequel rembobiner.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, q'[Erreur de définition de la variable %1 (valeur : %2) dans le processus d'id %0. Voir l'erreur dans le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, q'[Impossible de trouver le diagramme publié ou la version 0 du diagramme - veuillez spécifier une version ou un numéro de diagramme.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, q'[Impossible de trouver la version spécifiée du diagramme. Veuillez vérifier la version.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, q'[La réservation pour %0 est impossible. L'étape est déjà réservée par un autre utilisateur (%1).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, q'[La réservation pour %0 est impossible. Sous-flux %0 dans le processus %1 non trouvé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, q'[La tâche n'est plus en cours, elle est probablement déjà terminée. Veuillez rafraîchir votre liste de tâches.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, q'[Sous-flux actuellement verrouillé (non reservé) par un autre utilisteur. Veuillez réessayez ultérieurement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, q'[La libération de la réservation est impossible. Sous-flux %0 dans le processus %1 non trouvé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-procvar-no-prcs', c_load_lang, q'[Les paramètres ne peuvent pas spécifier de variable de processus sans ID de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'diagram-archive-has-instances', c_load_lang, q'[Vous avez essayé d'archiver un diagramme comportant des instances en cours d'exécution.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-subflow', c_load_lang, q'[Le destinataire du message ne peut pas verrouiller le sous-flux. Réessayez.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-error', c_load_lang, q'[Erreur lors de l'évaluation du paramètre. Expression non valide. Expression : %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-endpoint-not-supported', c_load_lang, q'[L'adresse MessageFlow indiquée ( %0) n'est pas prise en charge.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-msub', c_load_lang, q'[Abonnement aux messages verrouillé par un autre utilisateur. Réessayez.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-business-ref-null', c_load_lang, q'[Erreur lors de la création de la tâche d'approbation - La référence commerciale / la clé primaire du système d'enregistrement ne doit pas avoir la valeur NULL.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-interval-error', c_load_lang, q'[Erreur lors de l'évaluation de la date d'échéance. Expression d'intervalle non valide. Intervalle : %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-error', c_load_lang, q'[Erreur lors de l'évaluation de l'échéance. L'expression Echéance le n'est pas valide. Expression d'intervalle : %0.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-priority-error', c_load_lang, q'[Erreur lors de l'évaluation de la priorité. Expression de priorité non valide. Expression : %0. Priorité 3 utilisée à la place.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-bad-scope', c_load_lang, q'[Portée non valide (%0) fournie pour la variable de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'scheduler-repeat-shared-env', c_load_lang, q'[Intervalle de répétition du compteur trop fréquent pour l'hôte (%0) Intervalle demandé %1. Doit être supérieur à 1 minute.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-bad-json', c_load_lang, q'[Erreur dans le paramètre de configuration de destination d'archivage. Paramètre : %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-not-correlated', c_load_lang, q'[Le message reçu ne correspond pas à un message attendu.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-no-longer-current-step', c_load_lang, q'[Un message de réception d'étape de processus s'est déjà produit (clé d'étape incorrecte fournie).]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-diagram-event', c_load_lang, q'[Flows - Erreur interne lors de la journalisation d'un événement de diagramme.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'log-archive-error', c_load_lang, q'[Erreur lors de l'archivage du récapitulatif d'instance pour l'instance de processus %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'feature-requires-ee', c_load_lang, q'[Cette fonctionnalité nécessite une licence pour Flows for APEX Enterprise Edition.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_close_error', c_load_lang, q'[Erreur interne lors du traitement de la fermeture de l'itération sur le sous-flux %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_json_format', c_load_lang, q'[Erreur lors de la mise à jour de la variable de processus %1 : Format JSON incorrect (sous-flux : %0, valeur : %3.)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_lock_error', c_load_lang, q'[Erreur lors du verrouillage du détail d'itération (itération %0 boucle %2) pour l'ID de processus %1.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, q'[Flows - Erreur interne lors de l'enregistrement d'un évènement d'étape]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, q'[Flows - Erreur interne lors de l'enregistrement d'un évènement de variable]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, q'[Les objets de traitement pour %0 sont actuellement verrouillés par un autre utilisateur. Réessayez plus tard.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, q'[Plus d'un chemin d'accès trouvé alors qu'un seul est autorisé.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, q'[Aucune étape suivante trouvée pour le sous-flux %0. Vérifiez votre diagramme de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, q'[Processus %0 : la tâche %1 a échoué en raison d'une erreur PL/SQL - voir le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, q'[Processus %0: Tâche %1 arrêt du traitement demandé - voir le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, q'[Impossible de verrouiller le sous-flux %0, celui-ci est actuellement verrouillé par un autre utilisateur. Veuillez réessayer ultérieurement.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, q'[Réservation déjà effectuée sur la prochaine tâche pour vous.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, q'[Erreur de définition de la variable de processus. Type de données incorrect pour la variable %0. Erreur SQL affichée dans le débogage.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, q'[Erreur de définition de la variable de processus %1 : format de date incorrect (Sous-flux : %0, Valeur : %3.)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, q'[Erreur interne dans la recherche de l'objet %0 dans process_expressions. Erreur SQL affichée dans le débogage]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, q'[Sous-flux : %0 Erreur dans l'expression %2 de la variable : %1]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, q'[Ereur lors de la définition de la variable %1 avec la valeur %2 dans le processus %0 - Aucune donnée trouvée dans la requête.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, q'[Ereur lors de la définition de la variable %1 avec la valeur %2 dans le processus %0. Erreur SQL indiquée dans le journal des événements.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, q'[La tâche de workflow APEX %0 est associée à plus d'une étape de processus dans Flows for APEX.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, q'[Aucune erreur courante trouvée. Vérifiez votre diagramme de processus.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, q'[Vous avez essayé de démarrer un processus (id %0) qui est déjà en cours d'exécution.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, q'[Vous avez essayé de démarrer un processus avec un diagramme %0 qui inclut une activité d'appel s'appelant lui même.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, q'[Vous avez essayé de démarrer un processus (id %0) dont plusieurs copies sont déjà en cours d'exécution.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, q'[Vous avez défini plusieurs événements de début. Assurez-vous que votre diagramme n'a qu'un seul événement de début.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, q'[Aucun événement de début n'est défini dans le diagramme de flux.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-force-step-not-error', c_load_lang, q'[Impossible de forcer l'étape suivante sur un sous-flux qui n'a pas le statut erreur.]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-matching-object-error', c_load_lang, q'[Rembobinage : erreur lors de l'obtention de l'objet correspondant pour le rembobinage à partir du journal de sous-flux.]' );
  
  commit;
end;
/
