/*
-- Flows for APEX - engine_messages_zh-cn.sql
--
-- Engine Messages for language code "zh-cn"
--
-- Generated by language-load-generator
-- Generated on Fri, 05 Sep 2025 15:22:36 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "zh-cn"
declare
  c_load_lang constant varchar2(10) := 'zh-cn';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-error', c_load_lang, q'[评估设置时出错。表达式无效。表达式：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-procvar-no-prcs', c_load_lang, q'[设置不能指定没有进程 ID 的进程变量。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-endpoint-not-supported', c_load_lang, q'[不支持指定的 MessageFlow 端点 ( %0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-bad-scope', c_load_lang, q'[为流程变量提供的范围 (%0) 无效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, q'[获取范围 %2 中进程 ID %1 的进程变量 %0 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, q'[当前在 %0 遇到的中间引发事件类型不受支持。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, q'[需要在流程变量中设置对象 %0 的异步连接详细信息、图表异步连接详细信息或系统配置详细信息。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, q'[无法为对象 %0 创建异步连接。用户名在指定的应用程序中无效]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, q'[无法为对象 %0 创建异步连接。需要在进程变量、进程图或系统配置中指定用户名。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, q'[无法为对象 %0 创建异步连接。需要在进程变量、进程图或系统配置中指定应用程序 ID。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, q'[无法为对象 %0 创建异步连接。需要在进程变量、进程图或系统配置中指定页 ID。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, q'[%0 的子边界子流或计时器当前被其他用户锁定。稍后重试事务处理。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, q'[找不到类型为 %0 的 boundaryEvent 来捕获事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, q'[在子进程中找到多个 %0 boundaryEvent。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, q'[流引擎内部错误：流程 %0 子流 %1 模块 %2 当前 %4 当前标签 %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, q'[应用程序错误：未找到进程 ID %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, q'[应用程序错误：提供的子流 ID ( %0) 存在，但不是提供流程 ID ( %1) 的子项。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, q'[网关 %0 出错。提供的变量 %1 包含无效路由：%2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, q'[处理子流程 %0 上的合并网关时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, q'[变量 %0 中未提供网关路由指令，模型不包含默认路由。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, q'[%0 的进程对象当前被其他用户锁定。请稍后重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, q'[找到1 个以上的转发路径仅，只允许 1 个转发路径。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, q'[在子流 %0 上未找到下一步骤。检查您的流程图。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, q'[流程 %0：任务 %1 已请求处理停止 - 请参阅事件日志。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, q'[无法锁定子流程 %0，因为目前已被其他用户锁定。请稍后重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, q'[%0 的保留不成功。步骤已被其他用户 (%1) 保留。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, q'[%2 的保留不成功。未找到流程 %1 中的子流 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, q'[任务不再是当前任务，可能已经完成。请刷新收件箱。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, q'[子流程当前被另一用户锁定（未保留）。请稍后再次尝试您的预订。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, q'[保留发放失败。未找到流程 %1 中的子流 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, q'[未找到当前错误。检查您的流程图。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, q'[您尝试启动已运行的进程（标识 %0）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, q'[您尝试使用包括 callActivity 调用自身的图表 %0 启动进程。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, q'[在网关 %0 的模型中指定了多个默认路由。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, q'[找不到名为 %0 的相配链接捕获事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, q'[多个名为 %0 的相配链接捕获事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, q'[流程 - 记录实例事件时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, q'[流程 - 记录步骤事件时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, q'[流程 - 记录变量事件时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, q'[您尝试启动一个进程（标识 %0），其中多个副本已在运行。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, q'[未在流程图中定义起始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, q'[您尝试启动不存在的进程（标识 %0）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, q'[不支持的开始事件类型 (%0)。当前仅支持“无”（标准）、“消息”和“计时器开始事件”。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, q'[已发生此流程步骤。（在期望步骤关键字 %1 时却不正确的提供步骤关键字 %0 ）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, q'[无法找到子流程开始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, q'[计时器 %0 运行 %4 在流程 %1 中中断，子流程：%2。请参阅 error_info。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, q'[当前不支持为对象 %0 定义的周期计时器。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, q'[子流程 %0 的计时器当前被其他用户锁定。请稍后重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, q'[在 get_timer_definition 中未找到具有计时器的对象。子流 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, q'[为范围 %2 中的流程 ID %1 创建流程变量 %0 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, q'[更新范围 %2 中进程 ID %1 的进程变量 %0 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, q'[锁定范围 %2 中进程 ID %1 的进程变量 %0 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, q'[设置流程变量时出错。变量 %0 的数据类型不正确。调试输出中显示的 SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, q'[设置流程变量 %1 时出错：日期格式不正确（子流：%0，集：%3。）]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, q'[在 process_expressions 中查找对象 %0 时出现内部错误。调试输出中显示的 SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, q'[子流程：%0 变量 %1 的 %2 表达式中出错]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, q'[在进程 ID %0（集 %2）中设置进程变量 %1 时出错。查询中未找到数据。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, q'[在进程 ID %0（集 %2）中设置进程变量 %1 时出错。事件日志中显示的 SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, q'[在进程 ID %0（集 %2）中设置进程变量 %1 时出错。在事件日志中查看错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, q'[找不到已发布图表或草稿版本 0 - 请指定版本或 diagram_id]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, q'[找不到指定的图表版本。请检查版本规范。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, q'[分析流程 %0、子流 %1 中的计时器定义时出错。计时器类型：%2，定义：%3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, q'[未定义版本。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, q'[分析流程变量时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, q'[没有为路由定义网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, q'[此流程不存在网关定义。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, q'[无法获取流程实例 ID 和/或子流程 ID 以管理步骤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, q'[APEX 项或进程变量的数量错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, q'[一个或多个进程变量与 JSON 中定义的不同类型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, q'[%0 不是有效数字。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, q'[%0 不是有效日期。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, q'[提供的 JSON 无效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, q'[未找到数据。检查具有给定 ID 的图表是否存在。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, q'[意外错误，请与管理员联系。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, q'[无法解析图表。<br /> 请查看您的图表以确保其受支持。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, q'[更改已保存！]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, q'[流程 %0：ServiceTask %1 失败：配置参数中定义的默认工作区无效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, q'[流程 %0：ServiceTask %1 失败：未定义属性 "From" 和默认电子邮件发件人。请检查模型和配置参数。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, q'[流程 %0：ServiceTask %1 失败：未定义属性“至”。请检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, q'[流程 %0：ServiceTask %1 失败：未定义属性 "Body"。请检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, q'[流程 %0：ServiceTask %1 失败，请查看错误日志并检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, q'[流程 %0：ServiceTask %1 占位符 JSON 无效. 请检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'feature-requires-ee', c_load_lang, q'[处理此功能需要获得 Flows for APEX Enterprise Edition 许可。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_close_error', c_load_lang, q'[’处理子流 %0 上的迭代关闭时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_json_format', c_load_lang, q'[设置流程变量 %1 时出错：JSON 格式不正确（子流：%0，集：%3）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_lock_error', c_load_lang, q'[锁定进程 ID %1 的迭代详细信息（iter %0 循环 %2）时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, q'[模型错误：流程 BPMN 模型下一步将使用不支持的对象 %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, q'[未找到提供的子流程 ID ( %0)。检查更改了流程的流程事件（超时、错误、升级）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, q'[网关路由表达式错误。如果尝试使用嵌入式冒号 (：) 绑定变量，则会发生这种情况。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, q'[流程 %0：由于 PL/SQL 错误，任务 %1 失败 - 请查看事件日志。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, q'[已为您安排下一个任务。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, q'[您定义了多个起始事件。确保图表只有一个开始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, q'[开始工作时间记录不成功。未找到流程 %1 中的子流 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, q'[找到多个子流程开始。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, q'[对象 %0 的计时器定义不完整。类型：%1；Value1：%2 Value2：%3 Value3：%4 值？]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, q'[进程 %0 的计时器当前被其他用户锁定。请稍后重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, q'[删除范围 %2 中进程 ID %1 的进程变量 %0 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, q'[模型已更改。是否放弃更改？]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, q'[流程 %0：ServiceTask %1 失败：无法找到与图表中定义的应用程序 ID 关联的工作区。请检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, q'[流程 %0：ServiceTask %1 失败：未定义属性 "Template"。请检查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, q'[找到多行。请在查看器插件属性中启用“启用呼叫活动”设置。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, q'[尝试为流程步骤 %0 取消 APEX 工作流任务 (task_id：%1) 时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, q'[在 Flows for APEX 流程中未找到 APEX 人工任务 %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, q'[找到与多个 Flows for APEX 流程步骤关联的 APEX 人工任务 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, q'[APEX 人工任务 %0 不是流程的当前步骤。步骤可能已完成所有就绪。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, q'[APEX 人工任务结果流程变量未定义或无效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, q'[在应用程序 %1 中创建 APEX 人工任务 %0 时出错。有关详细信息，请参阅调试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, q'[创建 APEX 工作流任务时出错 - 优先级 %0 无效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, q'[创建 APEX 会话时出错。BPMN 图包含多个流程对象。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, q'[您尝试调用标记为不可调用的图表 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'diagram-archive-has-instances', c_load_lang, q'[您尝试归档包含正在运行的实例的图表。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-business-ref-null', c_load_lang, q'[创建审批任务时出错 - 业务参考/记录系统主关键字不能为 NULL。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-bad-json', c_load_lang, q'[归档目标配置参数出错。参数：%0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'log-archive-error', c_load_lang, q'[归档进程实例 %0 的实例概要时出错]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'scheduler-repeat-shared-env', c_load_lang, q'[主机 (%0) 请求的间隔 %1 的计时器重复间隔太频繁。必须大于 1 分钟。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-not-correlated', c_load_lang, q'[收到的消息与预期消息不匹配。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-no-longer-current-step', c_load_lang, q'[已发生流程步骤接收消息（提供的步骤关键字不正确）。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-msub', c_load_lang, q'[消息订阅已被其他用户锁定。请重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-subflow', c_load_lang, q'[消息接收者无法锁定子流。请重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-diagram-event', c_load_lang, q'[流 - 记录图表事件时出现内部错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-interval-error', c_load_lang, q'[评估到期日期时出错。间隔表达式无效。间隔：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-error', c_load_lang, q'[评估到期日期时出错。到期日表达式无效。间隔表达式：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-priority-error', c_load_lang, q'[评估优先级时出错。优先级表达式无效。表达式：%0。改为使用优先级 3。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-null', c_load_lang, q'[未配置归档或日志记录目标 - 请参阅配置 &gt; 日志记录或归档]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_other', c_load_lang, q'[在流程标识 %0（集 %2）中设置流程变量 %1 时出错。事件日志中显示的 PL/SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-call-act', c_load_lang, q'[倒带 - 父子流不是要倒带到的调用活动。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-previous-gw', c_load_lang, q'[未找到子流 %0 的上一个打开并行网关或包含网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'resume-invalid-status', c_load_lang, q'[只能恢复当前处于已挂起状态的流程实例。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-matched-object', c_load_lang, q'[倒带 - 未找到要倒带到的匹配打开对象。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-unknown-gw-status', c_load_lang, q'[重绕 - 重绕到以前的网关时未知的网关状态。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-previous-gateway', c_load_lang, q'[倒带 - 未找到要倒带到的以前网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-call-act', c_load_lang, q'[倒带 - 未找到要倒带到的父拜访活动子流。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-split-event-based-gw', c_load_lang, q'[ 倒带 - 无法从仍在运行的基于事件的网关倒带。首先将其中一个正向子流倒回基于事件的网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_plsql_other', c_load_lang, q'[执行 PL/SQL 时出错。事件日志中显示的 PL/SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-matching-object-error', c_load_lang, q'[检索子流 %0、当前步骤 %1 的匹配网关对象时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_cols', c_load_lang, q'[执行 SQl 查询时出错 - 查询返回多个列。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-subflow', c_load_lang, q'[重绕 - 未找到父子流。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_rows', c_load_lang, q'[在流程标识 %0（集 %2）中设置流程变量 %1 时出错。查询返回多行。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-cant-gway-from-event', c_load_lang, q'[重绕 - 无法从事件重绕到以前的网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-event-level', c_load_lang, q'[流 - 获取日志记录级别时出现内部错误]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-not-wait-at-gateway', c_load_lang, q'[重绕 - 子流未在网关处等待重绕到最后一步。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_values', c_load_lang, q'[执行 SQL 查询时出错 - 查询返回多个值。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-internal-error', c_load_lang, q'[对象 %0 的计时器内部错误。类型：%1；值：%2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspend-invalid-status', c_load_lang, q'[只能挂起当前处于运行或错误状态的流程实例。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-force-step-not-error', c_load_lang, q'[无法对未处于错误状态的子流强制执行下一步。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-multiple-previous-gws', c_load_lang, q'[为子流 %0 找到多个以前打开的并行网关或包含网关。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspended-cannot-complete-step', c_load_lang, q'[此处理实例当前已挂起。请稍后重试。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-last-step', c_load_lang, q'[重绕 - 在网关重绕之前未找到最后完成的步骤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-step-reposition-error', c_load_lang, q'[重绕 - 重新定位步骤时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-current-step', c_load_lang, q'[倒带 - 为倒带请求的目标步骤不是当前步骤的有效转换。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-matching-object-error', c_load_lang, q'[倒带 - 从子流日志中获取要倒带的匹配对象时出错。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_other', c_load_lang, q'[执行 SQL 查询时出错。事件日志中显示的 SQL 错误。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-subproc', c_load_lang, q'[倒带 - 父子流不是要倒带到的子流程。]' );
  
  commit;
end;
/
