/*
-- Flows for APEX - engine_messages_zh-tw.sql
--
-- Engine Messages for language code "zh-tw"
--
-- Generated by language-load-generator
-- Generated on Fri, 05 Sep 2025 15:22:36 GMT
*/

set define '^'
whenever sqlerror exit rollback;

PROMPT >> Loading Engine Messages for Language "zh-tw"
declare
  c_load_lang constant varchar2(10) := 'zh-tw';
begin
  delete
    from flow_messages
   where fmsg_lang = c_load_lang;

  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-bad-json', c_load_lang, q'[存檔目的地組態參數中發生錯誤。參數：%0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'log-archive-error', c_load_lang, q'[存檔處理作業執行處理 %0 的執行處理摘要時發生錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'scheduler-repeat-shared-env', c_load_lang, q'[主機 (%0) 要求的間隔 %1 的計時器重複間隔太頻繁。必須大於 1 分鐘。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-not-correlated', c_load_lang, q'[收到的訊息與預期訊息不相符。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-no-longer-current-step', c_load_lang, q'[接收訊息的處理作業步驟已經發生 (提供的步驟索引鍵不正確)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-msub', c_load_lang, q'[訊息訂閱已由其他使用者鎖定。請再試一次。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-lock-timeout-subflow', c_load_lang, q'[訊息接收者無法鎖定子流程。請再試一次。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-diagram-event', c_load_lang, q'[流程 - 記錄「圖表事件」時發生內部錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-interval-error', c_load_lang, q'[評估到期日時發生錯誤。間隔表示式無效。間隔：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'due-on-error', c_load_lang, q'[評估到期日時發生錯誤。「到期日」運算式無效。間隔表示式：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-priority-error', c_load_lang, q'[評估優先順序時發生錯誤。優先順序運算式無效。表示式：%0。已改用優先順序 3。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-error', c_load_lang, q'[評估設定時發生錯誤。表示式無效。表示式：%0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'settings-procvar-no-prcs', c_load_lang, q'[設定值無法指定沒有處理 ID 的處理變數。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'msgflow-endpoint-not-supported', c_load_lang, q'[不支援 MessageFlow 指定的端點 (%0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-bad-scope', c_load_lang, q'[提供給處理作業變數的範圍 (%0) 無效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-get-error', c_load_lang, q'[取得範圍 %2 中處理作業 ID %1 的處理作業變數 %0 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'ITE-unsupported-type', c_load_lang, q'[目前在 %0 發生不支援的「中間發出事件」類型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-session-params-not-set', c_load_lang, q'[必須在處理作業變數、圖表非同步連線詳細資訊或系統組態詳細資訊中設定物件 %0 的非同步連線詳細資訊。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-invalid_params', c_load_lang, q'[無法建立物件 %0 的非同步連線。指定的應用程式中使用者名稱無效]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-on-multiple-steps', c_load_lang, q'[發現 APEX 人工作業 %0 與多個 Flows for APEX 處理作業步驟關聯。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-pageid', c_load_lang, q'[無法建立物件 %0 的非同步連線。必須在處理變數、處理圖表或系統組態中指定頁面 ID。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-child-lock-to', c_load_lang, q'[%0 的子界限子流程或計時器目前已由其他使用者鎖定。請稍後重試您的交易。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-no-catch-found', c_load_lang, q'[找不到類型為 %0 的 boundaryEvent 來擷取事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'boundary-event-too-many', c_load_lang, q'[在子處理作業找到多個 %0 boundaryEvent。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'eng_handle_event_int', c_load_lang, q'[流程引擎內部錯誤：處理 %0 子流程 %1 模組 %2 目前的 %4 目前的標記 %3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-unsupported-object', c_load_lang, q'[模型錯誤：處理 BPMN 模型下一步使用不支援的物件 %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-prcs-not-found', c_load_lang, q'[應用程式錯誤：找不到處理作業 ID %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-in-prcs', c_load_lang, q'[應用程式錯誤：提供的子流程 ID (%0) 存在，但不是所提供處理 ID 的子項 (%1)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-no-rel-or-draft-v0', c_load_lang, q'[找不到已發行圖表或圖表的草稿版本 0 - 請指定版本或 diagram_id]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'version-not-found', c_load_lang, q'[找不到指定的圖表版本。請檢查版本規格。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer_definition_error', c_load_lang, q'[剖析處理 %0 (子流程 %1) 中的計時器定義時發生錯誤。計時器類型：%2，定義：%3]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-model-no-version', c_load_lang, q'[未定義版本。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-parsing-json-variables', c_load_lang, q'[剖析處理變數時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-route-not-define', c_load_lang, q'[未定義路由的閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-gateway-not-exist', c_load_lang, q'[此流程沒有閘道定義。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-no-instance-subflow-id', c_load_lang, q'[無法取得流程實例 ID 與或子流程 ID 來管理步驟。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-number', c_load_lang, q'[APEX 項目或處理變數數目錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-wrong-variable-type', c_load_lang, q'[一或多個處理變數的類型與 JSON 中定義的類型不同。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-number', c_load_lang, q'[%0 不是有效的數字。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-variable-not-a-date', c_load_lang, q'[%0 不是有效的日期。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-invalid-json', c_load_lang, q'[提供的 JSON 無效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-modeler-id-not-found', c_load_lang, q'[找不到資料。檢查指定 ID 的圖表是否存在。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-unexpected-error', c_load_lang, q'[未預期的錯誤，請與您的管理員聯絡。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-not-parsable', c_load_lang, q'[無法剖析圖表。<br /> 請複查您的圖表以確定支援圖表。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-saved', c_load_lang, q'[變更已儲存！]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-diagram-has-changed', c_load_lang, q'[模型已變更。要捨棄變更嗎？]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'wrong-default-workspace', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗：組態參數中定義的預設工作區無效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'workspace-not-found', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗：找不到與圖表中定義之應用程式 ID 相關聯的工作區。請檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-from', c_load_lang, q'[處理 %0：ServiceTask %1 失敗：未定義屬性「寄件者」和預設電子郵件寄件者。請檢查模型與或組態參數。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-to', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗：未定義屬性 "To"。請檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-template', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗：未定義屬性 "Template"。請檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-no-body', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗：未定義屬性 "Body"。請檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-failed', c_load_lang, q'[處理作業 %0：ServiceTask %1 失敗，請參閱錯誤日誌並檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'email-placeholder-json-invalid', c_load_lang, q'[處理作業 %0：ServiceTask %1 預留位置 JSON 是 invalid.Please，請檢查模型。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plugin-multiple-rows', c_load_lang, q'[找到多個資料列。請啟用檢視者外掛程式屬性中的「啟用拜訪活動」設定。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-cancelation-error', c_load_lang, q'[嘗試取消處理步驟 %0 的 APEX 人工作業 (task_id：%1) 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-found', c_load_lang, q'[Flows for APEX 處理中找不到 APEX 人工作業 %0]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-not-current-step', c_load_lang, q'[APEX 人工作業 %0 不是處理作業的目前步驟。步驟可能已完成所有就緒。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-invalid-result-var', c_load_lang, q'[未定義 APEX 人工作業結果處理變數或變數無效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-creation-error', c_load_lang, q'[在應用程式 %1 中建立 APEX 人工作業 %0 時發生錯誤。請參閱除錯以瞭解詳細資訊。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-priority-error', c_load_lang, q'[建立 APEX 工作流程作業時發生錯誤 - 優先順序 %0 無效。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-multiple-processes', c_load_lang, q'[建立 APEX 階段作業時發生錯誤。BPMN 圖包含多個「處理作業」物件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'call-diagram-not-callable', c_load_lang, q'[您嘗試呼叫標示為不可呼叫的圖表 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'diagram-archive-has-instances', c_load_lang, q'[您嘗試將含有執行中執行處理的圖表存檔。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'apex-task-business-ref-null', c_load_lang, q'[建立核准任務時發生錯誤 - 業務參考 / 記錄系統主索引鍵不得為空值。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-not-created', c_load_lang, q'[您嘗試啟動不存在的處理作業 (ID %0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-type-unsupported', c_load_lang, q'[不支援的開始事件類型 (%0)。目前僅支援「無」(標準)、「訊息」及「計時器開始事件」。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'startwork-sbfl-not-found', c_load_lang, q'[開始工作時間記錄失敗。找不到處理 %1 中的子流程 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'step-key-incorrect', c_load_lang, q'[此處理步驟已發生。(步驟索引鍵 %1 時提供了不正確的步驟索引鍵 %0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-no-start', c_load_lang, q'[找不到子處理開始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'subProcess-too-many-starts', c_load_lang, q'[找到多個子處理開始。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-broken', c_load_lang, q'[計時器 %0 執行 %4 在處理 %1 中中斷，子流程：%2。請參閱 error_info。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-cycle-unsupported', c_load_lang, q'[目前不支援為物件 %0 定義的週期計時器。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-incomplete-definition', c_load_lang, q'[物件 %0 的計時器定義不完整。類型：%1；Value1：%2 Value2：%3 Value3：%4]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-lock-timeout', c_load_lang, q'[其他使用者目前鎖定子流程 %0 的計時器。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-object-not-found', c_load_lang, q'[get_timer_definition 中找不到含有計時器的物件。子流程 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timers-lock-timeout', c_load_lang, q'[處理 %0 的計時器目前被其他使用者鎖定。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-set-error', c_load_lang, q'[為範圍 %2 中的程序 ID %1 建立程序變數 %0 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-update-error', c_load_lang, q'[更新範圍 %2 中程序 ID %1 的程序變數 %0 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-delete-error', c_load_lang, q'[刪除範圍 %2 中處理作業 ID %1 的處理作業變數 %0 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var-lock-error', c_load_lang, q'[鎖定範圍 %2 中程序 ID %1 的程序變數 %0 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_datatype', c_load_lang, q'[設定處理變數時發生錯誤。變數 %0 的資料類型不正確。在除錯輸出中顯示 SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_date_format', c_load_lang, q'[設定處理變數 %1 時發生錯誤：日期格式不正確 (子流程：%0，集合：%3)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_object_not_found', c_load_lang, q'[查詢 process_expressions 中的物件 %0 時發生內部錯誤。在除錯輸出中顯示 SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'restart-no-error', c_load_lang, q'[找不到目前錯誤。檢查您的處理程序圖。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-already-running', c_load_lang, q'[您嘗試啟動已在執行的處理作業 (ID %0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_other', c_load_lang, q'[在處理 ID %0 (設定 %2) 中設定處理變數 %1 時發生錯誤。事件日誌中顯示的 SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_static_general', c_load_lang, q'[在處理 ID %0 (設定 %2) 中設定處理變數 %1 時發生錯誤。查看事件記錄中的錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_error', c_load_lang, q'[子流程：%0 變數 %1 的 %2 運算式發生錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_sql_no_data', c_load_lang, q'[在處理 ID %0 (設定 %2) 中設定處理變數 %1 時發生錯誤。查詢中找不到資料。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'feature-requires-ee', c_load_lang, q'[處理此功能需要授權 Flows for APEX Enterprise Edition。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_close_error', c_load_lang, q'[」在子流程 %0 上處理反覆關閉時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'engine-util-sbfl-not-found', c_load_lang, q'[找不到提供的子流程 ID (%0)。檢查變更處理流程 (逾時、錯誤、呈報) 的處理事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-invalid-route', c_load_lang, q'[閘道 %0 發生錯誤。提供的變數 %1 包含無效的路徑：%2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-merge-error', c_load_lang, q'[在子流程 %0 上合併閘道時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-route', c_load_lang, q'[變數 %0 中未提供閘道路由指示，且模型未包含預設路由。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-bad-expression', c_load_lang, q'[無效的閘道路由表示式。如果嘗試以內嵌冒號 (：) 連結變數，就可能發生此情況。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'process-lock-timeout', c_load_lang, q'[%0 的處理物件目前被其他使用者鎖定。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'more_than_1_forward_path', c_load_lang, q'[找到1 個以上的正向路徑，但僅允許 1 個]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'no_next_step_found', c_load_lang, q'[在子流程 %0 上找不到下一個步驟。檢查您的處理程序圖。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_failed', c_load_lang, q'[處理 %0：作業 %1 因 PL/SQL 錯誤而失敗 - 請參閱事件日誌。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'plsql_script_requested_stop', c_load_lang, q'[處理 %0：任務 %1 要求處理停止 - 請參閱事件日誌。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timeout_locking_subflow', c_load_lang, q'[無法鎖定子流程 %0，因為目前已由其他使用者鎖定。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-already-placed', c_load_lang, q'[已為您預留下一個任務。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-by-other_user', c_load_lang, q'[%0 的保留失敗。步驟已由其他使用者 (%1) 保留。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-failed-not-found', c_load_lang, q'[%2 的預訂失敗。找不到處理 %1 中的子流程 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-incorrect-step-key', c_load_lang, q'[任務已不再是目前任務，可能已經完成。請重新整理您的收件匣。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-lock-timeout', c_load_lang, q'[其他使用者目前已鎖定 (未保留) 子流程。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'reservation-release-not-found', c_load_lang, q'[預留核發失敗。找不到處理 %1 中的子流程 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-username', c_load_lang, q'[無法建立物件 %0 的非同步連線。必須在處理變數、處理圖表或系統組態中指定使用者名稱。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'async-no-appid', c_load_lang, q'[無法建立物件 %0 的非同步連線。必須在處理變數、處理圖表或系統組態中指定應用程式 ID。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-diagram-calls-itself', c_load_lang, q'[您嘗試使用包含 callActivity 呼叫本身的圖表 %0 啟動處理作業。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-too-many-defaults', c_load_lang, q'[閘道 %0 的模型中指定了多個預設路由。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-no-catch', c_load_lang, q'[找不到名稱為 %0 的相符連結擷取事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'link-too-many-catches', c_load_lang, q'[一個以上的相符連結擷取事件名稱為 %0。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-instance-event', c_load_lang, q'[流程 - 記錄執行處理事件時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-step-event', c_load_lang, q'[流程 - 記錄步驟事件時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-variable-event', c_load_lang, q'[流程 - 記錄「變數事件」時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-already-running', c_load_lang, q'[您嘗試啟動一個已經執行多個複本的處理作業 (ID %0)。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-multiple-start-events', c_load_lang, q'[您定義了多個開始事件。請確定您的圖表只有一個開始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'start-no-start-event', c_load_lang, q'[流程圖中未定義開始事件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_json_format', c_load_lang, q'[設定處理變數 %1 時發生錯誤：不正確的 JSON 格式 (子流程：%0，集：%3.)]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'iter_lock_error', c_load_lang, q'[鎖定處理作業 ID %1 的重複詳細資訊 (iter %0 迴圈 %2) 時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'archive-destination-null', c_load_lang, q'[尚未設定存檔或記錄日誌目的地 - 請參閱組態 &gt; 記錄日誌或存檔]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'var_exp_plsql_other', c_load_lang, q'[設定處理作業 ID %0 (設定 %2) 中的處理作業變數 %1 時發生錯誤。事件日誌中顯示的 PL/SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-call-act', c_load_lang, q'[倒帶 - 上階子流程不是要倒帶的通話活動。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-no-previous-gw', c_load_lang, q'[找不到子流程 %0 的前一個開啟平行或內含閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'resume-invalid-status', c_load_lang, q'[只能繼續目前處於暫停狀態的處理執行處理。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-matched-object', c_load_lang, q'[倒帶 - 找不到要倒帶的相符開啟物件。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-unknown-gw-status', c_load_lang, q'[倒帶 - 回復至先前閘道時，發生未知的閘道狀態。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-previous-gateway', c_load_lang, q'[倒帶 - 找不到要倒帶的先前閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-call-act', c_load_lang, q'[倒帶 - 找不到要倒帶的上階通話活動子流程。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-split-event-based-gw', c_load_lang, q'[ 回復 - 無法從仍在執行中的事件型閘道倒帶。先將其中一個正向子流程倒回事件型閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_plsql_other', c_load_lang, q'[執行 PL/SQL 時發生錯誤。事件日誌中顯示的 PL/SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-matching-object-error', c_load_lang, q'[擷取子流程 %0 (目前步驟 %1) 的相符閘道物件時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_cols', c_load_lang, q'[執行 SQl 查詢時發生錯誤 - 查詢傳回一個以上的資料欄。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-parent-subflow', c_load_lang, q'[倒帶 - 找不到父項子流程。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_rows', c_load_lang, q'[設定處理作業 ID %0 (設定 %2) 中的處理作業變數 %1 時發生錯誤。查詢傳回多個資料列。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-cant-gway-from-event', c_load_lang, q'[倒帶 - 無法倒帶至事件的先前閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'logging-event-level', c_load_lang, q'[流程 - 取得日誌記錄層級時發生內部錯誤]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-not-wait-at-gateway', c_load_lang, q'[倒帶 - 子流程未在閘道等待以倒帶至最後一個步驟。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_too_many_values', c_load_lang, q'[執行 SQL 查詢時發生錯誤 - 查詢傳回一個以上的值。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'timer-internal-error', c_load_lang, q'[物件 %0 的計時器內部錯誤。類型 ：% 1 ；值 ：% 2]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspend-invalid-status', c_load_lang, q'[只能暫停目前處於執行中或錯誤狀態的處理執行處理。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-force-step-not-error', c_load_lang, q'[無法對非錯誤狀態的子流程強制下一個步驟。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'gateway-multiple-previous-gws', c_load_lang, q'[發現子流程 %0 有多個先前的平行或內含閘道。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'suspended-cannot-complete-step', c_load_lang, q'[此處理實例目前已暫停。請稍後再試。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-last-step', c_load_lang, q'[倒帶 - 在閘道倒帶之前，未立即找到最後完成的步驟。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-step-reposition-error', c_load_lang, q'[倒帶 - 重新定位步驟時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-no-current-step', c_load_lang, q'[倒帶 - 要求倒帶的目標步驟不是目前步驟的有效轉換。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-matching-object-error', c_load_lang, q'[倒帶 - 從子流程日誌取得要倒帶的相符物件時發生錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'exec_sql_other', c_load_lang, q'[執行 SQL 查詢時發生錯誤。事件日誌中顯示的 SQL 錯誤。]' );
  insert into flow_messages( fmsg_message_key, fmsg_lang, fmsg_message_content )
    values ( 'rewind-parent-not-subproc', c_load_lang, q'[倒帶 - 上階子流程不是要倒帶的子處理。]' );
  
  commit;
end;
/
